### ISSUE TITLE
WebComment: display comment restriction

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1002]
Originally on 2012-04-12

Comments can be restricted individually, independently from the record restriction. It would be needed to show the restriction state of a comment to the user, so that they know which information must not be shared (a reply to a comment will inherit the restriction of the original, so it is already safe on this side).

A basic "Restricted" label could be added to each comment, when it is individually restricted. Some flag similar to the one for restricted records could also be imagined (see also #867). It should however not degrade the reading experience of discussion pages by adding heavy (with vibrant, contrasted colors) graphics for every comment.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 4 years. Invenio 1.x is in feature freeze state now.

--
cc @inveniosoftware/triagers
