### ISSUE TITLE
Inspire: display problem when sorting by times cited

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1004]
Originally by *annetteh* on 2012-04-13

Searching via recid should display just one record. But sorting by times cited sometimes leads to the display of more than 1 record although it says: 1 records found. Example:
001:158501
https://inspirehep.net/search?ln=en&ln=en&p=001%3A158501&of=hb&action_search=Search&sf=&so=d&rm=citation&rg=25&sc=0
It is not obvious to me what the connection between the original record and the displayed ones is.

It may seem nonsensical to try to sort just one record. But the way I arrived at this bug is maybe not so uncommon. The search refersto:001:158501 automatically switches to times cited. I tried to look at the record itself by just removing "refersto:" from the search box, so remained in the times cited mode.

**Comment by jmartinm** [comment]
This seems to be fixed by now.
