### ISSUE TITLE
WebSession: customizable user dashboard

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1006]
Originally by *[nkasioum (@kasioumis)](https://github.com/kasioumis)* on 2012-04-16

Invenio's current 'Your Account' page (https://url.to.invenio/youraccount/display) is static, outdated and far from user friendly.

It could be replaced by a 'customizable user dashboard' that allows the user to configure the information he/she sees, and at the same time provides the information in a more user-friendly format.

jQuery could be used to provide a way to add / remove 'information boxes' as well as to move them around and reorder them.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 4 years. Check https://github.com/inveniosoftware/invenio-userprofiles and https://github.com/inspirehep/invenio-trends where you can submit updated requirements.

--
cc @inveniosoftware/triagers
