### ISSUE TITLE
WebSession: Your Activity page

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1007]
Originally by *[nkasioum (@kasioumis)](https://github.com/kasioumis)* on 2012-04-16

A new page: 'Your Activity' could be created to summarize the user's latest activity in the repository. This page should include information on the user's actions on the following: downloads, comments, reviews, votes, subscriptions, groups, baskets, alerts, searches, messages, submissions etc.

A short version of the user activity information should also exist in the 'Your Account' page.

**Comment by jirikuncar** [comment]
related also to notifications from #2622

**Comment by jirikuncar** [comment]
Session activity has been moved to Invenio-Accounts. Please follow https://github.com/inveniosoftware/invenio-accounts/issues/52
