### ISSUE TITLE
Inspire: missing space between initials in bibtex

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1011]
Originally by *annetteh* on 2012-04-16

Author initials in the bibtex format should be separated by a space since a dot apparently is not considered as a separator in bibtex - resulting in suppression of the 2nd initial.

**Comment by jirikuncar** [comment]
@kaplun is it still relevant for INSPIRE or has to be done something in Invenio core?

**Comment by kaplun** [comment]
@tsgit this is still the case today in INSPIRE. Can you have a look?
https://inspirehep.net/record/1087430/export/hx

**Comment by kaplun** [comment]
Moved to inspirehep/inspire#78
