### ISSUE TITLE
Check for gibberish in references before accepting them

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1013]
Originally by *[adeiana (@Osso)](https://github.com/Osso)* on 2012-04-17

Some scans end up with references which are complete gibberish. It should be possible to test for the sanity of references by avoiding too many symbols in a row in one reference.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 4 years. Check https://github.com/inspirehep/invenio-grobid 

--
cc @inveniosoftware/triagers

**Comment by kaplun** [comment]
And also http://github.com/inspirehep/refextract
