### ISSUE TITLE
BatchUploader: allow insertion of text MARC

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1023]
Originally on 2012-04-25

Batchuploader interface allows to "--insert" "TextMarc" records, but the underlying textmarc2xmlmarc.py will not support the creation of MARCXML without a record ID (tag 001), which is necessary to avoid when inserting records (and not updating/replacing).

 - The textmarc2xmlmarc.py could be enhanced to support input MARC without recid (a fake prefixing recid would still be needed in the input to differentiate records)
 - batchuploader_engine.py could strip off the recid created by textmarc2xmlmarc.py if it is run in "--insert" mode
 - The "--insert" option could be removed from web interface when "TextMARC" record is selected (and "TextMARC" removed when "--insert" is selected)

**Comment by jirikuncar** [comment]
Closed via 67c989217bd36ce03a3f7b222438cd6f337e3de5
