### ISSUE TITLE
inveniocfg --drop-tables and var/data/files

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1024]
Originally on 2012-04-25

Currently one my think that `inveniocfg --drop-tables` will entirely wipe an Invenio instance. This is mostly true but it will not touch any file on disk. In particular files attached to Invenio records will stay on disk under `var/data/files`. If then the user load again new records these files will stay on the way.

Either `--drop-tables` should also take care of removing files from disk (since their implicitly part of the data, although not stored in tables), all we should introduce a new `--drop-files` argument and we should recommend its usage for properly wiping out an Invenio instance.

**Comment by jirikuncar** [comment]
Solved in 2.0.0. Please re-open if you need it in 1.x.
