### ISSUE TITLE
rpdb2 warnings

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1025]
Originally on 2012-04-25

Currently, if one enable `CFG_DEVEL_SITE` but doesn't have *rpdb2* package installed, a set of warnings are printed on the screen per every invenio executable call:
```

Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/invenio/remote_debugger.py", line 94, in <module>
    globals()[name] = __import__(path, globals(), locals(), path.split('.'))
ImportError: No module named pydev.pydevd_file_utils
Error in remote_debugger, import of the pydev.pydevd_file_utils failedTraceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/invenio/remote_debugger.py", line 94, in <module>
    globals()[name] = __import__(path, globals(), locals(), path.split('.'))
ImportError: No module named pydev.pydevd
Error in remote_debugger, import of the pydev.pydevd failedTraceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/invenio/remote_debugger.py", line 96, in <module>
    globals()[name] = __import__(path)
ImportError: No module named rpdb2
```

On the other hand the *rpdb2* is optional hence these warnings should either not appear or at least prettified.

**Comment by jirikuncar** [comment]
@kaplun do you know if anybody is using this feature since we have *werkzeug* in Invenio 2.0?

**Comment by lnielsen** [comment]
+1 for removing. I don't think it's relevant anymore with werkzeug, ipdb and the development server.

**Comment by tiborsimko** [comment]
... and for people using Invenio v1.x, there is `winpdb` in `requirements-extras.txt`, so if people are debugging, chances are they have it installed already.  I'm therefore closing this issue.
