### ISSUE TITLE
Inspire xmlpublic

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1026]
Originally by *annetteh* on 2012-04-26

The spires xmlpublic format needs to be reproduced, see e.g.
http://www.slac.stanford.edu/spires/find/hep/www?rawcmd=fin+a+hawking&FORMAT=xmlpublic&SEQUENCE=

specifically (https://rt.inspirehep.net/Ticket/Display.html?id=180611):
- Title
- Author list (separated authors, so it can be automatically analyzed)
- Journal (if published)
- Volume (if published)
- Pages (if published)
- Year
- ArXiv/eprint number + report nr (if present)
- Citation count (this is very very helpful)
- Unique INSPIRE key
- DOI
and more (conf info...)

**Comment by jmartinm** [comment]
I have sent an email around INSPIRE to ask if this format is still relevant.

**Comment by hoc3426** [comment]
I would think all our API work would now give people what they want. Looking through RT it seems that this is the most recent request concerning the old SPIRES xmlpublic and it is already three years old:
https://rt.inspirehep.net/Ticket/Display.html?id=202468

H.
