### ISSUE TITLE
Citeform: display bugs for references

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#1028]
Originally on 2012-04-30

Reported by Michael Peskin.  Example: document 884003.  

Note that references 1c, 8, 10, 23 and 24 look fine on the detailed record references tab.

Click on the link to go to citeform.  

1) Notice that in citeform mode to display things, all of the lines mentioned above (the 3rd '1', 8, 10, 23 and 24) display incorrectly.  Michael was confused when trying to update his citations about why they looked wrong.

2) It wasn't obvious that updating the eprint number in the edit box on the left, immediately updated the display of the title on the right. But it probably should.

3) more mouseover help.

**Comment by jirikuncar** [comment]
see https://github.com/inveniosoftware/invenio-csl-rest
