### ISSUE TITLE
HEPJobs Form: postings go to wrong place

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#1035]
Originally on 2012-05-05

Something is weird about the HEPJobs submission form.  When a message is sent asking for confirmation of a posting, it's put into the HEP queue on inspirert, despite being addressed to jobs@inspire*; you would think that this would mean RT is misconfigured, but the configuration looks the same as all the other mail handling targets, and also it works.  Try it, send email to jobs@ and see what it does.

So I think that something is weird with how the recipient list is being constructed in JOBSUBMIT_Mail_Submitter.py - but I could be totally wrong.  In general though I'd suggest just using the RT interconnect library provided by bibcatalog.BibCatalogSystemRT().  An example of its use can be found in my branch 'thesis_form_reanimation'.

**Comment by jirikuncar** [comment]
@kaplun please close if it has been really fixed (see https://github.com/inveniosoftware/invenio/issues/1035#issuecomment-41860624).
