### ISSUE TITLE
WebSubmit: warn user when Javascript is disabled

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1039]
Originally on 2012-05-08

WebSubmit requires to have Javascript enabled on the browser client. While it is hoped that this requirement would be removed (see  [Savannah ticket 3178](https://savannah.cern.ch/task/index.php?3178)), it would be nice in the meantime to display a message to the user when visiting a submission page with Javascript disabled:

```
<noscript>
  Submissions requires to have Javascript enabled. 
  Please enable Javascript on your browser in order to submit.
</noscript>
```

**Comment by jirikuncar** [comment]
For *Invenio 2.x* we should display warning on top of every page if JavaScript is disabled.
