### ISSUE TITLE
BibSort: second order sort

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio#1040]
Originally on 2012-05-08

It would be nice to extend BibSort to consider also second order sorting.
Example: 1st order: date; 2nd order: title
(Sort all records by date, sort records that have the same date by title).

**Comment by tiborsimko** [comment]
I guess this can already be addressed to a good extent by techniques such as:

```
[sort_field_4]
name = report number
definition = MARC: 037__a,909C0r,088__a
washer = sort_case_insensitive
```

In the `master` code base it will be addressed via Elasticsearch.
