### ISSUE TITLE
BibKnowledge: less disruptive LHS rule check for uniqueness

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1045]
Originally on 2012-05-08

Currently when one wants to add a new mapping "foo->bar" in a knowledge base X, and that key "foo" already exists in another knowledge base Y, the user is presented a warning that the rule already exists, asking to confirm the insertion.

The warning is really disrupting the task of adding multiple entries to a KB. It is very likely that the LHS already exists in another KB, and very unlikely that the KBs are related in a way that the LHS should be unique. It is proposed that this behavior is flipped, so that the rule is added anyway (and user returns to the standard BibKnowledge form, ready to insert next mapping) , and that a panel is displayed in case the user would like to cancel the insertion (in a non-modal way). See attached mockup.

One could also want to flip between these two behaviours on a CFG_ variable basis, or as a per-user setting, or per knowledge base (new knowledge base attribute)

See also #652

(One could further streamline the task of inserting entries by sending asynchronous insertion requests in order to avoid full reload of the page, but that would be the aim of another ticket)

**Comment by jirikuncar** [comment]
Invenio-Knowledge [model for values](https://github.com/inveniosoftware/invenio-knowledge/blob/master/invenio_knowledge/models.py) requires unique keys per knowledge base.
