### ISSUE TITLE
download of files with space in name not working

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1047]
Originally by *buettner* on 2012-05-09

Uploading of such files works either via web interface or via command line, and the files can be found in the search interface. Clicking on the link to download them truncates the name at the first space. 

This seems to be related to 
http://kb.mozillazine.org/Filenames_with_spaces_are_truncated_upon_download

Other browsers:
works: chromium 18.0.1025.168 (Developer Build 134367 Linux) Ubuntu 11.04
does not even show the link: IE8 on windows XP

I have not tested safari or IE 9 yet

**Comment by tiborsimko** [comment]
I've tested that this works now in maint-1.2 branch, so I'm closing this ticket.  (Fixed via #2908 and related earlier commits.)
