### ISSUE TITLE
BibSort: sorting by indicator

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio#1048]
Originally on 2012-05-09

Some of the fields: 245 (but also, 222, 240, 242, 243) can use the second indicator to specify how many characters from a field should be omitted when sorting. It would be nice to have one washing function that takes these indicators into account (something in the same lines as remove_leading_articles)

**Comment by jirikuncar** [comment]
Elasticsearch supports script based sorting: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_script_based_sorting
