### ISSUE TITLE
Handle find doi

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1051]
Originally by *[adeiana (@Osso)](https://github.com/Osso)* on 2012-05-10

Be able to search for find doi 10.1007/BF01053584

**Comment by jirikuncar** [comment]
@kaplun Can you please have a look what (/if something) needs to be done to make it work with new search engine?

**Comment by jirikuncar** [comment]
`find doi <identifier>` should get translated by *Invenio Query Parser* into `doi:<identifier>` that Invenio can handle.

**Comment by kaplun** [comment]
This will better be implemented by dedicated DOI field in the data model.
