### ISSUE TITLE
WebAlert: set up new alerts on non-existing searches or on searches that don't yield results

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1052]
Originally by *[nkasioum (@kasioumis)](https://github.com/kasioumis)* on 2012-05-11

New alerts can only be set on searches that the user has already performed and have yielded results. It should be possible to also set up new alerts on searches that have not yet been performed or on searches that have already been performed but have not yielded results.
For this to be done there are two possible solutions:
1) New WebAlert interface that permits new alerts to be set up based on user provided search parameters and collections
2) Searches that do not yield results are recorded and shown in the user's search history

**Comment by jirikuncar** [comment]
Invenio 1.x is in feature freeze state. We will take this issue into account when preparing new alerting engine for Invenio 3.

**Comment by kasioumis** [comment]
@jirikuncar thanks, sounds good.
