### ISSUE TITLE
Need script to produce marcxml from PDG file

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1059]
Originally by *eduardob* on 2012-05-15

Need script to produce marcxml from PDG file. The marcxml will be fed to bibupload.

From:
PHLTA,14,105,S000M

To:
 <record>
 <controlfield tag='001'>48875</controlfield>
 <datafield tag='084'>
 <subfield code='a'>s000m</subfield>
 <subfield code='2'>PDG</subfield>
 <subfield code='9'>PDG</subfield>
 </datafield>
 </record>

**Comment by jirikuncar** [comment]
Is it still relevant?

**Comment by kaplun** [comment]
Definitively not for Invenio :)
