### ISSUE TITLE
websubmit_icon_creator to use PIL

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1061]
Originally

[PIL](http://www.pythonware.com/products/pil/) is a more python way of handling images in Python than ImageMagick, avoid calling system tools, and is less memory hungry.

The `websubmit_icon_creator` tool should be rewritten to use PIL rather than ImageMagick.

See also: #15

**Comment by jirikuncar** [comment]
We can probably replace it by *Flask-IIIF* and proper caching.

**Comment by drjova** [comment]
:+1:

**Comment by drjova** [comment]
@kaplun can we close it?

**Comment by kaplun** [comment]
Sure!
