### ISSUE TITLE
Author search: Middle initial problem (initial versus full name)

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1062]
Originally by *hoc* on 2012-05-15

There's a problem with searching via initials versus full-names.

find a pi, s y not a Pi, So Young
in SPIRES this has (correctly) a zero result, because all
Pi, So Young should be indexed to Pi, S Y
so this search would only find a non-zero result if there were, say,
Pi, Shan Yu (and there isn't, all S.Y. Pi are So Young Pi).

Looking at something where dashes aren't an issue:
find a crewther, r j not a crewther, rodney james
should find zero but instead finds all the papers not listing his full name.

Compare this with the well-functioning situation for single initials:
find a quigg, c not a quigg, chris
  finds zero because there's only one person who signs "Chris Quigg"      
  or "C. Quigg" 
find a quigg, c not a quigg, curtis
  gets 113 of his 248 papers, it just weeds out the ones he's signed as "Chris Quigg"

**Comment by jalavik** [comment]
Reopened as inveniosoftware/invenio-query-parser#23
