### ISSUE TITLE
WebSearch: user-facing exception on search (SPIRES syntax)

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#1067]
Originally on 2012-05-23

When using SPIRES syntax with the query: "find a whatever:", where 'whatever' is followed by a colon and 'whatever' is not a defined index field, there is a using facing exception error displayed:

```
Internal Error exceptions.IndexError list index out of range

URI: https://inspirehep.net/search?ln=en&ln=en&p=find+a+Guillet%3A&of=hb&action_search=Search&sf=&so=d&rm=&rg=25&sc=0
Time: 23/May/2012:11:18:31 +0200
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.19 (KHTML, like Gecko) Ubuntu/12.04 Chromium/18.0.1025.151 Chrome/18.0.1025.151 Safari/535.19
Client: 137.138.124.15
```

I think we should take a look at suppressing this type of error message to something more straightforward or even helping the user to correct his mistake, better yet, correct it automagically. Colons at the end of the search string should probably be stripped/ignored as a general rule.

**Comment by jalavik** [comment]
@jirikuncar I will check if this is still an issue and how the parser handles it. I guess it is safe to assume that colon expressions without a value can be ignored/treated as part of the value?

**Comment by jirikuncar** [comment]
> colon expressions without a value can be ignored/treated as part of the value?

I'm not an expert in Invenio/SPIRES syntax but I would expect following:

```
author:Ellis: -> search_unit(f=author, p=search_unit(f=Ellis, p='')) # will probably fail as InvalidKeyword('Ellis')
author:'Ellis:' -> search_unit(f=author, p=Ellis:, m=a))
Ellis: -> search_unit(f=Ellis, p=''))
'Ellis:' -> search_unit(f='', p=Ellis:, m=a))
```

**Comment by jirikuncar** [comment]
Follow in inveniosoftware/invenio-query-parser#19
