### ISSUE TITLE
BibIndex: add auto-repair facility

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#1069]
Originally on 2012-05-24

Sometimes the bibindex tasks detects certain inconsistencies and reports back to the administrators that --repair should be run on the affected tables. These inconsistencies often happens if the indexing task has somehow been interrupted (killed/crashed task or DB downtime). There are probably other reasons as well, but these are the one I have been personally seeing. It would be interesting to hear other experiences on this matter.

Now since the administrators would anyway try to run the repair on the affected indexes, bibindex should be able to automatically run these repairs before re-starting the initial task. Are there any possible scenarios where a repair would be unwise/dangerous to perform? If so, they should be taken into account when implementing this feature.

Overall, this enhancement should help making the system more autonomous, avoiding long indexing queue times if operators are not available right away to solve the issue.

PS: I can imagine some extra care must be taken to not run repairs on indexes currently being touched by another bibindex task (running in parallel).

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 4 years. Invenio 1.x is in feature freeze state now.

--
cc @inveniosoftware/triagers
