### ISSUE TITLE
access: remove legacy external authentication methods

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1083]
Originally

The following config variables:

- from `access_control_config.py`:
```python

# List of tags containing (multiple) emails of users who should authorize
# to access the corresponding record regardless of collection restrictions.
if CFG_CERN_SITE:
    CFG_ACC_GRANT_AUTHOR_RIGHTS_TO_EMAILS_IN_TAGS = ['859__f', '270__m', '506__m']
else:
    CFG_ACC_GRANT_AUTHOR_RIGHTS_TO_EMAILS_IN_TAGS = ['8560_f']


# CFG_EXTERNAL_AUTHENTICATION -- this is a dictionary with the enabled login method.
# The key is the name of the login method and the value is an instance of
# of the login method (see /help/admin/webaccess-admin-guide#5). Set the value
# to None if you wish to use the local Invenio authentication method.
# CFG_EXTERNAL_AUTH_DEFAULT -- set this to the key in CFG_EXTERNAL_AUTHENTICATION
# that should be considered as default login method
# CFG_EXTERNAL_AUTH_USING_SSO -- set this to the login method name of an SSO
# login method, if any, otherwise set this to None.
# CFG_EXTERNAL_AUTH_LOGOUT_SSO -- if CFG_EXTERNAL_AUTH_USING_SSO was not None
# set this to the URL that should be contacted to perform an SSO logout
```

- from `external_authentication_sso.py`
```python

# Tunable list of settings to be hidden
CFG_EXTERNAL_AUTH_HIDDEN_SETTINGS = ('auth', 'respccid', 'personid')
# Tunable list of groups to be hidden
CFG_EXTERNAL_AUTH_HIDDEN_GROUPS = (
...)

CFG_EXTERNAL_AUTH_HIDDEN_GROUPS_RE = (
...)


# Prefix name for Shibboleth variables
CFG_EXTERNAL_AUTH_SSO_PREFIX_NAME = 'ADFS_'
# Name of the variable containing groups
CFG_EXTERNAL_AUTH_SSO_GROUP_VARIABLE = CFG_EXTERNAL_AUTH_SSO_PREFIX_NAME+'GROUP'
# Name of the variable containing login name
CFG_EXTERNAL_AUTH_SSO_LOGIN_VARIABLE = CFG_EXTERNAL_AUTH_SSO_PREFIX_NAME+'LOGIN'
# Name of the variable containing email
CFG_EXTERNAL_AUTH_SSO_EMAIL_VARIABLE = CFG_EXTERNAL_AUTH_SSO_PREFIX_NAME+'EMAIL'
# Name of the variable containing groups
CFG_EXTERNAL_AUTH_SSO_GROUP_VARIABLE = CFG_EXTERNAL_AUTH_SSO_PREFIX_NAME+'GROUP'
# Separator character for group variable
CFG_EXTERNAL_AUTH_SSO_GROUPS_SEPARATOR = ';'
```

- from `external_authentication_ldap.py`
```python

CFG_EXTERNAL_AUTH_LDAP_SERVERS = ['ldap://scoldap.epfl.ch']
CFG_EXTERNAL_AUTH_LDAP_CONTEXT = "o=EPFL,c=CH"
CFG_EXTERNAL_AUTH_LDAP_USER_UID  = ["uid", "uniqueIdentifier", "mail"]
CFG_EXTERNAL_AUTH_LDAP_MAIL_ENTRY = 'mail'
CFG_EXTERNAL_AUTH_LDAP_GROUP_MEMBERSHIP = 'memberOf'
CFG_EXTERNAL_AUTH_LDAP_GROUP_UID = 'uniqueIdentifier'
CFG_EXTERNAL_AUTH_LDAP_GROUP_NAME = 'displayName'

CFG_EXTERNAL_AUTH_LDAP_HIDDEN_GROUPS = ['EPFL-unit', 'users']
```

should be all moved into `invenio.conf` so that that the whole authentication system could be decoupled from CERN/INSPIRE/OpenAIRE/EPFL specific configurations.

**Comment by jirikuncar** [comment]
@lnielsen this is something we might want to have a look at for allowing users to change their email addresses.

**Comment by lnielsen** [comment]
I'm thinking we can just replace occurrences of:

```python
CFG_VAR = val
```

with :

```python
from invenio.base.globals import cfg
CFG_VAR = cfg.get('CFG_VAR', val)
```

Shouldn't that do the job?

I've already done this for some of variables in #2873

**Comment by lnielsen** [comment]
By the way is external authentication replaced by Flask-SSO and oauthclient?

**Comment by tiborsimko** [comment]
@lnielsen Yes, the original issue is addressable via Flask-SSO and OAuth, so unless some Invenio 1.x installation needs this split, let's close this issue at hand and eventually reopen new one for OAuth.
IIRC @egabancho started to test OAuth for CDS lately.

**Comment by jirikuncar** [comment]
I would change  the title to `RFC External authentication method removal`. We have OAuth and SSO implemented in 2.x so we can remove `invenio/legacy/external_authentication` from all 2.x branches.

**Comment by lnielsen** [comment]
Some of the variables in ``access_control_config.py `` is still needed by Invenio, so I'll fix that using the method mentioned and then perhaps we deprecate the entire module?

**Comment by tiborsimko** [comment]
Seems we agree on SSO, and for @aw-bib and anyone else using LDAP with Invenio v1.x, we'd have to port LDAP external authentication method to the new "Flask style" using Flask-LDAP.  I guess this may be done later...

**Comment by jirikuncar** [comment]
@kaplun @tiborsimko can we proceed with *fast* deprecation policy (removed in 2.1) as we already have replacement for OAuth and SSO?

**Comment by kaplun** [comment]
:+1:
