### ISSUE TITLE
WebComment: possibility to switch off commenting on a record basis

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1093]
Originally on 2012-06-26

It would be useful to disable the commenting of a record based on its metadata. It could either be a simple datafield in the record that would switch off the comment submission form, or a more advanced set up that would only let emails/groups defined in the metadata to send comments.

(this would help in the case of reviewing workflows, where the commenting sessions are closed after some time)

Ideally the "Discussion" tab would still be accessible (for reading the already submitted comments), but it might be possible to imagine a possibility to optionally disable access to this tab (and comments) too. There is no such use case now (apart from the need to sometimes disable the "Discussion" tab for records that cannot be matched to a primary collection for disabling the tab from the WebSearch admin interface. In this case the switching on/off of all tabs -not only "Discussion"- could be enforced on a record basis).

**Comment by jirikuncar** [comment]
Is it still needed for legacy or shall we move it as requirement for new Invenio-Comments package?

**Comment by tiborsimko** [comment]
The Discussion tab can be enabled/disabled on a per collection basis.  I think this was deemed sufficient, so the ticket can be closed. @ludmilamarian @egabancho
