### ISSUE TITLE
WebComment: let "authors" reply to comments

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1094]
Originally on 2012-06-26

It is currently possible for authors to reply to comments by simply sending a regular comment. The reply might however be appended at the end of the discussion (when the max thread depth is reached), and it might not be trivial to differentiate it from comments sent TO the author. It might be useful to give a special status to responses from authors so that they would be closely coupled to the comment they respond to, and easily identifiable (visually) as such.

The list of users that could send such a response should be more clearly analyzed. The authors, as well as a list of users/group defined in some fields of the metadata would seem to be a good option.

It should be defined if only one response from an author would be allowed per comment, or if multiple could be sent per comment.

The typical use case is to let an author send a reply even after a reviewing round would be closed (see #1093), and very clearly identify responses from the author vs comments from reviewers in the case of reviewing workflows.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 3+ years.

--
cc @inveniosoftware/triagers
