### ISSUE TITLE
WebSearch: support new syntax collection:"CERN Divisions"

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1097]
Originally on 2012-06-27

`collection:FOO` query is currently mapped onto `980:FOO` query, basically.  For faceted search, it would be desirable if one can pass `collection:"CERN Divisions"`.

This can be achieved by enriching `search_unit()` in a similar way how e.g. `citedby` special queries are done.  The above query would simply return hitset of records belonging to the "CERN Divisions" collection.

Note that there may be a mixup of `collection` concept being used to represent 980 and being used to represent the collection name.  So beware WRT webcoll.  Either we could return Boolean OR between old-behaviour and new-behaviour, or we could distinguish between these cases via two independent `collection` and `collectionname` search operators.

As usual, test cases should be written.

**Comment by jirikuncar** [comment]
Supported since v2.0.0.
