### ISSUE TITLE
INSPIRE: easy search: make <enter> behave nicely

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#1099]
Originally on 2012-06-29

I think it's just some javascript tweaks needed, but we'll want to be careful to make sure we don't break any popular browsers.

Begin forwarded message:

>
> 3. Why should I push the "search" button all the time for the INSPIRES easy search, instead of pushing 
> the enter key on the keyboard? I hope the enter key can do it.

For me (mac, chrome+firefox) neither the return nor the enter key has any effect, not even jumping to the next field. This is probably not the desired behavior.

- Annette

https://inspirert.cern.ch/Ticket/Display.html?id=212255
>
> Use REPLY-ALL to reply to list
>
> To unsubscribe from the INSPIRE-DEV list, click the following link:
> https://listserv.slac.stanford.edu/cgi-bin/wa?SUBED1=INSPIRE-DEV&A=1

**Comment by jmartinm** [comment]
Just checked that this is already solved in INSPIRE.
