### ISSUE TITLE
use specific jQuery versions

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#11]
Originally on 2010-04-20

One more thing to do before 1.0 in the jQuery department: there are
still some svn/tags/latest parts in install-jquery-plugins.  This
is too bleeding edge, and we have been bitten by this in the past, so
to speak, e.g. file renames in
0c841f12e403c0bdb9cc38dd9a7cfbd2d3e4ff45, e.g.  calendar changes in
e2a978e7746fb2a929e58c23034f4e216bf6afe2.

So it would be good to go through the whole install-jquery-plugins
target and change remaining parts in order to wget always some very
specific version of a jQuery library, as is needed, like in my changes
mentioned above.  (I have been doing that as was necessary for
merging, I have not gone systematically through every jQuery
dependency we have.)

Can you please look at that?

If there is a trouble with some dependency lib URL stability, or
versions are lacking on the remote site, then we can host the
dependency on cdsware.cern.ch site, like the other installation files,
e.g. demo records, e.g. keyword ontologies.

**Comment by aw-bib** [comment]
Looking into the `Makefile`'s section related to this issue as we recently had a problem with some plugin. Note alos that ther're still some wgets without a forced -O as mentioned by @kaplun.

Unfortunatley, it is a bit beyond me which versions are really required. Probably, someone in the know could have a look at it?

Here is what I found in maint-1.1 as plugins without explicit version:

----------------------------------------------------------------------
* wget https://raw.github.com/malsup/form/master/jquery.form.js --no-check-certificate

Last tagged version on github is v3.19:
https://github.com/malsup/form/blob/v3.19/jquery.form.js

However, one may get 3.50 from jsDelivr:
http://origin.jsdelivr.net/jquery.form/3.50/jquery.form.js

----------------------------------------------------------------------
* wget http://jquery-multifile-plugin.googlecode.com/svn/trunk/jquery.MultiFile.pack.js

Latest version is r54:
https://jquery-multifile-plugin.googlecode.com/svn-history/r54/trunk/jquery.MultiFile.js

----------------------------------------------------------------------

* wget http://www.datatables.net/download/build/jquery.dataTables.min.js

current stable is 1.10.4
wget http://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js

Note: there is a further wget for
https://raw.githubusercontent.com/DataTables/DataTables/1.10.0/media/css/demo_table_jui.css
that looks related.

----------------------------------------------------------------------

**Comment by tiborsimko** [comment]
@aw-bib If you'd like to make a PR, please just use latest tagged versions.  (Hence no jsDelivr.)  We have a daily Jenkins build job that verifies that Invenio pre-requisites are downloadable, but it would be indeed good to finish this off one day...

**Comment by aw-bib** [comment]
@tiborsimko I'll try to refer to latest tagged and add -O in case.

**Comment by tiborsimko** [comment]
BTW this issue can be almost closed, except for:

- http://github.com/johndyer/mediaelement/zipball/master

that is asking for master version.

(And https://github.com/douglascrockford/JSON-js but this does not have any tagged releases still.)

**Comment by tiborsimko** [comment]
This was fully fixed in the summer in 700d1b83, using `zipball` version 2.8.11.
