### ISSUE TITLE
WebSession: lighter session management

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1101]
Originally on 2012-07-03

WebSession: lighter session management

During user storms, session generation may take a long time, making
the site to appear as not available even if there would be resources.
This ticket is about making session management lighter.

(1) The problems occur especially if a site did not run garbage
collection for the session table (`inveniogc -g`) since a long time.
For example, on INSPIRE, the session table once grew to 2+ GB in size.
This and other less-than-optimal DB queries lead to table lock
contention:

```
| 41555 | inspirehep | pcudssw1507.cern.ch:45737 | inspirehep |
          Query | 0 | Locked | INSERT session(
| 41563 | inspirehep | pcudssx1506.cern.ch:33785 | inspirehep |
          Query | 2 | update | INSERT session(
| 41573 | inspirehep | pcudssw1507.cern.ch:45741 | inspirehep |
          Query | 2 | Locked | INSERT session(
| 42667 | inspirehep | pcudssx1506.cern.ch:35370 | inspirehep |
          Query | 1 | Locked | INSERT session(
| 43961 | inspirehep | pcudssw1506.cern.ch:50829 | inspirehep |
          Query | 1 | Locked | INSERT session(
```

The DB was too busy (10+ load average) doing slow queries on other big
tables, so it could not process session queries fast enough because
the session table was also big because garbage collection was not run
there since many moons.  After the slow queries had been fixed and the
table truncated, the response was much faster.

(2) We can make session management lighter by several means, such as:

(2a) Possibly reduce number of SQL queries. Especially for
slashdot-like guest users that only come to a URL because of a tweet.
They are not authorised to anything, they just want to view a picture.

After the session cookie in the browser is created, we don't need to
keep much information, not update session parameters with respect to
session expiry (even for logged in users) much, etc.

If results of a query are not needed immediately, e.g. for session
expiry postponement, consider using `INSERT DELAYED`.  Although this
would tend to accumulate session queries in the DB stack, so this
should only be used for harmless queries indeed.

Technique like that possibly reduce number of SQL queries.

(2b) Switch from MyISAM engine to MEMORY engine.  We don't need to
remember sessions for too long, so they can be held in-memory only.
The memory tables can use B-tree or hash indexes; one can take
advantage of that.  Beware though of `max_heap_table_size` though,
which is something like 256 MB by default; we may need to increase it.

(2c) Switch from MyISAM engine to INNODB engine.  This should reduce
potential table lock contention issues too, since INNODB uses
row-level locking.

(2d) Switch to `memcached` or `redis` for session management.  This
would be very advatageous off-load MySQL fully.  Previous tests
indicated that both `memcached` and `redis` perform about similarly,
so we could take advantage of `redis` that could store session data
lazily onto disk and that could run replicated servers.

(2e) Use different DB hosts to store different sessions, and use
session-sticky haproxy balancing method.  This would be ultimate
session scalability technique for slashdot like scenarios in case we
have tens of web worker nodes.  This is something we can address
later.

(3) These were quick brain-dump notes only without much further
refinement.  We can discuss them IRL.

**Comment by jirikuncar** [comment]
Invenio 3 is using Flask-KVSession for lighter session management.
