### ISSUE TITLE
INSPIRE: Full first name does not search for any middle names

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1102]
Originally by *eduardob* on 2012-07-06

Hi Joe,

Received the following:

I noticed that searching for my paper with the string "a d'amico, guido"
does not retrieve any paper.
Instead, I need to use "a d'amico, g". However, this string retrieves
papers by another author with my same surname and first name initial.

I’ve confirmed this does happen but I don’t know why it does.

OK, fails for me too:

fin a o'connell,h [works]

fin a o'connell,heath [doesn’t work]

**Comment by jalavik** [comment]
Moved to appropriate INSPIRE channels.
