### ISSUE TITLE
xmlmarc2textmarc: do not modify record passed to create_marc_record()

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#1103]
Originally on 2012-07-09

When using the `create_marc_record()` facility, the signature is `create_marc_record(record, sysno, options)` and the returned value is a MARC record.

That function modifies the record passed, e.g 
```
del record["001"]
```
which is not desired, it should just output the textmarc.

**Comment by tiborsimko** [comment]
@jmartinm @jalavik @kaplun Was this addressed in the INSPIRE OPS code base perhaps?

**Comment by kaplun** [comment]
Nope!
