### ISSUE TITLE
WebAccess: case-insensitive check when adding accARGUMENT

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1110]
Originally on 2012-07-11

It is currently not possible to completely fix an authorization when one of the argument has been added with the wrong casing. Take for eg. the following case, where an admin mistakenly added an authorization for doctype "demopoe", instead of "DEMOPOE"

Admin adds:

```
action: Submit | role: anyUser | arguments: doctype=demopoe,act=*,categ=*
```

anyUser will not be able to submit to "DEMOPOE" because it does not match "demopoe". The admin then delete the authorization and try to add:

```
action: Submit | role: anyUser | arguments: doctype=DEMOPOE,act=*,categ=*
```

The newly added authorization will still use 'demopoe' casing, as it remained in the accARGUMENT table. It is necessary to remove the entry from the DB manually.

**Comment by tiborsimko** [comment]
Closing the issue, since Invenio 1.0 is very old stable release series, and a workaround exists. Invenio 1.0 users should really upgrade to latest Invenio 1.2 stable release series.
