### ISSUE TITLE
knowledge base: multiple entries

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1117]
Originally by *annetteh* on 2012-07-19

Some Inspire kb's seem to multiply their entries, e.g. kb 9:

E---Experiment-HEP
E---Experiment-HEP
E---Experiment-HEP
X---Experiment-Nucl
X---Experiment-Nucl
X---Experiment-Nucl

 or kb 7:
AAPPS Bull.---AAPPS Bull.
AAPPS BULL---AAPPS Bull.
BULL ASS OF ASIA PACIFIC PHYSICAL SOCIETIES---AAPPS Bull.
00346---AAPPS Bull.
AAPPS Bull.---AAPPS Bull.
AAPPS BULL---AAPPS Bull.
BULL ASS OF ASIA PACIFIC PHYSICAL SOCIETIES---AAPPS Bull.
00346---AAPPS Bull.
AAPPS Bull.---AAPPS Bull.
AAPPS BULL---AAPPS Bull.
BULL ASS OF ASIA PACIFIC PHYSICAL SOCIETIES---AAPPS Bull.
00346---AAPPS Bull.
 
Are they used at all? There seem to be 2 journal kb's and 2 subject kb's. Would be good to add in the description what they are used for.

- Annette

**Comment by jmartinm** [comment]
I guess the new `invenio-knowledge` has restrictions in place and this is not allowed anymore?

**Comment by tiborsimko** [comment]
Continuing in https://github.com/inveniosoftware/invenio-knowledge/issues/10.
