### ISSUE TITLE
WebSearch: "or" search with old arXiv ids fails

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1119]
Originally by *annetteh* on 2012-07-24

The search "arxiv:1105.5112 or arxiv:1105.5111 or arxiv:1105.5113" works perfectly fine. Using old-style arxiv nrs sometimes breaks an "or" search.
"arxiv:1105.5112 or hep-ex/0304038 or hep-ex/0307019" gives 73k results.

Search stage 1: basic search units are: [['+', 'arxiv:1105.5112', *, 'w'], ['|', 'hep-ex/0307019', *, 'w'], ['|', 'hep-ex/0304038', *, 'w'], ['|', 'or', *, 'w']]

"hep-ex/0304038 or hep-ex/0307019" gives no result.

Boolean query returned no hits. Please combine your search terms differently.
1	 	hep-ex/0307019
1	 	hep-ex/0304038
79087	 	or

**Comment by tiborsimko** [comment]
I think the issue was solved in https://github.com/inveniosoftware/invenio-query-parser.  If not fully, please re-open there.
