### ISSUE TITLE
Inveniocfg --update-config to regenerate help pages

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1120]
Originally on 2012-07-26

WebDoc pages can refer to some variables from config.py (for eg. CFG_SITE_URL, CFG_SITE_RECORD, CFG_SITE_NAME, etc.) such that it might be necessary to update the cache of these pages when some of these variables are changed.  It is proposed that `inveniocfg` is enhanced to take care of this task.

It would be sufficient to remove the cache files located at /opt/invenio/var/cache/webdoc, as these would be regenerated automatically upon access of the corresponding URL by a visitor. This removal could be triggered when running within function `inveniocfg.cli_cmd_update_config_py(...)`, and optionally also in `inveniocfg.cli_cmd_reset_sitename(...)` and `inveniocfg.cli_cmd_reset_siteadminemail(...)` such that the following would update the cache: 
```
$ inveniocfg --update-config
$ inveniocfg --update-all
$ inveniocfg --reset-sitename       # optional
$ inveniocfg --reset-siteadminemail # optional
```

Note that webdoc pages can make use of the following config variables:
```
CFG_SITE_NAME
CFG_SITE_SUPPORT_EMAIL
CFG_SITE_ADMIN_EMAIL
CFG_SITE_URL
CFG_SITE_SECURE_URL
CFG_SITE_RECORD
CFG_VERSION
CFG_SITE_NAME_INTL
```

-*Alternatively** a new option `--update-webdoc-cache` could be added to `inveniocfg` to avoid the need of regenerating cached pages for changes in the config that do not affect the above variables. 

-*Alternatively** it could also be possible to simply instruct the admin to manually remove the cache if needed at the end of running `--update-config`.

-*Additionally** it could be possible to add an option (and API) to `webdoc` CLI to clean the cache:
```
$ /opt/invenio/bin/webdoc --reset-cache
```

**Comment by jirikuncar** [comment]
WebDoc support has been removed in Invenio 3.
