### ISSUE TITLE
Inspire: experiment index

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1125]
Originally by *annetteh* on 2012-08-05

Currently only the complete name of an experiment, e.g. CERN-LHC-ATLAS, seems to be indexed, but not the parts of the name, e.g. ATLAS, like spires used to do. A search like "fin exp ATLAS" should work.

**Comment by jmartinm** [comment]
This still seems to be an issue:

https://inspirehep.net/search?ln=en&ln=en&p=fin+exp+ATLAS&of=hb&action_search=Search&sf=earliestdate&so=d&rm=&rg=25&sc=0

vs

https://inspirehep.net/search?ln=en&ln=en&p=fin+exp+CERN-LHC-ATLAS&of=hb&action_search=Search&sf=earliestdate&so=d&rm=&rg=25&sc=0

We can move this to our internal tasks as it is a matter of configuration, not of Invenio.

**Comment by jalavik** [comment]
Moved to INSPIRE Asana.
