### ISSUE TITLE
Citeform: quick fixes to limit user confusion

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#1127]
Originally on 2012-08-08

Here are some quick fixes we want on the cite form to limit the users' confusion:

See also #1028

- When searching for a reference, on the output format containing the search results, remove the search box at the top of the page.  The only way to search for references should be using the reference entry boxes on the citeform page.

- The "Search for Citation" link should not be clickable when the reference entry box is empty.

- There should be text - probably column headings? - indicating that the boxes on the left are for citation entry or text to search for a citation, and the items on the right are the formatted references for that citation - but only if it's a citeable reference (ie, it's in our HEP data set).

- There should be text somewhere on the page indicating that empty boxes on the left indicate a reference which isn't citeable in the HEP data set.  "No citeable reference found."  Or the boxes on the left that correspond to references that we don't have can have an asterisk in them perhaps. 

If you do the technical bits and don't know what wording to use for the wording bits, assign the ticket to Heath or Mike, and then follow up with an email explicitly telling them that they've had this ticket assigned to them.  Then they can write the wordings and re-assign the ticket to you.

**Comment by jirikuncar** [comment]
see https://github.com/inveniosoftware/invenio-csl-rest
