### ISSUE TITLE
citeform: a new frontend that has a giant pasteable box

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#1128]
Originally on 2012-08-08

The citation form is not very nice for people that want to give us their complete reference list.  We should have an alternate form where we still request their name and email address etc. but instead of the citation entry lines, we give them a big free-text box where they can cut and paste off their PDFs.  Then it still gets turned into an RT ticket as before.

The existing citeform and this one should interlink so users can find this one easily.

**Comment by jirikuncar** [comment]
See https://github.com/inveniosoftware/invenio-csl-rest
