### ISSUE TITLE
Guess about quoting in mixed search styles

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#113]
Originally on 2010-06-07

For searches of the style:
author:Vigen, jens auther:brooks, t

(note the lack of conjunction)

...the user may mean to do author:vigen, and keyword:jens and author:brooks, and keyword:t.  But probably not.

At least for author searches, and maybe for all searches, it would be nice to do this search twice.  Once as input, and once with all the bits between index keywords ("author:", "affiliation:", "date:", etc.) quoted.  These result sets should be compared, and one of the following did-you-mean behaviors displayed:
* If user input set is 0 and quoted results >0, note that user input gave no results and show quoted results
* If user input set is >0 and quoted results >0, ask "Did you mean" with the quoted set, and make that clickable.
* If user input set is >0 and quoted results 0, show user input results with no note.
* If user input set is 0 and quoted results 0, do normal no results returned.

**Comment by tiborsimko** [comment]
> What today would prove if we still have such bug?

SPIRES queries such as `find a some thing and t another thing`, if they are not expanded properly.  Kind onf like adding silent quotes or parentheses around terms (`author:"some thing" title:"another thing").  If nothing like RT83478 persists or popped up anew, this old issue can be closed.

**Comment by kaplun** [comment]
@tiborsimko on current INSPIRE this is evaluated as:
`'(author:"thing, some*" or exactauthor:"thing, s *" or exactauthor:"thing, s" or exactauthor:"thing, so" or exactauthor:"thing, som" or author:"some thing, *") and (title:another and title:thing)`

which seems correct to me. (beside the split between another and thing)

So I'll close this issue.
