### ISSUE TITLE
BibHarvest OAI-PMH server performance improvement

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1150]
Originally by *vbanos* on 2012-08-20

Current OAI-PMH server functions (file: oai_repository_server.py):
* get_modification_date, 
* get_earliest_datestamp, 
* get_latest_datestamp
do the following actions:
* retrieve a record's datetime from mysql with an SQL SELECT,
* parse it to python datetime
* convert it to UTC and return it
All this processing is done in function localtime_to_utc.

The suggested improvement is that datetime is convert to UTC inside the SQL SELECT using mysql function CONVERT_TZ.

The result is better performance and less python code.

**Comment by jirikuncar** [comment]
OAI-PMH harvester has been rewritten in Invenio 3.
