### ISSUE TITLE
SRU service implementation

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1153]
Originally by *vbanos* on 2012-08-21

We are implementing SRU (http://www.loc.gov/standards/sru/) API support for Invenio ( (http://invenio-software.org/wiki/Talk/WebAPIs).

In a few words, SRU requests are sent via HTTP URLs and responses are XML documents. There are three main commands: explain, searchRetrieve and scan.
* **explain** provides repository information
* **searchRetrieve** is about searching and retrieve metadata records
* **scan** is used to request a range of the available terms at a given point within a list of indexed terms

We have already implemented explain and searchRetrieve.

We have two remaining issues to complete our task:
* scan command requires query parameters formatted in CQL language (http://www.loc.gov/standards/sru/specs/cql.html). We have found a python library that parses CQL and generates a tree http://srw.cheshire3.org/downloads/ but we don't know how to generate an invenio query from the tree. Any ideas?
* searchRetrieve and scan commands query all records and return metadata as results. Is it necessary to do any security/authentication checks before returning the results?

**Comment by tiborsimko** [comment]
Closing as per the closure of #2319.  As @kaplun mentions, if wanted let's open a new issue in `invenio-search` to implement SRU support on top of the new `master` code base.
