### ISSUE TITLE
Extending BibDoc restriction to allow mixing firerole rules/roles/groups

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1154]
Originally on 2012-08-22

Currently BibDocs can be restricted via `FFT`} tags by using the `$r` subfield according to the syntax described in [http://invenio-demo.cern.ch/help/admin/bibupload-admin-guide#3.6].

So far, admins can specify the restriction of a BibDoc by setting either:
* a single *status* matching a WebAccess authorization for the action `viewrestrdoc`
* a single WebAccess *role*
* a single *group*
* a single *email address*
* a single *firerole rule*

It is advisible to be able to combine the above and let the admin to specify e.g. a firerole rule **and** a group or multiple groups, etc.

**Comment by jirikuncar** [comment]
Complex restrictions can be added to buckets in Invenio-Files-REST.
