### ISSUE TITLE
WebSearch: Better "Snippets courtesy of FOO" label

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1169]
Originally by *[pglauner](https://github.com/pglauner)* on 2012-09-12

"Snippets courtesy of FOO" shall only be displayed if FOO is stored in the future "courtesy" field or "courtesy" property in the "moreinfo" store of a bibdoc.

**Comment by jirikuncar** [comment]
Please re-open in `invenio-documents` if it's still relevant.
--
cc @CERNDocumentServer
