### ISSUE TITLE
WebComment: improve handling of long comments

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1173]
Originally on 2012-09-20

Comments are stored in column *body* of table *cmtRECORDCOMMENT*, which is currently defined as *text*. This limits the length of each comment to max 65535 characters, which can be reached in several typical use cases (taking into account the HTML markup that could be part of the comment).

It should be considered if the column type should be increased to *mediumtext*.

Furthermore the business logic should catch any attempt at exceeding this limit to prevent any data loss: this could be done client-side to not let the user enter more that N characters, and/or server-side with an error message reported to the user upon submission. 
Alternatives could for eg. consider the creation of a second (or third, fourth, etc) comment in the table with the remaining text, marking this additional comment as part 2 (or 3, 4) in a newly added column (which would then be resolved to a single comment on the display).

**Comment by jirikuncar** [comment]
Invenio 1.x is in feature freeze state.

(example of length validation: https://github.com/inveniosoftware/invenio-files-rest/blob/023762ea621ae9e3dfe549d3b9fc0823d0e709c2/invenio_files_rest/models.py#L561-L567)

--
cc @inveniosoftware/triagers
