### ISSUE TITLE
Webalert: API to get current alerts also in non-HTML form for processing

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1212]
Originally by *arwagner* on 2012-11-21

Up to Invenio 1.0.2 it is not possible to retrieve alerts set by a user in non-html formatted form. However, in scenarios with automatic alert setup this is highly desirable, especially as one needs a bunch of parameters to remove (and thus regenerate) an automatically generated alert.

It is thus proposed to add an API function in webalert. This could look like this:

----
```
def get_alerts(uid, ln=CFG_SITE_LANG):
    """perform_list_alerts display the list of alerts for the connected user"""
    # set variables
    out = ""

    # query the database
    query = """ SELECT q.id, q.urlargs,
                       a.id_basket, b.name,
                       a.alert_name, a.frequency,a.notification,
                       DATE_FORMAT(a.date_creation,'%%Y-%%m-%%d %%H:%%i:%%s'),
                       DATE_FORMAT(a.date_lastrun,'%%Y-%%m-%%d %%H:%%i:%%s')
                FROM user_query_basket a LEFT JOIN query q ON a.id_query=q.id
                                         LEFT JOIN bskBASKET b ON a.id_basket=b.id
                WHERE a.id_user=%s
                ORDER BY a.alert_name ASC """
    res = run_sql(query, (uid,))
    return res
```
----

and just encapsules the necessary db query nicely.

**Comment by jirikuncar** [comment]
Invenio 1.x is in feature freeze state. Please follow development of Invenio 3 packages.
