### ISSUE TITLE
BibKnowledge: import or link to textual KB file

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1215]
Originally on 2012-11-21

It would be useful for BibKnowledge to use knowledge base files as input source, such as BibConvert KB files (one rule per line, triple-dashes separated from-to values). Upon creation of such KB, only the path to the KB file would be recorded, and mappings would be resolved using this file. A caching mechanism could be implemented to make sure that a value is always returned, even if the input source is not available (eg. network issue, AFS, file deleted, etc.). It would not be possible to update such KB via the BibKnowledge interface (read-only).

In addition BibKnowledge should also be able to import such input file (one-short import, instead of linking to the file) to create a regular KB (editable, but not synchronized with the KB file).

See also related #1214

**Comment by hachreak** [comment]
can we move the issue to https://github.com/inveniosoftware/invenio-knowledge ? :)

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-knowledge #18](https://github.com/inveniosoftware/invenio-knowledge/issues/18) via [**ZenHub**](https://www.zenhub.com/)
