### ISSUE TITLE
WebSearch: display numbering when returning multiple records using the HTML MARC format

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1239]
Originally by *[nkasioum (@kasioumis)](https://github.com/kasioumis)* on 2012-12-17

Related to [RQF0180751](https://cern.service-now.com/service-portal/view-request.do?n=RQF0180751):

> Why are the records in a MARC21 display not numbered at all? The absence of numbering makes it very awkward to identify records when one has a printout of a lot of records. When I have such a printout, the first thing I have to do is to go through it and write in the numbers 1, 2, 3, 4, etc. This shouldn't be necessary.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 3+ years.

--
cc @inveniosoftware/triagers
