### ISSUE TITLE
RFC collections: misleading breadcrumbs and multiple parent collections

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1241]
Originally by *fcosta* on 2012-12-19

Apprently linked to the multiple (and obsolete) parent collections, misleading crumbreads appear, at least in cds like:

Home > Administrative Support (AS) > Translation and Minutes 

Obsolete parent collections links are left apparently because it is not easy to suppress them (not possible in WebSearch UI.

**Comment by jirikuncar** [comment]
I have a related question. Do we still want to allow multiple parents for a collection? Wouldn't be easier to allow only "forest" of collections. Then for each collection there is only one path to the root.

convert:
```
    A
   / \
  B   C
 /
C
```
to:
```
    A
   / \
  B   D
 /
C
```
where `D.dbquery := C.dbquery`.

Is anybody using it in production? (cc @invenio-developers)

**Comment by tiborsimko** [comment]
To add to @jirikuncar's question, there's also an issue of regular vs virtual collection tree.  A collection may be attached to the regular tree in one place and have one regular parent there, all the while it is also attached to the virtual collection tree and having one or more regular parents there.  If most Invenio sites aim at the simplification of the collection tree, leaving the job for later faceting, we may want to restrict all the various possibilites in Invenio 2, especially if they are "underused" in Invenio 1.

**Comment by egabancho** [comment]
Answering @jirikuncar question, we have this situation in CDS in a few places
```sql
mysql> select id_son, count(*) c from collection_collection group by id_son having c > 1;
+--------+---+
| id_son | c |
+--------+---+
|      3 | 2 |
|      5 | 2 |
|     16 | 2 |
|     19 | 2 |
|     20 | 2 |
|     22 | 2 |
|     23 | 2 |
|     24 | 2 |
|     25 | 2 |
|     26 | 2 |
|     27 | 2 |
|     30 | 3 |
|     31 | 3 |
|     32 | 3 |
|     33 | 3 |
|     34 | 3 |
|     35 | 4 |
...
```
One of the most visible examples could be the collection `Presentations & Talks` which is attached to two different regular parents, also `Academic Training Lectures` which it is attached to a regular parent and to a virtual parent, but the relation with the parents is regular in both cases.
If needed I can try to list the different situations we have, but probably we cover most of them ;-)

**Comment by tiborsimko** [comment]
>One of the most visible examples could be the collection Presentations & Talks which is attached to two different regular parents [...]

However is this still wanted, considering the ongoing simplification of the collection tree?

**Comment by egabancho** [comment]
@tiborsimko you are right, I should check the new collection tree for this kind of situations.

**Comment by jirikuncar** [comment]
Shall we change the collection graph to collection tree where each collection has only a single parent?

- [ ] single parent for collection
- [ ] decide on tree structure encoding

**Comment by kaplun** [comment]
:+1: as this would simplify authorization policy. For a given collection it would be always clear (given the chain of parents) whether it is public or not.

**Comment by tiborsimko** [comment]
> @tiborsimko you are right, I should check the new collection tree for this kind of situations.

Good, please check if this is still wanted, and let's proceed from that.

**Comment by jirikuncar** [comment]
[Invenio-Collections](https://github.com/inveniosoftware/invenio-collections) is using nested sets that prevent this problem.
