### ISSUE TITLE
WebLinkback: introduce limit on number of trackback registrations per IP, per second

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1246]
Originally on 2013-01-10

Similarly to WebComment which can limit the number of comments submitted by a unique user in a given time window (CFG_WEBCOMMENT_TIMELIMIT_PROCESSING_COMMENTS_IN_SECONDS, CFG_WEBCOMMENT_TIMELIMIT_PROCESSING_REVIEWS_IN_SECONDS), it would be good to introduce a mechanism to limit the number of trackback registrations a given IP can submit in a chosen time window (eg. 1 per day?). 

The idea would be to limit a bit the possibilities for spammers to make use of the trackback feature (the implementation of the ticket might only have a very limited impact though. It could be checked if better alternatives exist, but on the other hand this solution should be trivial to implement).

**Comment by jirikuncar** [comment]
Invenio 1.x is in a feature freeze. We recommend to disable WebLinkback in production.
