### ISSUE TITLE
GoogleBot and language support

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1251]
Originally on 2013-01-14

From [Savannah Task #8149](https://savannah.cern.ch/task/?8149)
----
GoogleBot is indexing all the languages of CDS interface. This might not be desirable since in any case the record in CDS are mainly in English. 
This is due to the sitemap sporting all the language URLs and to letting Google follow the language URLs at the bottom. We might wish to add a 'rel="nofollow"' attribute to such URLs and to instruct sitemap generator not to generate a link per every language.
----
Tibor adds:
On the contrary, it is desirable to let crawlers index all I18N collection splash pages, because if someone searches in google.fr for, say: 
"thèses de doctorat au CERN" 
then if we would have had properly translated collection names on CDSWEB 
(that we do not have still), then those users would discover our pages 
only if we allow indexing of `?ln=fr'. 

It is therefore better to solve the Google language detection issue in another way, e.g. by providing HTML meta headers like: 
```
<meta http-equiv="Content-Language" content="fr">
```
for French pages. 
This is done now. (committed 2008-11-27) 

That said, it would be indeed useful to populate {noindex,nofollow} properties in 
our pages everywhere, e.g. in the detailed record tabs.

**Comment by tiborsimko** [comment]
@kaplun IIRC this was already sufficiently addressed?

**Comment by kaplun** [comment]
Yes: although Google nowadays complains about our implementation. I have not yet figured out what is wrong with it though.
