### ISSUE TITLE
WebSearch: introduce 'bypassrglimit' action

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1254]
Originally on 2013-01-15

3ef9e5fa introduced the possibility for BibEdit users to bypass the limit for parameter 'rg' in search results. It is proposed to also let a distinct category of users to go over the limit, by introducing a "bypassrglimit" action (name to be refined).

Optionally one could even think of passing the limit as an optional parameter of the action, such that different roles could be granted different limits.

**Comment by jirikuncar** [comment]
Invenio 1.x is in feature freeze state.

**Comment by tiborsimko** [comment]
The feature was actually implemented in 89f7509cf300e68f763f989de4babbea5839819c.

**Comment by tiborsimko** [comment]
(as curators were deemed enough of a user category for this feature)
