### ISSUE TITLE
Updating Search Guide: ref to spires

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1257]
Originally by *annetteh* on 2013-01-17

From S-NOW ticket: [RQF0186727](https://cern.service-now.com/service-portal/view-request.do?n=RQF0186727)

[...]
would be great to update the spires references in the search guide
https://cds.cern.ch/help/search-guide

How to get documents from other servers (Google, SPIRES, KEK)
On the search results page, links to other servers like Google, SPIRES or KEK are automatically proposed in a box entitled "Try your search on". You can simply click on the proposed links to run your query on these search engines.

Note that the links aren't printed if the search engine doesn't support it. For example, SPIRES or KEK cannot search for terms within "any field", so we don't link to them in these cases.

The last sentence isn't even true I think. I have the impression that the box always looks the same regardless of the search. But I didn't check this extensively.
[...]

**Comment by kaplun** [comment]
This is really overlay specific.

It can be implemented as a separate package based on sphinx that can override the "documentation" package in Invenio
