### ISSUE TITLE
Lazy missing formats updates

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1264]
Originally by *[adeiana (@Osso)](https://github.com/Osso)* on 2013-01-21

This is related to http://invenio-software.org/ticket/985 but with a smaller goal.

Currently we compute the format on the fly when no format is stored in the database.
This patch allows us to to not waste that result and save it instead.

This allows us to remove queries for missing formats in bibformat.

**Comment by jirikuncar** [comment]
Closed via e6cfeffcfba5406740e9dab3dc28536e864780fd
