### ISSUE TITLE
OAIRepository: case sensitive setSpecs

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1265]
Originally on 2013-01-22

The OAI Repository returns a wrong response when one harvests using a setSpec with a casing different from the one defined by the server. For e.g. retrieving set "CERN" from the demo site is fine:

http://invenio-demo.cern.ch/oai2d?verb=ListRecords&metadataPrefix=oai_dc&set=CERN

while harvesting using lowercase "cern" is not (the server will mark the records in this set as deleted):

http://invenio-demo.cern.ch/oai2d?verb=ListRecords&metadataPrefix=oai_dc&set=cern

A selective harvesting using a non-existing set (whatever letter case) returns a correct answer:

http://invenio-demo.cern.ch/oai2d?verb=ListRecords&metadataPrefix=oai_dc&set=foo

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 3 years. Check https://github.com/inveniosoftware/invenio-oaiserver for updates.

cc @inveniosoftware/triagers
