### ISSUE TITLE
strip leading/trailing whitespace from query parameters

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1266]
Originally by *[Thorsten (@tsgit)](https://github.com/tsgit)* on 2013-01-23

uri: </search?ln=en&p=8564_y%3A%22super-kamiokande%22&of=hb&action_search=Search&ot=%20502>

there is a space in front of 502 in search parameter   &ot= 502

this triggers the exception below and an unhelpful error message. I think leading and trailing spaces should be stripped from key/value parameter assignments

Cheers
Thorsten

---------- Forwarded message ----------
From: admin@inspire-hep.net via RT <admin@inspirehep.net>
Date: Tue, Jan 22, 2013 at 10:39 PM
Subject: [INSPIRE-HEP #270335] Exception (connections.py:35:defaulterrorhandler) at http://inspirehep.net
To: 

----------------------------------------------------------------------------------------
Tue Jan 22 21:39:30 2013: REQUEST 270335 WAS ACTED UPON
----------------------------------------------------------------------------------------
Transaction:    Ticket created by admin@inspire-hep.net
Queue:          Admin
Subject:        Exception (connections.py:35:defaulterrorhandler) at http://inspirehep.net
Owner:          Nobody
Requestors:     admin@inspire-hep.net
Status:         new
Ticket URL:     https://inspirert.cern.ch/Ticket/Display.html?id=270335
----------------------------------------------------------------------------------------

Hello:

This exception has already been seen 86 times
    last time it was seen: 2013-01-18 09:14:49
    last time it was notified: 2013-01-18 09:14:26

- 2013-01-23 06:39:17 -> ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS b, bibrec_bib 5x AS bb WHERE bb.id_bibrec=1211443 AND b.id=bb.id_bibxxx AND b' at line 1") (connections.py:35:defaulterrorhandler)

-* User details
                                     agent: Mozilla/5.0 (X11; Linux x86_64; rv:18.0) Gecko/20100101 Firefox/18.0
                                     email: guest
                                     group: []
                                     guest: 1
                                  nickname:
            precached_canseehiddenmarctags: False
precached_permitted_restricted_collections: []
                        precached_useadmin: False
                       precached_usealerts: False
                      precached_useapprove: False
                      precached_usebaskets: False
                       precached_usegroups: False
                        precached_useloans: False
                     precached_usemessages: False
             precached_usepaperattribution: True
                   precached_usepaperclaim: False
                        precached_usestats: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: <>
                               remote_host:
                                 remote_ip: 76.26.96.182
                                   session: d83aab1f3e290f91250fc85b39964ef0
                                       uid: 0
                                       uri: </search?ln=en&p=8564_y%3A%22super-kamiokande%22&of=hb&action_search=Search&ot=%20502>

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 3 years. Check https://github.com/inveniosoftware/invenio-query-parser for updates.

cc @inveniosoftware/triagers
