### ISSUE TITLE
BibMatch: be smarter about big data

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#1273]
Originally on 2013-01-30

Currently, BibMatch first loads all records to match given as input into records and processes them one-by-one. When you have a long list of thousands of records you want to match, this process becomes slow and unreliable + after enough memory is filled it makes the computer slow or crash completely.

BibMatch should rather lazily load in records from the input source and avoid the large memory footprint.

Similarly, when validating MARC tags that may have several fields (such as our famous 3000 authors in collaboration papers) the validation becomes slow and at some point - pointless due to the shear number of authors.

For this case it would be good to either detect and avoid comparing collaboration authors or compare a select few, for example the 10 first etc.

**Comment by jalavik** [comment]
Will be deprecated in favor of https://github.com/inspirehep/invenio-matcher.

**Comment by jacquerie** [comment]
...which I'm finishing right now. Progress here: https://github.com/jacquerie/invenio-matcher/tree/new-architecture.
