### ISSUE TITLE
Simplify API to upload MARXML

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1276]
Originally on 2013-01-31

Currently, the most developer friendly way to upload MARCXML is to save it to disk, and then call `task_low_level_submission`.

E.g. in `Insert_Record.py` (websubmit function:
```python
[...]
from invenio.bibtask import task_low_level_submission, bibtask_allocate_sequenceid

[...]
    sequence_id = bibtask_allocate_sequenceid(curdir)
    if os.path.exists(os.path.join(curdir, "recmysql")):
        recfile = "recmysql"
    else:
        raise InvenioWebSubmitFunctionError("Could not find record file")
    initial_file = os.path.join(curdir, recfile)
    tmp_fd, final_file = tempfile.mkstemp(dir=CFG_TMPDIR,
                                          prefix="%s_%s" % \
                                          (rn.replace('/', '_'),
                                           time.strftime("%Y-%m-%d_%H:%M:%S")))
    os.close(tmp_fd)
    shutil.copy(initial_file, final_file)
    bibupload_id = task_low_level_submission('bibupload', 'websubmit.Insert_Record', '-r', '-i', final_file, '-P', '3', '-I', str(sequence_id))
    open(os.path.join(curdir, 'bibupload_id'), 'w').write(str(bibupload_id))
[...]
```

In principle it should be possible to simply have an API such as:

```python
from invenio.bibupload import schedule_bibupload
[...]
schedule_bibupload(user, mode, marcxml, ...)
[...]
```

that will take care of saving somewhere to disk the marcxml and schedule a bibupload task for you and return the task ID.

Additionally we can think of a synchronous version that will block and wait for termination (e.g. by polling the `schTASK` table.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 3 years. Check https://github.com/inveniosoftware/invenio-records-rest for new REST API.

cc @inveniosoftware/triagers

**Comment by kaplun** [comment]
On legacy one might also want to profit from an INSPIRE utility: https://github.com/inspirehep/inspire/blob/master/miscutil/lib/bibtaskutils.py
