### ISSUE TITLE
WebNews: new module to handle site news stories and present them to the user through a dedicated interface and discreet notifications

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1288]
Originally by *[nkasioum (@kasioumis)](https://github.com/kasioumis)* on 2013-02-07

Users are often interested in reading about all the significant changes on the site, in the form of news, concerning usability, appearance, content etc. At the same time administrators want to keep a history of all those news. The WebNews module suggests the creation of an infrastructure that will enable the administrators to add and manage news and the users to be informed at will through complete articles as well as through discreet notifications in the form of tooltips. Read more at the [WebNews](http://invenio-software.org/wiki/Development/Modules/WebNews) RFC wiki page.

Development: see [master-webnews](http://invenio-software.org/repo/personal/invenio-nkasioum/log/?h=master-webnews) branch.

**Comment by jirikuncar** [comment]
see https://github.com/inveniosoftware/invenio-news
