### ISSUE TITLE
WebSearch: searching restricted collections needs improving

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio#1295]
Originally on 2013-02-11

Currently, it is not possible to search only specific restricted collections from the home collection. The search will also add by default all the restricted children of the home collection that the user is allowed searching on.

**Comment by jirikuncar** [comment]
Can somebody confirm if it is still the case in #2587?

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
