### ISSUE TITLE
BibFormat: add support for the Google +1 button

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1296]
Originally by *[nkasioum (@kasioumis)](https://github.com/kasioumis)* on 2013-02-12

Along with the other bookmarking services, support for the Google +1 button could be offered to the user.

**Comment by kasioumis** [comment]
Updated fix at https://github.com/kasioumis/invenio/commit/129bf564bd79b47f099521db77be9f175907e59b

**Comment by egabancho** [comment]
For some reason this issue was never closed via a018bdbb2ca24f263d8a389a642d7d8a31f9e137
