### ISSUE TITLE
BibFormat: prettify the bookmark element icons

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1297]
Originally by _[nkasioum (@kasioumis)](https://github.com/kasioumis)_ on 2013-02-12

The default bookmark icons could be prettified to reflect the modern logos of some of the offered services.

**Comment by kaplun** [comment]
@ludmilamarian @switowski @egabancho this is only used on CDS...

**Comment by ludmilamarian** [comment]
Sure, we can close it. We might have a mega-branch containing this as well, we will see if time permits to clean it.
