### ISSUE TITLE
BibUpload: configurable DOI tag

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1298]
Originally on 2013-02-12

In fc4e5a42e3210fd00c727b2505764b801403a50b resulted from #1160, a new facility to verify DOI uniqueness during upload was merged.  However, the DOI field there is hard-coded to be `0247_`.  The DOI field location should be made configurable via techniques similar to `CFG_BIBUPLOAD_EXTERNAL_OAIID_TAG`.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 3 years. Check https://github.com/inveniosoftware/invenio-pidstore for DOIs management.

cc @inveniosoftware/triagers
