### ISSUE TITLE
WebSubmit: apply wash_for_xml() to form fields

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1308]
Originally on 2013-02-14

Currently, `wash_for_xml()` is implicitly called before creating the MARCXML representation of a record from the just-submitted metadata. 
This is useful in order to prevent bad situation where the XML is not valid at all.

However there are other situations where it would be nice to still strip away "bad" UTF-8 characters (e.g. when the raw values are passed to the LaTeX stamping function).

A radical solution to this issue would be to wash for bad characters in the early stages of submission, when the submitted form is parsed and is about to be written to disk, i.e. in `websubmit_engine.interface()` and `websubmit_engine.endaction()`.

**Comment by tiborsimko** [comment]
WebSubmit is deprecated in favour of `invenio-deposit`.
