### ISSUE TITLE
BibSort: use pluginutils for the washer functions

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio#1316]
Originally on 2013-02-18

Since each Invenio installation might benefit from custom defined washer functions, BibSort could be extended to use plugin-based washer functions instead of `bibsort_washer.py`. The pluginutils module can be used for loading these functions.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 3 years. Check https://github.com/inveniosoftware/invenio-search package that uses Elasticsearch.

cc @inveniosoftware/triagers
