### ISSUE TITLE
Introduce "useverbose" action to configure "verbose" usage authorization

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1321]
Originally on 2013-02-20

In c11ccd29586b66d05a44d93f5369fa0323ca4ec6 the `verbose` URL query argument has been restricted only to superadmins.

There are however several cases in which some non admin would like to use it for debug certain situation in a production environment. E.g. to debug BibFormat templates or user settings, etc.

It would be nice to introduce a new `useverbose` action in the WebAccess stack, optionally parameterized with e.g. a `scope` keyword which could have values such as:

- `BibFormat`
* `WebSearch`
* `WebSession`

**Comment by jirikuncar** [comment]
Invenio 1.x is in feature freeze state.
