### ISSUE TITLE
deposit: metadata extraction

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#1381]
Originally on 2013-03-07

1) XMP
2) Online services like Mendeley, CrossRef, DataCite, ORCID, Sherpa/Romea/Julliet

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-deposit #99](https://github.com/inveniosoftware/invenio-deposit/issues/99) via [**ZenHub**](https://www.zenhub.com/)
