### ISSUE TITLE
WebSearch: stringIO is passed to collect_user_info as req

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1404]
Originally on 2013-03-15

It is a typical usage pattern of simulating the `req` object by initializing it with a `StringIO()` object (especially in CLI scripts).
## The `search_engine.py` module should in this case be careful and dont't pass this to `webuser.collect_user_info()`. Alternatively this should return by default a guest user in this case.

Note this is connected with: INSPIRERT ticket 278223

**Comment by tiborsimko** [comment]
@kaplun Can be this closed?
