### ISSUE TITLE
BibCirculation: holding logical fields

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1407]
Originally on 2013-03-18

In CDS, within the Books collection, it exists an [eBooks](http://cds.cern.ch/collection/eBooks) virtual collection. This is based on a tag in the metadata. However it does not exist a corresponding physical book collection. 

This is not currently possible as the information whether a book has holdings is contained only in the db.

For this reason it would be necessary to create a holdings logical fields (a bit like we have journal etc.) that can then be used to create appropriate collection

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-circulation #19](https://github.com/inveniosoftware/invenio-circulation/issues/19) via [**ZenHub**](https://www.zenhub.com/)
