### ISSUE TITLE
BibCirculation: move CFG_BIBCIRCULATION_HOLIDAYS to the database

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1413]
Originally on 2013-03-19

Add a convenient web interface (and a corresponding table in the database) to edit the BibCirculation holiday periods, instead of having them hard-coded in `CFG_BIBCIRCULATION_HOLIDAYS` (in `bibcirculation_config.py`, which gets overwritten after each upgrade).

**Comment by jirikuncar** [comment]
We could also source an external calendar (iCal) with holidays.

**Comment by tiborsimko** [comment]
Closing this issue that will be better addressed in the new circulation module that is under development.  CC @mvesper @ludmilamarian @kasioumis @egabancho
