### ISSUE TITLE
formatter: Integrate citation formatter from citationstyles.org

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#1416]
Originally on 2013-03-20

http://crosscite.org/citeproc/ provides a DOI citation formatter with tons of citation styles. Unfortunately the it's not possible to just send a GET request with DOI to the URL, due to some AJAX loading.

The code behind the citation formatter is openly available as well as the citation styles at:
https://github.com/crosscite/citeproc-doi-server
https://bitbucket.org/fbennett/citeproc-js/
http://citationstyles.org/
https://github.com/citation-style-language/styles

**Comment by jirikuncar** [comment]
@lnielsen is it already implemented in https://github.com/zenodo/zenodo/tree/3e4f89a0f1236b330d2665ccb2b141d2ff68e0a5/zenodo/modules/citationformatter ? Shall me move it to Invenio?

**Comment by lnielsen** [comment]
The Zenodo citation formatter relies on a DOI, so I don't think it's appropriate to integrate in Invenio (first it doesn't rely on loca metadata, second not all records have DOIs). If anybody needs it at somepoint, we can externalize the Zenodo implementation in its own package.

I'll close the issue.
