### ISSUE TITLE
WebSession: support for concurrent authentication

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1420]
Originally on 2013-03-21

It should be possible to authenticate at the same time with multiple external authentication providers (e.g. arXiv and Orcid). In a given moment it should be possible to know what is the current login method of the user.

This could be implemented with the following steps:
1. enhancing `websession.loginUser()` by carefully storing *external settings* (currently namespaced by `EXTERNAL_` prefix) with a further namespace (e.g. say the login_method is `foo` then external settings provided by it would be prefixed with `EXTERNAL___foo___` (or some better spacing).
2. additionally store in the user_settings (committed with the call to `set_user_preferences()` the *stack* of authentication method (e.g. in a variable key called `authentication_methods` which could contain a list of authentication methods, with the first being the last one used. Indirectly, this information is going to be available in `user_info = collect_user_info(req)`
3. `loginUser()` should be further enhanced in order to directly manage `userEXT` table by directly and matching users. There are several workflows to be considered: let's assume the user is already authenticated with login method `foo1` as external_id `bar1` with uid `123` and the user logs in now with login_method `foo2` and external_id `bar2`:
   - if `foo2:bar2` is already known to the system:
     - if the uid matches the current uid, nothing to be changed
     - if the uid is different, **the two users need to be merged**.
   - if `foo2:bar2` is not already known then **a new row must be added in userEXT** with `uid:foo2:bar2` combination and nothing more have to be done.

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
