### ISSUE TITLE
WebSession: support for multiple emails

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1421]
Originally on 2013-03-21

Up to know the email address played a central role in Invenio, often considered as unique identifier for a user.

With Invenio supporting multiple authentication method (possibly concurrently), it is very likely that user have multiple email addresses that he might desire to be recognized in Invenio.

This require amending the current database tables structure in particular by introducing a new table `userEMAIL`

e.g.:

```sql
CREATE TABLE IF NOT EXISTS userEMAIL (
  id_user int(15) unsigned NOT NULL,
  email varchar(255) NOT NULL default '',
  priority int unsigned NOT NULL,
  PRIMARY KEY email (email),
  KEY id_user (id_user),
) ENGINE=MyISAM;
```

The `email` column in `user` table could be kept in order to maintain track of the *preferred* email address for the user for communications.

Special care must be devoted in adapting APIs (e.g. `collect_user_info` and friends in order to take into consideration the availability of more than one email address.)

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
