### ISSUE TITLE
global: set 'ln' parameter when calling 'page_not_authorized(..)'

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1423]
Originally on 2013-03-22

The generic page for access failures is rarely displayed in user's language, but `CFG_SITE_LANG`, as the language parameter is rarely passed when calling `webuser.page_not_authorized(..)`.

It would be nice to update the codebase globally, or have the `webuser.page_not_authorized(..)` to extract the language information from the given `req` object.

**Comment by jirikuncar** [comment]
Not needed in 2.x. Please re-open if needed for 1.x.
