### ISSUE TITLE
Webstat: Adding a search-by-collection feature to Custom Query.

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1434]
Originally by *stmartin* on 2013-03-27

The Custom Query Summary page on WebStat does not currently allow the user to ask for stats by collection. This can be implemented by adding a search box for collections, while making sure the user can only mention collections he is permitted to access, given the roles he is connected to.

**Comment by tiborsimko** [comment]
@ludmilamarian @kasioumis @egabancho Do you know if this is still of interest?  In theory, one can add to the query a term like "collection:THESIS".  (Using 980 values, not collection names.) This works well in Invenio v2.1 with collection names, actually.

**Comment by ludmilamarian** [comment]
I think this is something that we will tackle in the new ES based statistics module, so we can close this one.
