### ISSUE TITLE
BibSched: add filter for done tasks

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#1442]
Originally on 2013-04-02

Whenever going through the done tasks in bibsched, a quite common use case is to just want to see the tasks that had an error (or were ACKd)

Currently it is a tedious process to find those tasks so a command (say F) could be added an a prompt shown to the user to decide how to filter the tasks.

Some ways of filtering could be only ERROR tasks, only bibuploads, ...

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 3 years. Lot of improvements have been added since then ;)

cc @inveniosoftware/triagers
