### ISSUE TITLE
Link from edit page to physical copies absent for some records

### ISSUE THREAD

**Issue by rsripada** [inveniosoftware/invenio#1448]
Originally on 2013-04-04

The button 'Edit physical copies'(as in https://cds.cern.ch/record/edit/?ln=en#state=edit&recid=1537426)is absent for some records with physical copies.

Ex. https://cds.cern.ch/record/edit/?ln=en#state=edit&recid=229771

This record entry should have a button linking to

https://cds.cern.ch/admin2/bibcirculation/get_item_details?ln=en&recid=229771

**Comment by tiborsimko** [comment]
This was closed in the meantime by 8b0feb06b744a19fb605a59e650c7bada731b15a.
