### ISSUE TITLE
BibSched: monitor termination after timeout

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1450]
Originally on 2013-04-04

The bibsched monitor is basically always started via an *SSH* connection. If this drops (and the admin has not used tools such as `screen`, the bibsched process will stay there running idle forever (consuming SQL connection and resources).

It would be nice if there was a timeout (e.g. 24 hours) after which, if no key is pressed, the monitor terminates on its own.

**Comment by tiborsimko** [comment]
I guess the admins usually use `screen` or `tmux` to prevent this issue.
