### ISSUE TITLE
BibSched: recurrent task configuration

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1452]
Originally on 2013-04-05

In big Invenio installations it is common to have several recurrent bibtasks (and bibtasklets) that embed the policies and processes that are little by little improved. 

It would be great to be able to dump the set of recurrent bibtasks (regardless of their task id, and runtime) and then be able to load the configuration back (by either substituting the current recurrent tasks configuration or by adding just the missing tasks) (a bit like in webaccessadmin).

The dumped configuration could be stored by default in a file under `etc/bibsched/bibsched.cfg` and be implemented, e.g. as a list of strings to replay the task list.

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
