### ISSUE TITLE
WebSearch: EN DASH leads to invalid basic search units

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1454]
Originally by _[Thorsten (@tsgit)](https://github.com/tsgit)_ on 2013-04-08

a search for a string with an EN DASH instead of ascii hyphen like  _Cockcroft–Walton_

leads to invalid basic search units, e.g.: `[\'+\', \'cockcroft\\xe2\', \'\', \'w\']`

``` python
basic_search_units =  '[[\'+\', \'cockcroft\\xe2\\x80\\x93w\', 
\'\', \'w\'], [\'+\', \'co\', \'\', \'w\'], [\'+\', 
\'cockcroft\\xe2\\x80\\x93walt\', \'\', \'w\'], [\'+\', \'cockc\', 
\'\', \'w\'], [\'+\', \'cockcroft\', \'\', \'w\'], [\'+\', 
\'cockcr\', \'\', \'w\'], [\'+\', \'cockcroft\\xe2\', \'\', 
\'w\'], [\'+\', \'cockcroft\\xe2\\x80\\x93walton*\', \'\', \'w\'], 
[\'+\', \'cockcrof\', \'\', \'w\'], [\'+\', \'exactauthor:"for\', 
\'\', \'w\'], [\'+\', \'cockcroft\\xe2\\x80\\x93wa\', \'\', 
\'w\'], [\'+\', \'base"\', \ [...]
```

Valid utf-8 sequences should be preserved and not split into bytes when basic search units are determined.
Also, arguably EN-DASH and EM-DASH should be recognized and identified with hyphen?

**Comment by tiborsimko** [comment]
The issue seems to been solved in the meantime.  With the latest `maint-1.1`, I get:

```
In [9]: create_basic_search_units(req=None, p='Cockcroft–Walton', f='title', m='a')
Out[9]: [['+', 'Cockcroft\xe2\x80\x93Walton', 'title', 'w']]
```
