### ISSUE TITLE
Flask: speed up launching CLI scripts

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1462]
Originally on 2013-04-09

CLI commands in the next branch are slow to launch.  Would be nice to speed the launch up.  Here is comparison with the master branch:

```
$ workon invenio-master

$ time sudo -u www-data /opt/invenio/bin/bibindex --help >& /dev/null

Best of three calls:

real    0m0.567s
user    0m0.468s
sys     0m0.068s

$ workon invenio-next

Best of three calls:

$ time sudo -u www-data /opt/invenio/bin/bibindex --help >& /dev/null

real    0m2.606s
user    0m2.348s
sys     0m0.212s

```

Note that `inveniomanage` speed seems good, so hopefully this ticket will get solved automatically when `flaskshell` technique will get deprecated and when every module will use `inveniomanage`.

**Comment by jirikuncar** [comment]
Solved by using *Flask-CLI* in Invenio>=3.0.0a1.
