### ISSUE TITLE
BibEdit: ability to order similar fields

### ISSUE THREAD

**Issue by sbujam** [inveniosoftware/invenio#1463]
Originally on 2013-04-09

Hello devs,

Since you're currently putting efforts in making BibEdit even(!) better, I would most appreciate it if BibEdit was also able to re-order similar marc fields, based on precedence defined by the librarian.

BibEdit, xml export and import respect the precedence of similar marc fields, so it would only be a matter of creating the new functionality in BibEdit (and place the relevant 'arrow' buttons) for librarians to be able to re-order similar fields according to their needs and keep them like that.

This extra functionality would be useful for additional author and keyword fields (amongst others). As you know, author name placement is crucial for many publications and there is currently no quick'n'easy way for librarians to change it.

Thanks in advance!

ps. An extra step would be to expand this functionality also for  subfields (there are cases where the alphabetic order should be broken), but this is very rarely needed, would probably require a lot of visual and programming changes, and hence should probably be left for the future...

**Comment by jirikuncar** [comment]
@jmartinm is it doable or we will solve it in new JSON based editor?

**Comment by aw-bib** [comment]
@sbujam author _ordering_ should go to `$b`  in the 100/700 fields as you can not be sure that ordering of the tags as such is preserved anyway. cf. http://www.loc.gov/marc/bibliographic/bd100.html Ordering has no semantics in Marc and many exernal tools will not necessarily preserve it. In fact a bunch of them will happily reoder based on tag/indicators... So changing orering of authors for librarians is changing `$b` accordingly.

Regardless, it would be nice if `bibedit` reflects this in the GUI.

**Comment by jmartinm** [comment]
That was a nice request and thanks for the comment @aw-bib . As BibEdit is not receiving at the moment feature updates we could take it into consideration when the moment to implement a new editor based on JSON comes. It has not been requested more than once afaik, so should not be ``p_major``. We can close it as mark as ``some day`` ?
