### ISSUE TITLE
Available languages in dropdown list

### ISSUE THREAD

**Issue by sbujam** [inveniosoftware/invenio#1468]
Originally on 2013-04-11

Since Invenio is available in an increasing number of languages, wouldn't it nice to have them grouped in a dropdown list by default?

It would definitely save two valuable horizontal text lines, it would provide less 'unnecessary information' to the end user, and would make the change language feature more concise and flexible in placement around the page (let alone that it also goes along with the new Google 'philosophy' -see bottom right corner in accounts.google.com).

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 3 years. Check https://github.com/inveniosoftware/invenio-i18n for Jinja2 macro.

cc @inveniosoftware/triagers
