### ISSUE TITLE
User should be able to change his/her email even when using external accounts

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#151]
Originally on 2010-06-21

Currently, changing email is not possible for users who are using an external account (e.g. at CERN SSO, or LDAP). Actually this restriction was historically added in order for user not to be able to become someone else.

However, this should be today possible by probing the given email address via MailCookies like we already do for changing passwords or creating an account the for the first time.

**Comment by lnielsen** [comment]
@kaplun: I think this issue has been solved in master by allowing to change the email address. Can I close it?

**Comment by kaplun** [comment]
Oh sure :smile:
