### ISSUE TITLE
OAIRepository: restricted records support

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1511]
Originally on 2013-05-15

So far, the OAI-PMH server in Invenio automatically removes records belonging to any restricted collection from the resulting set.

It is however desirable to have a smarter implementation that treats OAI-PMH harvesters has real users (e.g. provided with a real IP address that could checked against FireRole rules, or better authenticated as real users, using web api keys).

**Comment by aw-bib** [comment]
@jirikuncar does https://github.com/inveniosoftware/invenio/commit/6aec1df09dbd971350ac28daf5d83abc29672c4a also fix this issue?

**Comment by jirikuncar** [comment]
Yes

**Comment by lnielsen** [comment]
We haven't tested if it actually fixes the problem. Also I don't think it's useful as it is now, since you'll need the OAI harvester to log into Invenio and maintain the session (i.e. like a browser would do).

**Comment by kaplun** [comment]
I think this has become for `master`?

**Comment by lnielsen** [comment]
Moved to https://github.com/inveniosoftware/flask-oaiserver/issues/1
