### ISSUE TITLE
BibField: keep/remove singletons

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio#1512]
Originally on 2013-05-15

Allow the admin to decide whether to keep or remove singletons from a given record.

It should be like `CFG_BIBRECORD_KEEP_SINGLETONS` in `bibrecord.py`

**Comment by tiborsimko** [comment]
@egabancho Where do we stand on this?

**Comment by egabancho** [comment]
Probably we can close it, once we have JSONAlchemy ready, one should be able to define this using the schema.

WDYT?

**Comment by lnielsen** [comment]
Yes, let's close it
