### ISSUE TITLE
Unsafe use of max()

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1525]
Originally by *[scarli (@invenio-developers)](https://github.com/invenio-developers)* on 2013-05-30

max of an empty list is not defined and rises and exception.

This happens for example in dbquery.py get_table_update_time() in case one specifies a wrong table name or a table is not present in the database.

Shall such max calls be guarded against empty sequences, or we are happy to crash in such situations?

**Comment by jirikuncar** [comment]
We can solve it on per-case basis. In `get_table_update_time` it can raise an exception.
