### ISSUE TITLE
BibUpload: unique identifiers

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1527]
Originally on 2013-06-04

BibUpload currently matches records also via `CFG_BIBUPLOAD_EXTERNAL_OAIID_TAG`. However no check is performed for the uniqueness of this ID. This opens the possibility for introducing duplicates via BibEdit. BibEdit, in fact, is going to send a `bibupload --replace` containing a `001` tag, thus skipping any further matching based on external identifiers.

What should be added is a step where the identifiers included in the incoming records are checked for uniqueness (as it already happens for `check_record_doi_is_unique()`

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
