### ISSUE TITLE
WebSearch: hide "deprecated" (or/and restricted) collections in "Search collections" list

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1536]
Originally on 2013-06-17

The search interface displays a list of all available collections under the "Search collections" label. This enables users to restrict queries to some selected collections. The list of collections is built using all available collections, including those not attached to the main collections tree. This might be an issue if some collections have been removed from the tree (replaced for example by other) but left unattached to keep links to it. It would therefore be nice if some checkbox on each collection settings would allow to remove it from this list.

Alternatively one could consider that only collection attached to the tree would be included in the list.

Additionally one could decide to filter restricted collections from this list.

**Comment by jirikuncar** [comment]
Implement method in `Collection` model `is_restricted(self, user_info=None)` where `user_info = user_info or current_user`.

**Comment by jirikuncar** [comment]
Moved to https://github.com/inveniosoftware/invenio-collections/issues/11.
