### ISSUE TITLE
WebMessage: find recipients on more criteria than just nickname

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1542]
Originally on 2013-06-20

When preparing a message, WebMessage allows the sender to search for users registered in the system using their nickname (https://invenio-demo.cern.ch/yourmessages/write). It might be however that a nickname does not exist for some users, for eg. when using external authentication systems (for eg. with `external_authentication_sso` when initialized with `enforce_external_nicknames=False`). It becomes then impossible to select these users as recipients, unless they specifically set a nickname in their settings. The same issue extends to "WebGroup", which uses WebMessage as a way to send invitation to join a group.

One possible solution would be to also search in the list of registered emails (and use these emails instead of missing nicknames everywhere needed). One drawback is that it gives access to the list of emails of registered users, which one might not want to expose (For eg. spamming. For eg. tendering and bidding processes at CERN might requires that competitors are not known, etc.). It would not be possible to strip out the domain part of the email, as the prefix would not always be unique.

Another possibility would be to force the construction of unique nicknames, based on the users email prefix (and resolve conflicts by adding an integer) when the external authentication system is not providing one. That might have however deeper consequences in the system.

An alternative would be to simply (optionally) ask the user to fill in their nickname the first time they log in through an external authentication system that does not provide a value for the nickname. It could simply direct to the his/her account page ([YourAccount](https://invenio-demo.cern.ch/youraccount/display)) with a message suggesting to set a nickname (with an explanation about the reason for such a nickname), in the same way as message are displayed there to the admin when an Invenio upgrade is available.

Please propose alternatives...

One could also consider this behavior to be a feature, which allows users to choose to remain unreachable/unknown to other users, unless they opt-in (by setting a nickname).

**Comment by tiborsimko** [comment]
In the meantime, all users of CDS have been attributed a nickname, filled automatically from CERN SSO, so I'm closing this issue. CC @kasioumis 

(Moreover, in Invenio 1.x installations, newly registered users are by default forced to set up a nickname, so this problem should not be visible there.)
