### ISSUE TITLE
http status code 200 despite errors in search

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1545]
Originally by *[Thorsten (@tsgit)](https://github.com/tsgit)* on 2013-06-26

Thorsten notes that there are errors with some http status codes returned in INSPIRE: 
For example we have a recurrent assertion error which presents a warning to the user, but also returns "HTTP/1.1 200 OK"

############# E X A M P L E ##############################################
p1=((weapons+mass+destruction)+WMD)+((chemical+biological+radiological+nuclear)+(weapon+defense+terror))
 Internal Error exceptions.AssertionError
Please contact help@inspire-hep.net quoting the following information:
    URI: http://inspirehep.net/search?ln=en&as=1&m1=a&p1=%28%28weapons+mass+destruction%29+WMD%29+%28%28chemical+biological+radiological+nuclear%29+%28weapon+defense+terror%29%29&f1=fulltext&op1=a&m2=a&p2=&f2=title&op2=a&m3=a&p3=&f3=author&action_search=Search&dt=&d1d=&d1m=&d1y=&d2d=&d2m=&d2y=&sf=&so=a&rm=&rg=100&of=hb
    Time: 04/Mar/2013:03:11:10 +0100
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:19.0) Gecko/20100101
Firefox/19.0
    Client: 67.164.150.73

Please send an error report to the administrator.

$ wget  -S 'http://inspirehep.net/search?ln=en&as=1&m1=a&p1=%28%28weapons+mass+destruction%29+WMD%29+%28%28chemical+biological+radiological+nuclear%29+%28weapon+defense+terror%29%29&f1=fulltext&op1=a&m2=a&p2=&f2=title&op2=a&m3=a&p3=&f3=author&action_search=Search&dt=&d1d=&d1m=&d1y=&d2d=&d2m=&d2y=&sf=&so=a&rm=&rg=100&of=hb'
-O /dev/null
--2013-03-03 18:56:16--
http://inspirehep.net/search?ln=en&as=1&m1=a&p1=%28%28weapons+mass+destruction%29+WMD%29+%28%28chemical+biological+radiological+nuclear%29+%28weapon+defense+terror%29%29&f1=fulltext&op1=a&m2=a&p2=&f2=title&op2=a&m3=a&p3=&f3=author&action_search=Search&dt=&d1d=&d1m=&d1y=&d2d=&d2m=&d2y=&sf=&so=a&rm=&rg=100&of=hb
Resolving inspirehep.net (inspirehep.net)... 137.138.4.150 Connecting to inspirehep.net (inspirehep.net)|137.138.4.150|:80... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Date: Mon, 04 Mar 2013 01:57:57 GMT
  Server: Apache
  Cache-Control: public, max-age=3600, no-cache="set-cookie"
  Vary: Cookie,ETag,Cache-Control
  Content-Type: text/html; charset=UTF-8
  Set-Cookie: INVENIOSESSIONstub=NO; path=/
  Set-Cookie: INVENIOSESSION=e021fdf5d29834955d570000705f0751; path=/
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
  Transfer-Encoding: chunked
Length: unspecified [text/html]
Saving to: `/dev/null'

    [  <=>                                                         ]
21,184      42.9K/s   in 0.5s

2013-03-03 18:56:18 (42.9 KB/s) - `/dev/null' saved [21184]
############# E X A M P L E   E N D ###########################################

This and many others are triggered by obviously automated processes, and since there is no error indication in the status, they don't stand a chance of even detecting that there is a problem with their daily probes.

400 => 'Bad Request' is probably a better response

Sam K notes that the bug is  "intermixed INSPIRE + Invenio, as it is a bug in the search_engine but it could be in one of the INSPIRE hacks or in the official Invenio one...".

Tibor adds "The thing is that HTTP headers are sent early by the search engine when the page header is generated and streamed to the browser.  If some kind of error occurs say 3 seconds deep in the refersto/citedby search process, then headers are already sent by that time.  Do we always want to wait until we are sure to have some search results in order to set HTTP header accordingly?  Not sure..."

**Comment by tiborsimko** [comment]
As mentioned by @tsgit, I was of the opinion that we don't want to wait for the search response in order to see which HTTP headers to send.  (Would be penalising the regular users too much.) I'm therefore closing this issue.  It can be reopened for 2.x if wanted.  CC @kaplun in case this was touched in INSPIRE overlay.
