### ISSUE TITLE
WebAccess: collection-based granularity

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1548]
Originally on 2013-06-28

`runbibedit` and `runbatchuploader` WebAccess actions already support the `collection` argument in order to have granular authorization for content curator.

In the same way `runbibmerge`, `runbibdocfile` and `runbibeditmulti` should be extended to understand the `collection` argument.

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
