### ISSUE TITLE
Allow to remove static formats from cache if they are no longer needed

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1549]
Originally by *arwagner* on 2013-07-01

It would be nice to have an bib-un-reformat like option to remove unnecessary bibformats from the db cache.

**Comment by tiborsimko** [comment]
The issue is addressed in Invenio v2.0 via `inveniomanager`.  For Invenio v1.x, let's use the `dbexec` example as a workaround.
