### ISSUE TITLE
WebComment: plain text edit mode

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio#1553]
Originally on 2013-07-10

Requested via CDS support line:

"Do you think it would be possible to add a plain text edit mode for adding comments to documents? I often find that text processing done by the engine can have substantial impact on appearance of the text, visible only after a comment is submitted."

**Comment by tiborsimko** [comment]
@ludmilamarian @kasioumis Can you please update this issue to reflect current status?

**Comment by ludmilamarian** [comment]
This will be addressed in the new module for commenting in Invenio3.
