### ISSUE TITLE
CDS: image tagging

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio#1554]
Originally on 2013-07-10

There have been already several discussions/proposal plans for this feature, but I'm adding a ticket since it would be nice to keep track of the related user requests:

(Requested via CDS support line)

Add functionality to place tags directly in photos in the cds photo database. This functionality would be useful in case of e.g. technical photos with lots of small details in it, in which one would like to draw attention to a particular small feature. Ideally these tags could then also be searched in a similar fashion as the keywords for an individual submission.

**Comment by tiborsimko** [comment]
@ludmilamarian Which milestone you would like to go for here? 1.x?  2.x?  Or close the issue as "someday" if there is no active work going on right now?

**Comment by ludmilamarian** [comment]
It should be 2.x. As we are moving along with CDS on master, the work started for this feature should be revised and completed during this year. Can we have 2.x milestones, without knowing for sure the x?

**Comment by tiborsimko** [comment]
If we have concrete planning and timing, then we could create a later milestone, e.g. 2.4 or 2.5 or even 2.9.  If we don't have concrete timing, then we can close it with "someday" and revive it when the time comes.  (There are few more issues in "someday" like this.)

**Comment by ludmilamarian** [comment]
I think we can close this one, as it will be treated later on in a dedicated module.
