### ISSUE TITLE
BibRank: index_term_count to be collection-aware

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1559]
Originally on 2013-07-15

Currently the BibRank method `index_term_count` defined in `bibrank_tag_based_indexer` does not let the admin to specify the collections from which to consider occurrencies of the term.

For example, currently, in INSPIRE there is a piece of configuration such as:

``` ini
[rank_method]
function = index_term_count

[index_term_count]
index_table_name = idxPHRASE10F
index_term_value_from_tag = 110__u
relevance_number_output_prologue = (
relevance_number_output_epilogue = )
```

to define the `papers in HEP` rank to be used to order [HEP institutions](http://inspirehep.net/collection/Institutions)

It is desirable to be able to specify a (list of) collection(s), from which to pick up matching recids. (otherwise the current computation is also done on hidden collections, restricted ones, not related one, etc.)

**Comment by tiborsimko** [comment]
@kaplun Can this be closed?

**Comment by kaplun** [comment]
:+1: We have survived until now without it, I guess it's not really needed afterall.
