### ISSUE TITLE
WebSubmit: `pdfopt` called even when not available in `CFG_PATH_PDFOPT`

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1560]
Originally on 2013-07-18

PDF can be _linearized_ (for fast web viewing) using `pdfopt` in several steps of the conversion chain handled by `websubmit_file_converter.py`. For eg. the following functions would explicitly call `CFG_PATH_PDFOPT`:
- `pdf2pdfx(…, pdfopt=False, …)`
- `pdf2pdfa(…, pdfopt=True, …)`
- `pdf2pdfopt(…)`
- `ps2pdfx(…, pdfopt=False, …)`
- `ps2pdfa(…, pdfopt=True, …)`
- `ps2pdf(…, pdfopt=True, …)`
  in a configurable manner (with `pdfopt` parameter, mostly set by default to `True`). In the conversion chain handled by `convert_file(…)` the above functions would be called with their default value for `pdfopt` parameter, independently of the availability of the `pdfopt` path in `CFG_PATH_PDFOPT`. It would be good to update the conversion chain (in `get_conversion_map()`) to use `{'pdfopt': can_pdfopt()}` as parameter for each of the above functions with `pdfopt=True`, or/and call `can_pdfopt()` within all the above functions prior to calling `CFG_PATH_PDFOPT`.

Note that until recently `pdfopt` would _in principle_ be available when `ghostcript` exists (such that _in principle_ the above functions would not be called when `pdfopt` does not exist) but `pdfopt` [has recently been removed](http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=260ddb3e53ffe852a8994dd00719931ca3f2beec) from `Ghostscript` package. See also #1561. One could imagine other cases where `pdfopt` is not found at install/configuration time while `Ghostscript` is.

**Comment by tiborsimko** [comment]
Closing the issue, since Invenio 1.0 is very old stable release series, and a workaround exists. Invenio 1.0 users should really upgrade to latest Invenio 1.2 stable release series.

**Comment by kaplun** [comment]
Just for reference, in INSPIRE we plan to linearize (and lowering resolution of) PDFs for fast opening in the record editor.

We are going to directly use `ghostscript` which nowadays fully support natively all these.
inspirehep/inspire-next#1706
