### ISSUE TITLE
WebSubmit: `pdfopt` to be replaced for PDF linearization when Ghostscript >= v9.0.7

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1561]
Originally on 2013-07-18

PDF can be _linearized_ (for fast web viewing) using `pdfopt` in `websubmit_file_converter.py`. The `pdfopt` tool used to be part of Ghostscript prior to version 9.0.7 and [has now been removed](http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=260ddb3e53ffe852a8994dd00719931ca3f2beec). 
It would be adequate to use directly Ghostscript for linearizing PDF when Ghostscript version > 9.0.7 is detected (as `pdfwrite` will  [allow linearization](http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=f2a40a3a7edd6d27caeaa19f7f644adf31ee972c) if `-dFastWebView` parameter [is set](http://www.ghostscript.com/doc/9.07/Ps2pdf.htm).

If the code is not updated the linearization will still be attempted but will fail, due to #1560.

**Comment by tiborsimko** [comment]
Closing the issue, since Invenio 1.0 is very old stable release series, and a workaround mentioned in 
https://github.com/inveniosoftware/invenio/issues/1560#issuecomment-41878219 may be considered sufficient. Invenio 1.0 users should really upgrade to latest Invenio 1.2 stable release series.
