### ISSUE TITLE
baskets: adding export formats

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1565]
Originally by *arwagner* on 2013-07-24

Though it is possible to adapt the list of export formats for **basket exports** via the usual *template_<something>* mechanism. 

In fact this functionality does not work for *adding* new formats. If one adopts the format list (tmpl_create_export_as_list()) one still can not export to other formats, as in def wash_of (webbasket.py) a new format will get rejected if it does not show up in this list as well. Cf. WRN_WEBBASKET_INVALID_OUTPUT_FORMAT. 

As this effectively prevents customization via the template alone, this should be redesigned.

Furthermore, in webbasket_template.py the literal texts for each format are coded in python including their respective names. It would be cleaner to derive them from the output format definition.

**Comment by jirikuncar** [comment]
Invenio 1.x is in feature freeze. It might appear as part of Invenio-Tags module.
