### ISSUE TITLE
WebAccess: more robust remote IP parsing

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1576]
Originally on 2013-08-23

The 'remote_ip' value of the `user_info` object can sometimes get IPs in formats which prevent the `access_control_firerole.acc_firerole_check_user(..)` to proceed. 

For eg. the following IPs would raise `InvenioWebAccessFireroleError` "_invalid literal for int()_" exceptions (occurring in `access_control_firerole._mkip(..)`):
- 10.251.9.204 10.237.125.92
- 10.15.7.61:10706

(These are real observed cases. See also "similar" #1233)

**Comment by kaplun** [comment]
I didn't remember about this one. Actually: why remote_ip is not an IP in the first place?

**Comment by tiborsimko** [comment]
> Actually: why remote_ip is not an IP in the first place?

No idea.  I guess @jeromecaffaro simply took what some instances sometimes receive IRL...

**Comment by tiborsimko** [comment]
I note that this is still the case for latest `maint-1.1`. However, there is no PR yet, and Invenio 1.1 is the old stable release, and we recommend to use Invenio 1.2 instead. Hence I'm closing this issue. If anyone encounters this problem, please reopen.
