### ISSUE TITLE
WebGroup: delegate group admin rights

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1586]
Originally on 2013-09-17

Groups can only be administrated by the user who created them. It would be nice to enable the possibility to add other admins (or at lest delegate some admin rights, such as approving new members, or removing members).

**Comment by BessemAamira** [comment]
we have developed a solution to this need by adding a new user group status "MODERATOR".
The admin of the group can choose a moderator from group's members.
The moderator can approve new members and removing members .

**Comment by jirikuncar** [comment]
This has been already solved by @hachreak and @bouzlibop for `2.x`.

@BessemAamira if you have a solution for `1.x` you can submit PR for `legacy` branch. Thank you

**Comment by jirikuncar** [comment]
Invenio 1.x is in feature freeze state, hence I'm closing this issue.
