### ISSUE TITLE
Document refextract and docextract

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1592]
Originally on 2013-09-24

In the upcoming [prod-on-master](http://invenio-software.org/repo/personal/invenio-sam/log/?h=prod-on-master) branch (containing all the work contributed by the INSPIRE team), several changes have been contributed to the *refextract* now known as *docextract*. 

An admin documentation explaining how to use refextract and docextract executables and how to configure them should be added.

**Comment by tiborsimko** [comment]
@kaplun Is there a PR for this issue?

**Comment by kaplun** [comment]
Absolutely not. And is probably superseeded by Grobid.
