### ISSUE TITLE
BibDocFile: 8564 to FFT converter

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1597]
Originally on 2013-10-02

It would be great to have a CLI tool that allows converting `8564` tags into `FFT` ones, so that it's possible to automatize importing of external resources.

E.g. say you have a record:
```
000978964 8564_ $$uhttp://ab-div.web.cern.ch/ab-div/Conferences/Chamonix/chamx2005/PAPERS/0_03.pdf$$yPublished version
```

we want to be able to automatically send a `bibupload --append` with:
```
000978964 FFT__ $$ahttp://ab-div.web.cern.ch/ab-div/Conferences/Chamonix/chamx2005/PAPERS/0_03.pdf$$dPublished version
```

This could be implemented e.g. by using `invenioconnector` so that it can run remotely. Additionally the upload step should be optional, and it should be possible to specify:
* the usual *collection/pattern/field* to restrict the record to work on.
* a regexp to match only certain 8564 tags (e.g. basend on the hostname or the extension).
* whether the original 8564 should be deleted.
* in this case whether the `$y` and `$z` fields should be ported over (as `$d` and `$c` in FFT)

**Comment by tiborsimko** [comment]
@jalavik @kaplun Has some refactoring of the INSPIRE OPS code happened?

**Comment by jalavik** [comment]
@tiborsimko Not really. I think we can close this issue as it has not had activity since 2013 and migration from BibDocfile to `invenio-documents` will probably be done differently.
