### ISSUE TITLE
WebComment: allow saving temporary comment before final submission

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1607]
Originally by *[nkasioum (@kasioumis)](https://github.com/kasioumis)* on 2013-10-22

When writing a comment, it would be nice for users to be able to temporarily save their comment without submitting for others to see. Then, when the comment is final they should be able to "fully" submit it.

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-comments #15](https://github.com/inveniosoftware/invenio-comments/issues/15) via [**ZenHub**](https://www.zenhub.com/)
