### ISSUE TITLE
xslt error with oai_repository_server

### ISSUE THREAD

**Issue by sbujam** [inveniosoftware/invenio#1614]
Originally on 2013-11-05

Hello everyone,

I'm creating this ticket following my email sent on 27/06/2013 titled "xslt error with oai_repository_server". It seems(?) that master branch still has this issue, so I thought I should bring this up again... [1]

----
I got an error that appears when I try to access /oai2d?verb=... part of my site.

The xslt is not properly loaded and (in Firefox) the user gets:
Error loading stylesheet: An unknown error has occurred (805303f4)
http://xxx.yyy.zzz/css/oai2.xsl.v1.0
(Notice the "http" while the oai2d url displays "https")
Internet Explorer is 'smarter' and since it cannot load the xslt, it displays the plain xml data.

The xml is produced as it should be, and if I select to see the html source, all the xml tags are properly shown.
Also, the oai2.xsl.v1.0 url IS correct, accessible and one can download the actual file if one copy-pastes the full url in a browser, however, strangely enough, in my case, the xslt is not automatically loaded and the above error is produced.

I identified the issue in oai_repository_server.py, in the part where the oai2.xsl.v1.0 is loaded. So, If I change CFG_SITE_URL to CFG_SITE_SECURE_URL [*], the issue is resolved! 

```
-    out += "<?xml-stylesheet type=\"text/xsl\" href=\"%s/css/oai2.xsl.v1.0\" ?>\n" % CFG_SITE_URL
+    out += "<?xml-stylesheet type=\"text/xsl\" href=\"%s/css/oai2.xsl.v1.0\" ?>\n" % CFG_SITE_SECURE_URL
```
Of course, this is only a quick 'hack' that worked for me. IF you're able to reproduce the error, a smarter way to handle this would be required for the general public.

Cheers,
Theodoros

[1] Hmm... It seems that neither http://invenio-demo.cern.ch nor http://inspirehep.net/ is affected by this (so it must have been handled in some way in the meantime)

**Comment by jirikuncar** [comment]
Fixed in f3ca8cb2.
