### ISSUE TITLE
WebStyle: improves https hack

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1642]
Originally on 2013-11-21

When serving HTTPS pages, Invenio does a hack and rewrite any external `http://www.example.org/foo/bar` URL to `https://inspirehep.net/sslredirect/www.example.org/foo/bar` for the HTTP URLs in order to fool certain browsers (but not all). 

Maybe we can make this hack smarter and instruct Invenio with a set of HTTP -> HTTPS mapping. It's not always obvious that one can replace HTTP with HTTPS and things will work. For example the MathJax CDN mapping is: 
http://cdn.mathjax.org/mathjax/latest/MathJax.js -> 
https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js

e.g. one can introduce a new config variable:
```python
CFG_WEBSTYLE_HTTP_HTTPS_PREFIX_MAP = {
    'http://cdn.mathjax.org/': 'https://c328740.ssl.cf1.rackcdn.com/',
    'http://twitter-badges.s3.amazonaws.com/': 'https://twitter-badges.s3.amazonaws.com/'
}
```

**Comment by tiborsimko** [comment]
@kaplun IIRC this may not be relevant anymore since MathJax issue was addressed differently in INSPIRE?

**Comment by kaplun** [comment]
Well, MathJax is indeed solved in a different way. On the other hand it's true that for certain external resources it's important to correctly rewrite the HTTPS URL. However this is will no longer be an issue as per the decision of serving all Invenio over HTTPS (See: #931).
