### ISSUE TITLE
WebSearch: wildcard search throws exception

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#1643]
Originally on 2013-11-22

While trying to make a wildcard search I misplaced the . resulting in 999_c:/*./

This causes Invenio to throw an exception:

```
Internal Error <class '_mysql_exceptions.OperationalError'> (1139, "Got error 'repetition-operator operand invalid' from regexp")
```

**Comment by tiborsimko** [comment]
This is still a problem on `maint-1.2`. @kaplun Any update on the INSPIRE OPS branch?

**Comment by kaplun** [comment]
Nope. Since websearch is deprecated in favour of elasticsearch in master I am closing this ticket.
