### ISSUE TITLE
BibDocFile: check/fix calls to `register_download(..)`

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1648]
Originally on 2013-11-27

The BibDocFile handler in `bibdocfile_webinterface.WebInterfaceFilesPages._lookup.getfile(..)` is calling `bibdocfile.register_download(..)` for each visit, i.e. request to access/download a file. It might however be possible that some clients that read by chunks (eg. resuming a download or maybe jumping directly to a given PDF page, movie timecode, etc.) would call the URL multiple times. It should be checked that this would not lead to multiple download registrations. If so, then it might be possible to register a download only if the requested range starts from the beginning of the file.

**Comment by kaplun** [comment]
There is no PR for this functionality but it's not a bad idea per se. So I am closing it with someday.
