### ISSUE TITLE
References tag 999 is hardcoded in some modules

### ISSUE THREAD

**Issue by sbujam** [inveniosoftware/invenio#1652]
Originally on 2013-11-29

The references tag (normally 999, but also user configurable in invenio(-local).conf) is hardcoded in the following files:

bibedit_utils.py (5 times)
bibedit_engine.py (3 times)
refextract_xml.py (1 time)

and should preferably be replaced by CFG_BIBUPLOAD_REFERENCE_TAG

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
