### ISSUE TITLE
bibupload to wash empty (sub)fields before import/replace

### ISSUE THREAD

**Issue by sbujam** [inveniosoftware/invenio#1654]
Originally on 2013-12-03

It would be nice if bibupload had an option to wash empty fields and subfields before dealing with them. This is what happens by default in bibedit when saving a record.

If you don't want to add another flag to bibupload, you could use --special-treatment mode and add a new mode "wash_empty_fields"...

Or, it could be applied by default since I cannot find a reason why one would like to upload empty fields/subfields :)

**Comment by tiborsimko** [comment]
@kaplun How has been the singleton flag doing on INSPIRE?

**Comment by kaplun** [comment]
We finally never did. So we still suffer from singletons here and there.

**Comment by tiborsimko** [comment]
Let's close this issue as per the `legacy` code base freeze then.  The singleton flag is there, so people could flip it, but its behaviour is not very well tested...
