### ISSUE TITLE
BibField: introduce proper cache invalidation for virtual fields

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1656]
Originally on 2013-12-04

BibField in master does not invalidate its cache properly.   A workaround was committed, see 987e0274d4ce93909542b8fb0aff9b3877475b28.  The cache invalidation for calculated fields could happen by (i) altering all clients to call cache invalidation methods for their particular virtual fields (not touching the rest, so that no info gathering would be done unnecessarily); (ii) introducing general time-based expiry.
In the latter case, beware of delay, some clients may need to have immediate synchronous reaction.

**Comment by egabancho** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it will be addressed in `master` code base differently.
