### ISSUE TITLE
WebSearch: new second-pass search operator

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1659]
Originally on 2013-12-05

It would be useful to have a second-pass search operator, say `@`, so that power users could write queries like:

```
author:ellis@affiliation:CERN
author:ellis@relator:editor
title:"neutrino mixing"@provenance:arXiv
```

This would work in a general second-pass manner: firstly, retrieve results as you do now (including false positives); secondly, pass through results calling field instance filtering function that would pick only the fields having wanted another subfield.  See also #1550.

The price to pay for a very generic `@` second-pass search operator would be the slowness in case the first step returns say 500K results through which the second step would have to crawl in order to filter out only the interesting gems that the user wanted.  The post-filtering step could be very slow then.

This could be speeded up further for regular search needs, such as find-this-author-at-this-institute, via a new kind of index offering search for:

```
author:ellis@cern
```
 
Howeer, this optimisation can be done later, since a generic second-pass search operator would be useful to have anyway.

**Comment by jirikuncar** [comment]
We shall clarify the syntax in Invenio-Query-Parser if needed. Otherwise one can use Elasticsearch simple query syntax directly.
