### ISSUE TITLE
BibIndex: --reindex should not zero last_updated

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1662]
Originally on 2013-12-11

Currently, `BibIndex`, in order to trigger a full reindex of an index (in case `--reindex` is used, zeros the `last_updated` column in `idxINDEX` table.

This actually affects currently running indexes and triggers them into reindex the very whole system on the live tables.

This trick should be avoided and better coding should be put in place in order to allow reindexing to work fully in parallel with the regular indexing process.

**Comment by tiborsimko** [comment]
@kaplun Can you please check what is the latest status in INSPIRE OPS regarding this issue?

**Comment by kaplun** [comment]
Finally we are doing reindexing by hand, as @fpoli code wasn't integrated neither in INSPIRE nor in Invenio. So we have a tiny script that clones the definition of an index, then we run a full indexing and then it perform a full swap.
