### ISSUE TITLE
Images: Lightroom plugin

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio#1665]
Originally on 2013-12-16

Investigate the possibility of publishing images to Invenio from Adobe Photoshop Lightroom via a plug-in.
Some documentation about creating a Lightroom plugin can be found here: http://www.adobe.com/devnet/photoshoplightroom.html
This development should be done on top of the future structure for images, that considers each image a first class citizen (a record), and a group of photos represent an album record.

**Comment by jirikuncar** [comment]
I'm closing this RFC with `r_someday`. Please re-open the ticket if the feature is needed. Anyway it should be probably implemented in separate repo.
