### ISSUE TITLE
BibDocFile:Download all files function

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1673]
Originally by *[switowsk (@switowski)](https://github.com/switowski)* on 2014-01-10

To facilitate the downloading of all files for records with a lot of files attached, it should be possible to download all files with one click (for example packed as .tar archive).

**Comment by ludmilamarian** [comment]
@switowski can you make a PR for cds-ops?

**Comment by switowski** [comment]
@ludmilamarian yes, but I need to fix the code first (it's not working after rebase)

**Comment by switowski** [comment]
Since we are deploying this on CDS, I have rebased the code and created a PR: #2820

**Comment by jirikuncar** [comment]
@switowski it will be closed automatically if you put `(closes #1673)` in the commit message in #2820.

**Comment by switowski** [comment]
@jirikuncar :ok_hand:

**Comment by tiborsimko** [comment]
Closed by fa009b4397c2749dd9cec1c0b877d4d9524b7b73.
