### ISSUE TITLE
BatchUploader: introduce limit of records

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio#1683]
Originally on 2014-01-20

It would be nice if BatchUploader would have some configurable limits, similar to MultiEdit (see also #77). In this way, any consequent processing jobs (indexing, etc.) would not impact the normal flow of the system.

Example:
  -   1 -> 500 records: add/update on the spot
  - 500 -> above: schedule the job for the evening

**Comment by lnielsen** [comment]
Invenio 1/2 is in feature freeze so closing ticket.
