### ISSUE TITLE
BibDocFile: BibDoc related copyright and license

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1684]
Originally by *[switowsk (@switowski)](https://github.com/switowski)* on 2014-01-22

Right now, user can only assign copyrights (field 542) and license (field 540) to the whole record. If there are files included in the record, it may happen that they should have a different copyrights and license. We need a feature that allows to edit copyrights and license of single files.

**Comment by lnielsen** [comment]
Invenio-Records-Files in Invenio 3 allows for custom metadata per file.
