### ISSUE TITLE
BibCheck: documentation

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1685]
Originally on 2014-01-22

BibCheck has been recently reimplemented from Lisp (never included into mainstream Invenio) into Python.

The documentation available in Invenio still refers to the old implementation and to a no-longer valid web interface.

This should be amended.

See e.g.:
<https://inspirehep.net/help/admin/bibcheck-admin-guide>

Additionally the old admin interface can be slashed:
<https://inspirehep.net/admin/bibcheck/bibcheckadmin.py>

since it is no longer in sync with the CLI.

**Comment by jirikuncar** [comment]
Follow development in [Invenio-Checker](https://github.com/inveniosoftware/invenio-checker) repository.
