### ISSUE TITLE
BibSched: documentation improvement

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1686]
Originally on 2014-01-22

BibSched has been improved a lot in recent master. Documentation in e.g. [https://inspirehep.net/help/admin/bibsched-admin-guide] need to be updated to be in sync with new features.

Additionally a link to the new read-only web interface must be added in:
[https://inspirehep.net/help/admin/]

**Comment by tiborsimko** [comment]
@kaplun Do you have some updates in the INSPIRE OPS driven branch?

**Comment by kaplun** [comment]
Nothing was done in that regard. Everything bibsched is already integrated.

**Comment by kaplun** [comment]
Since bibsched is deprecated I am closing this ticket.
