### ISSUE TITLE
BibEdit: applying Holding Pen changes to the same field should behave differently

### ISSUE THREAD

**Issue by ppiotr** [inveniosoftware/invenio#169]
Originally on 2010-06-24

when having multiple instances of the same field in a Holding Pen, a better mechanism for changes comparison should be provided.

cases:
 - if a field (or many) has been removed in the middle of the list, the deletion should be detected rather than change of all the subsequent fields.
 - if a field (or many) has been added in the middle, addition should be detected rather than change of structure of many fields
 - if a field has been moved, this fact should be detected
 - any combination of above
 
to think if moving of fields should be treated in some special way...

**Comment by jalavik** [comment]
@tiborsimko It can still be interesting, as we'll probably use the BibEdit Holding Pen merging feature in the meantime for labs/Holding Pen. However, I'll keep it assigned to me and move it to next where this may be implemented.

**Comment by kaplun** [comment]
We have not yet scheduled when the work dictidiffer web interface will start.

**Comment by jalavik** [comment]
The merging facility will stay as is on legacy, until replaced by a new editor with similar features. Closing this.
