### ISSUE TITLE
of=recstruct not handled in search engine

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1712]
Originally by *[adeiana (@Osso)](https://github.com/Osso)* on 2014-02-24

Currently situation:
We try to add a dictionary to a string and we throw a server error when of=recstruct

I think pretty much anything else is better.
I propose this solution:
1) We should modify the search engine to return the json representation of the recstruct objects.
2) We should modify the print_record() to return a filtered recstruct. That is needed because some fields are protected and should not exposed to the user.

**Comment by kaplun** [comment]
@tiborsimko strangely enough, the fact you merged #2207 haven't really closed this issue. I am closing it by hand now.
