### ISSUE TITLE
BibExport: sitemap priorities and change freq per collection

### ISSUE THREAD

**Issue by sbujam** [inveniosoftware/invenio#1718]
Originally on 2014-03-06

Right now the XMLs produced by bibexport (using both sitemap and googlescholar export methods) give a predefined value for 'priority' and 'change frequency' to every collection.

But in general, not all collections have the same importance, nor they are updated ie every week. So, I think it would be useful, if the user could specify a custom 'priority' and/or 'change frequency' setting per collection in the appropriate .cfg file.

Such an example configuration file could look like this:
```
[export_job]
export_method = sitemap
collection1 = Articles, 0.8, weekly
collection2 = Theses, 0.6, monthly
collection3 = Preprints, 0.5, weekly
```
_nb: since collection names could(?) contain commas, a different separator might have to be used to split names, priorities, etc_

**Comment by jirikuncar** [comment]
See https://github.com/inveniosoftware/flask-sitemap
