### ISSUE TITLE
BibRank: centralize record date retrieval

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1719]
Originally on 2014-03-11

A record can have several dates:
* Record creation (from `bibrec` table
* Publication date (`260__c`, `269__c`)
* Journal year (`773__y`)
* In general `260__c`, `269__c`, `111__x`, `502__d`, `773__y`

For sorting purposes (e.g. in in BibSort) or for plotting citation graph, it is needed to retrieve the earliest date that could represent when a document was first known.

For this reason a new config variable is advisable such as:

```python

CFG_BIBRANK_RECORD_EARLIEST_DATES = [
   ('260__c', ['%Y-%m-%d', '%Y']),
   ...
]
```

with the proposed syntax and interpretation: every element of the list represent a date that can be potential retrieved. Every element is a tuple, where the first element is a MARC tag, and the second is a list of format-dates that are going to be applied in order to parse the value of the date.

A new function will then be created:

```python
def get_record_earliest_date(recid, record=None):
    pass
```

Which given a `recid` (and an optional pre-parsed `record` in `recstruct` format, for performance needs), will return the earliest possible date extracting it from the record using the before describe parameters plus the record creation_date timestamp. In case a date resolves to a partial date (say only to a year or to a month), then it is completed with January and the 1st of the month (as necessary). If however for the same year(-month) an other date is available and is more precise, than this latest one is considered.

So say:

```
2013-05-03
2013
```

dates are available. Then the the date: `2013-05-03` will be returned

If:

```
2013-05-03
2012
```

dates are available, then the date: `2012-01-01` will be returned.

**Comment by jirikuncar** [comment]
Invenio 3 solves sorting problem with configuration option [`RECORDS_REST_SORT_OPTIONS`](
https://github.com/inveniosoftware/invenio-records-rest/blob/b2f300fc66ad3596ca93ce22aed50b7591dd78f1/invenio_records_rest/config.py#L90-L95).
