### ISSUE TITLE
BibRank: refactoring of refs linking

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1721]
Originally by *[adeiana (@Osso)](https://github.com/Osso)* on 2014-03-26

Currently bibrank is separating the indexing in 2 phases.
First it fetches all the information for the records, then it does finds links.

This does not allow us to:
* factor out the linking for a single reference. Currently there's 3 places that find links to references differently (bibformat, docextract and bibrank).
* we can't give priority to the recid when looking for references in order to speed up the linking process. As we first search for all journals and repport numbers when we reach the recid lookup we already wasted a lot of time.

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it will be addressed in `master` code base differently.
