### ISSUE TITLE
jsonalchemy: Invenio should accept any indicator as valid for any tag

### ISSUE THREAD

**Issue by fjorba** [inveniosoftware/invenio#1722]
Originally on 2014-03-28

A majority of Marc21 tags accept different values for indicators.  Currenty Invenio just uses a restricted subset, mostly empty or undefined values.

When valid Marc21 records from other sources are imported to Invenio, most of the fields are not recognized, because don't fall in this restricted subset.  For example, a title with valid tags and subfields, like:

 245 14 $a The Merchand of Venice

is not recognized as such: it is not displayed, not indexed, not exported.

Given the amount of combinations in Marc21, accepting any indicator as valid is a much better solution than the current behaviour.

The sooner this behaviour is corrected, the better.

**Comment by kaplun** [comment]
@jirikuncar just rebased and added `.` as suggested by @fjorba.
