### ISSUE TITLE
Using mod_version to simplify the Apache configuration

### ISSUE THREAD

**Issue by greut** [inveniosoftware/invenio#1723]
Originally on 2014-04-23

The current generated apache configuration tries to guess the running version (which is not bulletproof) and clutters the configuration with commen/uncomment instructions. Apache HTTP Server (>=2.0.56) has a builtin mod_version with let you do version specific configuration.

```
<IfVersion 2.1.0>
# current httpd version is exactly 2.1.0
</IfVersion>

<IfVersion >= 2.2>
# use really new features :-)
</IfVersion> 
```
https://httpd.apache.org/docs/2.2/mod/mod_version.html

Hence, the `guess_apache_24` function is no longer required.

Pull-request: http://invenio-software.org/repo/personal/invenio-yblanc/log/?h=ifversion

**Comment by tiborsimko** [comment]
Solved in Invenio 2.0 code base.
