### ISSUE TITLE
BibDocFile CLI --delete & --hard-delete problem

### ISSUE THREAD

**Issue by Dziolas** [inveniosoftware/invenio#1737]
There are a few problems I noticed recently. I was deleting some bibdocfiles via CLI doing things as follows:

1. I have a record with 2 different names for bibdocs attached.
2. One of the doc files was deleted (with --delete) and reverted back (with --undelete) its name is now "DELETED-NUMBERS-main". The other bibdocs name is "main" and it was added by mistake.
3. I'm deleting a file (there was just one revision and nothing else) associated with "main" bibdoc. The file is deleted and it doesn't show in the records page.
4. I want to change the name of  "DELETED-NUMBERS-main" bibdoc to "main" using ```
bibdocfile --recid=*** --with-docname= "DELETED-NUMBERS-main" --set-docname='main'
``` but I get the message that the "main" name is already in use.
5. I check the database ```
SELECT * FROM bibrec_bibdoc WHERE id_bibrec=***;
``` and there are two bibdocs: "DELETED-NUMBERS-main" and "main".
6. So I try to delete the "main" bibdoc with ```
bibdocfile --delete --recid=*** --with-docname= "main"
``` but this time I get a message that there is no MARC to produce.
7. I run the same command for the other doc file, I copy the resulting MARC, change the docname and run bibupload manually. The "main" doc file gets deleted, and now I can change the docname as in point 4.

I guess that there is a fix needed for removing empty (with no files attached) bibdoc.

My other suggestions are:
- when the last file is deleted from a bibdoc it should also delete the corresponding bibdoc,
- when bibdoc is undeleted it should have its name reverted to oryginal form (unless it is impossible)
```
main -> DELETED-1234-main -> main
```

**Comment by tiborsimko** [comment]
@Dziolas @kaplun Have you been working on these issues in the meantime?

**Comment by kaplun** [comment]
Since there is a workaround and given that current legacy code freeze, and new implementation in master I am closing this ticket.
