### ISSUE TITLE
RFC: CSS Code Style

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1770]
<a href="https://github.com/kneczaj"><img src="https://avatars.githubusercontent.com/u/4245137?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kneczaj](https://github.com/kneczaj)**
_Thursday May 22, 2014 at 13:04 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/263_

----

| Revision | Date             | Author |
| ----------- | ---------------- |---------|
| Initial      | 2014-05-22  | @kneczaj  |
| Formatting | 2014-05-22 | @jirikuncar |

# Current situation

Looking around there is no guideline about CSS style, which would be nice to have discussed. I mean classes naming scheme, and how to organize the CSS files in Invenio.

For our classes maybe we should set a standard prefix like: 'invenio-'

I had this book recommended by @jmartinm: "Scalable and Modular Architecture for CSS" by Jonathan Snook - maybe it's in our library. It is exactly about organizing of CSS code and some naming conventions.

# Proposal

If you have any other propositions comment it here.

```jinja2
<body class="{{site_name|default('invenio')}} blueprint-{{blueprint}} endpoint-{{endpoint}}">
{# or #}
<body class="invenio-{{blueprint}} invenio-{{blueprint}}-{{endpoint}}">
```
--
See also #1767

**Comment by tiborsimko** [comment]
See also:
- http://oocss.org/

**Comment by jacquerie** [comment]
Whoops, yesterday I got confused. The actual name of that CSS naming style is BEM: https://en.bem.info/method/definitions/.

**Comment by jirikuncar** [comment]
@inveniosoftware/triagers shall we include some parts in docs? My alternative recommendation for Invenio packages is: 

1. no custom CSS styles if possible;
2. use only classes from Bootstrap;
3. write LESS with variables if you have to write custom styles

**Comment by switowski** [comment]
> write LESS with variables if you have to write custom styles
Hmm, correct me if I'm wrong, but aren't we using SASS instead of LESS (at least Bootstrap 4 is using SASS so maybe it's better to switch) ? Also no matter what preprocessor, maybe it's nicer to start using the actual CSS variables (unless care about IE: http://caniuse.com/#feat=css-variables) ?

In general I agree with sticking to Bootstrap classes as much as possible. As for the methodologies proposed in the previous comments, I guess if we want to adapt one, it doesn't matter which one (although I'm also in favor of BEM), as long as we stick to it.

**Comment by jmartinm** [comment]
> write LESS with variables if you have to write custom styles

Probably you meant SASS as @switowski mentioned.

> no custom CSS styles if possible;

And if they are necessary, use some namespace to avoid as much as possible clashing with some styles in a given overlay ( something like `i-records-panel`, `i-records-title` VS `panel`, `records`)

If we follow those, we probably don't need any strict methodology.
