### ISSUE TITLE
RFC: fixtures loading from inveniomanage

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1771]
<a href="https://github.com/kneczaj"><img src="https://avatars.githubusercontent.com/u/4245137?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kneczaj](https://github.com/kneczaj)**
_Tuesday May 27, 2014 at 14:30 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/277_

----

I think it is sometimes helpful to be able to load single modules or classes with fixtures to Invenio database.

I am going to implement this functionality. There is already `load_fixtures` function in `invenio/base/scripts/database.py`. I am going to make this function accessible from the command line. The proposed argument list is:
```python
def load_fixtures(packages=[], fixture_classes=[], truncate_tables_first=False)
```
with no default packages. The function would take all the fixtures form 'fixtures' directory from packages list, and additionally add single fixtures classes from fixture_classes list.

The options from command line perspective would look like below:
```python
option_packages = manager.option('-p', '--packages', dest='packages',
                                 action='append',
                                 default=[],
                                 help='package import name (repeteable)')

option_fixtures = manager.option('-f', '--fixture_classes', dest='fixture_classes',
                                 action='append',
                                 default=[],
                                 help='fixture classes paths to load')
```
There is also `inveniomanage populate` option, maybe it makes more sense to modify this command?

**Comment by jirikuncar** [comment]
### Conclusion

Individual tests should install their fixtures in `setUp/tearDown`. An alternative for `fixtures` has been introduced as an extension see `invenio.ext.mixer`.
