### ISSUE TITLE
RFC oauth2server: defining scopes in registry

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1773]
<a href="https://github.com/lnielsen-cern"><img src="https://avatars.githubusercontent.com/u/1698163?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lnielsen-cern](https://github.com/lnielsen-cern)**
_Friday Jun 06, 2014 at 09:04 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/301_

----

**Question:**
How should Invenio modules define OAuth 2.0 scopes so that ``invenio.modules.oauth2server`` knowns about them? 

**Problem:**

An Invenio module may provide a REST API in ``restful.py`` see e.g. ``invenio.modules.deposit.restful``. The REST API may require authentication using OAuth 2.0. If authentication is required, it may also require specific OAuth scopes to be present in the OAuth access token. Here's a simple example of how that looks in ``restful.py`` file:

```python
class SomeRESTResource(Resource):
    @require_api_auth()
    @require_oauth_scopes('someresource:write')
    def post(self, oauth):
        # ...

def setup_app(app, api):
    api.add_resource(SomeRESTResource, '/api/myresource/')
```

Here the required scope is ``someresource:write``. Also, the ``setup_app`` is called on initialization to register the REST resource (similar to the blueprints).

The OAuth scopes must be registered so that ``invenio.modules.oauth2server`` knows all possible scopes for the current running application (to e.g. present them to the end user).

**Proposed solution A:**
Register scopes during setup_app in ``restful.py``:

```python
from invenio.modules.oauth2server.registry import scopes

def setup_app(app, api):
    api.add_resource(SomeRESTResource, '/api/myresource/')    
    scopes.register(Scope('someresource:write', 'Write my resource'))
```

**Proposed solution B:**
Register scopes in ``scopes.py`` (or ``scopesext.py``):

```python
scopes = [('someresource:write','Write my resource)]
```

**Proposed solution C:**

File structure:
```
mymod/oauth2serverext/__init__.py
mymod/oauth2serverext/scopes/__init__.py
mymod/oauth2serverext/scopes/someresource_write.py
```

and ``someresource_write.py`` would contain:

```python
scope = 'someresource:write'
help_text = 'Write access to some reosurce'
```

Main difference between (B) and (C) is that (C) has one file per scope vs (B) which has one file per module containing all scopes.

**Proposed solution (D):**

```python
# mymodule1/restful.py
class SomeRESTResource(Resource):
    @require_api_auth()
    @require_oauth_scopes(Scope("preferences:write", help=_("Write to your preferences"),
                          Scope("email:read", help=_("Read your email address") )
    def post(self, oauth):
        # ...

    @oauth.require_scopes('preferences:write')
    def put(self, oauth):
        # ...


# mymodule2/restful.py
class AnotherRESTResource(Resource):
    @require_oauth_scopes(Scope("anotherresource:write", help=_("Write to your resource"),
                          "email:read")
    def post(self, oauth):
        # ...
```
**Note:**
Note, this RFC is not about how the scope string (i.e. ``someresource:write`` in the example above) should look like.

**Comment by jirikuncar** [comment]
Scopes are registered via `invenio_oauth2server.scopes` entry point group in Invenio 3.
