### ISSUE TITLE
RFC deposit: authors field in article submission form

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1774]
<a href="https://github.com/kneczaj"><img src="https://avatars.githubusercontent.com/u/4245137?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kneczaj](https://github.com/kneczaj)**
_Friday Jun 06, 2014 at 16:03 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/302_

----

Hello,

I just saw that the design of the author field which I introduced in bootstrap migration commit was reverted. In my opinion the previous version (first screenshot) is not ideal because of two things:

* move/remove buttons are really small
* there is much space wasted between the inline fields

My design moves also 'move' button to the left to separate it from 'remove' button as the functionality differs much, and misclicking is not welcome here ;) although this is a minor issue, and for sure will get much discussion so I don't insist on it.

I attach both screenshots to discuss on them. Your opinions and other designs are welcome! :)

Design 1 "small buttons" (original):
![authors2](https://cloud.githubusercontent.com/assets/4245137/3202717/4de649f8-ed93-11e3-8f80-3dd8d28c20d9.png)

Design 2 "large buttons" (mine):
![authors](https://cloud.githubusercontent.com/assets/4245137/3202636/860ca058-ed92-11e3-8fa7-226829317ebe.png)

Design no. 2 is a fast revert and just presents the general idea, it may need tuning the fields sizes and removing some css glitches.

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-deposit #100](https://github.com/inveniosoftware/invenio-deposit/issues/100) via [**ZenHub**](https://www.zenhub.com/)
