### ISSUE TITLE
RFC deposit: form.js modularisation

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1775]
<a href="https://github.com/kneczaj"><img src="https://avatars.githubusercontent.com/u/4245137?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kneczaj](https://github.com/kneczaj)**
_Friday Jun 06, 2014 at 16:49 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/303_

----

Hello,

I work with deposit form for inspire and I need the access to `fieldlist` jQuery plugin defined in this file from outside. Right now in the deposit form there is everything. Do you mind if I move `fieldlist` to a separated file?

**Comment by jirikuncar** [comment]
The work has been moved to [Invenio-Records-JS](https://github.com/inveniosoftware/invenio-records-js).
