### ISSUE TITLE
global: Python 3.3+ compatibility

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1782]
<a href="https://github.com/jirikuncar"><img src="https://avatars.githubusercontent.com/u/189798?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jirikuncar](https://github.com/jirikuncar)**
_Tuesday Mar 25, 2014 at 13:17 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/138_

----

* [x] check print statements
* [x] check exception handling
* [x] check metaclasses
* [x] fix intbitset problem inveniosoftware/intbitset#3
* [x] use different Python library for *MySQL*

**Comment by jirikuncar** [comment]
Independent packages `invenio-*>=1.0.0` are being tested with Python 2.7, 3.3+
