### ISSUE TITLE
oaiharvest: replace jquery.treeview with jqTree

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1783]
<a href="https://github.com/greut"><img src="https://avatars.githubusercontent.com/u/1388?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [greut](https://github.com/greut)**
_Friday May 30, 2014 at 09:37 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/288_

----

jquery.treeview is quite outdated.
```
jquery.treeview#1.4.1 depends on jquery#<1.8 which resolved to jquery#1.7.2
```
Bower downloads it from: https://github.com/galileo-press/jquery-treeview

The project itself advises to migrate to [jqTree](https://github.com/mbraak/jqTree).

(The number of stars on bower.io speaks for itself: 1 vs 432)

**Comment by jirikuncar** [comment]
Updates have been done in https://github.com/inveniosoftware/invenio-oaiharvester.
