### ISSUE TITLE
travis: timeouted on Python 2.6

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1786]
<a href="https://github.com/jirikuncar"><img src="https://avatars.githubusercontent.com/u/189798?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jirikuncar](https://github.com/jirikuncar)**
_Thursday May 15, 2014 at 11:08 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/243_

----

* travis tests take more than 50 minutes on Python 2.6

--

See https://github.com/jirikuncar/invenio/pull/240#issuecomment-43178282

**Comment by hachreak** [comment]
can we close this issue?
