### ISSUE TITLE
groups: new REST API for admins

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1787]
<a href="https://github.com/jirikuncar"><img src="https://avatars.githubusercontent.com/u/189798?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jirikuncar](https://github.com/jirikuncar)**
_Wednesday May 28, 2014 at 11:14 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/280_

----

* example: GitHub teams API (https://developer.github.com/v3/orgs/teams/)

**Comment by hachreak** [comment]
@jirikuncar can you move this issue to https://github.com/inveniosoftware/invenio-groups ?

**Comment by jirikuncar** [comment]
see https://github.com/inveniosoftware/invenio-groups/issues/8
