### ISSUE TITLE
upgrader: ensure no auto-generated output on clean database

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1790]
<a href="https://github.com/lnielsen-cern"><img src="https://avatars.githubusercontent.com/u/1698163?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lnielsen-cern](https://github.com/lnielsen-cern)**
_Friday Apr 04, 2014 at 13:13 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/166_

----

Auto-generating an upgrade recipe on a newly created database should not add anything new. Currently lots of things are added. I.e.

```
inveniomanage database init
inveniomanage database create
inveniomanage upgrader create recipe -a ...
```

**Comment by jirikuncar** [comment]
Please check [Invenio-Migrator](https://github.com/inveniosoftware/invenio-migrator/) for updating from Invenio 1.x and 2.x.
