### ISSUE TITLE
tags: fix missing javascript

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#1792]
Tags editor is broken on search result page after login.

* [x] register javascript to "search" bundle when tags module is enabled (addresses #1769)
* [x] do not use inline javascript or `<script>` tag

**Comment by hachreak** [comment]
@jirikuncar can we move or close the issue?

**Comment by jirikuncar** [comment]
Fixed in https://github.com/inveniosoftware/invenio-tags/commit/a598b23a15c73d3344c2a88bba80e1e2e68a94f4
