### ISSUE TITLE
general: legacy html output called from jinja2 templates forces users to re-login

### ISSUE THREAD

**Issue by pbroz** [inveniosoftware/invenio#1853]
Steps to reproduce:

- go to to the record#128 at the next demo site at http://invenio-demo-next.cern.ch/record/128
- login as *balthasar*
- click the author link *Menzler, N.H.*

**You are a guest again!**

There are numerous instances of this behavior, this is just an example.

The problem is caused by the fact that the filter in `legacy/wsgi/init.py` that was replacing `CFG_SITE_URL` with `CFG_SITE_SECURE_URL` in html responses that were made from https seems to not be called when the legacy code is called from a jinja2 template.

P.S. This is an elaboration on issue #1821 which was corrected ad hoc. A more thorough correction is needed.

**Comment by jirikuncar** [comment]
- [ ] use only `url_for` in templates
- [ ] migrate `bfe`s

**Comment by jirikuncar** [comment]
> To me it looks like the `SESSION_STUB` cookie is not honored.

@kaplun Can you point where should we look for it? Thanks

**Comment by tiborsimko** [comment]
Superseded by Invenio 3. @pbroz If you need this for Invenio 2.0.x and if @jirikuncar's workaround is not enough then please re-open.
