### ISSUE TITLE
BibIndex: index datasets using parent's author

### ISSUE THREAD

**Issue by fpoli** [inveniosoftware/invenio#1885]
In the next days I will work on a task on BibIndex, I write here the proposal solution to have feedback about the future pull request that I will open.

We want to index the dataset records using the authors of a paper that is specified by id in the dataset record. For example, we want the search query `author:Ellis` to give both the papers and the datasets authored by Ellis. In the datasets the tag `786__w` contains the id of the papers using it (the "parent records").

A related discussion on Asana is https://app.asana.com/0/11661778102949/12201448138720

The proposal solution is to write a new `BibIndexParentAuthorTokenizer` extending `BibIndexMultiFieldTokenizer`. This new tokenizer will fetch phrases from the "parent record" and will return tokens using internally an instance of `BibIndexAuthorTokenizer`.

Since we want to use two tokenizers for the same field (`BibIndexParentAuthorTokenizer` and `BibIndexAuthorTokenizer` for the "author" field) we need to associate multiple indexes to the same field (but this is not supported by WebSearch) or we can use an "author" virtual index associated to two real indexes ("parentauthor" and "simpleauthor").

Since we also want to index the canonical author id in the "author" field, two more tokenizers are required (`BibIndexCanonicalAuthorTokenizer` and `BibIndexCanonicalAuthorParentTokenizer`). These two tokenizers will be associated to the virtual index "author".

At the moment the method `add_recID_range` of the class `WordTable` has an `if self.index_name in ('firstauthor', 'exactfirstauthor', ...): ...` that adds the canonical ids to the token list, but I think a tokenizer would be better.

For fetching the affected records in the indexing process the only solution we found is to extend the special case `if index_name in ('author', ...` in `get_recIDs_by_date_bibliographic()` (`bibindex_engine`).

All the above also for the "exactauthor" field.

**Comment by tiborsimko** [comment]
Closing as per https://github.com/inveniosoftware/invenio/pull/2021#issuecomment-141994399.
