### ISSUE TITLE
BibIndex: index journal first page

### ISSUE THREAD

**Issue by fpoli** [inveniosoftware/invenio#1886]
At the moment in Inspire it is possible to search for `journal-page: 13-15` or `773__c: 13-15` (they are equivalent). However, users usually wants to search using only for the first page (for example 13, if the range is 13-15). The first page is not in the index, so we are going to write a tokenizer that takes "13-15" and returns the tokens "13" and "13-15".

The related task on Asana is https://app.asana.com/0/11661778102949/12871817123946

**Comment by kaplun** [comment]
Ha! For once this was indeed already fixed. See: #2169

**Comment by tiborsimko** [comment]
Note: the new PR is #3520

**Comment by kaplun** [comment]
Closing this, since it's just specific to INSPIRE and already solved internally.
