### ISSUE TITLE
BibRank: possibility to disable citation losses check

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1894]
`BibRank`'s citation indexer currently skips updating records for which the number of citations drops under a certain threshold.

It should be possible though, to disable this check, e.g. with a CLI flag such as `--disable-citation-losses-check` so that it's again possible to update those records for which a human has well verified that the citation drop has an justifiable explanation.

**Comment by kaplun** [comment]
This is actually implemented in INSPIRE fork and can be integrated.

**Comment by tiborsimko** [comment]
@kaplun Thanks.  Can you please prepare a PR, considering this is labelled as "critical"? Or downsize its importance?

**Comment by kaplun** [comment]
That was critical for INSPIRE, but is minor now since the code was already implementing and is related to processes that are completely INSPIRE specific.

**Comment by tiborsimko** [comment]
Closing as per missing PR.
