### ISSUE TITLE
RFC Generic automatic record merger

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1897]
When two (or more) sites exchange records via e.g. OAI-PMH, it is often the case that an update of a record on site A, is going to conflict with updates on site B (e.g. if both site A and site B modified the same record field).

At the moment (in Invenio master) in case of conflict, upon upload, the record is going to be added to the holding pen, waiting for human curation. However, there are several situations where it should be possible to automatically merge the record update, by a configurable set of rules (e.g. to declare which fields have higher priority on which site, or by allowing pluggable merging rules...)

Now that bibupload is being rewritten in pu as a customizable workflow, it should be possible to create a step responsible for resolving merging conflicts (when possible).

**Comment by jirikuncar** [comment]
Please check https://github.com/inspirehep/json-merger
