### ISSUE TITLE
general: create examples of file headers with licence for different file types

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#1904]
#### Problem

Format of file headers is not harmonized.

#### Solution

Create sample headers for following file types:

* [x] python
* [ ] css/less
* [ ] js
* [x] jinja2
* [x] rst
* [ ] others?

#### Question

Where shall we locate those files?

#### Python

**NOTE** to have better PEP8 compatibility (see #2021) we decided to go for single `#` (sharp) in Python license. Please don't change it manually we will proceed with automatic script. Thanks
```python
# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) {year} CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
```

#### Jinja2
```jinja2
{#
# This file is part of Invenio.
# Copyright (C) {year} CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
```

#### reStructuredText

```rst
..
    This file is part of Invenio
    Copyright (C) {year} CERN.

    Invenio is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License as
    published by the Free Software Foundation; either version 2 of the
    License, or (at your option) any later version.

    Invenio is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Invenio-Kwalitee; if not, write to the Free Software Foundation,
    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

    In applying this licence, CERN does not waive the privileges and immunities
    granted to it by virtue of its status as an Intergovernmental Organization
    or submit itself to any jurisdiction.
```
(thanks to @greut)

**Comment by tiborsimko** [comment]
Now that we have `# ` for Python files, let's go for `# ` in Jinja too, so that we keep harmony...

**Comment by bouzlibop** [comment]
Not sure if this is the right place to ask this question (or if this was already brought up), but...  

Once I was told to keep all previous years in the license, something like: `## Copyright (C) 2012, 2013, 2014, 2015 CERN.` . After some years this could lead to having pretty long line with years listed.

What about using something like years ranges instead. [Here][1] is an example from `twbs/bootstrap`:
>Copyright (c) 2011-2015 Twitter, Inc 

[1]: https://github.com/twbs/bootstrap/blob/master/LICENSE#L3

**Comment by tiborsimko** [comment]
It is preferred to list individual years, because this technique allows for "year holes" and for different copyright holders.  (Since, generally speaking, it is not true that every file is touched every single year during  the YYY1-YYY2 interval.)  

Quoting from [GNU GPL Howto](http://www.gnu.org/licenses/gpl-howto.html):

"""The copyright notice should include the year in which you finished preparing the release (so if you finished it in 1998 but didn't post it until 1999, use 1998). You should add the proper year for each release; for example, “Copyright 1998, 1999 Terry Jones” if some versions were finished in 1998 and some were finished in 1999. If several people helped write the code, use all their names.

For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your documentation about this usage."""

**Comment by bouzlibop** [comment]
It's clear now - the importance of having the possibility for years holes. Thanks @tiborsimko for this reference.

**Comment by dset0x** [comment]
>The copyright notice should include the year in which you finished preparing the release (so if you finished it in 1998 but didn't post it until 1999, use 1998). You should add the proper year for each release; for example, “Copyright 1998, 1999 Terry Jones” if some versions were finished in 1998 and some were finished in 1999. If several people helped write the code, use all their names.

>For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your documentation about this usage.

-- https://www.gnu.org/licenses/gpl-howto.html

**Comment by bouzlibop** [comment]
Small addition/proposal here, regarding to `Jinja2` header, consider following:

**template.html**:
```python
{% extends "template_base.html" %}
```

**template_base.html**
```python
{#line1
line2
line3
#}
<h1>Hola</h1>
{%- block title %}
<h2>Hello Jinja</h2>
{%- endblock title %}
```

The output look like:
```

<h1>Hola</h1>
<h2>Hello Jinja</h2>
```

By using `-#}` instead of `#}` we can get rid of this extra line in the output.
