### ISSUE TITLE
tags: some improvements

### ISSUE THREAD

**Issue by konstantinoskostis** [inveniosoftware/invenio#1907]
The Tags API, REST API is merged and can now be used.

Some improvements can be made:

1. [x] Work on *flask-oauth* for tags REST API because of api change.
2. [ ] Add pagination to REST API

**Comment by hachreak** [comment]
@jirikuncar can we move or close the issue?

**Comment by jirikuncar** [comment]
> - [ ] Add pagination to REST API

@hachreak please check if it was implemented in *Invenio-Tags* and if not, please create an issue there.
