### ISSUE TITLE
BibDocFile: Escaping characters in Document Files Manager

### ISSUE THREAD

**Issue by switowski** [inveniosoftware/invenio#1918]
Hi,

yesterday I've noticed that there is a bug in the Document File Manager that allows user to upload a file with /,(,),. characters in the file name encoded using URL-encoding, for example "art%3A10.1007%2FJHEP01%282013%29057.pdf".
Aside from the fact that if those characters weren't encoded, Document File Manager wouldn't allow to upload files like that (at least not with front-slash in the file name), after a user uploads a file like that then we can have multiple problems:
- If a user deletes the file then the bibupload:FFT task with FIX-MARC is failing with error: `Stage 2B failed: ERROR: while synchronizing 8564 tags: invalid literal for int() with base 10: '12345678/art:10.1007`. It's caused by this function `decompose_file(urllib.unquote(recid_file))`
- Probably the same error might occur when a user is uploading more files to that record.
- Some format elements are not creating a correct URL to the file, for example Default_HTML_files.bft is creating link with decoded URL characters (so something like that: `/record/12345678/files/art:10.1007/JHEP01(2013)057.pdf` and that returns 404 instead of a file).

Tibor mentioned that someone was already working on patching that ?

**Comment by tiborsimko** [comment]
Closed by #3729.
