### ISSUE TITLE
previewer: support for zip files

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1928]
Introduce zip file previewer so that users can see and inspect the content of the file before downloading it.

Ideally, for big files, the users would be allowed to mark one (nested) file from the zip and download only that one.  This could be done as a future improvement.

The previewer could use new data demo record introduced in #1927 for tests.

**Comment by jirikuncar** [comment]
Check https://github.com/inveniosoftware/invenio-previewer/blob/master/invenio_previewer/extensions/zip.py
