### ISSUE TITLE
BibAuthorID: considering rabbit/tortoise modifications

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1966]
Currently, `bibindex` is well reindexing author related indexes when user's claims are registered in the `aidUSERINPUTLOG`.

However, when new associations are performed by the `rabbit` or `tortoise` algorithms of `BibAuthorID` these operations are not tracked.

One could be tempted to use the `aidPERSONIDPAPERS.last_updated`, however this wouldn't track properly removals of associations between `person` and `papers`.

Therefore, it is proposed to introduce a new table called `bibINDEXQUEUE` where tools such as BibAuthorID would be able to register which records and for which indexes a reindex need to be performed.

E.g. 
```SQL
CREATE TABLE IF NOT EXISTS  bibINDEXQUEUE (
    id_bibrec mediumint(8) unsigned NOT NULL,
    id_index mediumint(2) unsigned NOT NULL,
    PRIMARY KEY  (id_index, id_bibrec)
) ENGINE=MyISAM;
```

BibAuthorID would fill in this table, while BibIndex would consume it.

**Comment by jalavik** [comment]
BibAuthorID is deprecated and therefore I will close this task (This may also already be solved on INSPIRE side).
