### ISSUE TITLE
advanced search feels broken

### ISSUE THREAD

**Issue by greut** [inveniosoftware/invenio#1968]
**What I did**

* Open invenio pu/next or http://invenio-demo-next.cern.ch
* Hit the `+` for advanced search
* Enter my favourite Author: `Menzler, N.H.`
* Hit `Search` at the end of the form.

**What happened**

_Showing records 1 to 10 out of 101 results._
``TypeError: $search_query_field.data(...) is undefined``
https://github.com/inveniosoftware/invenio/blob/cfbff22c569cb67cb84d778d3f6e336d8203bcbe/invenio/modules/search/templates/search/helpers_base.html#L513

**What was expected**

A search result page with only the results from `Menzler, N.H.`. Optionnaly, the author field still displays the search I did.

**Comment by jirikuncar** [comment]
Advanced search has been removed from Invenio 3.
