### ISSUE TITLE
RFC: Login/Register vs Sign in/Sign up

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#1973]
**Problems:**

- Login/Register and Sign in/Sign up are both used in Invenio.
- To login/sign in you need two clicks (top right user menu + login menu item) and one page load.

**Proposal:**

1. Standardize on using Login/Register or Sign in/Sign up. Instances can decide for using the other version by use of translation strings for English.
1. Embed part of login/sign-in page in modal dialog on the current page to avoid having to wait for login/sign-in page loading (note #1963 reduces the two clicks to one click). See example below:

![zenodo 2014-07-21 09-51-44](https://cloud.githubusercontent.com/assets/1698163/3640972/fc2fcbd4-10ab-11e4-8ae8-7a47ca009a59.png)

**Comment by jmartinm** [comment]
Here is a related read http://blog.codinghorror.com/the-god-login/

**Comment by jirikuncar** [comment]
Can we agree on: *sign-in* and *create-an-account*?

**Comment by kaplun** [comment]
:+1:

**Comment by jmartinm** [comment]
Sign in/Register seem to be quite standard:

http://blog.codinghorror.com/the-god-login/#pickcommonwords

 sign-in and create-an-account are clear too imo

**Comment by lnielsen** [comment]
Whatever we choose just ensure it's easy to override the names.

**Comment by jirikuncar** [comment]
Sign In/Sign Up is used in Invenio-Accounts.
