### ISSUE TITLE
general: fake file downloads and HTTP requests in tests

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#1986]
##### Problem:

* Several tests are accessing real sites and when they are down the tests are failing. It also prevents people to run their tests offline.

##### Proposal:

* Use `httpretty` to fake HTTP requests.
* *Example:* https://github.com/inveniosoftware/invenio/blob/pu/invenio/testsuite/test_ext_arxiv.py#L83-L137

**Comment by dset0x** [comment]
It looks like `httpretty` has already founds its way into invenio. Perhaps this can be closed.

**Comment by jirikuncar** [comment]
@dset0x I'm not sure if all tests were amended. Have you checked it?

**Comment by dset0x** [comment]
@jirikuncar I misinterpreted the goal of this issue - I thought it was only about introducing the dependency.

In which case, the answer is no. I will try to get a list of all the tests that depend on making network requests.

**Comment by jirikuncar** [comment]
Fixed in dc2b479e2e28668f4686cce4fddf0c137eb31527.
