### ISSUE TITLE
RFC: translations split and use of https://www.transifex.com/

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#1989]
##### Current status (in next/pu)

Following libraries Babel and Flask-Babel are used:
- http://babel.pocoo.org/docs/cmdline/
- https://pythonhosted.org/Flask-Babel/

##### Problems

1. `invenio.pot` is huge and there is missing support overlay translations (see #828)
1. compiling translations after installation with `pybabel compile -fd invenio/base/translations/` command (one needs to get to source directory)
1. Flask-Babel does not allow easy domain switch (see fork Flask-BabelEx: https://pythonhosted.org/Flask-BabelEx/)
1. it can be difficult for non-tech translators to contribute to Invenio

##### Proposal

- [x] use domains and/or split translations loading per module (see #1984)
- [x] compile translations before creating zip/tar.gz
- [x] evaluate use of Flask-BabelEx or take part in improving Flask-Babel
- [x] create project on https://www.transifex.com/ (Indico is there)

**Comment by lnielsen** [comment]
Close it as someday?

**Comment by kaplun** [comment]
CC @Kennethhole, @blixhavn, @PXke, is TIND interested into internationalization of Invenio? (for INSPIRE we are English only for the foreseeable future).

**Comment by Kennethhole** [comment]
This seems interesting! 

TIND finalizing translation of Arabic, Russian and Chinese for 1.2 in these days. We will create a pull request when everything is ready and hopefully you are able to use some of it in 2.x. We definitely support using an app as transifex.com. We used https://poeditor.com/ ourselves and it makes it so much easier to manage the project.

It would be preferable to split translation per module. That would make it easier to create tasks, which is manageable in size. It makes it also easier to prioritize, as you can start with the modules you find important.

**Comment by jirikuncar** [comment]
> split translation per module

We are going to do it as we separating packages (see *invenio-records*, *invenio-pidstore*, etc.).

**Comment by tiborsimko** [comment]
One comment WRT transifex and other cloud-based solutions:

1. For the translator, it is interesting to see the context of the phrase he/she is translating, which may not be easy to do on the cloud.  Translating files locally, e.g. using Emacs po-mode, the translator can press `s` to go to the source code line where the given phrase occurs.  (Either to understand its context, or to improve Python message formatting, say `%s` -> `%(x_number)s`.)

2. The management of possibly-updated PO files in between stable versions (v1.1. v1.2, etc) and merging them is nicer with git too.

**Comment by jirikuncar** [comment]
Each package provides its own translations.
