### ISSUE TITLE
records: expose past revisions

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1990]
It would be useful to expose past revisions of records over the web.

Upon update of records, the past versions are all stored in the record
history table (`hstRECORD`).  The `bibedit` CLI offers functions to
inspect past versions, for example:

```
$ sudo -u www-data /opt/invenio/bin/bibedit --list-revisions 10
10.20140709180731
10.20140709180059
```

The record revision ID is of the form `RECID.YYYYMMHHhhmmss` where
`YYYY...ss` corresponds to the timestamp when the record was updated.
(Note that this equals to MARC tag `005`.)

Currently, the past record versions are exposed via the
above-mentioned `bibedit` CLI to the administrators, or in the record
editor UI panel to the cataloguers.  They are not easily exposed to
the regular end users.  It would be useful to expose past record
versions also via regular web interface, for example:

```
/record/18/export/xm?revision=REVID
/record/18?of=xm&revision=REVID
```

Task 1: implement the above `revision` argument to expose past master
formats in various record-accessing URLs and APIs, notably
`/record/NNN?of=XXX`.  This will provide 100% complete support for
exposing past historical versions of master formats.

There are several challenges here beyond implementing basic
functionality, notably regarding master-vs-derived formats and
regarding non-MARC master formats.

For example, let us say that BibTeX is an important output format for
a given Invenio installation.  Exposing past record versions in BibTeX
can be done in basically two ways: (a) take an old MARCXML master
format version and run it through the "latest greatest" BibTeX
conversion procedure using current conversion rules, as for the
current MARCXML master format; (b) take old MARCXML version and old
conversion rules, IOW take the old BibTeX format as it had been in
that past moment, and expose precisely that.  The former method has an
advantage that the output would be always "up-to-date" with current
BibTeX rules of the given installation, even in case the
MARCXML->BibTeX processing rules change, say when a new field is
added.  However, with the latter method the output would be "truer" to
what it has been at the given point in time of that old revision.

To use an analogy, one could say that:

```
incoming master format + transformation templates -> outgoing output format
```

where:

```
  marcxml + xslt -> dublincore
  marcxml + bibformat elements -> bibtex
  [...]
```

The former approach would call for using historical MARCXML version
with latest XSLT templates or bibformat elements, while the latter
approach would call for using even historical versions of templates
and bibformat elements.  (Which is not practical to do, since these
could use KB lookups or SQL lookups that are not preserved; hence it
would be better to cache the result of the conversion as a whole.)

The former can be considered a "best effort" support for past slave
formats (taking historical master format with latest conversion
templates).  The latter can be considered a "complete support" for
past history (taking pre-stored past slave formats).  To do this for
all slave formats can be quite time and space consuming, e.g. for a
site of 1M records, if every record contains 10 revisions and if we
store 1 master and 5 slave formats, then we'd have to store 1M*10*6
which is 60M records in our historical record store.

Ideally, we could introduce a configuration variable like
`CFG_BIBFORMAT_CACHED_FORMATS` where each site would define which
formats are considered "important" for an installation to keep the
historical versions of.  These formats would then be stored in the
historical record store alongside the master format, say during
`bibreformat` step.  This would give a chance to each site to decide
when to go for "best effort" support and when to go for "complete
support".

Task 2: extend history table `hstRECORD` (or introduce new store) that
would store any number of wanted formats of the record, depending on
the configuration.  (I.e. not only `marcxml` formats after record
updates.)  Extend all APIs to take advantage of such cached formats.

The same challenge applies to non-MARC master formats.  Their past
versions have to be stored in `hstRECORD`, so the table extension may
contain not `marcxml` column, but two `format_type` and `format_value`
columns.

Task 3: after we have some UNICODE demo records, write test cases for
processing non-MARC records in `hstRECORD` table.

Note that this is also very closely linked with versioning internal
JSON representation of records (`recjson`).  Currently, only latest
`recjson` representation of a record is stored in the record cache.
We may want to store past versions of `recjson` in `hstRECORD` history
table, however a similar dilemma remain: in case we introduce a new
metadata field, say "book price", do we want to reprocess all past
versions of all records to add this new field to archived versions?
Probably not.  However, if we decide to change deeply how to store
some field in JSON, we may want to adapt cached past versions too, so
that they would work with latest version of the client software.  This
is similar to how we planned to increase record API versioning: a
hypothetical example, if we change storage technique from:

```
<author>
  <name>Joe Doe</name>
</author>
```

to:

```
<author>
  <name>
    <firstname>Joe</firstname>
    <familyname>Doe</familyname>
  </name>
</author>
```

then the API version must change.  Similarly, if recjson configuration
changes dramatically, we may want to adapt past versions as well.

Using similar analogy, we have:

```
record_master_format + Record.create() + atlantis.cfg -> recjson
```

with two techniques: (a) we could version `atlantis.cfg` file and use
past record master formats to recreate past recjsons; (b) we could
store past versions of recjson as we go, like we do for marcxml and
hstRECORD.  The former is more economical on resources, the latter
better preserves history in case of important configuration changes.
(And captures any KB and SQL calls the format may be doing.)  This is
"best effort" vs "complete support" dilemma once again.

Considering recjson is internal master format, it is important to
provide flexibility.  Similarly, each site could decide based on a
configuration flag like `CFG_BIBUPLOAD_SERIALIZE_RECORD_STRUCTURE`.

Task 4: optionally archive also past recjson versions upon metadata
change and provide suitable API functions that would expose them (and
check their consistency against current field rules).

Speaking of recjson, additional challenge comes from calculated
fields, such as `number_of_citations`, `number_of_borrowers`.  It
would be useful to store these, but it must be very clear that these
are historical versions as of `YYYY..ss` timestamp.  This could become
actually another interesting use case, to be able to take a historical
snapshot of records at some wanted point in time, not only when a
record metadata changes, but also on demand, say each first day of
each month.  Kind of `bibedit --take-historical-snapshot` kind of API
that could be called from within bibupload, but also from time to time
to say keep track of the time dependence of the various calculated
fields such as number of citations or borrowers.

(This latter use case approaches the timely snapshotting of record
metadata and any interesting associated information for the Memento
RFC 7089 support, which will be addressed in other tickets.)

**Comment by jirikuncar** [comment]
One can use Memento protocol in Invenio 3 (see https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/memento.py).
