### ISSUE TITLE
records: introduce unified `wayback` URL argument

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1991]
After previous ticket #1990 to expose historical versions of records is
implemented, one can expose historical versions of records easily via:

```
/record/18/export/xm?revision=REVID
/record/18?of=xm&revision=REVID
```

The historical versions of records' documents are exposed differently,
via `version` argument:

```
/record/18/files/thesis.pdf?version=2
```

It would be useful to have a unique way of referring to past versions
of resources handled by the digital library, be they records or
documents (or other related information like discussion).

This could be done by introducing a new `wayback` URL argument that
would bring, as best as possible, the past version of a resource:

```
/record/18/export/xm?wayback=YYYYMMDDhhmmss
/record/18/files/thesis.pdf?wayback=YYYYMMDDhhmmss
```

The URLs would be internally translated to ones using `revision` (for
record metadata) and `version` (for file) and corresponding functions
would be called before serving the results.  So the `wayback` layer
could be relatively thin.

However, it may be suitable to extend this to other resources, such as
HTML detailed formats or XML reference list or even discussion
threads:

```
/record/18/?wayback=YYYYMMDDhhmmss
/record/18/references?wayback=YYYYMMDDhhmmss
/record/18/discussion?wayback=YYYYMMDDhhmmss
```

One possibility would be to create a new wayback module with a
waybackify daemon that would run in the background and go through
resources decorated with `@waybackify` (or defined in some
configuration variable) and take historical snapshots of results into
history store.  The serving part would then look in this wayback store
and serve what is available for given time snapshot.

(This would be useful for future Memento RFC 7089 support.)

**Comment by jirikuncar** [comment]
Memento protocol has been implemented in Invenio-Records-REST.
