### ISSUE TITLE
RFC: Memento API

### ISSUE THREAD

**Issue by bogdan-kulynych** [inveniosoftware/invenio#1992]
Memento is a framework for browsing and discovering the historical versions of Web resources. This RFC proposes to implement Memento API for Invenio based on #1990 and #1991.

Memento details:

- [Intro](http://www.mementoweb.org/guide/quick-intro/)
- [RFC 7089](http://www.mementoweb.org/guide/rfc/)
- [RFC 1123](http://www.mementoweb.org/guide/rfc/#RFC1123).

## Proposed API

Memento [pattern 2.1](http://www.mementoweb.org/guide/rfc/#Pattern2.1) API is chosen due to its modularity.

Let `R` be original library record (resource in Memento-speak), `G` the *TimeGate* endpoint for datetime negotiation, `T` the *TimeMap* endpoint for discovering the historical versions of `R`, `M` the `Memento`, a historical version of `R` corresponding to some datetime `D`, `REV` a record revision, `ID` the record id. 

### API endpoints

```
URI(R) = record/ID/
URI(M) = record/ID/?wayback=REV
URI(G) = timegate/record/ID
URI(T) = timemap/record/ID
URI(T) = timemap/k/record/ID(R)
```

See proposed API details [here](https://stackedit.io/viewer?url=https://raw.githubusercontent.com/bogdan-kulynych/cern-openlab-2014/master/proposal.md#introduction)

**Comment by jirikuncar** [comment]
Basic Memento API has been implemented in [Invenio-Records-REST](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/memento.py).
