### ISSUE TITLE
Allow the selection of full and brief format from the WebSearch collection interface

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#200]
Originally on 2010-07-07

(Originally submitted by Ferran Jorba on Savannah: https://savannah.cern.ch/task/?12167)

The tools to create formats (.bft and .py) are powerful and programmer oriented. 
However, there is no easy way to assign those brief and full formats to a given collection. It would be nice to integrate those options to the WebSearch collection definition, like portalboxes, search options and other collection specific preferences. Maybe this could make .bfo files obsolete? 
I understand that HB and HD should be the default, good enough for most collection and sites, and it should remain the valid ones unless a specific choice has been made. 
Please note that this preference should be taken into account also when creating the first, cached page (http://cdsware.cern.ch/repo/?p=cds-invenio.git&a=search&h=HEAD&st=grep&s=def+create_latest_additions_info)

**Comment by kaplun** [comment]
I believe this is an interesting need, indeed (we might also needed it INSPIRE for branding particular collections), but better do it on next...

**Comment by jirikuncar** [comment]
Each collection can have it's own Jinja2 template (see https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/collections/views/collections.py#L102-L105).

**Comment by kaplun** [comment]
Awesome! Thanks
