### ISSUE TITLE
BibCirculation: display number of copies in Item search result

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/invenio#2018]
When searching for items in the BibCirculation module, the column for displaying the number of copies for each result is empty, regardless of whether a copy exists or not.

**Comment by tiborsimko** [comment]
This is still the case with latest `maint-1.2`.  @blixhavn @Kennethhole If you have fixed it, do you have a PR to fix this issue?

**Comment by blixhavn** [comment]
I extracted what i did in the PR referenced above :)

**Comment by tiborsimko** [comment]
Thanks, changed the phrasing for the release notes and merged as 30e8f0f.
