### ISSUE TITLE
RFC: PostgreSQL support, jsonalchemy query object

### ISSUE THREAD

**Issue by MSusik** [inveniosoftware/invenio#2020]
*See also the footer for a second issue.*

## Improving queries on PostgreSQL records.

With the introduction of version 9.4 PostgreSQL allows using binary representation of JSON as a field - it is called `jsonb` and it is supported by SqlAlchemy. Obviously its performance is much better than `json`'s.

http://www.postgresql.org/docs/9.4/static/functions-json.html
http://docs.sqlalchemy.org/en/rel_0_9/dialects/postgresql.html#sqlalchemy.dialects.postgresql.JSONB

Moreover, after indexing such structures with GIN indices they work reasonably well. For example let us consider table author_jsonb:

id | json
---|------
integer| jsonb

And an example structure:

```python
{
    'papers' = [{'recid': 1 },{'recid': 2}],
    'canonical_name' = 'some_string'
}
```
Simple queries are very effective!
``` sql
select id from author_jsonb where json @> '{"canonical_name" : "some_string"}';
```
My benchmarks show that we might expect maximum 10% performance drop on such queries compared to relational databases. However, the more complicated queries we create, the significantly worse performance is expected (much worse than in relational version of database). 

``` sql
create index papers_index_b on author_jsonb using gin (((json->'papers')) jsonb_path_ops);
select id from author_jsonb where ((json->'papers')) @> '[{"recid" : 2}]';
```
Moreover, they require querying for the whole key/value pair - for example querying for an existance of a key with `?` operator is very expensive, no matter how we index the table.

Fortunately, it seems that there are people who work on improving this (see attached files):
http://www.pgcon.org/2014/schedule/events/696.en.html

They introduce a query language for `jsonb` field called Jsquery. Now my query might look like this:

```sql
select id from author_jsonb @@ 'papers @> {"recid": 2}';
```
This language is supposed to support key existance searches, querying for nested values and array operations better than current `jsonb` operators. Here is the link to the [official development repo](https://github.com/akorotkov/jsquery).

I believe this is a technology our project might want to use. We can also contribute in its development by suggesting weak points (if we are able to find some). Obviously, it will take some time for SqlAlchemy developers to provide this in their tool, so it is a glance into the future.

## Storage engines

From the main page of our readthedocs:

>Invenio requires a relational database backend to store information. MySQL or PostgreSQL (coming soon) are required for basic functionality, but there’s also support for a MongoDB of other experimental NoSQL solutions, including using SQLite for local development.

What is in current plans for invenio? If we are going to support configurable storage engines can you tell me more details about what will be available, how will it be reflected on our database, etc.?

**Comment by jirikuncar** [comment]
Solved in SQLAlchemy 1.1.0b1 (see http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html?highlight=jsonb#sqlalchemy.dialects.postgresql.JSONB).
