### ISSUE TITLE
accounts: delete account feature

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2023]
**Goal:**
Allow users to delete their account via the account settings.

**Additional info**
The account deletion facility should check any attached baskets, any predefined alerts, any submitted records, messages etc.

Overlays must be able to hook into the deletion process, to do custom processing via e.g. pre/post delete signals.

**Open questions:**
Do we delete the account or simply mark it as deleted for record keeping? 

See also issue #1973

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-accounts #136](https://github.com/inveniosoftware/invenio-accounts/issues/136) via [**ZenHub**](https://www.zenhub.com/)
