### ISSUE TITLE
general: rely on MutableMapping for SmartDict, LazyDict and LaziestDict

### ISSUE THREAD

**Issue by greut** [inveniosoftware/invenio#2029]
Rely on `MutableMapping` for `SmartDict`, `LazyDict` and `LaziestDict` and don't override the following methods: `__contains__`, `keys`, `items`, `values`, `get`, `__eq__`, `__ne__`, `pop`, `popitem`, `clear`, `update`, and `setdefault`.
* https://docs.python.org/2/library/collections.html#collections-abstract-base-classes
* https://github.com/inveniosoftware/invenio/blob/c4d74fd3945567d43888b8e0e19154b27ea445a9/invenio/utils/datastructures.py

**Comment by hachreak** [comment]
note: `SmartDict` moved into [jsonalchemy package](https://github.com/inveniosoftware/jsonalchemy/blob/3be6c674cdf5a98302573b2fb121473e526cadf5/jsonalchemy/wrappers.py#L33)

**Comment by hachreak** [comment]
with @jirikuncar we were talking about create a separate package for common data structures.

**Comment by lnielsen** [comment]
Separate package for common data structures: +1

**Comment by jirikuncar** [comment]
### Package name?

- `lazycollections` (my preference)
- `lazy_collections`

**Comment by tiborsimko** [comment]
Superseded by Invenio 3.
