### ISSUE TITLE
RFC templates: customizable html templates

### ISSUE THREAD

**Issue by kneczaj** [inveniosoftware/invenio#2041]
Some html templates existing in invenio are still demosite-specific. I can mention here the home page of invenio, and the main frame layout with navigation bar layout at page_base.html.

Such pages pulls always some specific css. On the other hand they are going to be almost always overwritten by an overlay, so the css required by them is going to interfere with overwritten templates. This issue is a topic of the following PR: https://github.com/inveniosoftware/invenio/pull/2028

Html snippets like a search-bar, deposit form, and similar are always welcome to have in invenio, as they have high probability of being reused.

**Comment by jirikuncar** [comment]
Most of the base templates has been modified to fit various use-cases (latest related PR #2789).
