### ISSUE TITLE
deposit: CKEditor superscripts and subscripts

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2069]
Superscript and subscripts are not handled correctly in CKEditor module in deposit. See description below.

---------- Forwarded message ----------
From: 
Date: Wed, Aug 6, 2014 at 2:08 PM
Subject: Subscripts and superscripts in Zenodo

Here's a description of what I've encountered:
I have been using a word document that has sub and super scripts in its text to create descriptions of files.  When I copy and paste the file into the text box, or either of the pop-up windows (paste as plain text or paste from Word), the sub and super scripts are turned into regular characters. By highlighting the text I want to add and dragging it into the text box, the sub and super scripts remain in the correct format.  I also found that I can add sub and super scripts by using <sub></sub> or <sup></sup> tags in the source view but if I return to normal view, they are lost.  If I use source view to add sub and super scripts, I must submit changes without returning to normal view.  Finally, once a description is submitted and displays the sub and super scripts correctly, if it is viewed in edit mode and changes are made to any other part of the record, the correct format is lost.

**Comment by mahiaayush** [comment]
ckeditor superscript subscript bug:
cases: when we select some text after that hit superscript tool again hit sub script tool then 
text is convert like blow: <sup><sub>select text</sup></sub>

i requested some-one please help me to solve out this bug.

**Comment by lnielsen** [comment]
@mahiaayush This is not the right place. Please report the problem directly to https://github.com/ckeditor whom we are unaffiliated with.
