### ISSUE TITLE
BibField: clean up `doi` field and other FIXME in `atlantis.cfg`

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#2075]
Similarly to #1557, there are more clean-ups to be done in `atlantis.cfg`.  For example, in `invenio.conf` we have:

```
CFG_OAI_ID_FIELD = 909COo
CFG_OAI_SET_FIELD = 909COp
CFG_OAI_PREVIOUS_SET_FIELD = 909COq
```

while in `atlantis.cfg` we have:

```
@persistent_identifier(4)
oai:
    creator:
        @legacy((("024", "0248_", "0248_%"), ""),
                ("0248_a", "oai"),
                ("0248_p", "indicator"))
        marc, "0248_", {'value': value['a'], 'indicator': value['p']}
    producer: 
        json_for_marc(), {"0248_a": "oai", "0248_p": "indicator"}
```

and:

```
FIXME_OAI:
    creator:
        @legacy((('909', '909CO', '909CO%'), ''),
                ('909COi', 'group'),
                ('909COs', 'number'),
                ('909COo', 'id'),
                ('909COp', 'set'),
                ('909COq', 'previous_set'))
        marc, "909CO", {'group':value['i'], 'number':value['s'], 'id':value['o'], 'set':value['p'], 'previous_set':value['q']}
```

Notice the naming differences: e.g. "oai.indicator" should rather be called "oai.set"; "oai.value" should rather be called "oai.id".

Historically, `909CO` MARC tag in Invenio Atlantis defaults was used to store OAI information.  Later, `0248` was chosen on CDS and elswhere as a better MARC tag location.  Invenio Atlantis defaults were not changed though, which permitted e.g. to test easily how Invenio is configurable for various site conditions.

However, as it is agreed that `0248` is better OAI location, we should probably move defaults there, so that new Invenio installations are using by default "good" MARC tags already.

(This is similar with 773 vs 909C4, etc, see #1557.)

P.S. See also other FIXMEs in `atlantis.cfg`.  It would be useful to go through the file, fix all FIXMEs, and fix `demobibdata.xml` and `democfgdata.sql` and `invenio.conf` accordingly.

**Comment by tiborsimko** [comment]
@Kennethhole and @egabancho have been working on this in recent months, so I wonder whether we can co-sprint on this issue to fix it before forthcoming v2.0.0 is out. The motivation is to start with relatively "clean" JSON model, so that we don't force sites to change their data model once this issue will be fully completed. 

One of the biggest inconveniencies in my eyes is the behaviour of JSON field return types when no schema is declared.  For example, it can return either dictionary or a list of dictionaries, depending on whether there is only one field instance, or more of them.  It seems safer to always declare `schema` everywhere in order to always return the same type.

Proposal: before v2.0.0 is out, go through the JSON definition file, check used field names and change them to match [MARC standard](http://www.loc.gov/marc/bibliographic/), check declared field repetitiveness in the MARC standard (R, NR) and enforce schema for every field accordingly.  Example:

```
formatted_contents_note:
    schema:
        {'formatted_contents_note': {'type': 'list', 'force': True}}
    creator:
        marc, "505__", {'miscellaneous': value['g'], 'title': value['t']}
    producer:
        json_for_marc(), {"505__g": "miscellaneous", "516__t": "title"}
```

See also https://github.com/cernopendata/opendata.cern.ch/issues/450 and others.

**Comment by kaplun** [comment]
@MSusik (@glouppe) since you already started working on this for representing author records, I think it makes sense for you to also take part to such sprint.

**Comment by fjorba** [comment]
How do you express _accept any indicator as valid_ (#1722)?

For example, how do you express main author, 100 (http://www.loc.gov/marc/bibliographic/bd100.html) or even more, main title, 245 (http://www.loc.gov/marc/bibliographic/bd245.html)?

**Comment by MSusik** [comment]
> since you already started working on this for representing author records, I think it makes sense for you to also take part to such sprint.

Fortunately, our record definitions have schema definitions. Moreover, the author record fields are even more strict as I define schema for every subfield. Check https://github.com/inspirehep/inspire-next/pull/170/files for details.

**Comment by fjorba** [comment]
@MSusik, @kaplun, @egabancho, Sorry, but I fail to see how you express that a 100 field with any first and second indicator is a valid author.  May you help me to find it, please?

**Comment by kaplun** [comment]
@egabancho could it be that @fjorba question is answered by simply putting:
```
creator:
      marc, "100%%", {'last': util_split(value['a'], ',', 0),
                      'first': util_split(value['a'], ',', 1),
                      'numeration': value['b'],
                      'title': value['c'],
                      'birth_year': int_util_split(value['d'], '-', 0),
                      'death_year': int_util_split(value['d'], '-', 1),
                      'previous_name': value['i'],
                      'status': value['g'], 'preferred_name': value['q']}
```
?

**Comment by fjorba** [comment]
@egabancho, @kaplun , if it is the case, please, *please*, **please**, fill *all* indicators for *all fields* this way.  And only, *only*, **only** change the default sctricty for those cases where it is *absolutely* needed.

Please.  Or check with your friendly librarian.

And then you could close also ticket #1722, and be happy.

**Comment by egabancho** [comment]
@kaplun @fjorba the issue with the indicators in JSONALchemy has been solved on pu sometime ago ;-)

You could take a look at 7ce4c93e20009031962161dcea302895efaf1170 and there is an example of it in the [tests](https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/jsonalchemy/testsuite/fields/title.cfg#L21)

**Comment by kaplun** [comment]
@fjorba, as @egabancho mention the functionality is there (i.e. one just need to put "." as a wildcard instead of "_" for the indicators (see the example provided by @egabancho). Can you send in as one of our "friendly librarians" (since at CDS and INSPIRE and Zenodo don't have these use-cases), a patch for the default config where you need to accept "all" indicators? In this way we can integrate once and for all the support for MARC as expected :smile:

**Comment by fjorba** [comment]
@egabancho, @kaplun is right.  An absolute Invenio newbie should be able to take standard Marc21 records, like those found at https://archive.org/details/ol_data, upload to her newly installed Invenio and expect them to be indexed and displayed correctly.  If not 100% (Marc21 is very large), at least most of it.  Yes, without fiddling with esoteric, home grown Invenio specific syntax.  Learning those details should be only needed for special, non-standard use cases (maybe like CERN, but unlike the rest of the world).

**Comment by fjorba** [comment]
Sorry, @kaplun, I misunderstood your request.   But I'm afraid I don't fully understand the syntax, as it seems to me that there are some stanzas for input and others for output, and moreover I cannot test it.  I don't have a dev version for Invenio.

But again, if Invenio states that it complies with Marc21, and you developers know and master this syntax, why don't you fill all indicators for all fields with a wildcard character (whatever it is) so all of them are recognized as valid values?

After doing that, test it with a few thousands real world Marc21 records, like those found at the above archive.org address, to test that it works.  This way, prospective new Invenio installations won't be frustated with unmatched claims.

**Comment by kaplun** [comment]
> Sorry, @kaplun, I misunderstood your request. But I'm afraid I don't fully understand the syntax, as it seems to me that there are some stanzas for input and others for output, and moreover I cannot test it. I don't have a dev version for Invenio.

Indeed extensive documentation is still in the pipeline...

The issue, as you know, is that in our use case we have always considered MARC as a simple way to encode bibliographic metadata, without trying to respect the whole MARC standard. Therefore without the internal expertise to real polish everything, if we simply add wildcards everywhere, don't we risk to over do it? Maybe indeed not, and this is going to be the less evil...

**Comment by fjorba** [comment]
@kaplun, it is much, *much*, **much** better to add wildcards for all indicators, that the current situation, where for example *no single title* is displayed or indexed as title.  Right, *no single real world Marc21 title* (see http://www.loc.gov/marc/bibliographic/bd245.html).  It means maybe like going from 10% compliance to 90%.

Do you loose or gain, with that change?

**Comment by Kennethhole** [comment]
I agree with @fjorba in this discussion. By following the marc21 standard, indicators are used for most of the fields and should therefore work out of the box. 

We are currently setting up Invenio master for a client and migrating their bibliographic records from Voyager, so we have plenty of records following the marc21 standards. I did not queite understand your request @kaplun, but we are happy to contribute back what we are doing to allow indicators.

**Comment by kaplun** [comment]
I am proposing a PR to try to address the specific issue of #1722 but in naked invenio installation of pu there is basically no MARC defined (beside in the testsuite). I will also send a PR for invenio-demosite with similar proposed changes for Atlantis. Maybe that this solves @fjorba issue?

**Comment by fjorba** [comment]
Thanks, @Kennethhole.  @kaplun, I'm a little bit lost with those PR and pu acronyms (I suspect that pu means «proposed updates», but nothing about PR), and a little scared with what I understand, where you propose «no MARC defined».  Does it mean that an absolute Invenio newbie ill be able to load her standard Marc21 records and a large percentage of their fields will be displayed and indexed out of the box?

For me, as a veteran Invenio user, having learned how to make indicators work the hard way, a better solution would be: please use the fields that you are using in your sub-standard demo records.  But accepting any indicator.  With this out or the box, we, the community, will happily send you patches to slowly complete as much Marc21 as possible.  But we need something that works out of the box, please.

A second step would be: use real Marc21 records.  There are millions out there, public domain or CC0, reusable and free to use.

**Comment by kaplun** [comment]
@fjorba PR stands for "pull request" :smiley: it's a GithHub slang. From what I am understanding, Invenio nowadays is being re-packaged into layers (and sometimes separate modules). With the demosite (Atlantis) available separately. If one does not install the demosite package, the base invenio package will contain basically no support for MARC (in terms of pre-existing configuration). So MARC users starting nowadays with Invenio will have to also take the invenio-demosite (i.e. Atlantis) and transform it to their needs.

@egabancho, @tiborsimko, is this correct?

**Comment by jirikuncar** [comment]
> ... no support for MARC ...

The plan is to create standard configuration for MARC and friends that will be shipped with `invenio` package as base for site customizations. (cc @egabancho)

**Comment by egabancho** [comment]
What @jirikuncar said is correct, we plan to create a `contrib` folder inside the record module where we should place any master format that we get from the community, being MARC the first of them.
This way when you install Invenio you can decide which formats you want to enable, and therefore be supported by your installation, plus you will be able to override them and add new ones.

But, as @kaplun pointed out before, for this kind of standard configuration files the help of our "friendly librarian" would be very much appreciated ;-)

**Comment by fjorba** [comment]
@egabancho, I'll be glad to help, as long as I know what I'm doing ;-)

**Comment by tiborsimko** [comment]
> The plan is to create standard configuration for MARC and friends that will be shipped with invenio package as base for site customizations. 

... which is exactly the purpose of this very issue!  We are cleaning up the default record JSON configuration file so that it would be MARC standard compliant (and MARC parlance compliant).  See the clean-up plan outlined in https://github.com/inveniosoftware/invenio/issues/2075#issuecomment-68843843.  

Furthermore, once this plan is implemented, Invenio users will be able to do exactly what @fjorba proposes above: take any MARC record, upload it "as is", and expect things to work out of the box, without having to tweak supplied MARC configuration.  @kaplun's comment about "no support for MARC" should not be taken literally on the user level; quite the opposite.  MARC is the recommended master format to use, see https://github.com/inveniosoftware/invenio/issues/2075#issuecomment-58026572.

**Comment by kaplun** [comment]
> @kaplun's comment about "no support for MARC" should not be taken literally on the user level; quite the opposite. 

Yes, sorry if I created confusion :-) And that's also why I called in you and @egabancho to correct me. My assumption was based on the current pu source code only.

**Comment by kaplun** [comment]
> ... which is exactly the purpose of this very issue! 

Well not really, as this is issue originally talks about `atlantis.cfg` and that's where it stems from my very personal confusion.

**Comment by fjorba** [comment]
Great @tiborsimko and @kaplun, thanks a lot!

Of course, I don't know anything about the Invenio internal uses of those configuration files, so may I ask: are they used also for those different record syntax exporting?  And for OAI harvesting and publishing?

**Comment by tiborsimko** [comment]
> this is issue originally talks about atlantis.cfg

Yeah, because if at all possible, we'd like to clean record JSON configuration both in master and next/pu branches, so that the stored JSON would be "almost" the same, if not fully the same, in Invenio 1 and Invenio 2 sites.  In this way it will be easier for sites to upgrade, or try to run LABS site ot out of the same database.  (Although not many modules use record JSON in Invenio 1, this is not that critical for master based sites; but it would be important for future 2.0 to 2.1 updates as well.)

**Comment by tiborsimko** [comment]
>  I don't know anything about the Invenio internal uses of those configuration files, so may I ask: are they used also for those different record syntax exporting? And for OAI harvesting and publishing?

In principle, one can produce various needed output formats out of JSON.  Also, one can do it from the master format for each concrete record.  The two approaches may be illustrated as follows:

```
   record 123 (=master format MARC)
                                   \
                                    \
                                     ------>  record JSON  --->  DC
                                    /
   record 124 (=master format EAD) /
```

versus:


```
   record 123 (=master format MARC) -------------------------> DC
                                   \
                                    \
                                     ------>  record JSON
                                    /
   record 124 (=master format EAD) / ------------------------> DC
```

In the first case, one standardises every possible master format on the input site to the same JSON, that all the various ouput channels (such as production of Dublin Core output format) use directly.

In the second case, even though one also creates record JSON and uses it for various core indexing and HTML displaying needs, the production of the Dublin Core output format relies on converting master formats, e.g. because one has MARC2DC style steet ready, or because it is otherwise more pratical to work with the record master format rather then standardised JSON.

The first option is still kind of "remoter" possibility, because many Invenio modules still assume that their master format is MARC.

BTW you can read some documentation about record JSON configuration format and possibilities at
http://invenio.readthedocs.org/en/latest/modules/jsonalchemy.html

**Comment by fjorba** [comment]
Thank you, @tiborsimko, it looks promising!

**Comment by jirikuncar** [comment]
Should the correct milestone be `1.2.x` or `1.x`? In Invenio 2 we should wait to new pythonic JSONAlchemy coming in `~2.2`.

**Comment by tiborsimko** [comment]
Superseded by Invenio 3. General MARC clean-up happened in https://github.com/inveniosoftware/dojson and https://github.com/inveniosoftware/invenio-marc21
