### ISSUE TITLE
installation: deprecation warning caused by rdflib

### ISSUE THREAD

**Issue by bogdan-kulynych** [inveniosoftware/invenio#2077]
`rdflib` causes deprecation warnings because of use of operator `<<` which is deprecated in `pyparsing` since version 2.0.1:

```
pyparsing.py:3546: DeprecationWarning: Operator '<<' is deprecated, use '<<=' instead
  ret << Group( Suppress(opener) + ZeroOrMore( ignoreExpr | ret | content ) + Suppress(closer) )
```
Solution would be to downgrade `pyparsing` to 2.0.0 (which breaks some existing code) or patch `rdflib`.

**Comment by jirikuncar** [comment]
`rdflib` is not longer needed in Invenio 3.
