### ISSUE TITLE
deposit: developer documentation

### ISSUE THREAD

**Issue by SarahBA** [inveniosoftware/invenio#2099]
According to add the Rest API feature to B2share, as we discussed before, we decide to use our deposition module and now we need to implement a new deposition workflow for B2share. I tried to install Zenodo to track how this workflow is working but I couldn't. I found out that it's using 'bwlWORKFLOW' table to retrieve data, but in B2share this table will not fill due to lack of the related workflow. I need more details on how this workflow is working and what are the important points that we should keep in mind while we are implementing ours? Also would you please tell me what data information is being stored in 'bwlWORKFLOW' table?

Secondly, I faced another problem: how can I extract a specific user's depositions from the database?  I couldn't have the required query for that because after checking the database, I couldn't find the required foreign key (id_user) in related tables like bibrec or bibdoc. So how can I find which record belongs to which user?

**Comment by jirikuncar** [comment]
IMHO we can close it as B2Share is moving towards new Invenio-Deposit module in Invenio 3.0.
