### ISSUE TITLE
RFC Adopting JS MVC framework

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#2110]
Now that we have standardised on JS/CSS bundles and RequireJS/AMD, we should probably revive our last year's discussion about possibly adopting a JS MVC framework.

The most popular options at the time were: (see [old discussion](http://invenio-software.org/wiki/Talk/JSFrameworks))
* [AngularJS](https://angularjs.org/)
* [BackboneJS](http://backbonejs.org/)
* [EmberJS](http://emberjs.com/)
* [Flight](http://flightjs.github.io/) by Twitter
* [ReactJS](http://facebook.github.io/react/) by Facebook; used for CDS by @greut 

See example "todo" application in various frameworks:
* http://todomvc.com/

See also our related discussions on: 
* JS coding style #1769
* JS/CSS bundles #1767

**Comment by jirikuncar** [comment]
`flight.js` can help us with designing proper re-usable components and should be sufficient for *core* Invenio.
