### ISSUE TITLE
oauth2server: end-user documentation 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2115]
- [ ] OAuth 2.0 Overview 
- [ ] Normal flow
- [ ] JavaScript flow
- [ ] Native app flow
- [x] Endpoint documentation
- [ ] Integrate with REST API docuemntation

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-oauth2server #52](https://github.com/inveniosoftware/invenio-oauth2server/issues/52) via [**ZenHub**](https://www.zenhub.com/)
