### ISSUE TITLE
oauthclient: Flask-OAuthlib 0.7 upgrade

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2120]
Flask-OAuthlib v0.7 (which seems to be just around the corner) will deprecate ``remote.authorized_handler`` (lepture/flask-oauthlib@2416e0c4b91333f551b5e194f712d38d34f8830f)

- [ ] Use ``remote.authorized_response()`` instead of ``remote.authorized_handler`` in ``authorized_default_handler`` and ``authorized_signup_handler``
- [ ] Remove ``with_response`` argument from ``handlers.make_handler``.

**Comment by jirikuncar** [comment]
Closed via inveniosoftware/invenio-oauthclient#61
