### ISSUE TITLE
oauth2server: token revocation endpoint

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2122]
Flask-OAuthlib v0.7 (soon to be release) has added support for token revocation. This can rather easily be added to the current implementation.

- [ ] Add revoke endpoint (lepture/flask-oauthlib@e01265599904d5a0eabe1c1d6fd32a1467c16b8a)
- [ ] Add tests

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-oauth2server #53](https://github.com/inveniosoftware/invenio-oauth2server/issues/53) via [**ZenHub**](https://www.zenhub.com/)
