### ISSUE TITLE
RFC formatter: BFX engine removal

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#2124]
#### Question

The BFX engine has fallen out of use many years ago.  Is anybody using and planning to use in the future BFX formatter engine?

--
see also https://github.com/inveniosoftware/invenio/issues/2049#issuecomment-51327877

**Comment by tiborsimko** [comment]
Since nobody replied on this RFC, let's remove it, perhaps even for v1.2 version; see #2563.
