### ISSUE TITLE
RFC workflows: common ingestion data model

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#2153]
Problem:
------------

The data model in Deposit and during harvesting (via oaiharvester) are not the same and do not share the same interfaces in workflow tasks. This means that for common operations, which both submission and harvesting workflows require, we need different tasks (or to add wrappers) for the same operation.

Consider a reference extraction task where we want to add references to the metadata of the new record. Currently, the data model in a deposit ingestion workflow looks like [this](https://gist.github.com/jalavik/0936bb16d8fc7dfb2b8e). While the data model in a harvesting ingestion workflow looks like [this](https://gist.github.com/jalavik/492777b5ecd23f4f19f0).

As you can imagine, the calls for adding the data (references) to the record are going to be different depending if it is a deposition or harvest. Since these types of records are basically the same thing (a metadata record being ingested), we should perhaps have a common interface to these functions.

Idea 1:
------------

We could use the abstract factory pattern and enforce a common interface using abstract base classes. Too abstract? Let’s look at an example task with this schema:

```python
def task_foo(obj, eng):
    # obj.type is for example “record”
    data = WorkflowPackageFactory.get_package(obj.type, obj)  
    sip = data.get_latest_sip()
    # do stuff with sip or data
    data.update()
```

First we have the basic data objects. A Deposition class (like the one we have today describing a submission package) and a Metadata class (new, describing a metadata record package from harvesting), implementing a minimum interface governed by BasePackage:

```python
from abc import ABCMeta, abstractmethod, abstractproperty
class BasePackage(object):
	__metaclass__ = ABCMeta

	def __init__(self, obj):
		self.obj = obj

	@abstractmethod
	def get_latest_sip(self):
		pass

class Deposition(BasePackage):
	# implements BasePackage ++

class Metadata(BasePackage):
	# implements BasePackage ++
```

Now how do we use these data types without knowing the class in the tasks? Here comes the factories (simplified in Python):

```python
class WorkflowPackageFactory(object):
	@staticmethod
	def get_package(factory_type, obj):
		if factory_type == "deposit":
			return Deposition(obj)
		elif factory_type == "record":
			return Metadata(obj)
		else:
			raise TypeError("Not a valid Factory type")
```
This one is following a common design pattern for these kinds of problems. It is probably the most complete solution, but is it the right one?

Idea 2:
------------
Rename current Deposition class to something more generic (like Ingestion) and use it for harvesting ingestion workflows as well (only slightly modified). This way all ingestion type tasks will have the same pre/post procedure as deposition tasks have now:

```python
def task_foo(obj, eng):
     data = Ingestion(obj)
     sip = data.get_latest_sip()
     # do task stuff
     data.update()
```

This one does not separate submission from harvesting, which do indeed share similar properties, but they are not necessarily 100% equal. It could, for example, spill some overhead of submission specific properties over to the harvesting records. This is where (1) better separates the two but still shares common functionality.

Anyway, probably the Deposition class would need to be refactored in a more generic way for this to be fully clean, which will add more work and may warrant another class for non-submissions.

Idea 3:
------------
Whats the problem? Just massage the data before calls whenever you need to:

```python
def task_foo_generic(data): 
    # accept for example SmartJson only - common interface
    # main calls to APIs (such as refextract) - the “task body”
    # data.update(references)

def task_foo_submission_style(obj, eng):
    d = Deposition(obj)
    sip = d.get_latest_sip()
    task_foo_generic(sip.metadata) # passes SmartJson
    d.update()

def task_foo_harvesting_style(obj, eng):
    task_foo_generic(obj.data) # passes SmartJson

def task_foo_gangnam_style(obj, eng):
    data = get_my_smart_data()
    task_foo_generic(data) # passes SmartJson
```

The last one is perhaps less work and mimics today's situation. I think it can be better, though, as it loses some consistency between ingesting records from submissions versus harvests. Some common operations could rather be shared (such as adding files to the record). If this is done differently in submission and harvesting it can get confusing and error prone. Workflows can be shared between the two less likely as well.

**EDIT:**

Idea 4:
-----------

We can combine (1) and (3) to:

* Keep generic task generic, i.e. not care so much about data model implementation
* Share some common features of bibliographic metadata ingestion in submission/harvesting.

In `invenio/modules/refextract/tasks.py`
```python
def extract_references(pdf=None, save_callback=None)
    def _extract_references(obj, eng):
        if not pdf:
            pdf = obj.data.get("pdf")
        references = some_refextract_api(pdf)
        if save_callback:
            save_callback(references)
        else:
            obj.data.update({"references": references})
    return _extract_references
```

In `invenio/modules/workflows/tasks/ingestion_tasks.py`
```python
def extract_references(obj, data):
    data = WorkflowPackageFactory.get_package(obj.type, obj)  
    sip = data.get_latest_sip()
    pdf = sip.get_file()
    refextract.tasks.extract_references(pdf=pdf, save_callback=sip.metadata.update)(obj, eng)
    data.update()
```

No matter the outcome of this RFC, I believe our harvesting data model should go in the direction of the data model of the current Deposition class as it allows for better separation of data. Because of this, I tend towards idea (1), but please come with comments and other suggestions! I am probably missing something obvious anyway.

**Comment by jirikuncar** [comment]
See https://github.com/inveniosoftware/workflow/releases/tag/v2.0.0
