### ISSUE TITLE
upgrader: warning when in fact an ERROR occurs

### ISSUE THREAD

**Issue by aw-bib** [inveniosoftware/invenio#2161]
Invenio upgrader  (tested v.1.1.3 upgrading from 1.0.2) throws only a WARNING in case of

       Failed to execute query ALTER TABLE

It seems it would be better to throw an error here. The case in question was

Failed to execute query ALTER TABLE bibfmt ADD PRIMARY KEY (id_bibrec, format);: (1062, "Duplicate entry '152534-xm' for key 1")

in the end preventing bibreformat from working correctly. (Inner join didn't return in usable time due to missing index.)

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze.  Please reopen if you have a PR.
