### ISSUE TITLE
WebSearch: default sorting per collection

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#2185]
Currently, several sorting (or ranking) algorithm can be configured per every collection in Invenio (master and earlier). However the default sorting configuration is silently set to be "Latest First", which, in Invenio master and earlier, is not even possible to deactivate.

At INSPIRE, "Latest First", where the date is computed from the bibliographic metadata, is a perfect default for the "HEP" (i.e. the Literature collection), the "Conferences" and "Jobs" collections. However it is sub-optimal for e.g. the "HepNames" (i.e. People collection), "Experiments", "Institutions" and "Journals" collection, where a default alphabetical sorting on the key name is making more sense.

**Comment by jirikuncar** [comment]
Invenio-Collections package has been simplified. This feature can be done by creating custom template with default sorting option for Invenio-Search-JS.
