### ISSUE TITLE
tests: unittest library import

### ISSUE THREAD

**Issue by romanchyla** [inveniosoftware/invenio#2191]
Since Flask-Testing will import unittest2 when available, certain Invenio tests may end up using different unittest library, which will cause head-scratching :) 

For example @unittest.expectFailure decorator will not work because of the _ExpectedFailure class is different

the following would solve it, but i don't know why Invenio had the >=py27 test, if necessary, then the problem may be deeper....

```
diff --git a/invenio/testsuite/__init__.py b/invenio/testsuite/__init__.py
index b4f57ef..1b0f555 100644
--- a/invenio/testsuite/__init__.py
+++ b/invenio/testsuite/__init__.py
@@ -28,10 +28,9 @@ CFG_TESTUTILS_VERBOSE = 1
 import os
 import sys
 import time
-pyv = sys.version_info
-if pyv[0] == 2 and pyv[1] < 7:
+try:
     import unittest2 as unittest
-else:
+except ImportError:
     import unittest
 import cgi
 import subprocess
```

**Comment by jirikuncar** [comment]
Invenio 3 is using PyTest for all new tests.
