### ISSUE TITLE
search: search form template display issue with 1000+ records

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2199]
**What I did:**

- Go to http://invenio-demo-next.cern.ch/ in Chrome
- View the developer tools, change "Search 110 records for" to "Search 1100 records for"

or alternatively, upload more than 1000 records in Invenio.

**What happened:**

Search form is now overfilled so input field is moved down. See screenshot.

![search_form_screen](https://cloud.githubusercontent.com/assets/1698163/4132967/3de3967c-3358-11e4-8791-07d33cd22e3d.png)

**What I expected:**

![search_form_screen_ok](https://cloud.githubusercontent.com/assets/1698163/4132974/4c2674f2-3358-11e4-94f0-1231b7616120.png)

That the search form size stays the same independently of the number of records.

**Comment by jirikuncar** [comment]
Moved to *Invenio-Search* repository as https://github.com/inveniosoftware/invenio-search/issues/16.
