### ISSUE TITLE
BibIndex (fulltext): Demo fulltext searching on inspire-hep-dev doesn't find 'rattazzon'

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#22]
Originally on 2010-04-29

Suprisingly:

astro-ph/0607086

does not find rattazzon even though it is in the fulltext (see snippet for "honor theorist" search in fulltext)

This may be due to its enclosure in '' in the text...

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
