### ISSUE TITLE
RFC: Client side testing of forms 

### ISSUE THREAD

**Issue by giokokos** [inveniosoftware/invenio#2221]
## Idea

It'd be nice to use testing frameworks for JavaScript.

## Proposals

* Library to fake XMLHttpRequest and AJAX calls: http://sinonjs.org/

* Behavior Driven Development testing framework for JavaScript. It does not rely on browsers, DOM, or any JavaScript framework. http://jasmine.github.io/2.0/introduction.html

### Testing

Our custom JS libraries for the forms.

=============
Ported from https://github.com/inspirehep/inspire-next/issues/79

**Comment by lnielsen** [comment]
Jasmine has been implemented and adopted in Invenio so I'm closing this RFC.
