### ISSUE TITLE
RFC: properties of custom wtforms fields

### ISSUE THREAD

**Issue by kneczaj** [inveniosoftware/invenio#2222]
Hello!

I am working right now on our submission form in inspire and I look in suspicious way on custom fields of invenio/inspire. To be consistent with invenio, I want to ask you about opinion about the problem I describe, and apply the result to invenio too.

### The issue

In `invenio/modules/deposit/fields` there are some custom wtforms fields defined. The fields follow a programming patterns where a field has `defaults` variable in its constructor, then updates default values by `**kwargs`, and then passes the result to the constructor of the base class, like below.

```python
class DOIField(WebDepositField, TextField):
    def __init__(self, **kwargs):
        defaults = dict(
            icon='barcode',
            validators=[
                doi_syntax_validator,
            ],
            filters=[
                strip_string,
                strip_prefixes("doi:", "http://dx.doi.org/"),
            ],
            processors=[
                missing_doi_warning,
                datacite_lookup(display_info=True),
            ],
            placeholder="e.g. 10.1234/foo.bar...",
            widget_classes="form-control"
        )
        defaults.update(kwargs)
        super(DOIField, self).__init__(**defaults)
```

The programming pattern used makes the field classes a default sets of arguments, not a real objects.

To confuse you a bit :), I will refer to the values assigned in the example above to *defaults* as *base values*.

I will explain you the problem looking at `validators` part which in my opinion shows its drawbacks in the most obvious way.

There are usually two kinds of validators needed:
1. data format dependent - to check the data type or syntax.
2. form dependant - e.g. a required field, a password which matches password in the other field, a duplicated element in the database

##### Looking from the 1st point perspective:*
If a field type is going to store some kind of data it should always validate its type, no matter in which form the field exists. If it is a date field, it should always check if there is a proper date typed. If it is an integer field, it should always check if there is a number inside. If it is a DOI field, it should always check if there is DOI inside.

This is our DOI field which should already check it's syntax:

```python
doi = fields.DOIField()
```

#####  Looking from the 2nd point perspective:
For example passing `Required()` validator to such a field is going to substitute the validators assigned to the original object, in the case above `doi_syntax_validator` which should be present in every field designed to store a DOI. Other general examples which stress even more the problem of loosing the base variables is a 'Date' field where you can write any number or text or an 'Integer' field where you can write a text inside.

Now there is a form dependant validator added, simple example - the field is mandatory so we add `Required()`:

```python
doi = fields.DOIField(
    validators=[Required()],
)
```

The pattern presently applied is resetting all the *data format dependent* validators. This shouldn't happen because we still deal with DOI field which should be always checked for proper syntax. The solution here is to copy-paste the validators with `Required()` added on the end.

The current pattern is error prone because:
* you can forget about it, that you need to copy-paste the default validators so the data format is not validated in your form.

... and such code is harder to maintain because:
* if the validation is extended and one more validator is added then our object in our form doesn't take advantage of the new functionality without additional work time spent.
* if the validator function name or signature is changed you need to adapt the form code.
* we need to expose the validators as invenio API cause they must be available from outside to be able to use. It is possible to encapsulate the validation functions and make them private.

... beside this the default validators/filters/processors values are pointless because:
* as we have in most of cases a bit different usage of a field which is use case/form dependent we want to add additional validators/filters/processors which overwrites the default ones anyway

... it seems that the patern is also unintuitive
Just look at these `FIXME` lines, it seems that something didn't work as expected for other developers...
https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/deposit/fields/issn.py#L38
https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/deposit/fields/keywords.py#L34
https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/deposit/fields/pages_number.py
https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/deposit/fields/title.py#L46

##### An example of an extreme misuse of a field class with the currently applied pattern:
One can pass default parameters of ISSNField field to DOIField and get a ISSN field which is of DOIField type. It's possible.

### Proposed solution
Rename `defaults` to `base` ;) and merge the arguments passed as arrays with `base` ones instead of substituting defaults.

##### One can ask a question:
*How can I get rid of these base validators/filters if they are just extended by the constructor of a field?*
If you really need it, it means that either you need a different field or they are not data format dependent so they should be deleted from the field definition and moved to form definition.

### Examples in external code
If you look at wtforms itself there are fields like `Integer()` which has integer validator and it is never overwritten, or `HiddenField()` which is always hidden no matter how you would like to substitute its default values.

**Comment by jirikuncar** [comment]
Recommended way is to use base parameters for standard WTForm fields as described in https://github.com/inveniosoftware/invenio/issues/2222#issuecomment-54809413.
