### ISSUE TITLE
BibUpload: update fails if original record is broken

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#224]
Originally on 2010-08-02

When a record of the database needs to be fixed, but the inserted version of the record cannot be parsed by BibRecord (typically because it contains invalid XML chars, possibly inserted by a previous version of BibUpload that did not check for XML-valid input, or inserted through some unconventional/deprecated means), it is not possible to replace this erroneous record by a valid MARCXML with BibUpload (in --replace mode)

The replacement is made impossible by the fact that BibUpload tries to load the previous record to keep the fields in `CFG_BIBUPLOAD_STRONG_TAGS`.

It might be interesting to have a special replacement mode that skips the original record (and hence CFG_BIBUPLOAD_STRONG_TAGS). Although this might be useful only to a very limited number of repositories running Invenio, it might still be good to have it in case BibUpload/BibRecord strengthens its reqirements in the future, and existing records would need to be "migrated".

**Comment by tiborsimko** [comment]
Closing the issue as it's addressed otherwise in Invenio v2.x.
