### ISSUE TITLE
Stemming breaks wildcard search

### ISSUE THREAD

**Issue by badzil** [inveniosoftware/invenio#225]
Originally on 2010-08-02

**Problem:**

```
In [17]: s.perform_request_search(p='Astrophysics')
Out[17]: [8, 11, 15]

In [18]: s.perform_request_search(p='Astrophysi*')
Out[18]: []
```

-*Cause:**

The global index is in Invenio stemmed by default and therefore the term stored for "Astrophysics" in the database is "Astrophys". When performing a wildcard search, the MySQL request is then "WHERE term LIKE 'astrophysi%'" and no results are found.

This problem is easily understandable for a developer who knows about the indexes and the stemming procedure however it is a surprising undesired "feature" for a normal user as the second search is the example is a broader search than the first one but returns less hits.

**Comment by jirikuncar** [comment]
Works with https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/search/searchext/engines/native.py#L235-L241 if stemming language is set for global index in this specific case.
