### ISSUE TITLE
BibIndex: speed up virtual reindexing

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#2288]
As observed with @egabancho, reindexing of virtual indexes (e.g. `bibindex -u admin -w global -R`) now takes much more time than necessary because of excessive hard-coded flushing frequency:

```console
$ git grep -Hni 10000 modules/bibindex/lib/ 
modules/bibindex/lib/bibindex_engine.py:822:    def run_update(self, flush=10000):
modules/bibindex/lib/bibindex_engine.py:1165:        flush = 10000

$ git grep -Hni run_update modules/bibindex/lib/
modules/bibindex/lib/bibindex_engine.py:2092:                vit.run_update()
modules/bibindex/lib/bibindex_engine.py:2101:                vit.run_update()
```

Flushing memory index to DB by 10K units, when a site is having 1000K records, leads to unnecessary excessive flushing, which slows down the process considerably.  (Rule of thumb: twice as many flushes, twice as long runtime.)

Hence the tasks:

- [ ] We can monitor typical memory usage and safely raise current defaults to say 100,000.  (Beware of full-text index containing many terms.)

- [ ] The indexer engine should be amended to respect any flushing frequency the admin set in CLI. (e.g. `bibindex -u admin -w global -R -f 500000`)

**Comment by tiborsimko** [comment]
@egabancho Can you please check whether this was fixed in CDS overlay?

**Comment by lnielsen** [comment]
Invenio 1/2 is in feature freeze, and Invenio 3 uses Elasticsearch for indexing.
