### ISSUE TITLE
BibRecord: detect invalid tag values in datafields and controlfields

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#230]
Originally on 2010-08-03

BibRecord should check and report invalid values in the `tag` attribute of datafields and controlfields (when parsing record with `correct=1`). For eg. the following should report an invalid MARCXML:
```
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns="http://www.loc.gov/MARC21/slim">
<record>
  <controlfield tag="001">1282443</controlfield>
  <datafield tag="005" ind1=" " ind2=" ">
    <subfield code="a">eng</subfield>
  </datafield>
  <datafield tag="245" ind1=" " ind2=" ">
    <subfield code="a">CERN leads the way with novel beam extraction</subfield>
  </datafield>
</record>
```

since the tag attribute of a datafield cannot be in 000-009. [The MARC 21 XML Schema](http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd)

xmlmarclint and BibUpload would inherit from this enhancement. Side effects should be analyzed (for eg. already erroneous uploaded documents might not be fixable afterwards, see task #224)

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
