### ISSUE TITLE
OAI Harvest breaks with valid XML if the tags do not match

### ISSUE THREAD

**Issue by aw-bib** [inveniosoftware/invenio#2300]
Scenario: Harvesting projects from 'OpenAire'.
Harvestingsetup:
* Source Name: CORDIS
* Base URL: http://api.openaire.eu/oai_pmh
* Set: 'projects' (far down)
* Metadata prefix: oaf
* Postprocess convert + upload

For conversion we developed an XSL stylesheet (`cordisapi2marc.xsl`) that is working. Using 'Test' for the repo works as well from the web frontend.

`oaiharvest -v 9 -r CORDIS -d2014-05-01:2014-08-31` should give a bunch of records as can be verified via http://api.openaire.eu/oai_pmh?set=projects&verb=ListRecords&from=2014-05-01&metadataPrefix=oaf&until=2014-08-31 (there are submissions in this time frame). Similar `oaiharvest` calls against cds or one of our other repos work well without issues.

__Issue__ Invenio (tested with 1.1.3)  believes there are no updates, nothing is done.

Source of this problem seems to be in `OAI_Session()`:

    if harvested_data.lower().find('<'+http_param_dict['verb'].lower()) > -1:

This checks if the return data contains something like `<ListRecords>`. However, OpenAire returns the identifier in question as `<oai:ListRecords>`. Obviously, this it is valid to give the explicit namespace here, thus the `find()` falls short.

To check if there are no records in the set:

    if harvested_data.lower().find('<error code="noRecordsMatch">'.lower()) > -1:
 
seems more appropriate, as defined in section 3.6 of http://www.openarchives.org/OAI/openarchivesprotocol.html.

This at least solves the harvesting part and on ends up with proper content in the harvesters output files.

A similar issue, however, comes in from `remove_duplicates()`. Here again regexps are used that search only for `<ListRecords>` and not the version with an explict namespace. Thus after successful harvesting the conversoin may still fall short as the `remove_duplicates()` effectively removes everything.

Additionally, in the case of _OpenAire_ the `remove_duplicates()` even results in invalid XML:

    <?xml versio
    </ListRecords>
    </OAI-PMH>

 thus `bibconvert` called some where down the road is quite unhappy.

Still working on fiddling out what's going on in `remove_duplicates()` and how to fix it in general.

**Comment by tiborsimko** [comment]
> @tiborsimko I can take a look at this.

I'm just having a look because of the forthcoming release of `1.1.x`.
