### ISSUE TITLE
search: set proper Cache and TTL information in HTTP headers

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#2302]
The `/search` pages use Redis as a backend to store user-selected facets.  The Redis cache for these facets expires after N minutes.  The search results pages should therefore emit proper Cache and TTL information in its HTTP headers, so that any eventual external cachers (such as varnish) could act accordingly to invalidate their caches automatically, without any configuration.

**Comment by jirikuncar** [comment]
Facets should reuse all query arguments intead of `qid` so that the redis cache can be rebuild when needed in search engine.

--
related #2987
