### ISSUE TITLE
deposit: autocompletion of from ORCID (author name when entering ORCID)

### ISSUE THREAD

**Issue by Kennethhole** [inveniosoftware/invenio#2309]
It happens that authors submit new work with different variations of their name. This could be resolved by letting them enter their ORCID and have Invenio auto complete their name.

I think integrating GET orcid_id API could be helpful?
http://support.orcid.org/knowledgebase/articles/116874-orcid-api-guide

Is this desired by more people?

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-deposit #90](https://github.com/inveniosoftware/invenio-deposit/issues/90) via [**ZenHub**](https://www.zenhub.com/)
