### ISSUE TITLE
WebSearch: make default behavior configurable

### ISSUE THREAD

**Issue by fiee** [inveniosoftware/invenio#2328]
Invenio’s search syntax is great, but much too complicated for inexperienced users. I’d need to have substring matching as default behavior in easy search, knowing it will increase cpu load.
Advanced search should be unaffected.
Tibor told me it would be easy to make search behavior configurable.

**Comment by lnielsen** [comment]
Invenio 3 via Invenio-Records-REST now supports changing the query parser, and by default include an Elasticsearch Query String query parser which can do google-like queries.

**Comment by fiee** [comment]
Thank you, but I don’t use Invenio any more; my customer switched to dspace or whatever.
