### ISSUE TITLE
RFC Holding Pen/workflows authorization

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#2329]
### Problem

In the Holding Pen interface, users are able to look at and interact with all objects running in workflows. For example, one object may have been halted in the workflow and flagged for approval by human (which can be then scheduled to continue through the `workflows.actions` interface "widgets").

1. How do we control access to this interface and the ability to "read" or "write" (e.g. see an object or be able to interact with it)? Shall we limit individual objects to users as per a few customizable parameters? Per workflow? Per "type"? Per "whatever the model has"? Or what about state (error, waiting, need action etc.) - presumably only admins are interested in programming exceptions being triggered in a workflow? Also, should access to an object change during the workflow?

2. How is access control managed when *running* workflows (from any source). Should the workflow be tied to a user or role?

### "Current" state

1. The first iteration of Holding Pen access control (seen on INSPIRE Labs) is just a simple gatekeeper: gain access or not to the interface. This is controlled via "viewholdingpen" authorization using the `invenio.ext.principal` extension that hooks into the `access` module (see WIP #2325). A user can then be connected to this action and thus access *anything* in Holding Pen. If user is not connected to this action (or a role connected to it) no access is granted.

2. Nothing really exists at the moment. A `id_user` column does exist in both the Workflow engine model and the Workflow object model, but it is mostly ignored/unused atm. I believe it was meant to signify the "owner".

### Proposal

1. For the interface, there could be two different types of authentication levels, read and write, at the workflow object (`BibWorkflowObject`) level and the workflow engine level (`BibWorkflowEngine`):
  >**read:** access to seeing (and filtering/searching) through any given record
  >**write:** access to manipulating (editing it, re-starting/continue workflow execution) any given record

2. For the "back-end" part, use the "write" access from above to control workflow execution.

The access can then be further managed through use of parameters to allow authorization based on the object/workflow properties.

*Silly question: Do we need the read/write distinction? Is it useful to allow seeing the records in Holding Pen but not touching - because why else be in Holding Pen if you are not there to "manipulate" things?*

#### Use cases:

Imagine a use-case where some user/role only should be able to access (and manipulate) submissions from workflow `my_submission`, then a new `runworkflows` authorization can be created with parameter `workflow.name == "my_submission"`and the user would then be allowed to see (and touch) objects in Holding Pen from this workflow.

Another case could be where access to an object is changed during a workflow. To allow this to change dynamically, we could use a new object property `roles/authorizations/restrictions etc.` or re-use the `extra_data` property, that can be modified in a task and predefined authorizations will look for it.

**Comment by jirikuncar** [comment]
Follow https://github.com/inveniosoftware/invenio-workflows/
