### ISSUE TITLE
search: verbose=9 option not working

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2339]
I am trying to debug some search problems and see that Next does not contain the url option verbose=9.

![screenshot from 2014-09-25 17 29 35](https://cloud.githubusercontent.com/assets/580727/4407289/3ba67ffa-44c9-11e4-9753-94a95e5641f2.png)

Is it possible to bring it back? It was useful in many cases.

**Comment by jirikuncar** [comment]
Search queries can be debugged directly on Elastic search cluster.
