### ISSUE TITLE
WebSubmit: improve mail sent by Send_Modify_Mail

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#234]
Originally on 2010-08-06

The email sent by `Send_Modify_Mail` include the list of fields modified by the user. For eg:

```
Hello:
        Dear Sir or Madam, 
photos DEMO-PICTURE-EXP-2010-001 has just been modified.
Modified fields: DEMOPIC_TITLE DEMOPIC_ABSTRACT Upload_Photos
[...]
```

This list is customizable, but usually refers to the file created by the submission for the function `Create_Modify_Interface.py`, which contains the list of field name codes.

The email can be improved by trying to match the element names to their description retrieved from table 'sbmFIELD', column 'sdesc'.

**Comment by ludmilamarian** [comment]
Closing this as there is no need for CDS.
