### ISSUE TITLE
RFC BibCatalog/tickets port

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#2340]
### Problem

The BibCatalog module is not ported to Invenio v2.0 yet, but a skeleton `tickets` module does exist.

This module is meant to implement plugins to connect to external ticketing/issue tracking services via API or simply to an e-mail inbox.

### Proposal

* Add a registry for the wrappers to RT/e-mail etc. to implement the required interfaces.
* Migrate RT plugin to use REST API instead of local perl based client.
* Use models to allow for generically attaching tickets to any kind of model (i.e., not only Record objects). For example to issue tickets about one or several users, authors, etc. (thanks @glouppe).
* Using these models should allow for the use case of query things like "tickets per model" (thanks @kaplun)  
* For the specific binding to RT, that means that such model must foreseen a way to map such IDs to configurable RT custom fields. Basically a configurable mapping must be foreseen.  (thanks @kaplun)

To implement the binding to RT, we could make use of some existing library like https://gitlab.labs.nic.cz/labs/python-rt

@kaplun @jmartinm @glouppe

**Comment by kaplun** [comment]
Note, in Invenio legacy for INSPIRE (PR still to be made) we ported BibCatalog to `python-rt`. That library is higher-level than python-rtkit and hence does more. However it looks like the library is unmaintained and had to locally patch it for INSPIRE. I offered to take over maintainance without an answer so far.

The library is GPL v3. I guess we can simply fork it, and maintain it locally.

**Comment by lnielsen** [comment]
Just seeing this one now.

I would be great tickets module is not bound to a specific backend. E.g. besides RT, it would great if we could use say, CERN Service Now, UserVoice, GitHub or whatever issue system you like.

Also, I can imagine use cases where you would have multiple backends in the same instance.

@kaplun  Do INSPIRE have any plans to take stab on this module?

**Comment by kaplun** [comment]
Yes, BibCatalog is indeed wrapping multiple engines (in principle), and this will stay (sorry if this seemed like RT-centric).

So as far as INSPIRE is concerned I guess it's in our interest to port it to master in the correct way, while still supporting at least the email engine and the RT engine.

**Comment by jalavik** [comment]
Closing as INSPIRE specific. For reference we use the `rt` python library directly on Labs.
