### ISSUE TITLE
jsonalchemy: remove old jsonalchemy test files

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2348]
Test files such as ``invenio/testsuite/data/test_authors.cfg`` that has been superseded by e.g. ``invenio/modules/jsonalchemy/testsuite/fields/authors.cfg`` should be removed.

**Comment by hachreak** [comment]
@egabancho has removed some files.
there are other files to remove? can you make a list of files to remove? Thanks :D

**Comment by jirikuncar** [comment]
Solved in Invenio 3.
