### ISSUE TITLE
search: better responsive search form

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2349]
**What I did:**
Browse http://invenio-demo-next.cern.ch in Chrome using Samsung Galaxy S4 emulation mode:

![atlantis institute of fictive science](https://cloud.githubusercontent.com/assets/1698163/4440532/62317210-47c6-11e4-8c63-6de70543985c.png)

**What happend:**
Search field width is very small, meaning it's very difficult to see what is being typed.

**What I expected:**
A wider search field. 
Possibly by moving Search tips, advanced search and search settings to out of the search field.

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-theme #59](https://github.com/inveniosoftware/invenio-theme/issues/59) via [**ZenHub**](https://www.zenhub.com/)
