### ISSUE TITLE
"About" page

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#239]
Originally on 2010-08-09

Invenio should support something like the MediaWiki "About" page, where users can go to see information such as which code branch and commit the source was checked out from, when the tree was built, which system libraries are installed, what database backend is being used (Currently always MySQL, but one could imagine others), etc. etc.  Information mostly intended as a convenience for developers and sys admins.  It's easy to find these things out, but it would also be easy to collect them all together in one place, and it would make each instance of lookup just a little bit easier.

**Comment by jirikuncar** [comment]
see http://invenio.readthedocs.org/en/latest/
