### ISSUE TITLE
SQLAlchemy: relationship and on delete cascade.

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#2419]
Hi at all,
Today I tried to modify the knowledge module to support automatically cascade deletion of KnwKBDDEF and KnwKBRVAL when I'll try to remove a row in KnwKB table.

First, I modified the database model:

```diff
diff --git a/invenio/modules/knowledge/models.py b/invenio/modules/knowledge/models.py
index d4542a5..8c0bff6 100644
--- a/invenio/modules/knowledge/models.py
+++ b/invenio/modules/knowledge/models.py
@@ -51,13 +51,18 @@ class KnwKBDDEF(db.Model):
 
     __tablename__ = 'knwKBDDEF'
     id_knwKB = db.Column(db.MediumInteger(8, unsigned=True),
                          db.ForeignKey(KnwKB.id), nullable=False,
                          primary_key=True)
     id_collection = db.Column(db.MediumInteger(9, unsigned=True),
                               db.ForeignKey(Collection.id), nullable=True)
     output_tag = db.Column(db.Text, nullable=True)
     search_expression = db.Column(db.Text, nullable=True)
-    kb = db.relationship(KnwKB, backref='kbdefs')
+    kb = db.relationship(
+        KnwKB,
+        backref=db.backref('kbdefs',
+                           cascade="all, delete-orphan"),
+        uselist=True)
     collection = db.relationship(Collection, backref='kbdefs')
 
     def to_dict(self):
@@ -65,7 +70,8 @@ class KnwKBDDEF(db.Model):
         return {'field': self.output_tag,
                 'expression': self.search_expression,
                 'coll_id': self.id_collection,
                 'collection': self.collection.name if self.collection else None}
 
 
 class KnwKBRVAL(db.Model):
@@ -80,7 +86,10 @@ class KnwKBRVAL(db.Model):
     m_value = db.Column(db.Text(30), nullable=False, index=True)
     id_knwKB = db.Column(db.MediumInteger(8), db.ForeignKey(KnwKB.id),
                          nullable=False, server_default='0')
-    kb = db.relationship(KnwKB, backref='kbrvals')
+    kb = db.relationship(
+        KnwKB,
+        backref=db.backref('kbrvals',
+                           cascade="all, delete-orphan"))
 
     def to_dict(self):
         """ Return a dict representation of KnwKBRVAL."""
```

Then, I executed:
```python
KnwKB.query.filter_by(id=1).delete()
db.session.commit()
```
And it remove only the row in KnwKB table.
Instead, I used:
```python
db.session.delete(KnwKB.query.filter_by(id=2).one())
db.session.commit()
```
And it works!
I looked to understand why and I found this post: http://stackoverflow.com/questions/19243964/python-sql-alchemy-cascade-delete
At the end you can read this: 

> Otherwise, you may wish to look at setting up the cascade for your database as well.

And follow the link: http://docs.sqlalchemy.org/en/rel_0_9/core/constraints.html#on-update-and-on-delete
I opened and I read the final note (note: we use MyISAM engine!):

> Note that these clauses are not supported on SQLite, and require InnoDB tables when used with MySQL. They may also not be supported on other databases.

And finally, we arrived to the real question: I should be careful how the query is constructed or exist a solution at all problems?

Thanks, :)
Leo

**Comment by dset0x** [comment]
I could be misinterpreting the issue here, but I am not sure if the correct approach was taken in #3239.
The problem with `cascade` (as quoted in https://github.com/inveniosoftware/invenio/issues/2419#issuecomment-59476170) is that the backend is unaware of this SQLAlchemy construct. One has to inform the model of this explicitly. Here is an example:

```python
class Workflow(db.Model):  # Parent
    __tablename__ = "bwlWORKFLOW"
    uuid = db.Column(...)
    child_logs = db.relationship("DbWorkflowEngineLog",
                                  backref='bwlWORKFLOW', cascade="all, delete-orphan")

class DbWorkflowEngineLog(db.Model):  # Children
    __tablename__ = "bwlWORKFLOWLOGGING"
    id_workflow = db.Column(db.String(36),
                            db.ForeignKey("bwlWORKFLOW.uuid", ondelete='CASCADE'),  # <---
                             nullable=True)
```

In fact, `ondelete='CASCADE'` is neccessary with InnoDB as it enforces the constraints.

**Comment by hachreak** [comment]
We use the `MyISAM` engine that doesn't support the cascade action:

> Note that these clauses are not supported on SQLite, and require InnoDB tables when used with MySQL. They may also not be supported on other databases.

**Comment by dset0x** [comment]
I see. It was on `InnoDB` which we use at INSPIRE that this appeared and fixed as above. This is going to get messy when #3243 and my patches land since I would rather stick to `ondelete`.

Either way, #3239 is probably fine in that case.

**Comment by tiborsimko** [comment]
Superseded by Invenio 3.

**Comment by PritpalSingh786** [comment]
How to delete two tables data combine using flask sqlalchemy query.
My tables and end points are:
class User(db.Model):
    uid = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    confirm = db.Column(db.String(60), nullable=False)

class Record(db.Model):
	rid = db.Column(db.Integer(), primary_key=True, autoincrement=True, nullable=True)
	title = db.Column(db.String(50), nullable=False)
	author = db.Column(db.String(128), nullable=False)
	description = db.Column(db.String(200), nullable=False)
	date = db.Column(db.Date(), nullable=True)
	user_uid = db.Column(db.Integer, db.ForeignKey('user.uid', ondelete='CASCADE'))

@app.route('/delete_account', methods=['GET', 'POST'])
def delete_account():
	if request.method == 'POST':
		try:
			username = request.form['username']
			delete_account = Record.query.join(User, User.uid==Record.user_uid).filter_by(username=username).first()
			db.session.delete(delete_account)
			db.session.commit()
			flash(username+' ''your account deleted successfully')
			return redirect(url_for('login'))
		except:
			flash('Wrong username or Invalid account')

	return render_template('delete_account.html', title='delete_account')


My problem is that my Record table data is delete but User table data is not delete. When I input username in my GUI.
