### ISSUE TITLE
installation: failure in utf-8-mysql-chain detection can be missleading

### ISSUE THREAD

**Issue by aw-bib** [inveniosoftware/invenio#2424]
In `lib/python/invenio/inveniocfg.py` there is testing for the UTF-8 chain implemented (1.1.4, l.676ff.) from `print "Testing Python/MySQL/MySQLdb UTF-8 chain..."` onward. This test consists of the creation of a temporary table writing some greek letter and checking the results. In case it fails, this results in an UTF-8 chain error to be reported.

The test itself is in principle correct, however it may also fail due to completely other circumstances. E.g. setting (erronously) `CFG_ACCESS_CONTROL_LEVEL_SITE  = 3` during invenio installation will work up to this point in the code and one might search the UTF-8 issue forever, as the exception is already thrown from the `CREATE TABLE` stanza.

I would suggest to check `CFG_ACCESS_CONTROL_LEVEL_SITE` first to give an easier interpetable return.

**Comment by lnielsen** [comment]
Invenio 1/2 is in feature freeze so closing this issue.
