### ISSUE TITLE
BibIndex: regression tests not cleaning well after themselves

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#2448]
`bibindex_regression_tests.py` do not clean properly after themselves and affect subsequent regression tests validity. This is currently a blocker for successful integration of #2395.

```
$ diff atlantis.sql atlantis-post-index.sql  | wc -l
3268
```

**Comment by tiborsimko** [comment]
Is this commit fully fixing the problem?  If so, can you please make a pull request?

**Comment by kaplun** [comment]
Yes it is... Although I have to check whether it depends on other bibauthorid thingies...

**Comment by kaplun** [comment]
OK, let's see what Travis has to say.

**Comment by tiborsimko** [comment]
@kaplun FYI I'm looking right now at fixing the regression test case setup/teardown troubles related to authority records, since it is connected to #2693.  So I'll fix it independently as part of that branch, OK?

**Comment by tiborsimko** [comment]
OK, I have it running as part of #2693, now "before" regression test suite and "after" regression test suite is giving the same results WRT `bibrec.modification_date`:

```console
mysql> select * from bibrec order by modification_date desc limit 10;
+-----+---------------------+---------------------+---------------+
| id  | creation_date       | modification_date   | master_format |
+-----+---------------------+---------------------+---------------+
|  10 | 2015-01-28 14:18:25 | 2015-01-28 14:21:43 | marc          |
|  12 | 2015-01-28 14:18:26 | 2015-01-28 14:21:43 | marc          |
|  98 | 2015-01-28 14:18:32 | 2015-01-28 14:21:43 | marc          |
|  55 | 2015-01-28 14:18:28 | 2015-01-28 14:21:43 | marc          |
| 141 | 2015-01-28 14:18:34 | 2015-01-28 14:18:34 | marc          |
| 125 | 2015-01-28 14:18:34 | 2015-01-28 14:18:34 | marc          |
| 128 | 2015-01-28 14:18:34 | 2015-01-28 14:18:34 | marc          |
| 129 | 2015-01-28 14:18:34 | 2015-01-28 14:18:34 | marc          |
| 130 | 2015-01-28 14:18:34 | 2015-01-28 14:18:34 | marc          |
| 131 | 2015-01-28 14:18:34 | 2015-01-28 14:18:34 | marc          |
+-----+---------------------+---------------------+---------------+
```

(Previously, records 20 and 118 were touched by the test suite and not restored back.)

**Comment by kaplun** [comment]
Tibor but these commits are not fixing the issue of
> Actually this boils down to `bibindex_engine.find_affected_records_for_index()` considering only MARC modifications ￼ and thus apparently ignoring external table related modifications.

correct?

**Comment by tiborsimko** [comment]
Those commits fix the original issue description, i.e. introduce proper clean-up when running the tests.  (Which was problematic even for MARC records.) I have not looked at possible non-MARC indexing differences... which is kind of orthogonal... it may be best living as a separate issue.
