### ISSUE TITLE
WebBasket: delete basket confirmation message

### ISSUE THREAD

**Issue by aw-bib** [inveniosoftware/invenio#2449]
In `tmpl_confirm_delete()` from `modules/webbasket/lib/webbasket_templates.py` are asked if they want to delete a basket like

    Are you sure you want to delete this basket?<p>1 user groups are subscribed to this basket.</p> 

The intention of the <p> is clear but it doesn't get rendered on display, so the user gets the above literally. (I didn't check if there are other points in the code where this happens.)

**Comment by tiborsimko** [comment]
Yes, the escaping is done too late. I had a look and it seems to apply only in WebBasket.
