### ISSUE TITLE
OAIRepository: config should allow to use "simple" search instead of "advanced search"

### ISSUE THREAD

**Issue by aw-bib** [inveniosoftware/invenio#2464]
Currently (tested 1.1 but it seems up to current master) OAI repository config is based on invenios old "advanced search". However, compared to the current version of "simple" search this imposes a bunch of restrictions if one needs more complex definitions of set specs. One can work around this by special collections that get exposed, still it would be nice to have the full flexiblity of invenios search at hand here as well.
A use case is e.g. a selective harvesting of bibliographic records by more complex criteria. At join2 e.g. iMPULSE (http://impulse.mlz-garching.de) harvests a certain subset of bibliographic entries from JuSER (http://juser.fz-juelich.de) for the respective publications database. The records for harvesting are defined by contributing institutes or usage of certain facilities. So basically we have a multi criteria definition for the set. Still, we do not want to introduce additional specialized and manual workflow steps as they are easily forgotten and/or need backend adoptions over time.

(@kaplun as discussed in chat)

**Comment by tiborsimko** [comment]
:+1: 

This would also solve one of sub-issues of #2622.

Does one of heavy OAI repository user teams have time to address this?

**Comment by lnielsen** [comment]
I think this would also solve problems in #2587

**Comment by tiborsimko** [comment]
CC @jirikuncar in the light of recent [Sprint-OAIServer](https://github.com/issues?q=user:inveniosoftware+milestone:Sprint-OAIServer)

**Comment by jirikuncar** [comment]
The Invenio-OAIServer package is querying Elastic client directly. The search pattern in OAI set definition is using the same (simple search) syntax as all Invenio 3 packages (Invenio-Search, Invenio-Records-REST, ...).
