### ISSUE TITLE
admin: index page does not work without trailing slash in Apache

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2470]
In an installation with Apache, accessing ```/admin``` without trailing slash gives ```403 Forbidden``` while accessing with the trailing slash works fine.

In a local installation with dev server the redirect works correctly.

Is this related to https://github.com/inveniosoftware/invenio/blob/pu/invenio/base/factory.py#L193 ?

Why are we changing the default behaviour of redirecting URLs without slash to their version with trailing slash? http://werkzeug.pocoo.org/docs/0.9/routing/#rule-format

**Comment by jirikuncar** [comment]
@jmartinm is it still broken? Maybe @lovasko and @dset0x can check that it works with #2645.

**Comment by jmartinm** [comment]
Yes, on our labs site https://labs.inspirehep.net/admin I can still reproduce the problem. Accessing admin without trailing slash gives me:

```
Forbidden

You don't have permission to access /admin on this server.

Apache Server at labs.inspirehep.net Port 443
```

**Comment by kaplun** [comment]
@jirikuncar the issue needs to be fixed into the `pages` module which creates several files:
`filters-1.0.0.js  form-1.0.0.js`. 

There is also a strange `rediscli-1.0.0.js` that we can't figure out the real usage. Possibly Flask Admin? @hachreak, maybe you know a bit more?
