### ISSUE TITLE
RFC: Records REST API (including search)

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2478]
This RFC is late since work on it has already started. Apologies for that. It's however just small wrapper around existing features such as ``format_record`` and ``perform_request_search`` so hopefully it will not be hard to get consensus.

**Proposal**
Create a new Records REST API which supports *getting* records and *searching* records. Additionally make the API flexible enough to be easily extended in the future if we would like to add batch uploading, files, comments, ... 

 * The basic REST *resource* is a ``record``, which internally is just represented via Invenio records. 
 * A record resource can have many different *representations*: ``application/json``, ``application/marcxml+xml``, ``application/mods+xml``, ``application/x-bibtex``, ``application/x-datacite+xml``, ``text/html`` just to name a few. 
 * Each *representation* (mime type) is produced by an *output format*. 
 * An overlay can configure which output format is used for each mime type, allowing an overlay to have a custom representation for e.g. ``application/json``. By default ``application/json`` will be produced by the ``recjson`` output format.

Additional features:
* Support both unauthenticated and authenticated access to API.
* Rate limiting (via Flask-Ratelimiter), with default limits for unauthenticated requests, and configurable limits per OAuth2 application.
* Pagination support

**URL design**

* GET Record
  * GET ``/api/records/:id`` where ``:id`` is the Invenio record id.
  * Request headers: ``Accept: <mime type>`` e.g. ``Accept: application/x-bibtex``. If not specified ``application/json`` is assumed.
  * Query parameters: None (but we could have something like ``?fields=title,author`` to limit the fields returned, but this would mainly make sense for ``application/json`` and be hard to implement for e.g. DataCite.
  * OAuth Scope required: guests (none), authenticated requests (``records:read``)
  * Error codes: 400, 403, 404, 410 (for deleted records), 415 (unsupported media type), 429 (rate limiting)
* LIST Records (i.e. search)
  * GET ``/api/records``
  * Request headers: ``Accept: <mime type>``. We'll have to think of how we can return output formats like e.g. DataCite which doesn't have the concept of collections. Do we just concatenate the results?
  * Query parameters: Two options exists
     1. Keep friends from ``perform_request_search`` such as ``p, c, cc, sf, rm ...``. Pagination however ``jrec`` and ``rg`` however will need to be implemented according to previous RFC #1724.
     2. (preferred) Take the chance to refactor the parameters to something a bit more user friendly and map them to ``perform_request_search``. E.g. something like ``query``, ``sort_field``, ``sort_order``.
  * Pagination: Like per previous RFC #1724 
    * Error codes: 400, 403, 415 (unsupported media type), 429 (rate limiting)

The URL design allows for possible future extensions such as:
```
# Relations from one record to other objects.
/api/records/:id/files/
/api/records/:id/comments/
# REST Subcollections for e.g. collections or communities (note return result is records in the given collection).
/api/records/collections/:collection_id/
```

**Open questions**:
How do we handle access records via multiple identifiers? By default a resource should only be available on a single URL, so alternative URLs could just redirect to the canonical URL. E.g.:

``/api/records/doi/10.5281/zenodo.1 -> /api/records/1``

or 

``/api/records/doi:10.5281%2fzenodo.1 -> /api/records/1``

or 

``/api/persistentid/doi/10.5281/zenodo.1 -> /api/records/1``

Do we have examples from other REST APIs how they deal with this?

Co-authored-by: @konstantinoskostis, @jirikuncar, @egabancho, @tiborsimko

**Comment by jirikuncar** [comment]
This is a follow-up of Invenio Developers Forum discussion about search API and :

### Arguments Proposal

this is a short summary from RFC description made by @lnielsen:

**Basic arguments**

Should be process by search engine directly.

* `query` - search pattern (`author:ellis`, `collection:"Books" title:python`, ...)
* `sort_field`, `sort_order` - sorting options
* `page`, `per_page` - pagination

**Extended arguments**

Following arguments can be processed by search extensions (`aggregations`, `collections`, etc.).

* `filters`, `#...` - filter/facets options **TO BE DISCUSED**
* `index`, `current_collection` (`cc`) - limit search

**Additional arguments**

Defined mostly for formatting purposes.

* `highlights=0/1,True/False` - display highlights
* `fields`, `exclude_fields` - display options

--
cc @inveniosoftware/developers

**Comment by lnielsen** [comment]
> sort_field, sort_order - sorting options

We might consider just ``sort=author`` (sac) and ``sort=-author`` (desc)?

**Comment by drjova** [comment]
@lnielsen +1

**Comment by jirikuncar** [comment]
> `sort=author` (sac) and `sort=-author`

I'm worried that it will bring problems with parsing and generating urls.

If you prefer everything in one argument that it might worth it to have a look at [ElasticSearch](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-uri-request.html) too.

> Sorting to perform. Can either be in the form of `fieldName`, or `fieldName:asc/fieldName:desc`. The `fieldName` can either be an actual field within the document, or the special `_score` name to indicate sorting based on scores. There can be several sort parameters (order is important).

**Comment by lnielsen** [comment]
I don't have a big preference, but your example points to an important point. Sorting by multiple fields for which ``sort_field``, ``sort_order`` is not very well suited. The elastic search syntax looks pretty good to me.

**Comment by jirikuncar** [comment]
> Sorting by multiple fields ...

... then something like `?sort=citedbycount:desc&sort=title:asc` could work better. Please note that I would like to avoid using `?sort=citedbycount:desc,title:asc` as it requires way more parsing.

**Comment by tiborsimko** [comment]
> This RFC is late since work on it has already started. Apologies for that. It's however just small wrapper around existing features such as format_record and perform_request_search so hopefully it will not be hard to get consensus.

Indeed, we already had a broad general consensus before, for example:

- http://invenio-software.org/wiki/Talk/WebAPIs#a3.NewAPIs

**Comment by tiborsimko** [comment]
This would nicely go with all the search module refactoring that is being done for v2.1.

**Comment by jmartinm** [comment]
The /export functionality should also be taken into consideration in this API - see https://github.com/inveniosoftware/invenio/issues/3351

**Comment by lnielsen** [comment]
Closing this RFC as it has been implemented in https://github.com/inveniosoftware/invenio-records-rest
