### ISSUE TITLE
Using manager.add_option() for inveniomanage subcommands has no effect

### ISSUE THREAD

**Issue by dset0x** [inveniosoftware/invenio#2486]
Using the following pattern in a module's manage.py file has no effect.
```python
def append_config(config):
    foo(config)
    return app

manager = Manager(append_config)
manager.add_option('-c', '--config', dest='config', ...)
```

What seems to happen is that `append_config` is never called (as per `flask.ext.script:Manager` documentation) and, instead, `append_config` is assigned to `manager.app`.

I assume that this is related to the signaling method that is used to loading managers, which does not override `add_option()`. Perhaps there is another way that is currently supported?

**Comment by jirikuncar** [comment]
Solved by using Click and Flask 0.11 (Flask-CLI).
