### ISSUE TITLE
RFC checker: support a more powerful configuration file format

### ISSUE THREAD

**Issue by dset0x** [inveniosoftware/invenio#2488]
ConfigParser and friends do not natively support any advanced types, forcing us to do things like [use RawConfigParser to actually get what the user put in the file](https://github.com/inveniosoftware/invenio/blob/master/modules/bibcheck/lib/bibcheck_task.py#L560) and then proceed to [manually replicate SafeConfigParser behaviour](https://github.com/inveniosoftware/invenio/blob/master/modules/bibcheck/lib/bibcheck_task.py#L531). It also makes validating the configuration files more tedious than it has to be.

Supporting a format like YAML (with PyYAML) and a validator (like pyKwalify) can help with problems like these. YAML natively supports more types, including dicts and nested lists. It can return class instances directly from the data, or even load code to allow administrators to extend functionality a little bit more. It also remains highly human readable and writable.

**Comment by jirikuncar** [comment]
Follow https://github.com/inveniosoftware/invenio-checker
