### ISSUE TITLE
RFC: ORCID oauth better local account discovery

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2532]
Problem
======

When using oauth with ORCID, the email of the user is not returned. The info returned is:

![token](https://cloud.githubusercontent.com/assets/580727/5073421/0b4b0370-6e82-11e4-8a12-bc5444e20fd7.png)

So the current default implementation does not provide useful information to discover what local user corresponds to the orcid login:

```python
def account_info(remote, resp):
    """ Retrieve remote account information used to find local user. """

    from ..handlers import token_session_key

    # Store ORCID of the user in session for later retrieval
    session[token_session_key(remote.name) + "_orcid"] = resp.get("orcid")
    return dict(email=None, nickname=None)
```

And it relies solely on the access token:

```python
def oauth_get_user(client_id, account_info=None, access_token=None):
    """
    Retrieve user object for the given request.
    Uses either the access token or extracted account information to retrieve
    the user object.
    """
    if access_token:
        token = RemoteToken.get_by_token(client_id, access_token)
        if token:
            return UserInfo(token.remote_account.user_id)

    if account_info and account_info.get('email'):
        u = User.query.filter_by(email=account_info['email']).first()
        if u:
            return UserInfo(u.id)
    return None
```

As the token expires, the user will see:

![orcidlogin](https://cloud.githubusercontent.com/assets/580727/5073479/74ca72a4-6e82-11e4-9a96-599af5ea6816.png)

And if they introduce their email an error message is shown as that email already exists for a local account! That is obviously not ideal...

Proposal
=======

We should instead rely on the ORCID returned from the oauth process in order to discover the local account.

One option is to query:

```
mysql> select * from remoteACCOUNT;
+----+---------+---------------------+----------user i------------------------+
| id | user_id | client_id           | extra_data                       |
+----+---------+---------------------+----------------------------------+
|  1 |      33 | 0000-0001-8607-8906 | {"orcid": "0000-0002-3598-8536"} |
|  2 |      34 | 0000-0001-8607-8906 | {"orcid": "0000-0002-3598-8536"} |
|  3 |      35 | 0000-0001-8607-8906 | {"orcid": "0000-0001-8135-3489"} |
|  4 |      36 | 0000-0001-8607-8906 | {"orcid": "0000-0002-2082-3106"} |
|  5 |      37 | 0000-0001-8607-8906 | {"orcid": "0000-0002-3598-8536"} |
|  6 |      38 | 0000-0001-8607-8906 | {"orcid": "0000-0002-3598-8536"} |
|  7 |      39 | 0000-0001-8607-8906 | {"orcid": "0000-0002-4133-3528"} |

```

in the above function ```oauth_get_user``` although this is quite ORCID specific.

Other options:

1. Extend user model https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/accounts/models.py#L48 to support external identifiers

2. Add new model to map ``user id`` to ``external id``

Any other options? Recommended way?

@jirikuncar @lnielsen-cern

**Comment by tiborsimko** [comment]
> Somewhere in Invenio we need to map an ORCID to a user (is this already done with bibauthorid?)

It can be done with authority records.  Every user would have an "author JSON record" where we  store all the various identifiers, be they CERN CCID, INSPIRE ID, ORCID, etc.  See e.g. the People database in invenio/master where this is already in place.

If we go this way, then it would make perfect sense to use the pidstore.  However, one inconvenience I see is that we'd have to create/maintain a person record for every user coming via ORCID, be he/she an author or not.  Hence one could have much more users in the People database than wanted for showing off.  (Which could be addressed via role flag or via non-null publication lookup.)

**Comment by jmartinm** [comment]
As https://github.com/inveniosoftware/invenio/issues/2600 got merged this can be closed.

Shouldn't it be closed automatically when the commit message contains ``Closes #``

**Comment by jirikuncar** [comment]
Yes. It will when @tiborsimko makes `pu` the main branch of the repository.

**Comment by tiborsimko** [comment]
> makes pu the main branch of the repository

... also, not before too long we'll be able to switch "master" to an Invenio 2 based branch ...
