### ISSUE TITLE
WebStat: custom query summary graph doesn't work

### ISSUE THREAD

**Issue by PXke** [inveniosoftware/invenio#2553]
Custom summary doesn't work. 

This is due to the fact that the import of mathplotlib is in a try .... except pass code structure. 

Adding mathplotlib as a dependence is almost enough to fix the problem.

**Comment by tiborsimko** [comment]
I think you mean custom query summary graph only, since regular custom event history grahps use flot.  I changed issue title accordingly.

**Comment by PXke** [comment]
You are right !

**Comment by tiborsimko** [comment]
@PXke If ready, can you please make a PR so that this can go to forthcoming v1.2.0?

**Comment by tiborsimko** [comment]
... unless PR #2375 is sufficient.

**Comment by PXke** [comment]
Yes, sorry #2375 is sufficient :smile: !
