### ISSUE TITLE
RFC Replace MailCookie with standard solution

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#2564]
### Proposal

There is a great package [itsdangerous](http://pythonhosted.org/itsdangerous/) that can help us with token handling.

**Example** from *http://blog.miguelgrinberg.com/post/restful-authentication-with-flask*:
```python
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

class User(db.Model):
    # ...

    def generate_auth_token(self, expiration=600):
        s = Serializer(app.config['SECRET_KEY'], expires_in=expiration)
        return s.dumps({ 'id': self.id })

    @staticmethod
    def verify_auth_token(token):
        s = Serializer(app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except SignatureExpired:
            return None # valid token, but expired
        except BadSignature:
            return None # invalid token
        user = User.query.get(data['id'])
        return user
```

**Pros**
- standard solution already used in Flask/Werkzeug
- no need for database (we suppose that `SECRET_KEY` is really **secret**)

--
* see also discussion in https://github.com/inveniosoftware/invenio/pull/2538#issuecomment-64254670
* cc @lnielsen-cern @jalavik @egabancho @tiborsimko

**Comment by jirikuncar** [comment]
**Q: Should token include?**
- [ ] roles
- [ ] actions
- [ ] scopes
- [ ] other ... *(please specify)*

**Comment by jmartinm** [comment]
CC @kaplun maybe related to the HepData use case where we want to pass some information to the users via email and allow them to submit with the token?

**Comment by kaplun** [comment]
Yes we probably need to associate a token to represent the right to create a given deposition with given pre-filled values and given temporary authorization.

**Comment by lnielsen** [comment]
Somewhat related to this RFC: Zenodo now has secret link generation using tokens generated by Itsdangerous. See more on https://github.com/zenodo/zenodo/blob/master/zenodo/modules/accessrequests/tokens.py and https://github.com/zenodo/zenodo/commit/bfd224f944de55a3b8590ec928221593b65233f1

**Comment by tiborsimko** [comment]
Superseded by Invenio 3. See also https://github.com/inveniosoftware/invenio-accounts/issues/7
