### ISSUE TITLE
BibCirculation: delete HB precached format when number of copies of an item has changed

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#257]
Originally on 2010-08-24

When the number of available copies of a record has changed, BibCirculation might need to delete the precached HB format from `bibfmt` table in order to let a chance to format elements relying on the number of items to be updated.

The behaviour could be configurable with a `CFG_*` variable so that the cache is updated when:
1. The number of copies has changed (added or removed copy)
2. The number of available copies has changed (new/removed copy, returned copy, on loan)
3. Never

**Comment by lnielsen** [comment]
Closing as Invenio 1/2 is in feature freeze and no longer needed in Invenio 3.
