### ISSUE TITLE
bibknowledge: kb_export searchtype is substring match by default

### ISSUE THREAD

**Issue by pedrogaudencio** [inveniosoftware/invenio#2570]
**Issue:**
I'm trying to map the arXiv categories to the Inspire ones form a knowledge base, since I'm doing it in the client-side, I make an ajax request to `/kb/export?kbname=<kbname>&format=json`. The workflow is [`request`](https://github.com/inveniosoftware/invenio/blob/pu/invenio/legacy/bibknowledge/webinterface.py#L119-L124) > [`kb_export()`](https://github.com/inveniosoftware/invenio/blob/pu/invenio/legacy/bibknowledge/admin.py#L624-L628) > [`get_kb_mappings_json()`](https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/knowledge/api.py#L201) > [`get_kb_mappings()`](https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/knowledge/api.py#L104-L106).

**Problem:**
Since the `searchtype` in [`kb_export`](https://github.com/inveniosoftware/invenio/blob/pu/invenio/legacy/bibknowledge/admin.py#L584) is by default `"s"`, it always queries [substring key/value matches](https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/knowledge/api.py#L104-L106).

**Proposal:**
Adding the `searchtype` parameter would make it empty by default in the export requests:
```diff
diff --git a/invenio/legacy/bibknowledge/webinterface.py b/invenio/legacy/bibknowledge/webinterface.py
index 03e9772..faf7256 100644
--- a/invenio/legacy/bibknowledge/webinterface.py
+++ b/invenio/legacy/bibknowledge/webinterface.py
@@ -76,6 +76,7 @@ class WebInterfaceBibKnowledgePages(WebInterfaceDirectory):
                                    'expression': (str, ''),  # for dynamic kbs
                                    'collection': (str, ''),  # for dynamic kbs
                                    'kbname': (str, ''),  # for exporting
+                                   'searchtype': (str, ''),  # for exporting
                                    'format': (str, ''),  # for exporting
                                    # for exporting to JQuery UI
                                    'term': (str, ''),
@@ -108,6 +109,7 @@ class WebInterfaceBibKnowledgePages(WebInterfaceDirectory):
         delete_mapping = argd['delete_mapping']
         kbname = argd['kbname']
         format = argd['format']
+        searchtype = argd['searchtype']
         limit = argd['limit']
 
         req.argd = argd  # needed by some lower level modules
@@ -121,6 +123,7 @@ class WebInterfaceBibKnowledgePages(WebInterfaceDirectory):
                                                format=format, ln=ln,
                                                searchkey=searchkey,
                                                searchvalue=term,
+                                               searchtype=searchtype,
                                                limit=limit)
```

@jirikuncar @jmartinm

Fixes https://github.com/inspirehep/inspire-next/pull/128.

**Comment by pedrogaudencio** [comment]
Sorry about the late late answer, @jirikuncar! I've checked the code, I guess there's [no way](https://github.com/inveniosoftware/invenio/pull/2607/files#diff-a0262544ad6aebb0f944df25183689f0R67) of querying using *just* the kb name, @hachreak?

**Comment by pedrogaudencio** [comment]
Also, I see the `searchtype` parameter is still [`"s"` by default](https://github.com/inveniosoftware/invenio/blob/pu/invenio/legacy/bibknowledge/admin.py#L573), which is a problem cause it filters some ~~a lot~~ of values. We're using this temporary commit https://github.com/inspirehep/invenio/commit/8f0daa311b29efbceb97e9c033098a7fdfcbe939 to solve it, but since it was already merged into [`master`](https://github.com/inveniosoftware/invenio/commit/eac2b3ce46cd0d1ba4ae37f60f59ac676ca6a454) maybe it could integrated in `pu` as well.

**Comment by tiborsimko** [comment]
> maybe it could integrated in pu as well.

Indeed, eac2b3ce46cd0d1ba4ae37f60f59ac676ca6a454 has been merged to next/pu, but `kb_export()` definiton in next/pu does not seem to have been changed accordingly...

**Comment by hachreak** [comment]
@pedrogaudencio  I'm working on move from `/api/knowledges/<int:id>` to `/api/knowledge/<str:name>`
#2686

**Comment by hachreak** [comment]
@pedrogaudencio  can we close the issue now? :)

**Comment by pedrogaudencio** [comment]
Hey @hachreak, sorry for the delay replying, I've been on holidays. Sure I'll close it, thank you for the help! ;)
