### ISSUE TITLE
BibCirculation: problem with 'Edit physical copies'

### ISSUE THREAD

**Issue by shesselbach** [inveniosoftware/invenio#2578]
When accessing the 'Item details' page of an item by e.g. pressing the 'Edit physical copies' button in bibedit a '500  Internal Server Error' is shown and an error mail is sent detailing an exception 
'HTTPError: HTTP Error 400: Bad Request' from urllib2 originating from the `BIBCIRCULATION_OPENER.open` call in the `get_book_cover(isbn)` function in bibcirculation_utils.py, lines 104ff. This call tries to retrieve a book cover for the item and is not essential for the functionality. (In Invenio 1.0 this problem did not arise because in the underlying code urllib instead if urllib2 had been used which throws no HTTPError exception.)

In the master branch this problem seems to be fixed by putting the BIBCIRCULATION_OPENER call into """ """, lines 179ff. A possible solution might be to back port this into the maint-1.1 branch.

I was able to get the BibCirculation working in our 1.1.4 test installation by porting the get_book_cover() function from master, i.e.
`"""cover_xml = BIBCIRCULATION_OPENER.open(...`
`...`
`...                 'Keywords=' + isbn)"""`
`cover_xml=""`
`...`
`except:`  (instead of `except AttributeError:` important!)

**Comment by tiborsimko** [comment]
@shesselbach Indeed this works well is master.  Can you please submit your maint-1.1 patch as a pull request?
