### ISSUE TITLE
BibEdit: correct uploading of controlfields

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#2582]
When you try to upload a record having controlfield such as:

```xml
 <controlfield tag="008">this is some text    after spaces</controlfield>
```

After upload you will get this:

```xml
<datafield tag="008" ind1=" " ind2=" ">
  </datafield>
```

BibUpload should treat 001-009 as controlfields.  (with special treatment of 001 and 005)

P.S. See also #230.

CC @Kennethhole

**Comment by kaplun** [comment]
So this is a bug related to BibEdit rather than BibUpload?

**Comment by kaplun** [comment]
Actually I am able to reproduce it. There is maybe mis-handling of controlfields in the javascript part.

**Comment by tiborsimko** [comment]
TIND's workaround is replace all whitespaces before the treatment, hence closing this issue as per the legacy code base freeze.
