### ISSUE TITLE
BibCirculation: prefill ILL forms when recid provided

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#259]
Originally on 2010-08-25

When going to `http://localhost/ill/article_request_step1?recid=XXX` or `http://localhost/ill/book_request_step1?recid=XXX`, pre-fill some fields with the metadata of given recid.

Leave form empty when no recid is provided

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-circulation #17](https://github.com/inveniosoftware/invenio-circulation/issues/17) via [**ZenHub**](https://www.zenhub.com/)
