### ISSUE TITLE
JSONAlchemy: Unexpected handling of lists in records' config

### ISSUE THREAD

**Issue by MSusik** [inveniosoftware/invenio#2599]
Recently I encountered a problem with JSONAlchemy config (.cfg) files. I wanted to create a field which should be a list of strings inside the record. Here is the definition:

``` python
schema:
        {'emails': {'type': 'list', 'force': True, 'schema': {'type': 'string'}}}
```
When there is no key `emails` in the dictionary handled to `Record.create` method, I obtain:

```python
>>> rec['emails']
[{'type': None}]
```
It seems that JSONAlchemy always understands schema as a base for a dictionary. Other than that, it works fine.

I can make it working by defining the field as:
```python
schema:
        {'emails': {'type': 'list', 'force': True, 'items': {'type': 'string'}}}
```
But in this case I can't pass the validation, as Cerberus expects dictionaries inside the list.

https://cerberus.readthedocs.org/en/latest/#items-list
https://cerberus.readthedocs.org/en/latest/#schema-list
Please note that Cerberus' documentation is not complete.

What to do?

**Comment by tiborsimko** [comment]
@MSusik What is the status of this issue?  The build you mentioned seems to be passing, and the line 1360 in the first log file shows no problem:

- https://travis-ci.org/MSusik/invenio/jobs/42638809#L1360

**Comment by MSusik** [comment]
Sorry, the correct one is:

https://travis-ci.org/MSusik/invenio/builds/42723050

**Comment by tiborsimko** [comment]
Thanks.  Can be the problem be related to `eval()` and reserved keywords, as in #2593?

**Comment by MSusik** [comment]
Unfortunately, it didn't fix the problem. Anyway, it shouldn't, as those problems touch different features.

**Comment by MSusik** [comment]
Closed as issue was moved to the new repo.
