### ISSUE TITLE
tests: distributed testing

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2605]
Distribute Invenio testsuite and overlay testsuites on multiple hosts to speed up testing.

Work is already ongoing on creating docker base containers for Invenio, that can be used to speed up the initial build of the VM image. That will already shave off a considerable amount from the build. To further speed up the build process, we should allow our testsuite to be distributed over multiple hosts.

Possible options include e.g. http://pytest.org/latest/xdist.html#xdist as well as https://pypi.python.org/pypi/distributed-nose/0.1.2

**Comment by jirikuncar** [comment]
see also #2986 by @crepererum

**Comment by jirikuncar** [comment]
Please check http://docs.pytest.org/en/latest/xdist.html for Invenio 3 packages.
