### ISSUE TITLE
account: controls on the number of login attempts

### ISSUE THREAD

**Issue by BessemAamira** [inveniosoftware/invenio#2614]
No protective mechanism against  "brute force" attacks is set up. This leads to a huge risk in the case of the login page. A hacker can use an authentication robot to determine the correct login / password (brute forcing). Consideration should be given control mechanisms on the number of connection attempts and / or by  putting up a "captcha"

**Comment by tiborsimko** [comment]
In a distributed system with many independent app servers, a global haproxy rate limiter would be desirable.

It may be better for the safety (and for auditing) to enrich the `user` table to store the number of unsuccessful login attempts and to introduce a configurable cut-off number starting from which the user would be alerted by email and/or his/her login attempts won't be accepted, for example.

**Comment by chokribr** [comment]
by setting CFG_WEBSESSION_DIFFERENTIATE_BETWEEN_GUESTS = 1 
I've got this error 
  File "/usr/lib/python2.6/site-packages/invenio/webinterface_handler_wsgi.py", line 212, in flush
    self.__write(https_replace(self.__buffer))
IOError: failed to write data

** Stack frame details

Frame flush in /usr/lib/python2.6/site-packages/invenio/webinterface_handler_wsgi.py at line 223
-------------------------------------------------------------------------------
       220             except IOError, err:
       221                 if "failed to write data" in str(err) or "client connection closed" in str(err):
       222                     ## Let's just log this exception without alerting the admin:
---->  223                     register_exception(req=self)
       224                     self.__write_error = True ## This flag is there just
       225                         ## to not report later other errors to the admin.
       226                 else:
-------------------------------------------------------------------------------
	                self =  '<invenio.webinterface_handler_wsgi.SimulatedModPythonRequest object at 0xb66366ec>'
	                 err =  "IOError('failed to write data',)"

**Comment by chokribr** [comment]
@tiborsimko  i think it will be better to create a new table with this structure 
CREATE TABLE `LoginAttempts` 
(
'USER_ID' INT(15) NOT NULL , 
`IP` VARCHAR( 20 ) NOT NULL ,
`Attempts` INT NOT NULL ,
`LastLogin_attempt` DATETIME NOT NULL 
)

**Comment by chokribr** [comment]
please look at this try in order to limit the number of login attempt in the legacy branch https://github.com/chokribr/invenio/commit/78f7e2c0eeeb103fe2123eb399e66881e7fb87db

**Comment by lnielsen** [comment]
Moved to inveniosoftware/invenio-accounts#141
