### ISSUE TITLE
RFC MathJax and Assets

### ISSUE THREAD

**Issue by MSusik** [inveniosoftware/invenio#2618]
I would like to use MathJax library with Assets. I created shims and added path to require config:

``` js
require.config({
...
   paths: {
...
      "mathjax": "vendors/MathJax/MathJax",
...
   },
   shim: {
...
    "mathjax": {
      exports: "MathJax",
      init: function (config){
        // this function is required as the assets can't work with
        // MathJax query string inside URL properly
        MathJax.Hub.Config({
            tex2jax: {
                inlineMath: [['$','$']],
                processEscapes: true,
                // please use those two to decide which parts of the site
                // should be rendered by MathJax
                processClass: "mathjax",
                ignoreClass: "nomathjax"
            },
            skipStartupTypeset: true,
            jax: ["input/TeX","output/HTML-CSS"],
            extensions: ["tex2jax.js","MathMenu.js","MathZoom.js"],
            TeX: {
              extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"]
            }
        });
        return MathJax;
      }
    })
...
}
```

Note that I have to include config inside init file, otherwise MathJax would have to be imported with a query string, for example:

```
http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
```

and it is not supported by Require library.

The above code works well, when `ASSETS_DEBUG` is set to `True`. Unfortunately, without it, the MathJax library asks for files tex2jax.js, mathmenu.js, mathzoom.js and config.js using relative path for builded bundle. It results in a 400 Error for each of those files.

WIth ASSETS_DEBUG:

```
304 http://localhost:4000/vendors/MathJax/extensions/tex2jax.js?rev=2.4-beta-2
```

Without ASSETS_DEBUG:

```
400 http://localhost:4000/extensions/tex2jax.js?rev=2.4-beta-2 // wrong one
```

How can I solve it? The only solution that I see is including MathJax using cdn, but I believe it is a wrong solution.

**Comment by tiborsimko** [comment]
> I thought that it might be some kind of Invenio standard to not use CDNs.

We try to give each site an option, see `CFG_MATHJAX_HOSTING` in master, so that they could decide whether to use CDN or local hosting.  This is because sometimes a site may be so restrictive that they want to be fully self-contained.  We also saw a use case of "travelling digital library" where  the network connection was very unsure, etc.  Hence the configuration option for people to choose from.
