### ISSUE TITLE
general: WTForms deprecation of `wtforms.ext.sqlalchemy`

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#2620]
bring forward WTForm 3.0 compatibility:

- [ ] replace by WTForms-Alchemy package: https://github.com/kvesteri/wtforms-alchemy
- [ ] `validators.Required()` to `DataRequired`

--
`invenio/modules/search/forms.py:30:from wtforms.ext.sqlalchemy.fields import QuerySelectField`

**Comment by hachreak** [comment]
now, are we compatible with WTForm 3.0?
Or remains other things to do? :)

**Comment by jirikuncar** [comment]
> replace by WTForms-Alchemy package

@hachreak still the first point is not finished (see `git grep wtforms.ext.sqlalchemy`).
