### ISSUE TITLE
general: investigate remote.autocomplete.field.js replacement

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#2621]
Is there existing library taking care about the same (autocomplete by title but storing primary key in hidden field)?

--
see original PR #2615

**Comment by jirikuncar** [comment]
Is it still relevant or we can close it?

--
cc @bouzlibop

**Comment by jirikuncar** [comment]
ping @hachreak @bouzlibop

**Comment by hachreak** [comment]
for me it's ok the `remote.autocomplete.field.js`.
