### ISSUE TITLE
accounts: store first and last name in user model

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2647]
Current ``user`` model contains:

```
id = db.Column(db.Integer(15, unsigned=True), primary_key=True,
                   autoincrement=True)
    email = db.Column(db.String(255), nullable=False, server_default='',
                      index=True)
    _password = db.Column(db.LargeBinary, name="password",
                          nullable=False)
    note = db.Column(db.String(255), nullable=True)
    settings = db.Column(db.MutableDict.as_mutable(db.MarshalBinary(
        default_value=get_default_user_preferences, force_type=dict)),
        nullable=True)
    nickname = db.Column(db.String(255), nullable=False, server_default='',
                         index=True)
    last_login = db.Column(db.DateTime, nullable=False,
                           server_default='1900-01-01 00:00:00')
```

We would like to store the user real name in order to address that person in emails and around the interface.

One proposed solution is to extend the user model, like Django https://docs.djangoproject.com/en/1.7/ref/contrib/auth/ to include optional first and last name.

What do you think?

**Comment by lnielsen** [comment]
+1 but call it ``given_names`` and ``family_name`` (see http://www.w3.org/International/questions/qa-personal-names#fielddesign).

And what about ``nickname`` -> ``username``.

Lastly, it would be useful to have a profile (adding extra information like  website, location, address) which would be custom per instance (similar to https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#extending-the-existing-user-model)

**Comment by lnielsen** [comment]
Actually do we need to split in given/family name? Could we just use ``full_name``?

**Comment by jirikuncar** [comment]
Is milestone 2.1 ok?

**Comment by lnielsen** [comment]
I guess we can keep ``nickname`` until 2.0 is released, and then change it afterwards (as discussed in the triage team)

**Comment by jirikuncar** [comment]
#### User model

* `given_names` and `family_name`
* `nickname` -> `username`

**Comment by tiborsimko** [comment]
> given_names and family_name 

Can go to 2.0 already, if INSPIRE needs it urgently for LABS?

>  nickname -> username 

Can go to 2.1 or even later.  (Not sure if it is worth it? Just do `git grep nickname` and `git grep username` to see the current occurrences; ideally one would have to amend both these terms to keep nice distinction.)

**Comment by jmartinm** [comment]
> Can go to 2.0 already, if INSPIRE needs it urgently for LABS?

I will create a PR for this very soon as it is indeed needed.

**Comment by lnielsen** [comment]
Anybody had an opinion about ``full_name`` vs ``given_names``/``family_name``? Using only full name alleviates are whole bunch of non-western issues. 

E.g. to make generated a full name from given_names/family_name you need to know the region. E.g. western countries use given names family name, where as in e.g. China they yse family name given names (i.e. reverse).

See http://www.w3.org/International/questions/qa-personal-names#partorder.

The W3C recommendation is to not split if at all possible:
http://www.w3.org/International/questions/qa-personal-names#singlefield

I had marked for in_triage to discuss this last Friday but we unfortunately didn't make it.

**Comment by tiborsimko** [comment]
In Hungary people often put family name before first name, too. And there are other issues: e.g. for CJK names, we may also want to store the original version in say Kanji, plus preferred transliteration in ASCII, if we want to cover various usage scenarios.  

All these various issues and use cases seem to call for using freer structure where additional information about user names would be stored, such as PostgreSQL's JSON column.  In the current MySQL based codebase, you could create optional `more_info` column, containing serialised key-value property store, like we do in bibdocs.  IOW, any wanted additional information about a user would be stored there as a Python dictionary.  If you don't need to search for first names, if you only use them for display purposes,  as you mentioned in your use case, then this should do, and would be more flexible and future-friendly than adding new fixed columns.

**Comment by jmartinm** [comment]
This issue can be closed I would say as it was addressed here https://github.com/jmartinm/invenio/commit/8a1e84a34fc70c6d805f7d8561902409eeaf34ab
