### ISSUE TITLE
bibindex kills the host computer sometimes

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#265]
Originally on 2010-08-29

On tislnx1 where we're running a dump of everything in -dev, reinstalling the site and starting up bibsched and friends works ok.  But as soon as the bibindex process fires, the load goes through the roof.  Sometimes to the point that the host falls over under the strain.

Probably we've got something about bibindex misconfigured, though it should be harder to end up with such misconfigurations.  This is a ticket to get this investigated more.

**Comment by jirikuncar** [comment]
Can't reproduce.
