### ISSUE TITLE
MySQL warning is spamming logs

### ISSUE THREAD

**Issue by PXke** [inveniosoftware/invenio#2650]
We realize that in several case with recent enough mysql instances, logs were spammed by this type of WARNING:

WARNING: <class '_mysql_exceptions.Warning'>: 'INSERT DELAYED' is deprecated and will be removed in a future release. Please use INSERT instead (/usr/lib64/p
ython2.7/site-packages/invenio/dbquery.py:258)

It would be really useful if a way to solve it was implemented.

**Comment by jalavik** [comment]
Hi @PXke, @kaplun made a PR to remove any `INSERT DELAYED` here: #2269. 

If you do not mind, I will close this issue. :boom:

**Comment by PXke** [comment]
Thank you !

**Comment by jirikuncar** [comment]
@jalavik the correct way is to update #2269 (by @kaplun) and add also (`closes #2650`). Thanks

**Comment by jirikuncar** [comment]
Looking deeply on the issue it's duplicate to #2268.
