### ISSUE TITLE
Replace SQLite for this Trac website

### ISSUE THREAD

**Issue by badzil** [inveniosoftware/invenio#266]
Originally

invenio-software.org Trac instance is awfully slow sometimes and if you do not have direct access to someone that can restart it, it is very frustrating and makes the site not usable. This might be due to the usage of SQLite and therefore another option might need to be tested/deployed.

For more in-depth information on this problem, look at [http://howfuckedismydatabase.com/].

**Comment by jirikuncar** [comment]
Invenio is now on GitHub: https://github.com/inveniosoftware/invenio/issues
