### ISSUE TITLE
formatter: error in with date anterior to 1900

### ISSUE THREAD

**Issue by PXke** [inveniosoftware/invenio#2673]
- 2014-12-19 10:26:01 -> ValueError: year=1488 is before 1900; the datetime strftime() methods require year >= 1900 (bfe_meta.py:232:parse_date_for_googlescholar)

*\* User details
No client information available

*\* Traceback details

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/invenio/bibformat_engine.py", line 717, in eval_format_element
    output_text = function(*_params)
  File "/usr/lib64/python2.7/site-packages/invenio/bibformat_elements/bfe_meta.py", line 138, in format_element
    parsed_date = parse_date_for_googlescholar(out[idx])
  File "/usr/lib64/python2.7/site-packages/invenio/bibformat_elements/bfe_meta.py", line 232, in parse_date_for_googlescholar
    return datetime(_(parsed_datetime[0:6])).strftime('%Y/%m/%d')
ValueError: year=1488 is before 1900; the datetime strftime() methods require year >= 1900

**Comment by jalavik** [comment]
@PXke This is in fact a general Python issue with the datetime library. There exists workarounds for this in the datetime library in Invenio: https://github.com/inveniosoftware/invenio/blob/master/modules/miscutil/lib/dateutils.py#L69

To fix this, we can change the import in `bfe_meta.py` to use `invenio.dateutils`:
https://github.com/inveniosoftware/invenio/blob/master/modules/bibformat/lib/elements/bfe_meta.py#L28

**Comment by PXke** [comment]
That would be really cool :) !

**Comment by jalavik** [comment]
Setting in triage, as this can be a discussion we can have if we should go over and amend this where needed.

**Comment by PXke** [comment]
up.

**Comment by jirikuncar** [comment]
@jalavik @PXke what is the desired milestone? Is there a related PR?

**Comment by PXke** [comment]
We have no PR for it. And no desired milestone for it. Even if like always earlier is better.

I upped it mainly because of the comment of @jalavik  about that this can be a discussion.

**Comment by tiborsimko** [comment]
> We have no PR for it. And no desired milestone for it. Even if like always earlier is better.

@PXke If your time permits, perhaps you could take care of this?  Our own `strftime` is a drop-in replacement for the default system function, so it should be relatively straightforward to fix this.  

E.g. here is good example from BibAuthorID:

```console
$ git grep strftime modules/bibauthorid/lib/
modules/bibauthorid/lib/bibauthorid_webapi.py:from invenio.dateutils import strftime
modules/bibauthorid/lib/bibauthorid_webapi.py:    strtimestamp = strftime("%Y-%m-%d %H:%M:%S", gmtime())
```

One needs to amend `bfe_meta.py` and friends in a similar way...

**Comment by jalavik** [comment]
Yeah, basically one has to think about where to apply it. The obvious target is to address places like formatting (display/exporting) where we work with records which may have bibliographic metadata dates prior to 1900. As you can imagine, it is not needed to do anything in modules where it deals with dates that are not bibliographic metadata.

**Comment by jirikuncar** [comment]
@jalavik @egabancho we should then check JSONAlchemy fields definition for `__import__('datetime')`.

**Comment by tiborsimko** [comment]
@PXke Would you like to have a go at this?

**Comment by PXke** [comment]
@tiborsimko it is a bit complicated, it will depend of a lot of things and @audub .

**Comment by tiborsimko** [comment]
OK.  Let's keep you as the "driver" of this issue, until a new assignee comes, OK?

**Comment by PXke** [comment]
Yes no problem. If I have time I will do it :wink:

**Comment by jalavik** [comment]
@PXke Note that some work is already done in #2728
