### ISSUE TITLE
knowledge: rest api issues

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2686]
@hachreak I had look at the new knowledge REST API looks great - just have some few minor comments that I'd like to fix:

- [x] ``/api/knowledges`` -> ``/api/knowledge`` (knowledge is uncountable, thus no plural)
- [x] ``/api/knowledges/<int:id>`` -> ``/api/knowledge/<str:id>`` i think it would make more sense for an end-user to access ``/api/knowledges/licenses/`` than ``/api/knowledges/2`` and ``name`` is already unique in the database model so it should be fine.
- [x]  Possibly allow disabling REST API access to a mapping (to ensure that not everything is exposed).
- [ ] 404 response includes HTML (see below)

```http
HTTP/1.0 404 NOT FOUND
Content-Type: text/html; charset=utf-8
Content-Length: 9319
Server: Werkzeug/0.9.6 Python/2.7.9
Date: Tue, 20 Jan 2015 16:15:01 GMT





<!-- base/bundles_base.html: jquery.js, invenio.js, invenio.css -->
<!-- base/bundles_base.html: require.js -->
<!DOCTYPE html>
<html lang="en">
<head>
```

**Comment by hachreak** [comment]
@lnielsen Thanks for you message! 

I reply to each point:

- Thanks! I'll correct it.
- In the end, we decided to use the id because, being a text field, you can also enter spaces or utf-8.
But if a field is usually purely textual ASCII, I think there are no problems.
@jirikuncar 
- I add oauth check?
- Thanks, I'll check and fix!

**Comment by jirikuncar** [comment]
> In the end, we decided to use the id because, being a text field, you can also enter spaces or utf-8. 

We can `url(de/en)code` the name, hence there should not be any problem with that.

**Comment by lnielsen** [comment]
Regarding the id vs name, we could simply also change name to a slug field or alternatively add a slug field which automatically set from name if no value is specified.

> I add oauth check?

I was more thinking about just perhaps have a boolean value in the data model to enable/disable API access to the KB. We could add an oauth scope check, but it might be overkill.

**Comment by hachreak** [comment]
I see that already exists a `slugify()` function in `invenio/utils/text.py`! :)
I can use it to automatically generate the slug and save it in db!

**Comment by hachreak** [comment]
@lnielsen 
I'll add also a boolean field in the model to enable/disable the REST API access to a mapping as you proposed.
I'll set enabled as default? Or disabled?

**Comment by jirikuncar** [comment]
@hachreak I would say enabled by default. There should not be many restricted mappings.

**Comment by lnielsen** [comment]
@hachreak @jirikuncar Yep I agree. Enabled by default.

**Comment by hachreak** [comment]
Hi @lnielsen, can you check if now we can close this issue? :)

**Comment by hachreak** [comment]
Hi @lnielsen which url response with HTML code? :)

**Comment by jirikuncar** [comment]
> - [ ] 404 response includes HTML (see below)

@lnielsen I'm closing the issue as it's not clear which url is returning wrong 404 response. Please re-open the issue if you spot any issue. Thanks
