### ISSUE TITLE
deposit: bootstrap-datetimepicker v4 not compatible

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2689]
I just confirmed that v3.1.3 work on Zenodo while v4 does not. I assume the fix is as easy as just locking the bower bundle version to something <v4. 

Alternatively, upgrade the JS to work with v4, but then INSPIRE should be notified that they need to upgrade their bower components (i.e. just add NOTE in commit message).

**Comment by lnielsen** [comment]
Ping @jmartinm

**Comment by pedrogaudencio** [comment]
Are you planning to upgrade the JS on Zenodo or just lock it to <v4, @lnielsen?

**Comment by lnielsen** [comment]
Quick fix in 411739a will just lock it.

**Comment by jirikuncar** [comment]
The version lock is ok, however we should address it for 2.1. Hence @switowski can you change the commit message to `addresses` from `closes` and I'll move the milestone to 2.1.

**Comment by switowski** [comment]
@jirikuncar Done.

**Comment by jirikuncar** [comment]
closed via #2691
