### ISSUE TITLE
Odd parenthesis use confuses... something.

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#269]
Originally on 2010-08-31

find (t supergravity or result ) and t quark

Note that space after 'result'.  Without it, the search works.  Which means it gives no results.  But with that space, then it complains that there are mismatched parentheses and breaks.

This is the behavior in my #131 version of search_engine_query_parser.  

But the version of seqp in master breaks just as much, and regardless of whether there's a space.

Annette noticed that (on -prod):
fin (a hawking) gives nothing
fin (a hawking or ellis) breaks too (only 3 results)
 ... but fin (a hawking or a ellis) looks OK

So there's something fascinatingly bizarre going on.

**Comment by jirikuncar** [comment]
It works well for Invenio queries.
```python
In [1]: from invenio.modules.search.api import SearchEngine

In [2]: s = SearchEngine('author:dixon -(collaboration:D0) title:QCD')

In [3]: s.query
Out[3]: AndOp(AndOp(KeywordOp(Keyword('author'), Value('dixon')), NotOp(KeywordOp(Keyword('collaboration'), Value('D0')))), KeywordOp(Keyword('title'), Value('QCD')))

In [4]: s = SearchEngine('(ellis )')

In [5]: s.query
Out[5]: ValueQuery(Value('ellis'))
```

Please re-open in Invenio-Query-Parser repo if you can reproduce the problem.
