### ISSUE TITLE
RFC elasticsearch: allow specifying of unicode character folding

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#2715]
While BibIndex is automatically folding unicode characters using the suboptimal `utf8_general_ci` collation (and in a parallel master-related future PR I am going to propose to allow to configure in a simple way the `utf8_unicode_520_ci` collation for certain indexes), it would be great to take this into account into the early elasticsearch integration into Invenio. In particular it should be easy (and we should have good defaults out of the box) to set the collation/character folding in elasticsearch so that indexes are properly configured.

See: http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/unicode-normalization.html

**Comment by kaplun** [comment]
@marioskogias @jirikuncar WDYT?

**Comment by jirikuncar** [comment]
@kaplun this should not be a problem when the decision about configuration format of native/elasticsearch indexer is made.
