### ISSUE TITLE
RFC SQLAlchemy: validation library

### ISSUE THREAD

**Issue by MSusik** [inveniosoftware/invenio#2720]
There is a library with some validation resources:
https://bitbucket.org/blazelibs/sqlalchemy-validation/src

Before you start shouting that it doesn't support Python3, there is a PR in queue:
https://bitbucket.org/blazelibs/sqlalchemy-validation/pull-request/3/pyhon-33-and-34-support

The library might help achieve more consistency in our databases. For example, using this library, you can validate multiple fields with the same function. Default SQLAlchemy validators are decorators, and decorating one function with two of them doesn't work.

**Comment by jirikuncar** [comment]
After some research I've found following [example](https://gist.github.com/matrixise/6417293) for multi-field validation. Can you give us more specific example for using the proposed library?

**Comment by jirikuncar** [comment]
@MSusik if you find `sqlalchemy-validation` useful for *core* Invenio, please prepare PR with a prototype and re-open this issue. Thanks
