### ISSUE TITLE
INSPIRE formatting changes

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#273]
Originally on 2010-09-01

Collecting here a list of Formatting Changes needed in INSPIRE:

1) Put links to hm and xm formats back in the detailed record page.   Now that we have hidden the hidden fields in these formats, they are useful to display, especially for admins

2) In, for example,

http://inspirebeta.net/record/201469/references

The journal publication info does not show. This is a minor change to
the format (Detailed HTML references) I would eliminate report
numbers unless no other info, or if they are arXiv, and I would add
Journal information (link journal info to doi, if possible, and link
arxiv to arXiv. Link title to INSPIRE record

3) (per Mark Doyle) Adding a few fields to NLM format:
 For instance, it would be helpful if the publication information (journal, volume, page) was returned for published articles, the arXiv id for e-prints, etc. were returned along with the rest of the metadata. Also, when there are multiple URLs associated with a resource, they are all tagged as self-uri without any information about the different URLs (online journal, inspire record, etc.). Any possibility of at least getting the first part improved (the information is in the MARC record, so I think it is just a matter of adding some more fields to the NLM export).

**Comment by jirikuncar** [comment]
@kaplun is it still applicable on latest INSPIRE?

**Comment by jalavik** [comment]
@jirikuncar I believe this is safe to close. Most issues have been sorted and/or going to be addressed with the new formatter.
