### ISSUE TITLE
docker: introduce initial configuration

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#2736]
- [ ] Move and refactor kickstart scripts from tiborsimko/invenio-devscripts into invenio/scripts.
- [ ] Create initial Docker/Fig configuration.

**Comment by jirikuncar** [comment]
It looks like `fig` will become `docker-compose`.

**Comment by kaplun** [comment]
In which this play with @lovasko's work?

**Comment by tiborsimko** [comment]
> In which ways this play with @lovasko's work?

It's part of it, we are splitting the task, I'm refactoring devscripts and preparing Docker/Fig configurations similarly to https://github.com/inveniosoftware/flask-ratelimiter/commit/ce77fe0bc2851c4ceb6c57d422bd4d46e638fe72, and @lovasko is building on top of it to create plugs to Jenkins/OpenStack.

**Comment by tiborsimko** [comment]
I have initial configuration for Invenio v1.0.x with Python-2.4 ready.  (Since it was our minimal requirement there.)  Not many OS images offer Python-2.4 still, let alone MySQL-5.0, so I'll commit CentOS-5 only instructions for `maint-1.0` and `maint-1.1` branches, and we can refactor things later for `master` and `next`.
