### ISSUE TITLE
oauthclient: validate email address on user sign-up

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2739]
For oauth services where the email address is not provided upon first sign up (such as ORCID) we currently show a sign-up form with an input for the email address but that email address is not being validated.

The email address should be validated but ideally the flow of the user wanting, for example, to submit should not be blocked until he/she validates email address.

So the proposal would be to do something similar to what https://balsamiq.com/ is doing. Upon sign-up you can start using the app right away but the validation email states:

> To start your trial, you need to verify your email address. Please go to the link below and log in:

> https://inspirehep.mybalsamiq.com/confirm/ac62ef1a8ce02277c901b61d86690e7fb3d1e1fb

> If you don't confirm within the next 2 days, your site will be suspended. If you don't confirm within a month, the site will be deleted.

> Almost there!

So we could allow for some days to access without validation and after that, block the account.

**Comment by jirikuncar** [comment]
Can we reuse the email validation used for "native" accounts?

**Comment by lnielsen** [comment]
Yes, it should just be tied in with the normal account verification.

**Comment by lnielsen** [comment]
Actually I would downgrade it from enhancement to bug :-)

**Comment by jirikuncar** [comment]
> Actually I would downgrade it from enhancement to bug :-)

Then we should move it to 2.0.X.

**Comment by jirikuncar** [comment]
@jmartinm any progress with this issue?

**Comment by lnielsen** [comment]
This should be somewhat simpler now when #2873 is integrated. It adds a method ``user.verify_email()`` that we just need to call.

**Comment by lnielsen** [comment]
http://invenio.readthedocs.org/en/latest/modules/oauthclient.html
