### ISSUE TITLE
RFC Admin interface bootstrap template

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2743]
**Problem**

Currently our admin interfaces is constrained in space (e.g. tables gets squeeze and there's not much real estate), and design is not particularly nice.

**Proposal**
1. Change base templates for all pages below ``/admin/`` that uses Flask-Admin to a standard admin bootstrap theme.
2. Here are examples of free templates:
  - http://almsaeedstudio.com
  - http://www.blacktie.co/2014/07/dashgum-free-dashboard/
  - http://www.egrappler.com/templatevamp-free-twitter-bootstrap-admin-template/
  - http://startbootstrap.com/template-overviews/sb-admin-2/

Alternatively we could build something ourselves and model it over something like:
http://demo.neontheme.com/dashboard/main-3/

**Comment by jirikuncar** [comment]
> http://demo.neontheme.com/dashboard/main-3/

:+1:

**Comment by lnielsen** [comment]
Neon is unfortunately not free, but in my opinion the one that looks the best.

**Comment by lnielsen** [comment]
Seems like http://almsaeedstudio.com/AdminLTE/index.html might be the best open source version we can get.

/cc @jmartinm @jalavik Any opinions (re. deposit stats/holding pen)?

**Comment by jalavik** [comment]
@lnielsen Yeah, looks decent. So the idea is to have this dashboard style to navigate across all admin pages including curation tools such as bibedit/multiedit and Holding Pen?

**Comment by lnielsen** [comment]
In the first round I would just make all Flask-Admin pages into using this new layout. I.e. collection management, index management, user management, kb management, stats pages?, .... 

I'm not sure where e.g. holding pen/bibedit fits best. Likely there are some admin tasks which a best to keep in normal site layout - e.g. also deposits etc. Probably you're the best person to say where holding pen would fit best.

**Comment by jmartinm** [comment]
Thanks @lnielsen , it looks promising. Right now all the Flask-Admin interfaces are table based to edit some models, what do you have in mind once we move to this theme would be the layout?

Is the idea to move to that /admin page all the functionalities we have currently in /youraccount/display to access all tools like @jalavik suggested?

I am not sure if we will get into conflicts if we try to embed inside of that admin interface things like the Holding Pen, BibEdit and so on as it seems to depends in a handful of 3rd party libraries.

**Comment by lnielsen** [comment]
The idea would be that it for admins only - i.e. youraccount should not go there since it's for end-users, and I you would want to change the interface for normal users. Ie it's basically most of below I imagine could go in the admin:

![screen shot 2015-02-13 at 16 43 31](https://cloud.githubusercontent.com/assets/1698163/6190051/8b2fd874-b39f-11e4-8ed9-858af01631c7.png)

**Comment by jirikuncar** [comment]
Moved to https://github.com/inveniosoftware/invenio-admin/issues/5
