### ISSUE TITLE
previewer: overlapping `collapse` in zip preview tree

### ISSUE THREAD

**Issue by bouzlibop** [inveniosoftware/invenio#2748]
Problem:  
![recorded2](https://cloud.githubusercontent.com/assets/8625570/6079601/e6fc69f8-ae07-11e4-8ad1-139fe2a15a48.gif)

**Comment by jirikuncar** [comment]
- [ ] generate div `id` as "full-path" in the tree

**Comment by bouzlibop** [comment]
Closed by: https://github.com/inveniosoftware/invenio/pull/2755
