### ISSUE TITLE
bibtex and arXiv

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#275]
Originally on 2010-09-01

In export of arXiv records in BibTeX format we should follow  the recommendation on the arxiv.org
> site:
> 
>   "For the new style arXiv identifiers (April 2007 and onwards) we
> recommend
>    these bib-style extensions:
> 
>      archivePrefix = "arXiv",
>      eprint        = "0707.3168",
>      primaryClass  = "hep-th",
>   "

Currently we export arXiv in front of eprint, as well as in prefix.   It should be stripped from eprint.

**Comment by kaplun** [comment]
This was actually implemented in the INSPIRE overlay https://github.com/inspirehep/inspire/blob/master/bibformat/format_elements/bfe_INSPIRE_bibtex.py#L272-L287
