### ISSUE TITLE
Introduction of url redirection for records moved to external sites.

### ISSUE THREAD

**Issue by sbujam** [inveniosoftware/invenio#2751]
In addition to the work already done for merged records (that handles redirection from merged bibno to new bibno **within** Invenio), it would be nice If a librarian could somehow define a redirection to an **external** url for a record that has been permanently deleted.

This would seem useful if for example one moves some records (or an entire collection) from one invenio site to another and wants to help users that have kept bookmarks of the old url location, find the new one.

A special 980 tag "MOVED" could be used (with similar functionality to "DELETED"), that could also hold the redirection url, along with an optional message.
People who search for this record (via websearch, OAI, API, etc) would get for example a "Record deleted and moved to XXXX. Please update your bookmarks." along with the optional message.

**Comment by aw-bib** [comment]
Please note that this feature has a lot in common with the usage of persistent identifiers (doi, handle, urn, purl, what have you). It sounds like a good idea to think about replacin /record/12345 style linking by some such mechanism in the first place. E.g. (in Marc speak) to give something like http://doi.org/12.3456/123456 as link if 0247_ $2doi is set.

**Comment by aw-bib** [comment]
Another sidenote that sprang to my mind this morning: this seems also related to #2573.

**Comment by jirikuncar** [comment]
- It can be solved by new "external PID type" in Invenio-PIDStore.
- More info about redirects: http://pythonhosted.org/invenio-pidstore/usage.html#redirecting
