### ISSUE TITLE
installation: pdftk not available for CentOS 7

### ISSUE THREAD

**Issue by sbujam** [inveniosoftware/invenio#2760]
It seems that pdftk is not available for CentOS7/RHEL7 neither in binary format NOR it can be compiled from source because it requires gcj (and relevant libgcj), which are considered **deprecated** and will **not** be available for these distributions. 
See also [this post](https://github.com/documentcloud/docsplit/issues/123) and [this post](https://www.centos.org/forums/viewtopic.php?f=48&t=47420).

(Having said that, it *seems* that both pdftk and gcj are still available for Ubuntu 14.x and Debian 7.x)

The pdftk developer is aware of this and plans to *eventually* provide a version that will not require gcj. However, because this seems to be quite a heavy task and because pdftk development seems to have slowed down (no official release/update for 1 1/2 year), it might be a good idea to put a *warning* regarding the CentOS7/RHEL 7 incompatibility in the INSTALL file [*].

[*] for me this is a 'blocker' for Centos7 (as I will need pdf stamping) and I found it the hard way...

**Comment by kaplun** [comment]
Thanks for pointing this out. Actually the stamping can nowadays being reimplemented using Pythonic
PyPDF2 (http://pythonhosted.org/PyPDF2/)

**Comment by jirikuncar** [comment]
@switowski @ludmilamarian @egabancho is it in plans for CDS?

**Comment by jirikuncar** [comment]
There are solutions based on http://docs.wand-py.org/en/0.4.3/

**Comment by ewheelerinc** [comment]
@sbujam, We just ran into the same issue. libgcj.so.10 from el6 is compatible with el7's shared library bindings for PDFtk. We built some RPMs that include the library from CentOS6, so if you would like a 1-line install then see here depending on your architecture: https://www.globallinuxsecurity.pro/pdftk-works-on-centos-7/

--
Eric Wheeler
