### ISSUE TITLE
jsonalchemy: `Record.get_record` is inconsistent regarding `str` and `unicode` types

### ISSUE THREAD

**Issue by dset0x** [inveniosoftware/invenio#2772]
`invenio.modules.records.api:Record.get_record` returns a dict with keys and values of type `str` when it is first called.

After the first call, and once the result has been cached in `invenio.modules.records.models:RecordMetadata` (retrieved via `invenio.modules.jsonalchemy.jsonext.engines.sqlalchemy.SQLAlchemyStorage` in the case of `get_record`), both keys and values are now `unicode` instead of `str`.

A simple fix would be to amend its [last `return` statement](https://github.com/dset0x/invenio/blob/pu/invenio/modules/records/api.py#L91) to
```python
return cls.storage_engine.get_one(recid)
```

This may add some overhead in the function call, but since this interfaces for the database, it would probably be better to be as consistent as possible with the result.

**Comment by kaplun** [comment]
:+1: 
Alternatively when the record is being built it can be already constructed using `unicode` everywhere. @egabancho, @jirikuncar?

**Comment by egabancho** [comment]
@jirikuncar should we move this to [jsonalchemy repo](https://github.com/inveniosoftware/jsonalchemy)? or at least duplicate it there so we know we work only with unicode characters in other modules as well.

**Comment by jirikuncar** [comment]
@hachreak can you have a look and make all keys/values `unicode`?

**Comment by jirikuncar** [comment]
@egabancho maybe we should hotfix it here for 2.1. WDYT?

**Comment by tiborsimko** [comment]
:+1: for a hotfix until standalone jsonalchemy is usable.  The output of `get_record()` had better be consistent...
