### ISSUE TITLE
general: `LESS_RUN_IN_DEBUG` has effect only on first load

### ISSUE THREAD

**Issue by jacquerie** [inveniosoftware/invenio#2777]
Steps to reproduce:

1. Setup an Invenio pu instance as described by `INSTALL.rst`, including the demosite.
2. Have the following additional settings in `invenio.cfg`:
```
    (invenio2)~/.virtualenvs/invenio2/var/invenio.base-instance$ cat invenio.cfg
    [...]
    COLLECT_STORAGE = u'flask.ext.collect.storage.link'
    DEBUG = True
    LESS_RUN_IN_DEBUG = False
    ASSETS_DEBUG = True
    DEBUG_TB_INTERCEPT_REDIRECTS = False
    TESTING = True
```
3. Run `inveniomanage runserver` and see that `less.js` is running:
![01_less_working](https://cloud.githubusercontent.com/assets/381280/6208730/885cef54-b5bd-11e4-9a42-9cae595a9a94.png)
4. Reload the page:
![02_hard_reload](https://cloud.githubusercontent.com/assets/381280/6208741/a82e6128-b5bd-11e4-80c1-9188dd1015b9.png)
5. Now `less.js` isn't running anymore:
![03_less_not_working](https://cloud.githubusercontent.com/assets/381280/6208748/c3e60b3c-b5bd-11e4-9595-c65224ccc197.png)

It should be noted that restarting the server "fixes" the problem for one more load.

It'd be helpful to have this running so that styles can be more easily debugged using source maps, as described for instance here: http://robdodson.me/debug-less-with-chrome-developer-tools/

**Comment by bouzlibop** [comment]
**Regarding the `less.js` not working.**

What I notice is that the first time the page is loaded html source looks like:
```html
<link rel="stylesheet/less" type="text/css" href="/less/user-menu.less"/>
<link rel="stylesheet/less" type="text/css" href="/less/sticky-footer.less"/>
<link rel="stylesheet/less" type="text/css" href="/less/zenodo.less"/>
```
but the second time:
```html
<link rel="stylesheet" type="text/css" href="/less/user-menu.less"/>
<link rel="stylesheet" type="text/css" href="/less/sticky-footer.less"/>
<link rel="stylesheet" type="text/css" href="/less/zenodo.less"/>
<link rel="stylesheet" type="text/css" href="/css/accounts/login.css"/>
```
I think the lack of `stylesheet/less` is causing the problem here, but I'm not sure how to fix that now ;/

---

Even after fixing this I'm not sure if we'll be able to debug `less` files.
As described at the page you mentioned:
>Important: If you use less.js to compile your LESS in the browser, the techniques we'll be covering will not work for you. Please see this ticket for more information.

Link to the ticket: https://code.google.com/p/chromium/issues/detail?id=285786

**Comment by jacquerie** [comment]
**Regarding the `less.js` not working.**

Thanks, I didn't notice this. I might investigate its cause, but it has lower priority due to your next observation.

---

Uh, I didn't notice that as well! Even the author of `less.js` suggests to fall back to server side compilation: https://github.com/less/less.js/issues/1541.

**Comment by jacquerie** [comment]
Well, [this line](https://github.com/inveniosoftware/invenio/blob/765e5739514108eac3f8ba0480639e7e4ba81d9a/invenio/ext/assets/extensions.py#L137) looks suspicious. In fact, removing it fixes this bug, but I'm not sure if it's breaking something else. Will submit a PR.

**Comment by bouzlibop** [comment]
Great! This change looks really promising ..
