### ISSUE TITLE
global: flask app not reloading

### ISSUE THREAD

**Issue by bouzlibop** [inveniosoftware/invenio#2778]
As described here: http://stackoverflow.com/a/28242285/2230231, due to some changes in `Werkzeug 0.10`, now automatic changes detection is not working (unless it was my case in my `zenodo` local env and also @hachreak told me that he has the same issue) - it also affects noticeable increase of CPU usage.

The **proposed solution** (taking [this](https://github.com/mitsuhiko/werkzeug/blob/4e2c6746e565eaba7b3bd7489337580b62db610b/werkzeug/_reloader.py#L246-L251) into account) is to install [watchdog](https://pypi.python.org/pypi/watchdog).

Shall we add this somewhere in requirements?

**Comment by jirikuncar** [comment]
@bouzlibop you can add it here https://github.com/inveniosoftware/invenio/blob/pu/setup.py#L133-L135
