### ISSUE TITLE
login page error  CFG_WEBSESSION_DIFFERENTIATE_BETWEEN_GUESTS = 1  

### ISSUE THREAD

**Issue by chokribr** [inveniosoftware/invenio#2779]
by setting CFG_WEBSESSION_DIFFERENTIATE_BETWEEN_GUESTS = 1 
the access to the login page is disabled and I've got this error :
File "/usr/lib/python2.6/site-packages/invenio/webinterface_handler_wsgi.py", line 212, in flush
self.__write(https_replace(self.__buffer))
IOError: failed to write data
flush in /usr/lib/python2.6/site-packages/invenio/webinterface_handler_wsgi.py at line 223

**Comment by kaplun** [comment]
Hi! Is this happening on latest master? Or which version of Invenio?

**Comment by kaplun** [comment]
Note that this functionality might be considered nowadays deprecated. It existed in order to support e.g. Baskets and Alerts for guests users in order to provide a cheap showcase without requiring user authentication.

**Comment by chokribr** [comment]
i thought that by storing guest  user information in the session table  will helpful   for resolving this issue https://github.com/inveniosoftware/invenio/issues/2614 !. 
in other hand to set back  CFG_WEBSESSION_DIFFERENTIATE_BETWEEN_GUESTS = 0, i've got to   delete guest user session from table session and guest user from user table in order  to restore invenio functionality!.

**Comment by jirikuncar** [comment]
> @kaplun ... this functionality might be considered nowadays deprecated

Can you create RFC for removing `CFG_WEBSESSION_DIFFERENTIATE_BETWEEN_GUESTS` from Invenio 2.X?

**Comment by kaplun** [comment]
Done in #2786

**Comment by kaplun** [comment]
No longer valid as per #2786.
