### ISSUE TITLE
admin: admin/ page dropdown not working with ASSETS_DEBUG=False

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2781]
When running in production, admin/ pages are currently broken.

With `ASSETS_DEBUG=True` they work but there is an error in the console:

```javascript
 Uncaught ReferenceError: jQuery is not defined select2.min.js:21
```

So probably the assets build is failing for admin/ pages and Bootstrap.js is not available.

**Comment by jmartinm** [comment]
The bug seemed to be introduced in https://github.com/inveniosoftware/invenio/commit/3dfe0f402d96893680111aabc36c6f9231ac00c3

as select2.js is not requirejs ready.

@hachreak @bouzlibop I see you introduced this commit.

What is select2.js used for?

**Comment by bouzlibop** [comment]
@jmartinm, I think I was mentioned in the commit as a co-author, because I was trying to provide some ideas/possible solutions for this one here - https://github.com/inveniosoftware/invenio/issues/2690#issuecomment-72041860
So said, I don't know what `select2.js`  is used for.
Actual question still remains.

**Comment by hachreak** [comment]
When I opened Knowledge Admin Page (http://0.0.0.0:8080/admin/kb/) I had this error in Flask-Admin filters (http://0.0.0.0:8080/admin/js/filters-1.0.0.js):

![filter](https://cloud.githubusercontent.com/assets/377047/6226520/6e71b988-b696-11e4-8a6a-688549c3002a.png)

**Comment by PXke** [comment]
https://github.com/select2/select2/issues/2946

Can someone take a look ?

**Comment by jirikuncar** [comment]
@PXke it isn't released yet, is it?

**Comment by PXke** [comment]
@jirikuncar to be honest I don't know how the release process does work. But two days ago it is has been tagged 4.0.0-rc2, so I imagine that perhaps it did.
