### ISSUE TITLE
session: remove CFG_WEBSESSION_DIFFERENTIATE_BETWEEN_GUESTS

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#2786]
```python
## CFG_WEBSESSION_DIFFERENTIATE_BETWEEN_GUESTS -- when set to 1, the session
## system allocates the same uid=0 to all guests users regardless of where they
## come from. 0 allocate a unique uid to each guest.
CFG_WEBSESSION_DIFFERENTIATE_BETWEEN_GUESTS = 0
```

In modern Flask time, if one wants to store some session related data for a guest user, should better do it in a cookie. This functionality had been implemented in the past in order to showcase certain Invenio functionalities (baskets, alerts) to guests users, without requiring them to login.

In modern time it is socially acceptable to require authentication to use user oriented functionalities of an online service.

So this RFC is to propose the removal of such configuration piece (thus simplifying the session/authentication/authorization stack).

**Comment by chokribr** [comment]
The number of user login attemp could be stored in the cookie?

**Comment by jirikuncar** [comment]
@chokribr cookie is not a safe place. Better solution would be to use *Flask-Ratelimiter* and use the *nickname/email* as a key.

**Comment by tiborsimko** [comment]
:+1: 

IIRC INSPIRE was the only installation using this feature (for guest submissions and paper claiming) in recent years.
