### ISSUE TITLE
RFC audit log (and undo functionality)

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#2791]
It would be great to introduce an audit log for all the modifications that are performed online to e.g. knowledge bases (sort of who added/updated/deleted what and when), so that it's possible to check the history of modification and also undo changes in case of mistakes.

**Comment by lnielsen** [comment]
@kaplun: Do you mean some sort of automatic undo feature where you undo with a press of a button, or that by having the audit log you will be able to manually undo changes?

**Comment by lnielsen** [comment]
Dependent on merge of new audit module.

**Comment by tiborsimko** [comment]
Note that we have started a general "audit" module that will permit any client to register an audit log event with any number of parameters.

**Comment by kaplun** [comment]
> Note that we have started a general "audit" module that will permit any client to register an audit log event with any number of parameters.

@tiborsimko, where is/what is the current status of the audit module you pointed out?

**Comment by kaplun** [comment]
My understanding is that @tiborsimko's team is going to attack this and other OAIS components in the next months, so I am attaching it milestone v2.4.0.

**Comment by kaplun** [comment]
The module now exists under https://github.com/inspirehep/invenio-matcher, so I guess we can close this RFC and add use cases there.
