### ISSUE TITLE
Provide more helpful messages for gibberish syntax

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#281]
Originally on 2010-09-05

Frankly broken syntax such as:
* (ellis -muon (|kaon))
...should receive a better error message than "Mismatched Parentheses".  Because the parentheses match beautifully; it's just that the search itself makes no sense.

See also #131.

**Comment by jirikuncar** [comment]
`(` can't be before binary operator `OR`,`|`

--
- `'(ellis -muon | kaon)'` works well `OrOp(AndOp(ValueQuery(Value('ellis')), NotOp(ValueQuery(Value('muon')))), ValueQuery(Value('kaon')))`
- `'(ellis -muon (|kaon))'` gets interpreted as `AndOp(AndOp(ValueQuery(Value('ellis')), NotOp(ValueQuery(Value('muon')))), ValueQuery(Value('|kaon')))`
