### ISSUE TITLE
installation: database password escaping

### ISSUE THREAD

**Issue by eamonnmag** [inveniosoftware/invenio#2844]
I've been following the INSTALL.rst instructions for installation of the pu branch.

When setting the database password (CFG_DATABASE_PASS) in the configuration, either through inveniomanage or via manual editing of the cfg file, there is an inconsistency.

If the password is set as password with no quotes, this command fails:
```inveniomanage database init --user=root --password=$MYSQL_ROOT --yes-i-know```
Since the resulting SQL is invalid without the password wrapped in quotes.

When the password is wrapped in quotes, this command will work.
However, now the below command will fail to work
```inveniomanage database create```

So to get this working, you have to edit the config file again and remove the quotes, leaving u'password' in place.

**Comment by jirikuncar** [comment]
@eamonnmag could you please amend the commit message according to *Invenio* standards.

Example:
```
installation: fix database password escaping

* Wraps password in quotes.  (closes #2844)

Signed-off-by: you
Reviewed-by: Jiri Kuncar <jiri.kuncar@cern.ch>
```
