### ISSUE TITLE
RFC Documenting Javascript code

### ISSUE THREAD

**Issue by MSusik** [inveniosoftware/invenio#2845]
# Problem

Currently in Invenio there is no standard for documenting the Javascript code.

https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/workflows/static/js/workflows/tags.js
https://github.com/inspirehep/inspire-next/blob/master/inspire/modules/deposit/static/js/deposit/task_manager.js

# Proposal

Use only the `Sphinx` one, add the information about it in _guidelines for contributing_, `kwalitee` or somewhere else.

**Comment by bouzlibop** [comment]
Glad to see this RFC :smiley:

I'm not sure if `Sphinx` is as expressive when it comes about js code as other javascript documentation tools (eg. [jsdoc](http://usejsdoc.org/) has special tags to describe `events` and `mixin` and also comes with handy examples on how to document [AMD modules](http://usejsdoc.org/howto-amd-modules.html)), but I think it would be the easiest to start using in the project. It would also be good, I guess, to agree on some convention when it comes about documenting some repeatable pieces of code - like `flightjs` components - as it would help to improve readability of that code.

:+1: for the proposal

**Comment by MSusik** [comment]
>  like `flightjs` components - as it would help to improve readability of that code.

Agreed, I think that especially documenting `flightjs` events requires more attention.

**Comment by kaplun** [comment]
:+1: for deciding on a standard. Sphinx would have the benefit of centralizing documentation into readthedocs.org, correct? Additionally we badly need some introduction on all our infrastructure (bower, amd, jasmine) to help a JS newbie (such as me) getting oriented.

**Comment by lnielsen** [comment]
Sphinx doesn't sound like a bad idea, but what are some of the  alternatives to Sphinx besides jsdoc?

**Comment by bouzlibop** [comment]
[Here](http://blog.fusioncharts.com/2013/12/jsdoc-vs-yuidoc-vs-doxx-vs-docco-choosing-a-javascript-documentation-generator/) is nice article, which deals with the most popular tools (JSDoc, YUIDoc, Doxx, Docco), containing a comparision table at the end.

**Comment by PXke** [comment]
:+1:  for the RFC !

**Comment by jirikuncar** [comment]
There is an example for Sphinx and Javascript documentation: https://github.com/eternicode/bootstrap-datepicker/blob/master/docs/conf.py

**Comment by MSusik** [comment]
> There is an example for Sphinx and Javascript documentation: https://github.com/eternicode/bootstrap-datepicker/blob/master/docs/conf.py

Important to note here is that they don't document their code _per se_. Our usecase is different, as we want to document functions inside the code. Sphix's disadvantage is that there is no way to document JS special constructions, such as events.

Still, if we can't integrate any of standards mentioned by @bouzlibop with RTD, I would suggest sticking to Sphinx.

However, I see one tool that might come in handy:
https://github.com/juhamust/jsdoc-toolkit-rst-template

**Comment by bouzlibop** [comment]
> > There is an example for Sphinx and Javascript documentation: https://github.com/eternicode/bootstrap-datepicker/blob/master/docs/conf.py

> Important to note here is that they don't document their code per se. Our usecase is different, as we want to document functions inside the code. Sphinx's disadvantage is that there is no way to document JS special constructions, such as events.

Agreed - I think it would be painful to be obliged to maintain docs and code in separate files (this is the case when using only `Sphinx` with [its current JavaScript support](http://sphinx-doc.org/domains.html#the-javascript-domain)).

I found this ext - https://github.com/lunant/sphinxcontrib-autojs - which could probably work for us (it is similar to sphinx `autodoc` - getting docs from source files). It enforces you to have comments like: 
```js
/**:SomeClass.prototype.someMethod( reqArg[, optArg1[, optArg2 ] ] )

The description for ``someMethod``.
*/
```
as so starting with double asterisks (similar to [how it is done](http://usejsdoc.org/about-getting-started.html#adding-documentation-comments-to-your-code) in JSDoc). Another thing is that I'm not sure how stable it is - last commit is from around 4 years ago and it has only 63 downloads in the last month from `PyPI`. Anyway I tested it with some files and it worked for me.

My feeling is however that if we want to produce some solid documentation we should go with `JSDoc` annotations anyway.

**Comment by jirikuncar** [comment]
- documentation is hosted using GitHub pages http://inveniosoftware.github.io/invenio-search-js/
- automatic documentation deployment https://github.com/inveniosoftware/invenio-search-js/blob/master/deploy.sh
- CI integration https://github.com/inveniosoftware/invenio-search-js/blob/master/.travis.yml#L76-L77
