### ISSUE TITLE
RFC git branch reogranisation after the release of v1.2.0 and v2.0.0

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#2852]
After this week's two new feature releases, **v1.2.0** (stable) and **v2.0.0** (development), the time has come to forward our git branches again.

Here is the recall of our branch policy:

- [Understanding official repo branches](http://invenio.readthedocs.org/en/latest/developers/git-workflow.html#understanding-official-repo-branches)

The branch forwarding requires some extra conventions now that we have important technology differences between Invenio v1 and Invenio v2 code bases. Here is a plan we have been roughly thinking about:

**1.** There are two new release maintenance branches:

- maint-1.2
- maint-2.0

As usual, they accept only bug fixes, without any API changes or DB schema changes, etc.  This is not surprising, it works exactly like the usual `maint-X.Y` branches.

**2.** It is recommended to start any new developments on top of Invenio v2 code base only.  This means doing the following branch renaming:

- current `next` will be renamed to new `master`

All new developments will go here, and eventually this branch will give birth to a later release named v2.1, with its own future `maint-2.1` branch.  Again, nothing surprising here, this is exactly like the past `master` branches.

**3.** Some new features may still be developed for the old Invenio v1 code base.  (This is the novelty point, as in the past the `master` branch was simply forwarded.)  It means to perform the following branch renaming:

- current `master ` will be renamed to `old` or `legacy`

If an installation needs some new feature on top of their Invenio v1 instance, it may be developed there.  Eventually this might give birth to v1.3, v1.4, and even later v1.x code base releases.

However, and this is significant difference, if a new feature branch is prepared only for the "old" v1 codebase, without any counterpart for the "new" v2 codebase, then this feature won't get automatically merged upstream anymore, and might "die" inside some of the v1.x release series -- unless somebody takes it and adapts it for the new v2 code base.

This is dictated by the significant code infrastructure differences between Invenio v1 and v2, where it does not make much sense to develop new feature for v1 and try to "port it" to v2 later.

In summary, it is strongly recommended to use v2 code base for all new feature developments from now on, but if someone running an Invenio v1.2 instance needs a new feature, it is recommended to prepare two branches, one for v1.x and one for v2.x codebase, otherwise the feature may die inside some of the v1.x releases.

**4.** What about past feature requests or pull requests?

The triage team will reclassify past issues, feature requests, and pull requests as either for the "old" v1 code base (when important to a service), or the "new" v2 code base (preferred), or for the "old and new" code bases (rare).  Such a triage effort has been running in the past few months and it will intensify now that v2.0.0 is out.

**5.** What about unstable features that needs side maturing?

Again, we can use `next` and `pu` branches, as until now, which means that:

- current `pu` will be dropped
- we can start new `next` out of `master` when a need arises
- we can start new `pu` out of `next` when a need arises

As in the past, it is recommended to use `master` for all new feature developments whenever possible, with a commit-early-commit-often policy, all the while carefully isolating potentially dangerous or immature features by making them easily "unpluggable" or otherwise "configurable away" from the setup, in order not to hurt other existing Invenio v2 installations.  See items 4 and 5 of our [contributing guidelines](https://github.com/inveniosoftware/invenio/blob/master/CONTRIBUTING.rst).

**WDYT?** Especially those teams that may need have new non-trivial feature developments for the old v1.x code base in the pipeline?

**Comment by kaplun** [comment]
So, indeed, for INSPIRE we still have a maximum (today) of 336 commits that could possibly go into Invenio `legacy`. Most of them are related to the the mega author module (#2395) (which is actually already outdated) and which is going to be reimplemented from scratch for Invenio 2. Some of them are related to refextract, many are simple bug fixes which could go into maint-1.2. So I guess that if we contribute all the work that is currently just sitting in the INSPIRE, ahem, fork, we could contribute to causing the birth of Invenio `1.3` :smile: Also CDS has many branches still to be integrated.

So I can very well see the need for having a `legacy` branch, at least to allow CDS/INSPIRE to contribute back upstream what has been developed in the last years, and which could be still useful for Invenio users who are not yet able to jump on the v2 wagon...

**Comment by lnielsen** [comment]
+1

**Comment by jirikuncar** [comment]
+1

**Comment by ludmilamarian** [comment]
+1
Indeed, as @kaplun mentioned, for CDS there is also the need for a 'legacy' branch for contributing all the already deployed features that have not yet been integrated into Invenio. Some of these features might not need a v.2.1 branch as they will be (or have been) fully re-implemented. These developments are for webnews, webcomment, webalerts, bibdocfile, videos, images.

**Comment by tiborsimko** [comment]
Thanks, closing as agreed.
