### ISSUE TITLE
RFC Dropping INSPIRE-centric legacy code

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#2853]
Part of Invenio code is completely INSPIRE specific and went into the `v1.2.0` (future former `master` branch) partially because of the limitations in plugging optional functionalities in Invenio. Nowadays thanks to the modular approach of `v2.0.0` it is possible to separate such code and move it where it is due to, i.e. the INSPIRE overlay.

This parts amount to:
- [x] **pdfchecker** (a completely INSPIRE-specific module, needed to refresh a given HEP record related to an arXiv record, upon arXiv updates)
- [ ] **HEPData** (this functionality is scattered around in miscutils and search engine, in particular because it introduces a new *Data* tab in the detailed record view.)
- [ ] **plotextractor** (a completely INSPIRE-specific module, upon arXiv updates)

**Comment by lnielsen** [comment]
+1

I guess this could even be expanded to include remove instance specific code from Invenio (e.g. CFG_CERN_SITE and friends):
```
$ git grep 'if CFG_CERN_SITE' | wc -l
     102
```

**Comment by jalavik** [comment]
:+1:  Indeed `CFG_XXX_SITE` should be purged where feasible for `1.x` and should exist nowhere in `>2.x`.

**Comment by PXke** [comment]
+1 Really good ! If possible it would be still cool if the specific INSPIRE modules could be avaiable separately for if needed plug them in an instance through an overlay.

**Comment by tiborsimko** [comment]
Is anyone already working on implementing this, considering the target v2.1?

**Comment by hachreak** [comment]
see also `git grep "CERN.*hack"`

**Comment by jalavik** [comment]
I can volunteer for the pdfchecker and plotextractor. Anything HepData we can just kill outright as it is re-implemented by @eamonnmag and on INSPIRE Labs we'll reuse any widgets from there.

**Comment by tiborsimko** [comment]
Superseded by Invenio 3.0.
