### ISSUE TITLE
RFC richer structure in commit log messages 

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#2856]
## Background

Invenio commit log messages have standardised format described in:

- https://github.com/inveniosoftware/invenio/blob/master/CONTRIBUTING.rst (recommendation 6)
- http://invenio-software.org/wiki/Tools/Git/Workflow#R2.Remarksoncommitlogmessages

Besides better QA, better readability, easier future bisecting, etc,
this permits also to prepare release notes in an automated manner.

This works OK for small incremental update releases with 100+
commits:

- https://raw.githubusercontent.com/inveniosoftware/invenio/v1.1.4/RELEASE-NOTES

but it does not work so well for large feature releases consisting of 1000+
commits, as the recent v1.2.0 and v2.0.0 releases:

- https://raw.githubusercontent.com/inveniosoftware/invenio/v1.2.0/RELEASE-NOTES
- https://raw.githubusercontent.com/inveniosoftware/invenio/v2.0.0/RELEASE-NOTES

The problems include:

- Shortness of messages.  The commit message headline is limited to
  some 50 characters, which is good for being concise, however this is
  often not sufficient to express given change with reasonable
  clarity to the end users.

- Nature of changes.  We have started to use "NOTE" in the commit logs
  to attract attention to important (compatibility) changes, however
  this is not enough to inform the user about the nature of the
  change.  "Is it a new feature?  A bug fix?  Or just some internal
  refactoring that I don't have to care about?"

- One feature branch may consist of many commits, while for the
  reporting we may only need one item.  Some of the commits may be
  better "silenced" in the high-level end-user report.

## Proposal

Let's introduce richer structural markup in our commit log messages
that would address these drawbacks so that we could generate nicer,
more informative *progress reports* in between releases, and *release
notes* later.

Sphinx can serve as an example of what I have in mind:

- http://sphinx.readthedocs.org/en/latest/changes.html#release-1-2-3-released-sep-1-2014

There are basically two approaches how to address this: (1) via commit
log messages; (2) via tickets (issues, pull requests).

### Option 1: use richer structure in commit messages

We could use more leading labels besides NOTE, for example:

```
foo: better support for xyzzy and zyxxy

* FEATURE Foo now supports xyzzy in all the user facing web pages.

* FIX Corrects interface to Zyxxy...

* INCOMPATIBLE Removes foo...

Reviewed-by: John Doe
```

(Side note: instead of textual labels, we could use a subset of
[standard emojis](http://www.emoji-cheat-sheet.com/) that GitHub
supports, say ``:bug:`` instead of ``FIX``, bringing additional eye
candy to our commit logs.)

The richer commit log message structure could be checked by and
enforced via ``kwalitee`` tool that every programmer should run before
making pull requests anyway.

**Advantage:** git repository has all the information about our
software; this "preserves history"; it is usable offline; it is
independent of the ticketing system we use; it is close to
acked-by/reviewed-by directives.

**Disadvantage:** once committed, the information cannot be changed;
the integrators should pay extra attention and should promote
forward-thinking about formulating user-visible changes.

### Option 2: use ticket tracker

Everything we are dealing with has an issue on GitHub, and we triage
our issues with labels and milestones for release planning and
priorities:

- https://forum.invenio-software.org/t/triaging-issues-labels-milestones/58

Hence, instead of enriching the commit log message, we could store
release note like information in GitHub issues.  E.g. github issues
title could be used for item reporting, and could be made more verbose
that the commit log message headline.

Since our NOTE label contain verbose text to be displayed to users,
we'd have to store such a structured information an extra comments,
for example structured in YAML style:

```
notes:
  feature:
   - Foo now supports xyzzy in all the user facing web pages.
  fix:
   - Corrects interface to Zyxxy...
  incompatible_change:
   - Removes foo...
```

**Advantage:** messages can be easily edited after commit is done; "user
insignificant commits" can be grouped in one single issue/PR/branch;
usage of issues drives us to use tickets for everything, improving
visibility/milestone/planning.

**Disadvantage:** bound to concrete ticketing system; offline usage is
impossible; it is easy to "destroy history"; the notes are stored
outside of acked-by/tested-by/reviewed-by information (unless we
refactor this one too); extra information storage via issue comment
looks kind of ugly.

### Option 3: use git notes

We could use other techniques, such as git notes, where integrators
can store the further information about commits.  However, we've
[discussed that before](https://forum.invenio-software.org/t/usage-of-git-notes/55)
and found the usage of git notes not that attractive.

### WDYT?

Which of these directions do you prefer?

## Label set

Whatever technique we'll happen to prefer, we should muse in parallel
about the suitable label set to use.  

For example:

label         | meaning
--------------|-------------------------------------------
FEATURE       | commits adds a new feature
IMPROVEMENT   | commit improves an existing feature
REMOVAL       | commit removes some feature
FIX           | commit fixes a bug
DOCUMENTATION | no code, just docs
REFACTORING   | no user-facing changes
COMPATIBILITY | compatibility remarks, dropping Python-2.6
NOTE          | general note

**Comment by kaplun** [comment]
I very much like going more the GitHub way: should GitHub ever disappear one day we would have very likely yet another exit strategy. 
Additionally this further centralizes the meta-information about code. The fact that is not availble online seems nowadays more of a minor annoyance mostly only for the system integrator who would anyway need to download such information through the APIs in order to compile the changelogs.
The fact that one could also amend this documentation afterwards (as in a wiki) make this option a plus.

**Comment by jirikuncar** [comment]
I'm for **Option 1** as commit messages are important during bug hunting.

> *Disadvantage:* once committed, the information cannot be changed; the integrators should pay extra attention and should promote forward-thinking about formulating user-visible changes.

I see it more as an advantage as it enforces structure to commit messages.

**Comment by hachreak** [comment]
I think we can use commit message.
But, after we publishing a new version, we can collect all this messages with a script and update the changelog file conseguently, like SQLAlchemy do: http://sqlalchemy.readthedocs.org/en/rel_0_9/changelog/index.html
An another very useful feature in SQLAlchemy is that they note in documentation when a new feature is inserted:
e.g. http://sqlalchemy.readthedocs.org/en/rel_0_9/core/connections.html#sqlalchemy.engine.Connection.get_isolation_level

![sql](https://cloud.githubusercontent.com/assets/377047/6526251/144bc6b0-c410-11e4-822b-b02fe0b47e9b.png)

**Comment by tiborsimko** [comment]
> But, after we publishing a new version, we can collect all this messages with a script and update the changelog file conseguently

That's exactly what we do as well with RELEASE-NOTES, and the purpose of this RFC is to have more structure there.

> An another very useful feature in SQLAlchemy is that they note in documentation when a new feature is inserted:

Great that you brought it up, yes we use this in Flask extensions already, for example:

- https://github.com/inveniosoftware/flask-menu/pull/20#discussion_r19813027

We should start using it in Invenio too.

**Comment by dset0x** [comment]
I have some issues with piggybacking commit messages:
* They would add a hurdle for getting commits merged.
* A single commit (or even PR) may not reflect an entire user-level feature. In fact, it may even be (partially) undone before the following release. Would we rewrite git history just for this?
* Commit messages are written for programmers to read and derive information from, not for metadata. If we follow this approach, then this will also mean that we can undo restrictions such as "no verbs in the summary", which I struggle with, as they make my summaries very vague at times. (Example:
 `base: apache generator switches to cfg`
What _switches_ is this referring to? Are they being moved to config? Are they added to config? Is 'generator' _switching_ to 'cfg'?)

We can maintain a structured `CHANGELOG` file when committing user-concerning or API-affecting changes.

---

What uses emojis other than github?

**Comment by jirikuncar** [comment]
> A single commit (or even PR) may not reflect an entire user-level feature.

Each commit (PR) should be self-containing. It is fine if you have many commits in your working branch, but before it gets merged to *upstream* one should squash them.

First line is a brief description that should be descriptive enough if you do `git log --format=oneline` (`| grep '^<component>:'`).

Reminder: each commit in PR **MUST** to pass **ALL** tests, otherwise it makes bug-hunting/bisecting quite hard.

> We can maintain a structured `CHANGELOG` file when committing user-concerning or API-affecting changes.

That would be a big source of conflicts during merges.

**Comment by tiborsimko** [comment]
> What uses emojis other than github?

According to [emoji cheat sheet](http://www.emoji-cheat-sheet.com):

- Campfire, GitHub, Basecamp, Redbooth, Trac, Flowdock, Sprint.ly, Kandan, Textbox.io, Kippt, Redmine, JabbR, Trello, Hall, Plug.dj, Qiita, Zendesk, Ruby China, Grove, Idobata, NodeBB Forums, Slack, Streamup, OrganisedMinds, Hackpad, Cryptbin, Kato, Reportedly, Cheerful Ghost, IRCCloud, Dashcube, MyVideoGameList, Subrosa, Sococo, Quip, And Bang, Bonusly, Discourse, Ello, Twemoji Awesome, Got Chosen, Flow, ReadMe.io, esa, DBook, Groups.io, TeamworkChat and Damn Bugs.

**Comment by switowski** [comment]
I like the first option with the label set. Having a proper amount of metadata in the commit message is more convenient when I'm searching for something in the log. By *proper* I mean just enough to know what exactly this commit is doing without going to github to read the PR each time (but if I want to know **why** do we need a specific feature then I can go and read the PR). And the emojis are cool but the uppercase labels in git looks more clear for me.

**Comment by dset0x** [comment]
> It is fine if you have many commits in your working branch, but before it gets merged to upstream one should squash them.

What about the step-by-step _development_ reasoning that is enveloped their order?

> each commit in PR MUST to pass ALL tests, otherwise it makes bug-hunting/bisecting quite hard.

Will the new CI cater for this? I have unmerged branches that have this issue.

**Comment by jirikuncar** [comment]
> What about the step-by-step development reasoning that is enveloped their order?

Of course do whatever you like in your branch. Just keep it mind to squash the commits when everything is done.

**Comment by tiborsimko** [comment]
> In fact, it may even be (partially) undone before the following release. Would we rewrite git history just for this?

Nope, we do not allow rewriting git commit history in already-pushed branches in the official repository.
But your concern is very valid, the release notes would have the full history there, kind of like:

- Foo: initial release of bar and baz
- Foo: improves baz 
- Foo: improves baz even more
- Foo: drops baz for xyzzy

This can be (1) good for those sites that track `master` (see my *progress report* use case), but it is (2) bad for those sites that track only released versions (see my *release notes* use case).

I don't think it is too bad to report full history.  We plan to have shorter release cycles, so this should not be too probable.  (Plus we should think more *before* making those N changes.)

If we do want to solve this, we could perhaps invent some special markup, e.g. the later commit could say something like:

- INVALIDATES fff111 fff222 fff333

so that script would know not to include release notes from those commits.  Just a possibility.

> We can maintain a structured CHANGELOG file when committing user-concerning or API-affecting changes.

Sound like an old technique. This is how GNU Emacs used to do these things traditionally.  Generally speaking, contributors did not like it too much, as it kinds of duplicates the logging what VCS does. I'd rather generate CHANGELOG from VCS or from tickets than relying on people to update it manually. 
(Since we want to have high level of details there for the *progress report* use case, as in "what incompatible changes does 2.1.0.dev2150413 brings that may break Zenodo?"  Important for sites tracking bleeding edge `master`.)

Though we could naturally combine these techniques, e.g. generate it automatically but allow editing results later.  Like I'm doing with RELEASE-NOTES to clean obvious issues, such as people mistyping module names, making issue to be mis-categorised.

**Comment by dset0x** [comment]
I don't see how this stores the reasoning.

**Comment by tiborsimko** [comment]
> I like the first option with the label set. Having a proper amount of metadata in the commit message is more convenient when I'm searching for something in the log. By proper I mean just enough to know what exactly this commit is doing without going to github to read the PR each time 

This "offline usage" is a great asset of option 1 for me too.

**Comment by kaplun** [comment]
> > We can maintain a structured CHANGELOG file when committing user-concerning or API-affecting changes.
> Sound like an old technique. This is how GNU Emacs used to do these things traditionally. Generally speaking, contributors did not like it too much, as it kinds of duplicates the logging what VCS does. I'd rather generate CHANGELOG from VCS or from tickets than relying on people to update it manually. 
(Since we want to have high level of details there for the progress report use case, as in "what incompatible changes does 2.1.0.dev2150413 brings that may break Zenodo?" Important for sites tracking bleeding edge master.)

Old does not necessary imply wrong, and additionally the git log does not solve the issue of separating the audience: final admins Vs. developers.

Plus, what if one forgets about documenting at commit log time a given API changes, new functionality etc.? Would you recommend introducing an empty commit afterwards (not sure if this is possible)?

> That would be a big source of conflicts during merges.

Not if would use `registry` for that. Then every module would be responsible for its own announcements...

> > An another very useful feature in SQLAlchemy is that they note in documentation when a new feature is inserted:
> Great that you brought it up, yes we use this in Flask extensions already, for example:

> inveniosoftware/flask-menu#20 (comment)
> We should start using it in Invenio too.

But it's currently not possible at commit time to know the version in which a given commit will end into. At best we could say: *not available in versions earlier than x.y.z included* :smile:

**Comment by dset0x** [comment]
> (Since we want to have high level of details there for the progress report use case, as in "what incompatible changes does 2.1.0.dev2150413 brings that may break Zenodo?" Important for sites tracking bleeding edge master.)

I think this is the major decision point here. This makes adding the information in the commit messages themselves the only way. I was thinking based on the assumption that other projects leave me with: _"If you are tracking git, you are on your own to figure out what broke when"_.

Another big point is the development style. Some projects are mature enough for their commits to be mostly fixes and small-to-medium sized feature additions, while this is not the case with `next`, where large modules are added often. This is why I find squashing to be too information-concealing.

> But it's currently not possible at commit time to know the version in which a given commit will end into. At best we could say: not available in versions earlier than x.y.z included :smile: 

After some more thinking: perhaps tighter release cycle will make per-release goals more clear.

**Comment by tiborsimko** [comment]
> Old does not necessary imply wrong

Howgh!  I too prefer Beethoven to Shakira :smile: or, to use more software development related anecdote, the good old CLOS with multi-method dispatch more than any "modern" OO based on simple message passing.

> git log does not solve the issue of separating the audience: final admins Vs. developers

... and it is indeed the role of this RFC to look for solution.  E.g. having note labels would address this, since admins are interested in reading only some notes, while developers should read everything.

> Plus, what if one forgets about documenting at commit log time a given API changes, new functionality etc.?

That's indeed why option 1 puts more pressure on the integrators to get this right from the get go.  Which is a disadvantage of option 1 and advantage of option 2, as I stated in the original RFC. 

I think we should compare pros/cons of each technique and choose the least inconvenient one for everybody.

**Comment by jirikuncar** [comment]
> `* INVALIDATES fff111 fff222 fff333`

:+1:

**Comment by tiborsimko** [comment]
> But it's currently not possible at commit time to know the version in which a given commit will end into.

I think it is possible.  Adding features is not allowed for patchelevel point releases, so if we are on 2.1.0.dev20150305 now, and if somebody makes a PR that adds a new API or modifies an existing API, then he/she can safely add:

```
.. versionchanged:: 2.1
```

to the code at the moment of asking for merge.

(And if we happen to release it as Invenio 3.0, not as 2.1, due to some other reason, then we just replace all 2.1 by 3.0 just before releasing in these docstring lines.)

**Comment by tiborsimko** [comment]
> After some more thinking: perhaps tighter release cycle will make per-release goals more clear.

That's indeed what we are aiming for, now that we have fresh start with both the legacy code base (sprinting for v1.3) and the new era code base (sprinting for v2.1). 

(Making releases out of 1000+ commit changes is far from ideal, both for end users and for us developers.)

**Comment by hachreak** [comment]
Maybe we can consider a:
### Option 4
Put all this messages in the code (with a good format, to decide) and leave the commit messages more lightweights.
We can put the comments directly in the code or in separate files. 
The advantage of this method, instead of using commit messages, is that these are read/write.
Then, to collect all the messages we can use something like `git diff previous_version HEAD | grep -v ^- | grep "# MSG"`. Or other techniques.. :P

**Comment by kaplun** [comment]
> Maybe we can consider a:
> Option 4

Yep, that's more or less along the line of @dset0x + my proposal:
> > >We can maintain a structured CHANGELOG file when committing user-concerning or API-affecting changes. 
> > That would be a big source of conflicts during merges.
> Not if we would use registry for that. Then every module would be responsible for its own announcements...

(GitHub should consider using Disquss for the commenting functionality :smile:)

**Comment by tiborsimko** [comment]
> leave the commit messages more lightweights.

We insist on preparing quality commits, i.e. logically separate, i.e. atomic, i.e. always passing tests, i.e. always having good kwalitee, etc, so that the understanding (and later bug hunting and bisecting) would be easy.  If people are encouraged to write good atomic commits, cannot they write good structured commit messages at the same time?  Seems like a cheap add-on for great benefit.

> We can put the comments directly in the code

And indeed we should, like that "versionadded" and "deprecated" and other reST formatting in API function docstrings.    

> The advantage of this method, instead of using commit messages, is that these are read/write.

... and a disadvantage is that one cannot easily ask questions like "who developed this feature and who approved it?" because `git blame` is not enough in this read/write case.  

(If you write github issue numbers there, then it would be kind of duplicating the effort, because people are to put them in commit log messages too, for having proper closure via `closes #nnn` facitily.)

**Comment by jalavik** [comment]
**Option 1** seems to be the path of least resistance in terms of adapting to a new way and it certainly has other pros as mentioned. With smaller release cycles it should also be easier to treat any mistakes that slipped through in the release notes themselves.

In addition, to aid this review process, it would be cool if we could somehow easily generate the release notes for whole Invenio or within a certain module to see how they would look for the current commit. Especially when checking if "invalidating" any previous commits is necessary. Perhaps as part of `kwalitee` tool? 

I am going into details now, but speaking of invalidating, maybe we should have another keyword/syntax when removing a module that would invalidate anything previous for this module from the release notes (not that it would happen often..).

**Comment by tiborsimko** [comment]
> In addition, to aid this review process, it would be cool if we could somehow easily generate the release notes for whole Invenio or within a certain module to see how they would look for the current commit. Especially when checking if "invalidating" any previous commits is necessary. Perhaps as part of kwalitee tool? 

So far I've been having (personal) script that generate these release notes, and the rough plan was to (1) agree upon using git commits or github issues; (2) adapt the script accordingly; (3) commit it to Invenio scripts place; (4) make it display *live* those *progress reports* kind of stats on the new invenio-software.org page (i.e. Flask one, non-Trac one).  This should make following up and reading progress notes easy. 

(E.g. you recall those NOTE comments that we introduced for simpler tracking of changes potentially breaking sites on master... so the new invenio-software.org web site would be assembling them live, providing nice reading experience, and "on steroids", i.e. with all the new labels.)

**Comment by jalavik** [comment]
> (4) make it display live those progress reports kind of stats on the new invenio-software.org page

That sounds cool!

**Comment by jirikuncar** [comment]
@egabancho @kaplun 

```
component: short description

* FIXES#1234

* NEW

Signed-off-by: ...
```

**Comment by jmacmahon** [comment]
Not that I'm DLT, but Option 1 makes the most sense to me too.  Having as much as we can in the Git repo itself seems to be a good idea.

**Comment by glouppe** [comment]
In in favour of Option 2. This is the least constraining solution for (occasional) contributors. Lowering the barrier for contributions is indeed a good thing in my opinion. Though I agree this requires more work for integrators.

**Comment by jirikuncar** [comment]
> This is the least constraining solution for (occasional) contributors.

Some stats since v1.1.0.
```
Occasional developers (<10 commits):
~70 people, ~200 commits, avg ~2.8 commits per developer
Regular developers:
~30 people, ~3500 commits, avg ~116 commits per developer
```

Personally, I would rather cherry-pick and amend all commit messages from occasional developers than from all commits from 2 regular developers in order to have (semi-)automatically generated RELEASE-NOTES from commit messages.

**Comment by tiborsimko** [comment]
> Personally, I would rather cherry-pick and amend all commit messages from occasional developers

Yes, that's been the usual practice in `master`, and even for commits from not-so-occasional developers, because suggesting wording changes and queueing fully-ready branches so that people would rebase them just to amend the commit message, one branch after another so that pending branches would be fast-forward-mergeable, can result in lot of "empty" waiting time.

> I would like to see all regular/core developers/reviewer to take care about commit and commit message kwalitee. 

:+1: This joins my point expressed above on the fact that we pay great attention to commit atomicity and kwalitee, for good reading/bisecting reasons (which is especially useful in our project with high turn-over of developers); so if people pay more attention *also* to commit log message labelling and structuring, it should not be too big of an add-on burden to what we already do anyway...

(And individual developers will be able to use the kwalitee checker to catch any bad structuring upfront, and reviewers/integrators should pay attention to this in any case while adding "Reviewed-by" QA label to people's branches, as part of `invenio-check-branch` like process.)

**Comment by tiborsimko** [comment]
> Not increasing the barrier for contributions (which is already quite high) is indeed a good thing in my opinion. 

Wouldn't this concern be addressed by providing `kwalitee` tool that people run locally on their branches to see authoritative and comprehensive report on what's recommended to fix in their branches?  

At first try, the occasional contributors may see the kwalitee observations as funny-sounding perhaps, but if the report is comprehensive and all-encompassing, then people are also handed clear path to improvement, a kind of authoritative "learning aid".

(Note: currently the kwalitee tool may "overdo" or "underdo" certain warnings, but we plan on improving it constantly.  E.g. for `master` the PEP-8 is only recommended, so `invenio-check-branch` only shows kwalitee warnings brought by the new feature branch itself.  We can configure `kwalitee` in similar way so that its output would be fully authoritative in similar manner, based on agreed coding standards in each concrete project.)

**Comment by egabancho** [comment]
I would say option 1 plus adding the API changes to the docstrings `.. versionchanged:: 2.1` should be more that enough.

My only concern is about redundancy in the commit message, are we going to write `closes #nnn` and also `fixes #nnn`?

**Comment by drjova** [comment]
:+1: for Option 1

**Comment by bouzlibop** [comment]
Among the options proposed __Option 1__ seems to be the most coherent with me.
About emoji - I think that might be a nice by-product of introducing this richer structure in commit messages if only we would be able to find proper mapping for all labels we want to introduce.

**Comment by tiborsimko** [comment]
> My only concern is about redundancy in the commit message, are we going to write closes #nnn and also fixes #nnn? 

Nope, usually the addition of leading label should be sufficient.  

Here is one simple example:

- commit message old style:

```
commit b957a8a21d57c0801538bb93ee05f7bd7d04e5e3
Author: Tibor Simko <tibor.simko@cern.ch>
Date:   Wed Jan 28 10:23:16 2015 +0100

    BibIndex: fix new-old record incremental indexing
    
    * Fixes incremental indexing leak for "new old" records, i.e. new
      records that were uploaded as if they were old, via some 005 value
      from the past.  (closes #2693)
    
    * Also, amends `find_affected_records_for_index()` default parameter
      values from mutable empty lists to immutable `None` in order to
      prevent potential mishaps.
    
    Signed-off-by: Tibor Simko <tibor.simko@cern.ch>`
```

- commit message new style

```
commit b957a8a21d57c0801538bb93ee05f7bd7d04e5e3
Author: Tibor Simko <tibor.simko@cern.ch>
Date:   Wed Jan 28 10:23:16 2015 +0100

    BibIndex: fix new-old record incremental indexing
    
    * FIX Fixes incremental indexing leak for "new old" records, i.e. new
      records that were uploaded as if they were old, via some 005 value
      from the past.  (closes #2693)
    
    * Also, amends `find_affected_records_for_index()` default parameter
      values from mutable empty lists to immutable `None` in order to
      prevent potential mishaps.
    
    Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
```

This commit contains headline and two paragraphs.  The headline would be ignored, the first paragraph would be used inside a "Bug fixed" section of the release notes, and the second paragraph would be ignored as well.  (Or, better said, only visible to developers using git logs.)

***

To take a slightly more complex example, consider the following commit message:

```
commit 13d3840146bdb9be52885ec91af357a017ba17be
Author: Nikolaos Kasioumis <nikolaos.kasioumis@cern.ch>
Date:   Tue May 27 21:56:05 2014 +0200

    WebSearch: search results pattern limit fix
    
    * Fixes pattern-limit style of queries (`/search?subject=physics`)
      by modifying `prs_apply_search_limits` so that the `results_final`
      dictionary is updated, rather than re-defined locally.
      (closes #1750) (PR #1751)
    
    Signed-off-by: Nikolaos Kasioumis <nikolaos.kasioumis@cern.ch>
    Co-authored-by: Ludmila Marian <ludmila.marian@gmail.com>
    Tested-by: Tibor Simko <tibor.simko@cern.ch>`
```

In the new commit log style, one would want to reword the message to something user-oriented and something developer-oriented, for example:

```
commit 13d3840146bdb9be52885ec91af357a017ba17be
Author: Nikolaos Kasioumis <nikolaos.kasioumis@cern.ch>
Date:   Tue May 27 21:56:05 2014 +0200

    WebSearch: search results pattern limit fix
    
    * FIX Takes properly into account the search pattern limit queries
      (for example `/search?subject=physics`) that might have been 
      passed from the Advanced Search interface.
      (closes #1750) (PR #1751)

    * This is done by modifying `prs_apply_search_limits` so that 
       `results_final`  dictionary is updated, rather than re-defined locally.
    
    Signed-off-by: Nikolaos Kasioumis <nikolaos.kasioumis@cern.ch>
    Co-authored-by: Ludmila Marian <ludmila.marian@gmail.com>
    Tested-by: Tibor Simko <tibor.simko@cern.ch>
```

**Comment by tiborsimko** [comment]
> About emoji - I think that might be a nice by-product of introducing this richer structure in commit messages if only we would be able to find proper mapping for all labels we want to introduce.

One could surely invent some corresponding emojis *after* we first agree upon the label set.

So let's take this occasion to muse about the label set proposed in the original RFC first.  In view of internal notes not having any label (see above), these could be used for refactoring etc; so perhaps we can simplify the label set to something short like:

label                    | meaning
----------------------|----------------------------------------------------------------
NEW                   | commit adds a new feature
FIX 	                   | commit fixes a bug
BETTER  	           | commit improves an existing feature
COMPATIBILITY | compatibility remarks, removing features and dependencies
NOTE 	           | any general note (if needed)

A low number of labels could have direct translation to coloured labelled badges in the release notes, e.g. green for new, blue for better, orange for fixes, red for compatibility notes, gray for general notes.

(And if we want to have emojis, there are many ways how to find an association between  these labels and the [available set](http://www.emoji-cheat-sheet.com/); though personally I think the short uppercase textual labels might be sufficient.)

**Comment by lnielsen** [comment]
I would add one extra label ``SECURITY`` meaning ``commit fixes a security issue`` since this is relevant to highlight explicitly in release notes.

**Comment by jirikuncar** [comment]
Collecting all comments and suggestions from this RFC and closing it with following outcome.

## Conclusion

label                    | meaning
-----------------------|----------------------------------------------------------------
NEW                    | commit adds a new feature
SECURITY          | commit fixes a security issue
FIX 	                    | commit fixes a bug
BETTER  	    | commit improves an existing feature
INCOMPATIBLE | compatibility remarks, removing features and dependencies (see also #2875)
NOTE 	            | any general note (if needed)

Finish your commit with a git signature following #2876.

**Comment by dset0x** [comment]
I may have missed what were the final reactions about `INVALIDATES` in the comments above. What is the final verdict about it?

**Comment by jirikuncar** [comment]
@dset0x @tiborsimko I would go for `INVALID` instead of `INVALIDATES`. If you agree we can close this RFC and move it to documentation. Do you have any specific section in mind?

**Comment by dset0x** [comment]
I think `INVALID` is better. It helps to remember them - one can now think "What I'm typing right now '**is** {a,for,} new/security/fix/better/invalid/incompatible/note'"

**Comment by tiborsimko** [comment]
@dset0x @jirikuncar Hmm, `INVALID fff1122` may look a bit too harsh, as if the whole SHA1 commit is invalidated, not only its log message. That kind of impression. What about inventing something gentler, perhaps `SUPERSEDE fff1122` (or `SUPPLANT fff1122`, or `REPLACE fff1122`)?  I'd vote for "supersede" which has more positive spin than "invalid".

**Comment by jirikuncar** [comment]
@dset0x @tiborsimko I would then suggest `* AMENDS fff1122`

**Comment by dset0x** [comment]
@tiborsimko @jirikuncar What about `REWORD` or `REWORDS`, which is git jargon?

**Comment by tiborsimko** [comment]
@dset0x WRT `REWORDS`, we sometimes don't want to only reword a message, but change the meaning completely, because the feature might have been changed N times and even dropped before the release is made.  (See the [use case discussed above](https://github.com/inveniosoftware/invenio/issues/2856#issuecomment-77568892).)  In this case, we'd be not only "rewording" previous commits, but rather "amending" its features, as it were.

@jirikuncar WRT `AMENDS`, I like it better than `REWORDS`.  Though I'm not sure whether the git analogy plays in our favour here.  Technically, we are not "amending" last commit and its message, we are "superseding" what was done in perhaps N previous commits in the past; hence `SUPERSEDE` may be perhaps clearer.  Anyway `AMENDS` seems fine as fell.

**Comment by dset0x** [comment]
@tiborsimko Indeed, `REWORDS` carries the wrong meaning.

`SUPERSEDE` is more generic, and may imply that more liberal changes were made than `AMENDS`, which I suspect will often be the case.

**Comment by tiborsimko** [comment]
Invenio Developer Forum 2015-03-30: common agreement to go with AMENDS.
