### ISSUE TITLE
docker: prepare Dockerfile for 2.x branch

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#2858]
I tried to install invenio master from docker and there is a problem:
```bash
git clone https://github.com/inveniosoftware/invenio.git invenio2docker
cd invenio2docker
docker-compose up
```

And, the error:

```
Complete!
Loaded plugins: fastestmirror
Cleaning repos: base epel extras updates
Cleaning up Everything
Cleaning up list of fastest mirrors
 ---> b0bc273d953a
Removing intermediate container 0c0a8484f277
Step 2 : ADD requirements.txt /tmp/requirements.txt
 ---> 4f40edc1e5bc
Removing intermediate container 62d0f41a3ab1
Step 3 : ADD requirements-extras.txt /tmp/requirements-extras.txt
Service 'web' failed to build: requirements-extras.txt: no such file or directory
```

**Comment by jirikuncar** [comment]
@hachreak the `Dockerfile` needs to be completely rewritten for Invenio 2.x. I have started with very simplified version in my [docker](https://github.com/jirikuncar/invenio/tree/docker) branch (https://github.com/jirikuncar/invenio/commit/568ada845d20a9594713e34644e0ccc3ed4dae6f).

**Comment by tiborsimko** [comment]
In Invenio v2.0, the demo site was split into its own overlay, so I think most of Docker application building will be done in overlays.  (I had planned to set up an example for the demo site and the CERN Open Data, but I did not get to it yet.)  Inside Invenio itself, I think the Docker could be rather thin, basically just to install the software and run the tests...

**Comment by jirikuncar** [comment]
> basically just to install the software and run the tests...

I would say: basically just to install the software ~~and run the tests...~~

**Comment by tiborsimko** [comment]
> I would say: basically just to install the software 

(to be able to run the tests; we wouldn't run them in CMD)

**Comment by jirikuncar** [comment]
> to be able to run the tests

:+1:

**Comment by jirikuncar** [comment]
- [ ] add new configuration `INVENIO_ALLOWED_ENVS` with list of allowed os environment variables to ease creation of `docker-compose.yml`

**Example**
```console
export SQLALCHEMY_URI = mysql://invenio:invenio@mysql/invenio
export REDIS_HOST = redis
INVENIO_ALLOWED_ENVS=SQLALCHEMY_URI,REDIS_HOST inveniomanage runserver -h 0.0.0.0 -p 8080
```

--
cc @lnielsen @tiborsimko @kaplun @egabancho

**Comment by hachreak** [comment]
Ok, I'm working on new dockerization: https://github.com/hachreak/invenio/tree/fix_docker

**Comment by tiborsimko** [comment]
> INVENIO_ALLOWED_ENVS=SQLALCHEMY_URI,REDIS_HOST

Is this needed? The Invenio app uses many more environment variables, such as `GD_ACCESS_TOKEN` in `googledrivefs.py`, or just take `HOME` and `TZ` and `PAGER` ones...

**Comment by jirikuncar** [comment]
> Is this needed?

Yes, as discussed with @lnielsen IRL. 

Summary: this variable creates list of keys that can be replaced in `app.config` and hence can have impact on application itself.

Following environment variables have limited impact and its usage should be anyway deprecated/removed.

> `GD_ACCESS_TOKEN` in `googledrivefs.py`

It's there because we were trying to get integrated to `pyfilesystem` but normally it should be always supplied with user access token.

**Comment by tiborsimko** [comment]
> Summary: this variable creates list of keys that can be replaced in app.config and hence can have impact on application itself.

Then maybe a better name is needed.  If you do `git grep os.environ`, there are quite a few more environment variables that also have impact on an Invenio application. Was the idea to list them all and protect their usage everywhere in the code base, if they are not allowed via this new variable?  (That's bigger than just "prepare Dockerfile"...)

**Comment by jirikuncar** [comment]
`os.environ` is fine as long as its value doesn't modify `app.config` (see 85a03a441ebe205eaf1085a98df514728ac96603).

**Comment by jirikuncar** [comment]
`os.environ` is fine as long as its value doesn't modify `app.config` (see 85a03a441ebe205eaf1085a98df514728ac96603).

**Comment by tiborsimko** [comment]
What about `INVENIO_APP_CONFIG_ENVS`?  Reads simply as "Invenio app config environments", which seems to denote well the meaning.

(`INVENIO_ALLOWED_ENVS` reads as "Invenio allowed environments", which seems too much, as if Invenio wouldn't allow any other envs anywhere else in the codebase...)
