### ISSUE TITLE
User Test: different author search results for lj dixon

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#286]
Originally on 2010-09-15

Comment from Lance Dixon tests last week: 

"find a l.j. dixon"   does not  find the correct results in inspirebeta (off by several).   In Joe's tislnx1 (running 131, 188, etc) it finds 1 extra compared to SPIRES (actually it finds the same number, but SPIRES has one extra, a recent paper).  We have not identified the one extra paper yet, and understood the difference.  Two actions here:  Confirm that 131 corrects the main error, then fix the remaining one paper (if it is in error)

**Comment by jalavik** [comment]
Moved to the appropriate INSPIRE channels.
