### ISSUE TITLE
accounts: password hashing

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2874]
# Problem

Invenio password hashing is based on MySQL's AES encryption of the email address using the password as secret key.

This means e.g. that if the email address of a user is changed their password is invalidated.

# Proposal

* Explicitly store password salt instead of relying on email address.

* Support multiple hashing algorithms concurrently. 

* Support automatic deprecation and migration of hashes when user signs in.

* Support for overlay specific algorithms for password hashing.

* Deprecate Invenio's hashing algorithm in favour of SHA512.

* Implementation wise this will add two columns to ``user`` table: ``password_salt`` and ``password_scheme``. Additionally password hashing will rely on passlib library for all the low-level machinery.

# Implementation

See PR #2873

**Comment by lnielsen** [comment]
cc @jmartinm @jalavik @kaplun @ludmilamarian @egabancho @tiborsimko @jirikuncar

**Comment by kaplun** [comment]
I like the proposed implementation. I guess this superseeds #1529

**Comment by lnielsen** [comment]
I'll consider this RFC as accepted, since nobody complained so far and IRL discussions have agreed to it. I'll close it via commit message from PR #2873

**Comment by PXke** [comment]
Sad, I just saw it but why SHA-2 ? I know that SHA-3 is young but SHA-1 has been compromised, SHA-2 is basically based on the same principle as SHA-1. 

http://competitions.cr.yp.to/sha3.html

Password hashing : 
https://password-hashing.net/timeline.html

It could be cool to always be on top of the art in terms of security solution.

**Comment by lnielsen** [comment]
> Sad, I just saw it but why SHA-2 ? I know that SHA-3 is young but SHA-1 has been compromised, SHA-2 is basically based on the same principle as SHA-1.

Firstly, the RFC makes sure that we can use any hashing algorithm in the future and automatically migrate existing hashes. Hence, you just need implement your SHA3 hasher , and then we can support SHA3.

I.e. we'll always be on top of the latest hashing solution :-)

> Why not SHA3

Simply because passlib does not support it. See https://code.google.com/p/passlib/issues/detail?id=42
Argument is that it's easier to make brute force attacks.

**Comment by PXke** [comment]
Okay, it makes sense. Thanks for the answer.

**Comment by tiborsimko** [comment]
> I'll consider this RFC as accepted, since nobody complained so far and IRL discussions have agreed to it. I'll close it via commit message from PR #2873

Yes.  We should probably remove the RFC label in cases like this, when the matter was agreed upon but takes some time to implement, so that the issue would be better label-separated from the other outstanding RFCs.

**Comment by PXke** [comment]
@tiborsimko @jirikuncar  :+1:
