### ISSUE TITLE
RFC deprecation policy and utils

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2875]
# Problem

Currently we are using ``PendingDeprecationWarning`` and ``DeprecationWarning`` to deprecate features in Invenio. E.g.:

```
warnings.warn("Feature X is deprecated. Please use Y instead.", PendingDeprecationWarning)
warnings.warn("Feature X is deprecated. Please use Y instead.", DeprecationWarning)
```

The problem is we do not know easily when we should upgrade from ``PendingDeprecationWarning`` to ``DeprecationWarning`` and when to completely remove the deprecated code.

# Proposal

1. Adopt a deprecation policy. See below.

2. Adopt [utilities similar to Django](https://github.com/django/django/blob/master/django/utils/deprecation.py) for managing deprecations. I.e. add

```
# Current version +0.2
class RemovedInInvenio22Warning(PendingDeprecationWarning):
    pass

# Current version +0.1
class RemovedInInvenio21Warning(DeprecationWarning):
    pass
```

after each release we rename the warnings. This way we get a syntax error for code that has to be removed, and we can easily see when a feature can be removed when.

Suggestion for deprecation policy (which ties into Invenio release process):

A minor release version (A.B) may deprecate certain features from previous releases. If a feature is deprecated in version A.B it will continue to work in version A.B and A.B+1 but raise warnings. It will be completely removed in version A.B+2. Example:

* Invenio 2.0 marks feature X as deprecated. The feature will still work, but it will issue the silent warning ``RemovedInInvenio22Warning``  (PendingDeprecationWarning).
* Invenio 2.1 still contains the feature, but the warning ``RemovedInInvenio22Warning`` is now loud by default (DeprecationWarning).
* Invenio 2.2 will completely remove the feature.

(based on https://docs.djangoproject.com/en/1.7/internals/release-process/#internal-release-deprecation-policy)

**Comment by tiborsimko** [comment]
:+1:

**Comment by kaplun** [comment]
I just read this only now! Any way :+1:
