### ISSUE TITLE
inveniomanage: no option for updating config variables

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/invenio#2881]
There should be a way of updating config options through Inveniomanage, either by extending `inveniomanage config set CFG_OPTION value` or implementing `inveniomanage config update CFG_OPTION value`

**Comment by jirikuncar** [comment]
Updating of a file is bit tricky. If you find a nice solution please submit a PR.

**Comment by blixhavn** [comment]
Could you elaborate on how it's tricky? Are there any problems with doing it manually?

**Comment by kaplun** [comment]
I guess the problem stems from the fact that invenio.cfg is infact a Python file, and therefore open to writing all sorts of Python there.

But we could stick to a convention of adding a comment:
```python
# Created by inveniomanage, please do not edit directly
```

And then for editing it: one could import it, amend the `globals()` and then recreated a corresponding python file by carefully using `repr()`.

**Comment by jirikuncar** [comment]
You can have a look here https://github.com/inveniosoftware/invenio/blob/master/invenio/base/scripts/config.py#L131-L159.

**Comment by kaplun** [comment]
I don't understand. What's that code? Is update already there?

**Comment by tiborsimko** [comment]
> I don't understand. What's that code? Is update already there?
 
There's a rudiment for interactive "update" facility, but not `inveniomanage config update CFG_OPTION value` that would be indeed nice to have, but that requires more work...

**Comment by jirikuncar** [comment]
We recommend using text editor and version control system for editing configuration in Invenio 3.
