### ISSUE TITLE
RFC Invenio Matcher (legacy BibMatch)

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#2886]
BibMatch is a highly customizable Invenio legacy module that allows to check if a given record already exists in the system. This is of paramount importance in the context of a.g. a service such as INSPIRE where documents are aggregated from different sources and one desire to minimize the human effort in spotting record duplicates.

The implementation in Invenio legacy was mainly evolved as a set of calls to the native Invenio search engine, working around performance limitations, and completely bound to MARC.

If Invenio goes full steam for elasticsearch, bibmatch could in principle be simply reimplemented from scratch by having a thin layer that loads from a registry a set of queries expressed using elasticsearch dsl language: https://github.com/elastic/elasticsearch-dsl-py.

Elasticsearch natively support fuzzy searching, thus allowing to find most similar record.

Such module should at least offer a simple API that, given an incoming Invenio record, and a piece of configuration, should be able to answer with a weighted list of records in the system, *matching* the given record, i.e. answering the question whether there are records which are actually the same as the provided one (within the provided configuration).

Such configuration could vary a lot on a case by case, would depend on the particular instance of Invenio and on the particular document types. E.g. (article, preprint, proceeding, conference contribution, book, miscellaneous, note).

cc: @jalavik

**Comment by lnielsen** [comment]
+1 The more we can rely on existing tools that we don't have to maintain the better.

Btw, deduplication in OpenAIRE https://blogs.openaire.eu/?p=116

**Comment by kaplun** [comment]
> Btw, deduplication in OpenAIRE https://blogs.openaire.eu/?p=116

It's interesting to observe that in the case of OpenAIRE, they try to find *all* duplicates across the whole repository in a given time. Invenio has always privileged incremental algorithms and I believe for finding duplicates we can continue with this philosophy: upon new record ingestion (or modification), the change is checked against the whole database.

**Comment by jalavik** [comment]
+1 for simplicity and leveraging existing tools.

We would need to check if this will indeed solve the required use cases of fuzzy search and other special cases.

There was some substantial WIP done to port bibmatch to matcher module already, albeit following the existing schema (still native calls, not adapted to jsonalchemy). Possibly it can be merged if in good state (on me to do it) as an intermediary. Or, we simply abandon it and start from scratch with elasticsearch as proposed here.

**Comment by PXke** [comment]
Do you plan to create a  layer of abstraction in case someone would like to do something not fully dependant on elasticsearch function ?

I mean perhaps elasticsearch support fuzzy search, but perhaps some other way could be implemented.

**Comment by kaplun** [comment]
I am not sure about this...  In the end it becomes so thin... BibMatch could become a simple

```python
def matcher(record):
    """
    return list of tuples (record-id, confidence-level)
    """
```

one simple function call that behind calls in several pluggable ways elastic search. Indeed nothing prevents the plugins to call something different than elasticsearch...

**Comment by PXke** [comment]
Okay!

Could we before anything is implemented, do a recapitulation of :
What we want in I/O, what are the wished performances, options that the matcher should have, and use-cases in 2.0 ? 

Thanks in advance.

**Comment by ksachs** [comment]
Could we collect a few points from catalogers (=humans) what works best for matching? I.e what is a fuzzy titel or author search?

**Comment by tiborsimko** [comment]
> Could we before anything is implemented, do a recapitulation [...]
> Could we collect a few points from catalogers [...]

:+1:  If the module is being "restarted" for Invenio 2, then it would a good idea to enrich this RFC with the list of various use cases we plan to cover.  (Some from Invenio 1 will still be there, some may be perhaps dropped now, some will be new...)  Currently, the RFC seems to underline "technical aspects", while we may perhaps want to take some time out and rethink its use cases, as the general title "BibMatch in Invenio 2" would seem to imply?

**Comment by kaplun** [comment]
Note: http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html

**Comment by kaplun** [comment]
The module now exists under https://github.com/inspirehep/invenio-matcher, so I guess we can close this RFC and add use cases there.
