### ISSUE TITLE
multimedia: remove module specific cache

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#2887]
The multimedia module does not makes use of ``invenio.ext.cache`` but instead uses it's own implementation:

https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/multimedia/api.py#L590

@drjova Will you have time to fix it?

**Comment by lnielsen** [comment]
Seems to only be a few calls that must be changed in ``restful.py``

**Comment by drjova** [comment]
@lnielsen yes, please assign me. Actually we should completely remove it and use the Flask-IIIF extension.

**Comment by lnielsen** [comment]
Great. Thanks a lot.

I think we can remove it without requiring deprecation since it's been in ``PACKAGES_EXCLUDE``. 

/cc @jirikuncar

**Comment by jirikuncar** [comment]
> since it's been in `PACKAGES_EXCLUDE`.

Please just keep `invenio/modules/multimedia/__init__.py` with active deprecation message.

**Comment by drjova** [comment]
:+1:

**Comment by drjova** [comment]
WIP #2924

**Comment by drjova** [comment]
I think we could close this issue

cc @jirikuncar, @lnielsen
