### ISSUE TITLE
RFC BibClassify in Invenio 2

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#2888]
`BibClassify` is an Invenio legacy module that given some publication metadata (e.g. title and abstract) or directly a PDF, tries to extract the keywords of the document (matching a given static taxonomy). The current implementation is purely statistical. The keywords are typically used, e.g. in the context of INSPIRE, to aid catalogers understanding core documents from non core one.

Today, we have the chance to reimplement this module in terms of machine learning.

@glouppe

**Comment by lnielsen** [comment]
Just my five cents:

I'm thinking there ought to be existing tools out there which we can used nowadays, and thus this module can be simplified to only dealing with the interface between Invenio and those tools?

Also, I see this module could be useful many different places in Invenio. E.g. in deposit it could be used to extract metadata. 

Other properties besides keywords that could be very interesting to extract (just as use cases for the module):
- Language
- Copyright 
- License
- Metadata (title, authors, ...)
- Grants
- Subject

Also, the ML tools can be both local/remote. E.g. OpenAIRE has a service to extract grant information from text.

**Comment by glouppe** [comment]
I agree that we should use/improve/contribute to existing machine learning libraries instead of writing our own.  

That being said, it would be worth defining the scope of "bibclassify". From a machine learning point of view, extracting representative keywords is a quite different task from parsing metadata (== docextract?), which is itself quite different from guessing the subject of paper given metadata. 

In any case, all are nice machine learning problems that I would be glad to tackle, depending on our list of priorities.

**Comment by kaplun** [comment]
> From a machine learning point of view, extracting representative keywords is a quite different task from parsing metadata (== docextract?), 

Sure. bibclassify is not about metadata extraction, but possibly about using available metadata (such as title and abstract which are very verbose) to be used instead of the PDF source.

**Comment by PXke** [comment]
Yeah I agree we should focus on bibclassify main task of extracting keywords.  Perhaps a RFC for an extractor could be good !

The main problem with the current bibclassify is that it needs a thesaurus. The main consequence is the complexity of getting it working on general purpose repository or with a repository hosting documents in different languages. 

It would then be cool if the new bibclassify could work in a way where it could "learn" to recognize keywords. Ideally in a multilingual environment. 

If bibclassify could have like a global view of a repository it would be a big plus. For example if I have two universities in medical area,  it would be efficient to determine most used keywords to try to define their main field of competencies. 

It would be awesome !

**Comment by tiborsimko** [comment]
> The main problem with the current bibclassify is that it needs a thesaurus. 

Perhaps we could support a simple "controlled vocabulary", but in practice I think this would probably quickly lead to working with full-scale ontologies.  Soon after starting with a controlled vocabulary, people would probabyl ask "How do I define a synonym for my controlled vocabulary term?" or "How do I defined an alternative term for this expression?".  Perhaps we could just facilitate initial ontology building, e.g. offer populating it from the list of frequent keywords that papers already have.  Just an example.

> If bibclassify could have like a global view of a repository it would be a big plus. For example if I have two universities in medical area, it would be efficient to determine most used keywords to try to define their main field of competencies.

Considering that the system contains papers published by the researchers of these two universities, and considering that each paper has a list of keywords, then asking for the field of competency of each university is just another "search summary page", like the author pages.  So the "global view of the repository" use case is just an extension of search, as it were, simply building upon the powers of BibClassify, that should properly populate the papers' keywords with proper terms in the first place.

**Comment by PXke** [comment]
>Perhaps we could support a simple "controlled vocabulary", but in practice I think this would probably quickly lead to working with full-scale ontologies. Soon after starting with a controlled vocabulary, people would probabyl ask "How do I define a synonym for my controlled vocabulary term?" or "How do I defined an alternative term for this expression?". Perhaps we could just facilitate initial ontology building, e.g. offer populating it from the list of frequent keywords that papers already have. Just an example.

It could be a solution, but I still imagine a perfect world were, the basic ontology could be generated automatically, and then involve people to complete or guide it, then let the code improve it continuously in a supervised learning fashion.

>Considering that the system contains papers published by the researchers of these two universities, and considering that each paper has a list of keywords, then asking for the field of competency of each university is just another "search summary page", like the author pages. So the "global view of the repository" use case is just an extension of search, as it were, simply building upon the powers of BibClassify, that should properly populate the papers' keywords with proper terms in the first place.

Perfect :+1:

**Comment by tiborsimko** [comment]
Superseded by Invenio 3.  https://github.com/inveniosoftware/invenio-classifier
