### ISSUE TITLE
User Test: Latex titles had some problems

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#289]
Originally on 2010-09-15

When we did user testing with Lance Dixon, some of the titles of some of his search results looked pretty bad.

Travis, you wrote:
> LaTeX translater seems not to work.   the images show up one line lower than they should   (I.E. running windows)

Can you find an example and then disown or reassign this ticket?

**Comment by jirikuncar** [comment]
There has been several updates to math rendering since last comment (e.g. c1e6cf4dd0085ded6a555c1907b388a2419e1910 98cb816b34c8f26add51ab7a75400db26eeb131a).
