### ISSUE TITLE
records: 500 error when record does not exist

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/invenio#2891]
When trying to access a rec_ID that does not exist, one should get a pretty 404 message instead of a 500 error. This is probably due to [`guess_primary_collection_of_a_record`](https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/records/views.py#L66) being called before checking whether the [`record_exists`](https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/records/views.py#L91).

**Comment by lnielsen** [comment]
FYI, see the PR I just reference. I think it will fix the problem.

**Comment by blixhavn** [comment]
See https://github.com/inveniosoftware/invenio/pull/2873/files#r26558445
