### ISSUE TITLE
Collection names with special characters may crash webcoll

### ISSUE THREAD

**Issue by gholman** [inveniosoftware/invenio#2902]
I have a collection name with a forward slash '/' as in "DOE/NSF Reviews"
When I run webcoll, webcoll will hang/timeout when attempting to cache this collection.

System details:
* Invenio version:  1.2.0
* Python version: 2.7.3 (default, Mar 13 2014, 11:03:55)  [GCC 4.7.2]
* Apache version: Apache/2.2.22 (Debian) [/usr/sbin/apache2]
* MySQLdb version: 1.2.5
* MySQL version: 5.5.41-0+wheezy1

Steps to reproduce:
-----------------
1. Collection name = "DOE/NSF Reviews"
2. Run 'sudo -u www-data /opt/invenio/bin/webcoll  -f -v9'
3. Run bibsched
4. Observe task.log entries stop at collection with special character and no task.err is created

Workaround:
-----------------
Rename collection name, e.g. "DOE-NSF Reviews"

**Comment by tiborsimko** [comment]
BTW, as discussed on the mailing list, this issue was observed during Invenio v1.1 to v1.2 upgrade.  We can write an upgrade recipe to catch this upfront.
