### ISSUE TITLE
RFC Nginx and others

### ISSUE THREAD

**Issue by lovasko** [inveniosoftware/invenio#2913]
The topic of replacing Apache with Nginx or other possible WSGI serving techniques came up during the talk "Apache configuration" delivered by @dset0x and me few Mondays ago. We have not advanced much in this regard and to do so, there are some questions to be asked:

1) Is there some current issue with Apache?
2) Is there some bonus feature we can gain by employing the Apache alternatives that we can not gain by tweaking Apache?

Thanks!

**Comment by jirikuncar** [comment]
> The topic of replacing Apache with Nginx

`s/replacing Apache with/supporting not only Apache but also/`

**Comment by lovasko** [comment]
@jirikuncar that is a valid remark, thanks :) but still, the questions asked are valid

**Comment by jirikuncar** [comment]
> 1) Is there some current issue with Apache?

It looks like there is since #2645 has been created.

**Comment by lovasko** [comment]
> It looks like there is since #2645 has been created.

The generator of the configuration was in a bad shape. That has been worked on and fixed. But the Apache technology itself has nothing to do with buggy Invenio code. So from the point of the #2645 issue there is nothing wrong with Apache.

**Comment by jirikuncar** [comment]
> Apache technology itself has nothing to do with buggy Invenio code.

Can you please mention reported issues? Thank you

**Comment by lovasko** [comment]
#2626 which will be fixed by #2645

**Comment by kaplun** [comment]
I guess in the short term we are all happy with simply keep on using Apache, since the computation is mainly in the Python part of Invenio. Support fo Ngnix is a nice to have functionality that is simply not urgent now. 

> buggy Invenio code.

I assume you meant *bugs into Invenio code* :wink: .

**Comment by lovasko** [comment]
>I assume you meant bugs into Invenio code

yes, thank you.

**Comment by audub** [comment]
Even though Nginx support is not urgent, I see a potential for running Invenio more efficiently. Nginx is known to consume far less resources than Apache. Which will reduce the cost of running invenio instances. So even though it is not urgent, I think it is a nice topic to focus on.

**Comment by lnielsen** [comment]
@lovasko Apache does the job, so being independent is not urgent. However as @jirikuncar mentions it's desirable to be independent of the frontend so that we are not bound to hard to any particular product.

**Comment by lovasko** [comment]
>desirable to be independent of the frontend so that we are not bound to hard to any particular product.

@lnielsen could you explain more about the front-end please?

**Comment by tiborsimko** [comment]
For CERN Open Data Portal we use Nginx in the front end caching layer.  It can replace Varnish with essentially the same performance and easier configuration language.    It also offers haproxy and Apache/mod_proxy_balancer facilities.  Offering an Nginx/Invenio configuration out of the box would be useful as it can potentially replace HAProxy/Varnish/Apache/Invenio stack.

P.S. As others mentioned, this is more a nice-to-have, not need-to-have-tomorrow feature.

**Comment by lnielsen** [comment]
@lovasko That Invenio is independent of Nginx, Apache, Lighthttpd, Gunicorn, uwsgi, …. etc

**Comment by jirikuncar** [comment]
Examples of nginx configuration:
- https://github.com/zenodo/zenodo/blob/master/docker/nginx/nginx.conf
- https://github.com/cernanalysispreservation/analysis-preservation.cern.ch/blob/master/docker/nginx/nginx.conf

**Comment by tiborsimko** [comment]
... and in Invenio itself: :)

-  https://github.com/inveniosoftware/invenio/tree/master/nginx
