### ISSUE TITLE
assets: error on bundle rebuild

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2921]
Unfortunately the following commit https://github.com/inveniosoftware/invenio/commit/d4464450e81a6192360fdc0d24bfcda3da7ce145 introduced  a fix, but also a problem.

While working with ``less`` in the last days, I saw that when a bundle needed to be rebuild (because of a file was updated) after a page refresh the following error was being thrown:

```python

File "/home/jmartinm/.virtualenvs/pu-inspire2/src/webassets/src/webassets/env.py", line 731, in __getitem__
key = key.lower()
AttributeError: 'tuple' object has no attribute 'lower'
```

And the problem appears here https://github.com/inveniosoftware/invenio/commit/d4464450e81a6192360fdc0d24bfcda3da7ce145#diff-dc717d85d0b109c334416b4b5a305f8cR138 as 

```python
ipdb> bundle.filters[0]._options
{'extra_args': (None, 'LESS_EXTRA_ARGS', None), 'line_numbers': (None, 'LESS_LINE_NUMBERS', None), 'less': ('binary', 'LESS_BIN', None), 'run_in_debug': (None, 'LESS_RUN_IN_DEBUG', None), 'paths': (None, 'LESS_PATHS', None)}
ipdb> bundle_copy.filters[0]._options
{'extra_args': (None, (None, 'LESS_EXTRA_ARGS', None), None), 'line_numbers': (None, (None, 'LESS_LINE_NUMBERS', None), None), 'paths': (None, (None, 'LESS_PATHS', None), None), 'run_in_debug': (None, (None, 'LESS_RUN_IN_DEBUG', None), None), 'less': (None, ('binary', 'LESS_BIN', None), None)}
```

The ``deepcopy`` alters the ``_options`` attribute that is later accessed and provokes an error.

I checked that reverting the commit makes this error go away.

**Comment by jirikuncar** [comment]
It works with `copy` instead of `deepcopy`. @jmartinm can you confirm?

**Comment by jmartinm** [comment]
I actually think we could simplify the code. Having ``less.js`` in the browser has no use as far I can see.

This is a simplified version that works for me:

https://github.com/jmartinm/invenio/commit/5b9ef704292eb47652b6cc264580b8109b64243c

With this, in development mode, if I change any ``less`` file affected by the bundle they get recompiled on  page refresh and my changes immediately visible. If no change is made then no recompilation happens.

If it is agreed, I can kill the LESS_RUN_IN_DEBUG code that does the in-the-browser compilation, it would simplify a bit the Invenio code.
