### ISSUE TITLE
search: SyntaxError with colon search

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2931]
The following search:

```
035__a:oai:arXiv.org:1503.06238
```

which is being used [here](https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/arxiv/__init__.py#L161) breaks the search engine:

https://gist.github.com/anonymous/cf4a997848a64c95ec2b

**Comment by jirikuncar** [comment]
@jmartinm the colon in search term value might be tricky. Have you tried `035__a:"oai:arXiv.org:1503.06238"` instead?

**Comment by kaplun** [comment]
IIRC, In Invenio legacy `foo:` is interpreted as a field if and only if a corresponding field is actually defined. Can't we as well build a whitelist of recognized field, and have the parser to check against it?

**Comment by jirikuncar** [comment]
@jmartinm @kaplun please re-open this issue on `invenio-query-parser` with correct test case. It's clearly a parsing problem.

**Comment by kaplun** [comment]
Superseeded by inveniosoftware/invenio-query-parser#16
