### ISSUE TITLE
OAIHarvest: stuck when trying to harvest

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio#2936]
For some estrange reason after deploying 3d60603e08d0a4e95e79d70d37bf9107531be30a on CDS, specially the modification done on `modules/oaiharvest/lib/oai_harvest_getter.py`, OAIHarvest gets stuck on `source arXiv is going to be updated`.

There is no error on the logs or any kind of output.

cc @aw-bib

**Comment by aw-bib** [comment]
There was an issue just discovered and fixed by @jalavik with some greedy/nongreedy regexp in removing namespaces in https://github.com/inveniosoftware/invenio/pull/3297 and https://github.com/inveniosoftware/invenio/pull/3298. Same for CDS?

**Comment by jalavik** [comment]
@egabancho Yeah, I believe this problem with resumptionToken is causing the stuck forever issue. I've seen on INSPIRE that #3298 fixes the problem.

**Comment by egabancho** [comment]
Great, I will test it asap and will let you know

**Comment by egabancho** [comment]
It works smoothly for us :+1:
