### ISSUE TITLE
submit: failing upgrade recipe 

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio#2954]
For those of us coming from an Invenio 1.2.x installation the `sbmCOLLECTION_sbmCOLLECTION` table doesn't have a primary key, which makes `submit_2015_03_03_fix_models.py` fail at 

```python
# drop primary keys
op.drop_constraint(None, 'sbmCOLLECTION_sbmCOLLECTION',
                               type_='primary')
```

```console
sqlalchemy.exc.OperationalError: (OperationalError) (1091, "Can't DROP 'PRIMARY'; check that column/key exists") 'ALTER TABLE `sbmCOLLECTION_sbmCOLLECTION` DROP PRIMARY KEY ' ()'
```

Just for completeness this the Invenio 1.2.x table:

```mysql
mysql> describe sbmCOLLECTION_sbmCOLLECTION;
+-----------------+---------+------+-----+---------+-------+
| Field           | Type    | Null | Key | Default | Extra |
+-----------------+---------+------+-----+---------+-------+
| id_father       | int(11) | NO   |     | 0       |       |
| id_son          | int(11) | NO   |     | 0       |       |
| catalogue_order | int(11) | NO   |     | 0       |       |
+-----------------+---------+------+-----+---------+-------+
3 rows in set (0.00 sec)

mysql> show create table sbmCOLLECTION_sbmCOLLECTION \G
*************************** 1. row ***************************
       Table: sbmCOLLECTION_sbmCOLLECTION
Create Table: CREATE TABLE `sbmCOLLECTION_sbmCOLLECTION` (
  `id_father` int(11) NOT NULL DEFAULT '0',
  `id_son` int(11) NOT NULL DEFAULT '0',
  `catalogue_order` int(11) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8
1 row in set (0.00 sec)
```

**Comment by jirikuncar** [comment]
@egabancho wow, no primary index in the table! That's bit unexpected. We should probably just check if there is something like `has_primary_key` in *SQLAlchemy(-Utils)* otherwise simple `try: ... except sqlalchemy.ext.OperationalError: ...` should do the job.

**Comment by jirikuncar** [comment]
Moving milestone to `2.1` as it was introduced in 10210558be791cd21eadf23bbb7341daf070b33f (cc @hachreak).

**Comment by hachreak** [comment]
SQLAlchemy-Utils have a function `has_unique_index()`.

> A column has a unique index **if it has a single column primary key index** or it has a single column UniqueConstraint.

Maybe we can use it to check if exists before try to remove it.
Something like:
```
if has_unique_index(X):
  drop_key(X)
```

@jirikuncar I'll create a PR for master?

**Comment by jirikuncar** [comment]
@hachreak yes please
