### ISSUE TITLE
RFC WebComment in Invenio 2

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio#2957]
WebComment is the legacy commenting engine which allow users to add comments to records in the form of a discussion.

The current main features are:
* Replay to comment
* WYSIWYG/Markdown editor
* Filtering by text
* Filtering by file and version association
* Attach files to comments
* Associate comments to record files and versions
* Subscription to a comment
* Soft commenting deadline
* Custom extra headline for comments
* Collaps expand comments (persistent per user)
* Report abuse (+ admin tools)

It would be nice if the new implementation is more flexible allowing comments to be connected to a document (or anything) directly. 

One possible solution would be to build an extension that uses any of the existing commenting engines like [isso](https://github.com/posativ/isso/)(written in python) or [Disqus](https://disqus.com).

But I think we should also allow custom implementations as some of the functionalities we are using right now are quite hard to find.

cc @kasioumis

**Comment by kaplun** [comment]
:+1: for outsourcing commenting to an external framework, such as the proposed Isso. Comments are not the core business of Invenio and we are going therefore to be better served by some third-party modern framework.

I have given a brief look at Isso and indeed looks promising. We should evaluate pros and cons though. Disqus is :-1: (unless someone wants to really integrate it in is own overlay) because it's not a framework/tool but an external service.

**Comment by tiborsimko** [comment]
> Disqus

For sites hosting confidential material, it may not be possible to use cloud-based solutions.

> Isso

This would be more interesting possibility.  Have you done extensive feature comparison?  Also, what about per-page, per-equation, etc annotations?  We may want to tackle the future of these two facilities together.

**Comment by kaplun** [comment]
Isso seems currently pretty basic. Doesn't seem to support authentication. On the other hand allows to attach commenting everywhere (identifying the anchors with a URI). Then one can programmatically query it to discover new comments in case of indexing.

However the fact that has no integrated authentication seems a very weak point.

**Comment by egabancho** [comment]
> Have you done extensive feature comparison?

We, @kasioumis and I, did a quick comparison an we found a few weaknesses on Isso.

As @kaplun pointed out the user authentication is the most visible one.

We also think storing CDS comments on SQLittle is not the best solution, they claim that comments are not big data and they put this example:

> For example, 209 threads and 778 comments in total only need 620K (kilobyte) memory. Excellent use case for SQLite.

In a normal week we usually get around 500 comments on CDS.

**Comment by switowski** [comment]
> Subscription to a comment

We actually have a user asking for that ([RQF0475329](https://cern.service-now.com/nav_to.do?uri=u_request_fulfillment.do?sys_id=b5bce2644c8dc640c71326a7289711a2%26sysparm_view=tabs_new)) and it makes sense to have two levels of subscription:
* Subscribe to the whole discussion
* Subscribe to a single comment (should we subscribe users to their own comments by default ?)

**Comment by egabancho** [comment]
Moved to https://github.com/inveniosoftware/invenio-comments/issues/13
