### ISSUE TITLE
config: Wrong default OAI Repository metadata formats

### ISSUE THREAD

**Issue by jgarcial** [inveniosoftware/invenio#2962]
I think the default config ```CFG_OAI_METADATA_FORMATS``` in ```invenio/base/config.py```

```
CFG_OAI_METADATA_FORMATS = {
    'oai_dc': ('XOAIMARC', 'http://www.openarchives.org/OAI/1.1/dc.xsd',
                           'http://purl.org/dc/elements/1.1/'),
    'marcxml': ('XOAIDC',
                'http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd',
                'http://www.loc.gov/MARC21/slim'),
}
```

Aren't the keys of the dictionary wrong?

**Comment by kaplun** [comment]
Hi @jgarcial, Is there a recommended standard/convention for these names? If I check the OAI-PMH standard I can only find in the examples `oai_dc`, e.g. see:
http://www.openarchives.org/OAI/openarchivesprotocol.html#ListMetadataFormats

Additionally, the `oai_marc` mentioned in the example is different MARC serialization than our exposed `marcxml`: see http://www.openarchives.org/OAI/2.0/guidelines-oai_marc.htm

**Comment by jgarcial** [comment]
@kaplun It's simpler than that. The mapping is wrong.
```'oai_dc'  -> 'XOAIMARC'```
```'marcxml'-> 'XOAIDC'```

**Comment by kaplun** [comment]
:tada: ahah. I haven't noticed that. It's something introduced when porting the moduele to the new master, as the configuration is correct in legacy. 

Can you send a PR with the correction on top of maint-2.0?

Cheers!
     Sam
