### ISSUE TITLE
BibHarvest admin interface - incorrect message

### ISSUE THREAD

**Issue by ppiotr** [inveniosoftware/invenio#298]
Originally on 2010-09-23

When adding a new harvesting source, the source URL is first validated.
The user is given a possibility of continuing anyway in case, the URL can not be validated.

In such a case, the message informing about a correct validation is displayed. (and should not be !)

**Comment by kaplun** [comment]
This was actually fixed by @jalavik in f9271a01bb74bf578285b10edee2632ee0888f5f
