### ISSUE TITLE
BibClassify: performance issues and false results

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#2980]
We noticed that BibClassify often got "stuck", e.g. taking an unreasonable long time, on our labs instance. In addition some keywords extracted were plain wrong. Local testing did not reveal the same behavior. After some debugging it turned out that:

* `is_pdf()` check do not correctly work with PDFs having colons in the filename when extracting the fulltext - causing bad data to be passed onwards and cause wrong results and the performance issues.
* After extracting the text from a PDF references are removed, but it is not always working well. E.g. removes the entire fulltext if first page has a table of contents mentioning *References*.

A PR is incoming that addresses these issues by using refextract api that already does this job of getting the fulltext from PDF better and initial testing shows that things are working well.

**Comment by jirikuncar** [comment]
> A PR is incoming that addresses these issues by using refextract api ...

@jalavik any progress or PR? Shall we move it for 2.1.1?

**Comment by jalavik** [comment]
@jirikuncar Actually this issue was fixed via https://github.com/inveniosoftware/invenio/commit/181fb0230bdd0433006434e7a4c5ad70501e7d46 and https://github.com/inveniosoftware/invenio/commit/4b56c071c54a0e1f1a86dca49fe455207d4148c7
