### ISSUE TITLE
RFC communities: externalise module

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#3008]
## Problem 

Communities is a module so far only in use on Zenodo, and thus not really a core Invenio module. As discussed recently off list, having many modules inside Invenio makes maintainability much harder.

## Proposal

Remove communities module from Invenio and make it into a separate package in @inveniosoftware. The module will not be integrated back into Zenodo, so it's still useable by others if wanted.

**Comment by lnielsen** [comment]
cc @bouzlibop

**Comment by jirikuncar** [comment]
Shall we start in new repo: `inveniosoftware/invenio-communities` or `inveniosoftware/invenio-communities-module`?

**Comment by jalavik** [comment]
Regarding the naming, I'd suggest keeping only `inveniosoftware/invenio-communities` as the `module` part should be superfluous.

**Comment by lnielsen** [comment]
Yes, let's follow the pattern: ``invenio-<module name>`` for externalised modules, so +1 for ``invenio-communities``. I'll create the repo once the RFC is accepted.

**Comment by jirikuncar** [comment]
Let's go for https://github.com/inveniosoftware/invenio-communities then.
