### ISSUE TITLE
User-selectable preferred output formats

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#301]
Originally on 2010-09-28

Cf. [[#93691](https://inspirert.cern.ch/Ticket/Display.html?id=93691|rt)].

It would be nice if users could select their preferred output formats and be shown only those options in the display.  So instead of the result list looking like:
```
    - References | BibTeX | LaTeX(US) | LaTeX(EU) | EndNote 
```
they might see (because of the preference they've put into a cookie, or on their user profile page):
```
    - References | LaTeX(US) | EndNote 
```

**Comment by jirikuncar** [comment]
Overlays can customize the templates showing these output formats to fit their users.
