### ISSUE TITLE
jasmine: cli and travis integration

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#3014]
Problem Jasime tests are not executed as part of CI cycle, and thus can be broken at any time. Also, it should be easier for developers to execute the Jasmine tests in multiple browsers using something like Karma.

Task forked from #2221
Related to #1769

**Comment by tiborsimko** [comment]
Superseded by Invenio 3.  Example: https://github.com/inveniosoftware/invenio-accounts/blob/master/.travis.yml
