### ISSUE TITLE
RFC exclude legacy code from kwalitee checks

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3022]
### Problem:
everytime you create a PR that involve some file from legacy code you receive a lot of warnings that we normally ignore because is legacy code.

### Proposal: 
We can use my [PR#65](https://github.com/inveniosoftware/kwalitee/pull/65) to automatically exclude legacy code.

### How:
1. accept my PR#65
2. Introduce in .kwalitee.yml this:
```yaml
excludes:
- (.)+/legacy/(.)+
```

Any comments/ideas?

**Comment by lnielsen** [comment]
+1 for fixing the problem, i.e. that kwalitee warns about errors which is ignored during integration. Ideally  kwalitee should be like Travis - if there's a green light, it won't be integrated.
