### ISSUE TITLE
collections: portalbox text overflow

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3023]
Hi guys,
I installed the demo site and in home page, in right bar, the text doesn't respect the width of the box.
This css seems to fix the issue:

```css
.panel-body {
word-wrap: break-word;
}
```

### Before

![9b1a811a-336d-11e4-9917-44ecf13984fc](https://cloud.githubusercontent.com/assets/377047/7176247/ed5825f8-e41c-11e4-8685-3c93a6ebaa4d.jpg)

### After

![8ca52072-336d-11e4-9b53-f77d1ba56135](https://cloud.githubusercontent.com/assets/377047/7176257/ffd7c846-e41c-11e4-8cc5-7d4be6fbf44a.jpg)

From: https://github.com/inveniosoftware/invenio-demosite/issues/38

**Comment by jacquerie** [comment]
+1, tested working and browser support seems to be there: http://caniuse.com/#feat=wordwrap

**Comment by lnielsen** [comment]
Can you make a PR?
