### ISSUE TITLE
Multi-record editor: Apply only to specific instances does not work

### ISSUE THREAD

**Issue by audub** [inveniosoftware/invenio#3031]
The feature to add a subfield only to specific instances seems broken. If you do a query like this: 

![unnamed-2](https://cloud.githubusercontent.com/assets/2854307/7199571/28215248-e4f6-11e4-86a8-bb453965c1b9.gif)

The result is an empty subfield:

![unnamed-3](https://cloud.githubusercontent.com/assets/2854307/7199584/37d1f436-e4f6-11e4-9f74-6bed5165630e.gif)

As a workaround we can query for: AMPARO AND 987__a:"Teaching materials, manuals"

**Comment by tiborsimko** [comment]
@audub Which Invenio version is this for?  Do you want to add subfield $a when $a is already present with some given value?  This would lead to a multiple subfields in the same field... Didn't you rather want to act on "other subfield", which is how the multi-record editor UI usually presents this feature?
