### ISSUE TITLE
scripts: manager database dump not implemented

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/invenio#3042]
https://github.com/inveniosoftware/invenio/blob/master/invenio/base/scripts/database.py#L220

This function should at least contain a FIXME, or cast a not_yet_implemented exception.

**Comment by jirikuncar** [comment]
### Proposal

Investigate usage of an existing tool e.g. https://github.com/cuducos/alchemydumps.

**Comment by tiborsimko** [comment]
Superseded by Invenio 3.
