### ISSUE TITLE
collections: record restricted after insert

### ISSUE THREAD

**Issue by giannistsan** [inveniosoftware/invenio#3051]
How to reproduce
=============

1. Insert new record with `bibupload -i`
2. Run `bibindex -u admin`
3. At that moment the new record is correctly indexed in the `collections` index

```python
In [1]: from invenio.modules.search.searchext.engines.native import \
   ...:                 search_unit_in_idxphrases

In [3]: 358 in search_unit_in_idxphrases("HEP", 'collection', 'e')
Out[3]: True
```

But the record is still **restricted**.

Running

```bash
$ redis-cli flushdb
```

does not fix it.

Only restarting the dev server makes the record visible.

**Comment by jirikuncar** [comment]
### Proposal

Fix following data cachers to take into account last update of collection index:
- [ ] https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/collections/cache.py#L46
- [ ] https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/collections/cache.py#L85

and clear following memoized function:
- [ ] https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/collections/cache.py#L154
- [ ] https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/collections/cache.py#L167
