### ISSUE TITLE
inveniogc: convert all sql left joins to intbitset operations

### ISSUE THREAD

**Issue by fjorba** [inveniosoftware/invenio#3054]
After fixing some extremely slow sql queries (#428, thanks, @kaplun) , and backporting this inveniogc to my systems (trivially), inveniogc still hangs my test server. I had to kill it after 36 hours of burning disk and CPU.  After digging the system with mytop, it is evident that left join kills MySQL very badly, and inveniogc cannot complete. Please convert all them to intbitset operations.

The consequences are important; database tables keep growing and occupy a lot (a lot!) of disk space, like 3.1 GB only for keeping (obsolete) session information.

**Comment by kaplun** [comment]
Do you have this patch in your installation?

Commit 7fc855b312bfd1c5df6d5a5972ddf01e010da63c
Author: Tibor Simko <tibor.simko@cern.ch>
Date:   Wed Jul 4 14:48:56 2012 +0200

    installation: new index on session.session_expiry
    
    * Adds index on session.session_expiry.  Helps in speeding up
      the garbage collection process based on session expiry times.

**Comment by fjorba** [comment]
It seems so:
```
 $ echo 'show create table session;' | dbexec | sed 's/\\n/\n/g'
 Table   Create Table
 session CREATE TABLE `session` (
  `session_key` varchar(32) NOT NULL DEFAULT '',
  `session_expiry` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `session_object` longblob,
  `uid` int(15) unsigned NOT NULL DEFAULT '0',
  UNIQUE KEY `session_key` (`session_key`),
  KEY `uid` (`uid`),
  KEY `session_expiry` (`session_expiry`)
 ) ENGINE=MyISAM DEFAULT CHARSET=utf8
```

It is in the same machine where I have run inveniogc.

**Comment by aw-bib** [comment]
Are there any news on this end? We just ran into it as well even though it just took longer for us to hit the wall. (Thought this was already fixed.)

**Comment by kaplun** [comment]
In Invenio-1.2.x, thanks to 06d7f5f0e61c7926503be462355f0995ea456441 the default storage engine for sessions becomes http://redis.io/, thus allowing for auto-expiration and no longer this sort of troubles. If you are still using Invenio-1.1.x you can try backporting the above patch...

**Comment by aw-bib** [comment]
For the time beeing I'll then have to try the backport. Thanks :)

**Comment by tiborsimko** [comment]
If you use native sessions, then you can clean them all fast at a quiet server time (say over the weekend) like this:

```
sudo apache2ctl stop
echo "TRUNCATE session" | /opt/invenio/bin/dbexec
sudo apache2ctl start
```

This will force logout upon everybody, hence the importance of doing it when the server is mostly idle.  The old sessions will be killed rapidly in this way and the rest of `inveniogc` should then proceed faster.

P.S. If you want to be more permissive and keep recent sessions, you could do something like `DELETE FROM session WHERE session_expiry < '2015-08-01 00:00:00'`.

**Comment by kaplun** [comment]
I think the query that is actually blocking the system is:
```python
result = run_sql("""SELECT u.id
    FROM user AS u LEFT JOIN session AS s
    ON u.id = s.uid
    WHERE s.uid IS NULL AND u.email = ''""")
    write_message(result, verbose=9)
```

Which indeed is a left join and might explain why it is so slow. BTW you might want to set:
```python
CFG_WEBSEARCH_PREV_NEXT_HIT_FOR_GUESTS = 0
CFG_WEBSESSION_DIFFERENTIATE_BETWEEN_GUESTS = 0
```

in your `invenio-local.conf` file. This should allow not allocating unnecessary session and guest users.

**Comment by tiborsimko** [comment]
And note that when the `session` table is empty, this query would be ultra fast...  so no blocker anymore.

**Comment by tiborsimko** [comment]
Closing this issue, as there are workarounds, as per the `legacy` code base freeze.
