### ISSUE TITLE
WebSearch: detailed record page tabs miss language parameter in CFG_SITE_LANG

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#308]
Originally on 2010-10-11

Tabs ("References", "Discussion", etc.) on detailed record pages miss on purpose the 'ln=XX' parameter when the page is viewed in language 'CFG_SITE_LANG' (for eg: http://invenio-demo.cern.ch/record/96?ln=en): the consequence is that the browser preferred language is used when clicking on these tabs even if the user has specifically chosen to view the detailed page in language 'CFG_SITE_LANG'.

'ln=XX' should now be added whatever the value of 'CFG_SITE_LANG' is (in search_engine.py).

**Comment by jirikuncar** [comment]
@egabancho @switowski is it still relevant to CDS?

**Comment by switowski** [comment]
@jirikuncar the problem still exists on CDS

**Comment by switowski** [comment]
I have create a Jira ticket for this issue: https://its.cern.ch/jira/browse/CDS-672

**Comment by tiborsimko** [comment]
> the problem still exists on CDS

... and on Invenio demo site v1.2.0 as well.  The language had been well added to most links, but it seems the tabs were missed.

**Comment by tiborsimko** [comment]
Closed by #3729.
