### ISSUE TITLE
documents: integration with Flask-IIIF

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#3080]
- [ ] extend Flask-IIIF to read bytestream
- [ ] legacy fallback for `recid:{recid}` and/or `recid:{recid}-{filename}` and/or `{document.uuid}`

--
cc @blixhavn @egabancho @drjova

**Comment by blixhavn** [comment]
Maybe we can get a 403 or something if the requested thumbnail is on a restricted document we don't have access to?
