### ISSUE TITLE
websubmit templates use direct "/submit", should use CFG_SITE_URL+/submit

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#309]
Originally by *man* on 2010-10-11

If someone wants to create a site where the site url is indirect, for instance "my.site.com/cds-invenio", websubmit templates will break the site because they use direct urls -> my.site.com/submit instead of my.site.com/cds-invenio/submit.

**Comment by egabancho** [comment]
This issue has been open since 2010 and nobody did anything to fix it or reported the same issue again
