### ISSUE TITLE
RFC bibXXX census

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3094]
Can we take a census of the status of all bibXXX commands? 
Can you help me to collect informations? :)

I'd like to have an overview of the current state (which one are currently used, which are deprecated, atc..).
Wen can use this issue to mark progress.

For now, I executed the command without check all cases and I initially collect this information about them:

- [ ] [N] bibauthorid `ImportError: No module named bibauthorid.scripts.bibauthorid`
- [ ] [N] bibcatalog `ImportError: No module named pluginutils`
- [ ] [N] bibcheck `ImportError: No module named config`
- [ ] [W] bibcircd
- [ ] [W] bibclassify
- [ ] [W] bibconvert
- [ ] [N] bibedit `ImportError: No module named scripts.bibedit`
- [ ] [W] bibencode
- [ ] [W] bibexport
- [ ] [W] bibindex
- [ ] [W] bibmatch
- [ ] [W] bibrank
- [ ] [W] bibrankgkb
- [ ] [N] bibreformat (bibsched say `CERROR`)
- [ ] [W] bibsched
- [ ] [W] bibsort
- [ ] [W] bibstat
- [ ] [W] bibtaskex
- [ ] [W] bibtaskex
- [ ] [W] bibtasklet
- [ ] [N] bibtex (bibsched say `CERROR`)
- [ ] [W] bibupload

Legend:
- U: still used
- D: deprecated
- W: working
- N: not working

cc @tiborsimko @lnielsen @kaplun @jalavik

**Comment by jirikuncar** [comment]
Invenio 3 is using only Elasticsearch indexes.
