### ISSUE TITLE
global: remove all run_sql from modules

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3098]
Actually we have this modules that contains one or more `run_sql` (and consequently raw sql queries).

- [ ] access
- [ ] bulletin
- [ ] comments
- [ ] formatter
- [ ] indexer
- [ ] messages
- [ ] records
- [ ] search
- [ ] sequencegenerator

One of the next goal should be convert them completely.

**Comment by jirikuncar** [comment]
Invenio 3 is using only SQLAlchemy models.
