### ISSUE TITLE
global: invenio.config deprecation

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3106]
@jirikuncar told me that it's there only for legacy code and should be deprecated.
But if you execute `git grep "invenio.config"`, you can see that also many "normal" modules use it.

Can we deprecate it and substitute all `invenio.config` with `invenio.base.config`?

**Comment by jirikuncar** [comment]
> Can we deprecate it and substitute all `invenio.config` with `invenio.base.config`?

We can deprecate it but we should not replace it with `invenio.base.config` but with `invenio.base.globals:cfg` or `current_app.config`. Please note that we should do it only in `invenio.modules` as `invenio.legacy` requires UTF-8 values.

**Comment by jirikuncar** [comment]
Invenio 3 modules are using standard Flask configuration (`current_app.config`). Additional configuration loading has been moved to Invenio-Config package.
