### ISSUE TITLE
WebAccess: minor ommission in a doc example (regarding groups and fireroles) may produce an exception

### ISSUE THREAD

**Issue by sbujam** [inveniosoftware/invenio#3107]
It seems that if one follows the example in the WebAccess docs, and tries to enter:
```deny group badguys```
in a firerole, an exception is thrown.

By reading the code, I found out that the solution is VERY simple: I just have to put single or double quotes in the groupname to make it work! So, 
```deny group 'badguys'```

is OK and produces no exceptions.

The requirement to have expressions included in quotes is very reasonable, so my proposal is to simply change the example(s) in the docs, according to this requirement.

**Comment by tiborsimko** [comment]
Thanks, merged as e7ba096.
