### ISSUE TITLE
RFC bibdocfile: removed in 2.3

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#3110]
### Proposal

As documents module is getting stable we propose to deprecate bibdocfile module and remove it in 2.3.

- [ ] fulltext extraction to special field in document
- [ ] add migration script (matching fields from bibdocfile to new document model)
- [ ] missing cli vs. admin interface

**Comment by lnielsen** [comment]
+1

**Comment by egabancho** [comment]
+1

**Comment by kaplun** [comment]
Newbie question: how restrictions are supported by the new document model? In particular in terms of streaming documents?

**Comment by lnielsen** [comment]
Restrictions works more or less like in bibdocfile. See 
- https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/access/jsonext/fields/acl_base.cfg 
- https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/records/views.py#L211
- https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/access/bases.py#L56

With respect to streaming I'm not sure though.

**Comment by tiborsimko** [comment]
Removed in Invenio 3.

**Comment by jirikuncar** [comment]
see Invenio-Files-RESR instead (https://github.com/inveniosoftware/invenio-files-rest)
