### ISSUE TITLE
RFC accounts: REST API for settings

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#3111]
After musings with @egabancho we propose following (REST) API for accessing user settings:

```
GET /api/account/<id or nickname>/settings?key=<key>
```

**Comment by egabancho** [comment]
cc @drjova

**Comment by lnielsen** [comment]
What is the use case for accessing the settings, and how can user edit the settings themselves?

And have you considered:
```
GET /api/account/<id or nickname>/settings/:key
```

**Comment by jirikuncar** [comment]
> `GET /api/account/<id or nickname>/settings/:key`

It was just a quick musing and it was the other option. I like it, hence :+1:

**Comment by egabancho** [comment]
> What is the use case for accessing the settings, and how can user edit the settings themselves?

The use case for CDS would be mainly to retrieve/update the home page boxes configuration.

**Comment by lnielsen** [comment]
I'm know I'm probably opening a can of worms here, but perhaps it's worthwhile taking the settings out of the ``user`` table and into a separate one?

**Comment by jirikuncar** [comment]
That would be nice start for new general "User Settings" service. Can we elaborate more on possible use-cases of `PUT`ting/`GET`ting data in safe way from JavaScript using (REST) API? (cc @egabancho)

**Comment by lnielsen** [comment]
The user settings I see only as a backend thing. I.e. no generic UI on the top since it won't be customisable enough (note, this doesn't prevent a module for adding a /views/settings.py that get/update values in the user settings backend - it's just that we shouldn't have a generic UI into it).

**Comment by egabancho** [comment]
Each module will provide its own API and storage for the settings (even if related with a user account)

**Comment by jirikuncar** [comment]
:+1:
