### ISSUE TITLE
knowledge: add filter for knowledge mappings

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3112]
A common use case when using knowledge bases is to focus on a given KB and add/remove/edit some entries.

At the moment, the Flask Admin interface looks like:

![screenshot 2015-05-08 11 23 33](https://cloud.githubusercontent.com/assets/580727/7533811/e981950e-f574-11e4-8e6d-d495a203a015.png)

Which makes it quite difficult to navigate a given KB.

Is it possible to add a filter under `Add Filter` on top so that all KBs appear and a user can focus on one of them? At the moment `Add Filter` is empty.

@hachreak

**Comment by jirikuncar** [comment]
@jmartinm (or @hachreak) can you move it to `invenio-knowledge` package?

**Comment by hachreak** [comment]
Hi @jmartinm,
I knew that Invenio had some imcompatibility with Flask Admin (e.g. see https://github.com/inveniosoftware/invenio/issues/2690 )
If you open "Knowledge Base" and "Knowledge Mapping" pages and click on "Add Filter", the browser give you some errors? Can you see any filter?

**Comment by jmartinm** [comment]
@hachreak this is what I see. There is no error in the console.

Clicking the filters does not do anything :(

![localhost 5000 admin kb 1](https://cloud.githubusercontent.com/assets/580727/7590166/4ffa7d32-f8c7-11e4-9449-3830c58c09ab.png)
![localhost 5000 admin kbrval 2](https://cloud.githubusercontent.com/assets/580727/7590170/51c8a260-f8c7-11e4-9816-82d51f5efe04.png)

**Comment by tiborsimko** [comment]
Superseded by Invenio 3.
