### ISSUE TITLE
RFC Dependency graph of Invenio modules

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3120]
Talking with @jirikuncar we thought that can help have a global vision of inter-dependencies of modules.
Especially now that We started to move out them.
So, I created [this script](https://github.com/hachreak/console-utils/blob/master/invenio-utils/invenio_internal_dependencies.sh) and I generated this .png image:

![dependencies](https://cloud.githubusercontent.com/assets/377047/7584485/36cb2d12-f89e-11e4-83da-9e662dd0f768.png)

**Comment by crepererum** [comment]
[line 80](https://github.com/hachreak/console-utils/blob/master/invenio-dependencies.sh#L80): `s|~/tmp/dependencies.dot|$TMPFILE|`

Why exactly do you ignore imports like `import invenio.modules.foo as bar`? You say that they're `external`, but I do not really understand what you mean by that.

**Comment by hachreak** [comment]
Thanks.. I forgot to replace the file name.. :)

For the question: normally if we need to import something we use `from something import something` and we leave `import something` only for external packages.
Try to look. You'll find that there are only few places that not use this rule (and probably legacy code).
But, yes, if you want be more general, you can add a new filter to look for that case.. :)

**Comment by crepererum** [comment]
Improved version that uses [snakefood](http://furius.ca/snakefood/) and edge deduplication:

https://gist.github.com/crepererum/a054355a7c49ebbba85d

![invenio-deps](https://cloud.githubusercontent.com/assets/1529400/7721890/c58399f2-fedb-11e4-8951-c272acd0b363.png)

**Comment by crepererum** [comment]
Removing transitive components using `tred` (part of graphviz):

![test2](https://cloud.githubusercontent.com/assets/1529400/7722270/f02383d6-fede-11e4-982a-d2f9108684f2.png)

This shows that we have a dependency cycle. We should think about how to remove this, because these kind of structure make upgrading and dependency management complicated. Furthermore it may be an indicator for the existence of a bad module design (which does not mean that it implies that the design is bad).

**Comment by hachreak** [comment]
:+1:

**Comment by kaplun** [comment]
What's the the arrow meaning: does "x -> y", means "x (indirectly) import y"?

**Comment by hachreak** [comment]
x require y to works

**Comment by crepererum** [comment]
For the full graph: `x -> y` <=> "`x` imports `y` in some way (e.g. `import y`, `from y import foo`, `import y as bar`, ...). Dynamic imports are ignored though.

For the reduced graph: `x -> y` => "`x` imports `y` in some way" (notice the implication instead of an equivalence).

In both graphs, non-python relations (templates, static files, whatever is written to the DB or the broker) are ignored.

**Comment by hachreak** [comment]
Dependency graph after modules externalization:

![deps](https://cloud.githubusercontent.com/assets/377047/9680375/bbb00fc2-52f6-11e5-89b4-9ea004cefc35.png)

Generated by [find_invenio_external_modules_deps.sh](https://github.com/hachreak/console-utils/blob/master/invenio-utils/find_invenio_external_modules_deps.sh)

**Comment by hachreak** [comment]
![dependencies](https://cloud.githubusercontent.com/assets/377047/9872650/0fd86782-5b9b-11e5-9ee9-90b5b624d331.png)

**Comment by hachreak** [comment]
the latest one:

![dependencies](https://cloud.githubusercontent.com/assets/377047/9877226/d4982c04-5bbb-11e5-857f-d14c53bba83c.png)

@SamiHiltunen

**Comment by hachreak** [comment]
Removing transitive components using `tred` (part of graphviz):

![deps_without_transitive](https://cloud.githubusercontent.com/assets/377047/9878847/0ee0d0ec-5bc5-11e5-84f5-d6aee080c5ae.png)

**Comment by hachreak** [comment]
without `invenio` (and removing transitive components):

![deps](https://cloud.githubusercontent.com/assets/377047/9879754/04d36cd2-5bc9-11e5-9a04-423e6194aae8.png)

**Comment by jirikuncar** [comment]
### Issues

- [ ] cycle collections - search - records
- [ ] cycle collections - search - knowledge

**Comment by hachreak** [comment]
Current module dependencies (from `requirements.py`)

![current_modules_deps](https://cloud.githubusercontent.com/assets/377047/10140327/392115f0-6607-11e5-836b-30ae012118fe.png)

**Comment by jirikuncar** [comment]
Separation of Invenio 3 packages has been finished.

--
Check `pipdeptree` or similar tools to visualize recent dependencies.
