### ISSUE TITLE
deposit: feedback on file upload validation errors

### ISSUE THREAD

**Issue by jgarcial** [inveniosoftware/invenio#3124]
When you click submit but the files uploaded don't pass the validation, you go back to the form page but you don't see the error warnings.
This is confusing for the users, because they don't know what is wrong. You need to click on 'Save' to see the warning messages.

**Comment by lnielsen** [comment]
If you have errors in the form, press save, then reload the browser, is the errors displayed then?

**Comment by jgarcial** [comment]
Yes, that works. But users won't expect this behavior.

**Comment by lnielsen** [comment]
> Yes, that works. But users won't expect this behavior.

Yes, I agree. Was just trying to figure out where the problem might be.

**Comment by lnielsen** [comment]
Superseded by Invenio-Deposit and Invenio-Files-REST
