### ISSUE TITLE
global: -f/--force option for inveniomanage config

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio#3134]
`inveniomanage config set/create ...` commands fail if the key already exists.

As we use these commands during installation it would be useful to have an option which prevents them from failing (print warning and return 0). We would then be able to differentiate real failures from repetitions of the same config key set/create.

My current use case is the B2SHARE installation script. I have to add some ugly code in order to be able to use the bash `set -e` command.

**Comment by jirikuncar** [comment]
@nharraud what about calling it `-f/--force` or `--yes-i-know`?

**Comment by nharraud** [comment]
@jirikuncar  good idea. More consistent with the rest.

**Comment by jirikuncar** [comment]
Config command has been removed in Invenio 3.
