### ISSUE TITLE
installation: failed to create database on OS X

### ISSUE THREAD

**Issue by jochenklein** [inveniosoftware/invenio#3146]
Following the [installation guide](https://github.com/inveniosoftware/invenio/blob/master/INSTALL.rst) to install Invenio on OS X, @nharraud and I got following error when creating the database `$ inveniomanage database create` on `master` branch:

```
Test connection...      [ERROR]

************************************************************************
** DATABASE CONNECTIVITY ERROR:                                       **
** (_mysql_exceptions.OperationalError) (1045, "Access denied for     **
** user 'master'@'localhost' (using password: YES)").                 **
**                                                                    **
** Perhaps you need to set up database and connection rights?If yes,  **
** then please execute:                                               **
** console> inveniomanage database init --yes-i-know                  **
** The values printed above were detected from your configuration. If **
** they are not right, then please edit your invenio-local.conf file  **
** and rerun 'inveniocfg --update-all' first.                         **
**                                                                    **
** If the problem is of different nature, then please inspect the     **
** above error message and fix the problem before continuing.         **
************************************************************************
```

We fixed that issue by editing the `invenio.cfg` file: `(invenio)$ vim var/invenio.base-instance/invenio.cfg`:
* replacing `master` with `root` in `CFG_DATABASE_USER = u'master'` and
* add `CFG_DATABASE_PASS = u''` (if you haven't set a root password)

**Comment by jalavik** [comment]
I had the same problem recently. I found a solution with the grants setup using `@'%'` instead of `@localhost`. So if you simply add another grant that use `@localhost` in place of `%`, it works.

**Comment by jalavik** [comment]
Added 2.1 milestone as it can be a potential problem for people when installing on OS X. We can try adding to the database init script an additional grant that uses `@localhost` in addition to `@'%`.

**Comment by tiborsimko** [comment]
@hachreak Can you please have a look?  "master" vs "root" sounds like a PostgreSQL vs MySQL thing...

**Comment by nharraud** [comment]
@tiborsimko The problem is not coming from the user name. As said by @jalavik, `'myuser'@'%'` does not include `'myuser'@'localhost'` on mysql. Thus we need to perform two grants.
https://www.stormconsultancy.co.uk/blog/development/bug-of-the-day/todays-gotcha-localhost-is-not-included-in-the-wildcard-when-granting-mysql-permissions/

**Comment by tiborsimko** [comment]
@nharraud Yes, and I also pointed out that "master" should not be really used as a default string if people don't have any `CFG_DATABASE_USER` defined?  (rather "root", although the regular user would be called "invenio", not "root", by default)

**Comment by jirikuncar** [comment]
@tiborsimko it comes from the installation guide when people call their database same as the branch they are working on ...

**Comment by tiborsimko** [comment]
@jirikuncar Aha, OK :smile: FWIW in `invenio-devscripts` I've been using "inveniomaster" DB userr and name, so that I could have "inspiremaster", etc, for all the overlays I may be working on.  (Naked "master" seems too short to me.)
