### ISSUE TITLE
workflow: bwlOBJECT records not deleted after deleting bwlWORKFLOW record

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3147]
If you run testsuite on deposit you can see that 2 records remains on `bwlWORKFLOW` table.

Using PostgreSQL, I'm receiving this error:

```python
IntegrityError: (psycopg2.IntegrityError) update or delete on table "bwlWORKFLOW" violates foreign key constraint "bwlOBJECT_id_workflow_fkey" on table "bwlOBJECT"
E       DETAIL:  Key (uuid)=(6549633a-fef6-11e4-89dd-080027bebe68) is still referenced from table "bwlOBJECT".
E        [SQL: 'DELETE FROM "bwlWORKFLOW" WHERE "bwlWORKFLOW".uuid = %(uuid_1)s'] [parameters: {'uuid_1': UUID('6549633a-fef6-11e4-89dd-080027bebe68')}]
```

**Comment by jalavik** [comment]
Interesting. Could it be something missing regarding cascading deletes here: https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/workflows/models.py#L337-L339 ?

**Comment by hachreak** [comment]
I'm trying to investigate that :)
Transforming that line in:

```python
workflow = db.relationship(
  Workflow, foreign_keys=[id_workflow], remote_side=Workflow.uuid,
  backref=db.backref('workflow_objects', cascade="all, delete-orphan")
)
```

**Comment by hachreak** [comment]
The changes seems to resolve the issue.
And I found the problem with the 2 records..... in (test)[https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/deposit/testsuite/test_deposit_models.py#L52] the records are created, executed the tests, but not removed... :)
