### ISSUE TITLE
full-text snippets: better phrase search snippet selection

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#315]
Originally on 2010-10-17

When users search for a phrase in the full-text index, a Boolean word query combination is currently performed.  Example: `higgs mechanism` in the demo site.  When showing fulltext snippets for the query, it will be useful to first grep for the phrase and offer those snippets, if available, and only fall back to grepping individual words when there is no phrase.

BTW, beware of stemming when grepping for a phrase, e.g. one can stem individual words and look for those with a wildcard and a space between, kind of like `higgs mechanism` -> `higg\w*\smechan\w*`. Note also that some sites may not have enabled stemming in full-text, so this wildcard game should not be performed then.

**Comment by jirikuncar** [comment]
Closed via 51f54e7 and #836.
