### ISSUE TITLE
collections: collection: Vs cc=

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3157]
Using latest `master` my understanding was that the following queries were going to be equivalent:

https://qa.inspirehep.net/search?p=collection:Institutions
https://qa.inspirehep.net/search?cc=Institutions

But does not seem to be happening. Is it a problem of our installation or `cc` is still supposed to be used?

@jirikuncar

**Comment by jirikuncar** [comment]
`cc` should be still used. `c` argument has been deprecated and one should use `p=collection:"Bar"` instead.
