### ISSUE TITLE
plotextractor: store original plot format

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#316]
Originally on 2010-10-17

During plot extraction workflow, the original plot should be stored in whatever format we may have on the input side (usually EPS for arXiv files).  We should then derive PNGs for web preview and store them as "derived formats" or perhaps "subformats" to its original EPS format, if the original format is not easily ready for nice in-browser-display.  (Note also that storing PNGs as `derived formats' will help in saving storage space inodes.)

We should then update `bfe_plots.py` and friends in order to display "slave" PNG instead of "master" EPS where appropriate.

**Comment by jalavik** [comment]
@tiborsimko Yeah, sort of. Probably nice to have as part of the labs harvesting when the regular arXiv harvesting will be looked over. In the INSPIRE case, we'll possibly address this in labs and for next.

**Comment by kaplun** [comment]
Moved to https://github.com/inspirehep/plotextractor/issues/2
