### ISSUE TITLE
bibdocfile: 404 on file URLs

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3160]
How to reproduce
=============

For example, in the Invenio demo site, click on any file (with URL like `http://localhost:8888/record/59/files/0204143.pdf`)

to get:

![screenshot 2015-05-26 22 18 05](https://cloud.githubusercontent.com/assets/580727/7822346/2151b2fa-03f5-11e5-8190-19f35951ffd1.png)

Same happens if a new file is uploaded through FFT and then tries to be accessed. The metadata reflects the change as field 856 is created (and also the file is listed in `bibdocfile` cli) but it is not accessible in the URL.

**Comment by jirikuncar** [comment]
Probably `get_record(recid, reset_cache=True)` needs to be called.
