### ISSUE TITLE
template: make invenio_format_date filter more robust

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/invenio#3161]
At the moment, the `invenio_format_date` filter defined [here](https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/template/__init__.py#L188) requires a datetime string of the format `2005-11-16 15:11:57`. If given anything else, it prints "N/A".

As a way to make this filter more robust, and thus applicable to more use cases, I think that it should be expanded to accept other possible date strings as well. Anything not recognized should be passed directly through the filter. Examples:

* dd-mm-yyyy hh:mm:ss
* dd-mm-yyyy
* yyyy-mm-dd hh:mm:ss
* yyyy-mm-dd
* dd/mm/yy hh:mm:ss
* dd/mm/yy
* yyyy/mm/dd hh:mm:ss
* yyyy/mm/dd

Also, the filter should be able to accept a custom dateformat string. The default `datestring_format` should be defined in the config file rather than hardcoded in `utils.date`.

**Comment by lnielsen** [comment]
Note https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/babel/filters.py

**Comment by jirikuncar** [comment]
Can we deprecate `invenio_format_date` since we have *Babel* filters?

**Comment by lnielsen** [comment]
I think so. 

```
$ git grep invenio_format_date | wc -l
       6
```

**Comment by PXke** [comment]
:+1:

**Comment by tiborsimko** [comment]
:+1:

**Comment by jirikuncar** [comment]
It is not used in Invenio 3.
