### ISSUE TITLE
accounts: send email validation when a User is inserted

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio#3169]
It would be cleaner to send the validation email when a new `User` is inserted in the database, using SQLAlchemy `after_insert` event. However sending the validation email modifies the database, which is not permitted in `after_insert` handlers.
An attempt at this can be found here: nharraud/invenio@1ada2fa1a0ef6d569b1d7c9621ea479d707a59b9
I tried to send the email using celery to avoid modifying the database in the trigger. However this is not possible as celery tasks run in the main process during tests.

**Comment by hachreak** [comment]
I recently rewrote the "lost password" behavior #3326 (I hope it'll be integrated soon in master). 
It send an "confirmation" email with the link for change password.
Maybe you can use the same method.

**Comment by jirikuncar** [comment]
Flask-Principal is taking care about it in Invenio-Accounts module.
