### ISSUE TITLE
bibdocfile: replace ligatures when textifying

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#317]
Originally on 2010-10-18

To work around Firefox/Mac ligature display problem, a quick fix was introduced recently in d24b8dd3c7c30c958536b24ad03f6f311ea9d5ef.

However, the ligatures should be replaced at the textification time already, because the full-text indexing and searching behaviour is influenced by ligatures too, e.g. one gets on INSPIRE:

```
  fulltext:coeﬃcient - 38,412 hits
  fulltext:coefficient - 787 hits
```

which is not good, because users are not probable to type UTF-8 `ﬃ' character at the search time :).  By expanding ligatures at the full-text textification time, the indexer and the searcher would work in ASCII-like mode so`ffi' would be used in these words everywhere, and Firefox/Mac workaround would not be needed anymore.

So the `sed` expressions should be basically ported to `bibdocfile` textification time.

BTW note also that the Firefox/Max workaround currently generates lots of messages in Apache err file like:

```
sed: couldn't write 1377 items to stdout: Broken pipe
sed: couldn't write 3264 items to stdout: Broken pipe
sed: couldn't write 58 items to stdout: Broken pipe
sed: couldn't write 399 items to stdout: Broken pipe
sed: couldn't write 757 items to stdout: Broken pipe
sed: couldn't write 255 items to stdout: Broken pipe
```

**Comment by tiborsimko** [comment]
The original issue is still valid and observable on INSPIRE:

-  `fulltext:coeﬃcient` ... 158,130 records found 
- `fulltext:coefficient` ... 14,870 records found

CC @kaplun who may want to check this in INSPIRE LABS.

**Comment by kaplun** [comment]
This issue is going to be solved in INSPIRE via elasticsearch-mapper-attachments:
https://github.com/inspirehep/inspire-next/issues/612 and the icu plugin.

Hail to ES :dancer:
