### ISSUE TITLE
access: access control problems

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#3184]
You cannot access Holding Pen as superadmin currently. Also, I've noticed a few problems in the access control module.

* `CFG_SUPERADMINROLE_ID`  is not set properly due to application context issue, but exception is masked by a classic `try..except: pass`.
* There is a quote too much in a SQL query.

~~I am submitting a PR shortly~~. Done

**Comment by jirikuncar** [comment]
@jalavik thanks
