### ISSUE TITLE
docker: support for boot2docker

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#3194]
In general the new docker+docker compose works very nicely. I've tested it on OS X with boot2docker and found some few issues.

**Problem 1** 
Boot2docker creates a minimal VirtualBox VM with docker installed on it and pipes all docker commands to that VM. 
Docker-compose bridges the containers ports to the localhost network interface on the docker host, which in case of boot2docker is localhost on the VM. This means that none of the ports are open to the VM host system (OS X in this case). 

The fix is quite easy as provided by @crepererum:

```
ports:
    - "127.0.0.1:5000:5000"
```
->
```
ports:
    - "5000:5000"
```

It makes sense when the docker host is also the developer machine that the docker containers ports are not opened to your entire LAN. So not sure what the best fix is here. Perhaps just add documentation for boot2docker or provide two different docker-compose files. 

**Problem 2**
Given that problem 1 is fixed, then there's still a problem that ``CFG_SITE_URL`` is set to ``http://localhost:5000`` in ``docker_boot.sh``. Perhaps the fix here is just to ingest ``CFG_SITE_URL`` 
via env variables similar to e.g. ``CFG_DATABASE_HOST``.

**Comment by crepererum** [comment]
See:
 - https://github.com/boot2docker/boot2docker/blob/master/doc/WORKAROUNDS.md#port-forwarding
 - `docker port`
 - https://github.com/docker/docker/issues/4007
