### ISSUE TITLE
RFC: kill (or maim) invenio/legacy/websession/inveniogc.py?

### ISSUE THREAD

**Issue by jacquerie** [inveniosoftware/invenio#3209]
While working on #3079 I stumbled on `invenio/legacy/websession/inveniogc.py`, which uses a few MySQL-only constructs.

One option I see is killing the entire script: the parts that are still needed can be implemented as cron jobs or fab tasks, the rest of the cruft can be trashed.

In alternative, we can wrap any code that uses MySQL-specific syntax with a:
```python
if CFG_DATABASE_TYPE == 'mysql':
    [...]
else:
    raise NotImplementedError
```
This is still a backwards-breaking change, since someone who switches to PostgreSQL will have to deal with it.

WDYT?

* [ ] Cleaning of BibSched logs (no longer needed, since bibsched is deprecated?)
* [ ] Clean temp files (should be built using a registry where every module advertize itself?)
* [ ] Clean cache (superseded by proper usage of Redis?)
* [ ] Clean bibxxx (superseded by new data model and foreign keys)
* [ ] Clean old documents versions (should we really need this one?)
* [ ] Check table (rather implemented as a system-related cronjob) - but might lock up the system
* [ ] Optimize tables (ditto)
* [ ] Clean sessions (superseeded by proper usage of Redis?)
* [ ] Clean BibEdit cache (BibEdit deprecated and additionally like clean temp files activity)
* [ ] Guest user garbage collector (no longer valid as guest users are no longer allocating a user in the system + foreign keys?)

**Comment by jalavik** [comment]
:+1: On splitting these up to (a) existing scripts (for example some database operations can live under `inveniomanage database ...`).

We could list the various tasks that inveniogc is doing and evaluate which ones are worth migrating/keeping/killing.

**Comment by kaplun** [comment]
:+1:

**Comment by jirikuncar** [comment]
Hopefully some of the GC tasks can be removed by using `ON DELETE CASCADE` on foreign keys.

**Comment by kaplun** [comment]
> We could list the various tasks that inveniogc is doing and evaluate which ones are worth migrating/keeping/killing.

Note that @switowski worked on several more improvements to GC (driven by CDS) that needs to be considered for this exercise (#2959)

**Comment by kaplun** [comment]
Added to the initial RFC

**Comment by hachreak** [comment]
I created a Pr to remove websession on master: #3326

**Comment by hachreak** [comment]
`websession removal` merged.
@jacquerie  Can we close the issue?

**Comment by jirikuncar** [comment]
Most of the cleaning tasks are not necessary in Invenio 3 since we are using DB transactions.
