### ISSUE TITLE
global: remove MySQL specific legacy code

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#3214]
- legacy: remove mysql specific codes (see `git grep MySQLdb`, `git grep "SHOW TABLES"`, `git grep "CHECK TABLE"`, `git grep "RLIKE"`, `git grep "PRIORITY"`, `git grep DATE_FORMAT`, `regexp`)

- stems from #3079 roadmap issue

**Comment by jacquerie** [comment]
There's also `SHOW CREATE TABLE`, which was used in the past in `invenio/modules/upgrader` to build the upgrade recipe. Should these be migrated as well?

**Comment by jirikuncar** [comment]
@jacquerie IMHO you can ignore old upgrade recipes.

**Comment by jacquerie** [comment]
Ok! :+1:

**Comment by hachreak** [comment]
We need also find a equivalent for postgresql of `git grep "ON DUPLICATE KEY UPDATE"`

**Comment by hachreak** [comment]
The list:
- [ ] `git grep "ON DUPLICATE KEY UPDATE"`
- [ ] `git grep "SELECT LAST_INSERT_ID()"`
- [ ] `git grep UNIX_TIMESTAMP`
- [ ] `git grep "SLAVE STATUS"`
- [ ] `git grep "INSERT IGNORE"`
- [ ] `git grep inet_aton`
- [ ] `git grep MySQLdb`: waiting #3326
- [ ] `git grep "SHOW TABLES"`
- [ ] `git grep "CHECK TABLE"`
- [ ] `git grep "RLIKE"`
- [ ] `git grep "PRIORITY"`
- [ ] `git grep DATE_FORMAT`
- [ ] `regexp`
- [ ] `git grep SHOW CREATE TABLE`

**Comment by jirikuncar** [comment]
Invenio 3 is using only SQLAlchemy database independent models.
