### ISSUE TITLE
PostgreSQL: serial id is not update after manually creation a admin user

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3216]
I have not exactly undestand why, but tests fails when try to create a new user, because PostgreSQL try to assign id = 1 (that already exists in database).
I found a solution moving [this code](https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/legacy/__init__.py#L50-L54) inside a fixture.

**Comment by jacquerie** [comment]
Maybe I'm misunderstanding something, but isn't this expected? You try to create a user with `id = 1`, which is impossibile, since there's already one. Here's what I see in an `inveniomanage shell` session:
```python
In [1]: from invenio.modules.accounts.models import User
In [2]: from invenio.ext.sqlalchemy import db
In [3]: u = User(id=1, email='foo@example.com', password='', note=1, nickname='admin')
In [4]: db.session.add(u)
In [5]: db.session.commit()

IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry '1' for key 'PRIMARY'") [...]

In [6]: db.session.rollback()
In [7]:  u = User(email='foo@example.com', password='', note=1, nickname='admin')  # Note the missing 'id'.
In [8]: db.session.add(u)
In [9]: db.session.commit()
```

**Comment by hachreak** [comment]
The [code](https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/legacy/__init__.py#L50-L54) is called after database creation to fill the database with some records.
One of this record is the admin user in User table.
And it's ok. 
The problem is when in a testsuite I try to create a temporary user useful for some test.
In those cases, I received the `Duplicate` error as if the current value of the user id had not been updated.
