### ISSUE TITLE
SQLAlchemy: UUID value on PostgreSQL

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3217]
I had some issue with UUID column on PostgreSQL because in models we mix String column with UUID.
It worked with mysql because of [this](https://github.com/hachreak/invenio/blob/master/invenio/ext/sqlalchemy/types/guid.py#L38) where UUID was "casted" as chars.
But it's not the same for any other database server.

**Comment by lnielsen** [comment]
Sorry another question, why are the log entries removed when removing the workflow/bibworkflowobject?   Aren't they useful even after an object has been removed? Some of these logs should be stored in an audit log instead, but we don't have that yet.

**Comment by hachreak** [comment]
Are you talking about the cascade deletion introduced here https://github.com/inveniosoftware/invenio/commit/ac2bd1fa67d73f1c0d0ff0d649966b850e878a00 ? :)

**Comment by jalavik** [comment]
@lnielsen Thats a good point. Indeed we should probably amend that to not delete the logs.

**Comment by lnielsen** [comment]
@hachreak I just noticed the commit message:

```
* Defines a delete cascade action for BibWorkflowObject and
  BibWorkflowObjectLog if you delete a Workflow.
```

**Comment by hachreak** [comment]
The cascade for BibWorkflowObjectLog was introduced by https://github.com/inveniosoftware/invenio/commit/ac2bd1fa67d73f1c0d0ff0d649966b850e878a00 
Sorry, the commit message is not completely correct.
