### ISSUE TITLE
deposit: improve file upload workflow

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio#3226]
(this issue was previously there: inveniosoftware/invenio-demosite#63)

SCENARIO:
- user creates a new submission and fill mandatory fields
- user clicks on `choose files` and choose a file
- user click on `submit`

RESULT:
The new created submission does not have any document even though the user chose a document.

PROPOSED SOLUTIONS:
1. Display a popup warning if the user chose a file without uploading it.
2. Always upload documents when clicking on submit. We could then remove the `start upload` button.
3. Slight design improvements: the progress bar is not explicit. A user does not understand that it is related to upload. It only seems to be a grey rectangle. We can add a 0% or "not uploaded" inside. The `start upload` button could also be more visible.

Another problem is the `save` button which saves everything except the files which have not been uploaded.

**Comment by jirikuncar** [comment]
Follow updates in [Invenio-Deposit](https://github.com/inveniosoftware/invenio-deposit) repository.
