### ISSUE TITLE
tags: assignes 0 on foreign keys

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3246]
The module permits to set 0 as valid value on foreign keys id_usergroup and id_user.
On PostgreSQL, this generate an error.

See https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/tags/models.py#L145

**Comment by jirikuncar** [comment]
Can you move the issue to `invenio-tags` repo?

**Comment by hachreak** [comment]
Closed by inveniosoftware/invenio-tags#4
