### ISSUE TITLE
Users need to see their total citations in a given year

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#326]
Originally by _hoc_ on 2010-10-26

Users would like a way to see the total number of citations a person got in a given year. e.g. how many citations did John Ellis get in 2009? Presently this can't be done over the web (you can see how many papers of his were cited or how many papers cited him but each of his papers could have been cited 10 times in 2009 and this would miss that, in the second case, each citing paper could have cited 5 Ellis papers and we'd also miss that).

Probably the best thing would be to give citesummary an option to restrict the result to citations from a given year. 

This is important for people generating end-of-year activity reports and the like.

Heath.

**Comment by jirikuncar** [comment]
@kaplun has it been already fixed?

**Comment by kaplun** [comment]
@tiborsimko would be nice to have access to all these branches mentioned by Valkyrie...

**Comment by kaplun** [comment]
Ah cool it's still online :)

**Comment by kaplun** [comment]
for reference I pushed Valkyrie's code to https://github.com/kaplun/invenio/commit/d485262d4b46d75edecf9d2df8439efe767aca47

It's now of course badly conflicting (4 years have passed!!!) worth taking it account for 2.x

**Comment by kaplun** [comment]
@jacquerie it's one of those derived computations that we should be able to build using the relation module :-)

**Comment by jirikuncar** [comment]
@nharraud interesting example for ElasticSearch aggregations.

**Comment by kaplun** [comment]
Closing this since in INSPIRE we now have implemented a dedicated dashboard:

https://github.com/inspirehep/inspire-citesummary-js
