### ISSUE TITLE
RFC plans for refactoring access module

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3299]
- [x] Remove [admin_lib.py](https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/access/admin_lib.py)
- [ ] Remove [webaccessadmin.py](https://github.com/inveniosoftware/invenio/blob/master/invenio%2Fmodules%2Faccess%2Fscripts%2Fwebaccessadmin.py) and move functionality in `manage.py` (see #3381)
- [ ] Remove not used functions from [control.py](https://github.com/inveniosoftware/invenio/blob/master/invenio%2Fmodules%2Faccess%2Fcontrol.py).
This is a list of functions candidates:
  - acc_add_argument
  - acc_delete_action
  - acc_delete_argument
  - acc_delete_argument_names
  - acc_delete_possible_actions
  - acc_delete_role_action
  - acc_delete_role_action_arguments
  - acc_delete_role_action_arguments_names
  - acc_delete_role_action_arguments_group
  - acc_find_delegated_roles
  - acc_find_possible_actions_all
  - acc_find_possible_actions_user
  - acc_find_possible_actions_user_from_user_info
  - acc_find_possible_activities (used only by `webuser.py`)
  - acc_find_user_role_actions
  - acc_get_action_details
  - acc_get_action_name
  - acc_get_action_roles (only used in legacy `webuser` and legacy `admin_lib.py`)
  - acc_get_all_roles
  - acc_get_role_actions
  - acc_get_role_definition
  - acc_get_role_details
  - acc_get_role_users
  - acc_merge_argument_groups
  - acc_split_argument_group
  - acc_verify_action
  - acc_is_role (used only in `invenio/legacy/bibdocfile/webinterface.py`)
- [ ] Move model validation from `control.py` to the `models.py`.
- [ ] Convert raw sql to SQLAlchemy code.
- [x] access: fix foreign key declaration. #3099
- [ ] Create a official API
- [ ] Create a complete testsuite

Any comments and suggestions?

cc @jirikuncar

**Comment by kaplun** [comment]
Are you going to tackle the usage of `-1` to mean no arguments for an action? (which breaks foreign key usage)?

**Comment by hachreak** [comment]
I already resolved the problem removing foreign key and create a ad-hoc SQLALchemy relationship.
I need more time to finish to prepare PR to fix it.
I'll add the Issue/PR to the list.

**Comment by kaplun** [comment]
:+1:
