### ISSUE TITLE
DOI is not prominently displayed on detailed record

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#330]
Originally by *hoc* on 2010-10-29

Should he full DOI should be displayed in a detailed record. As it is, it just forms the link to the journal server, e.g. http://inspirebeta.net/record/843382?ln=en
In SPIRES we displayed the DOI in case it was useful to people:
http://www.slac.stanford.edu/spires/find/hep/www?eprint=arXiv:1001.3422

Heath

**Comment by kaplun** [comment]
Already Implemented in INSPIRE overlay
