### ISSUE TITLE
RFC: bibupload has no activated tests

### ISSUE THREAD

**Issue by dset0x** [inveniosoftware/invenio#3306]
#### Pretext
Some branches were hit by a `bibupload` bug not long ago and this has cost us some development time. I believe the patch that fixed it was 4e4225b7f1dcd7688c3d42b5be8675ceed6f8428.

#### Problem
From this it seems that there is nothing checking if basic `bibupload` uploading is working in travis.

#### Current state
Integration tests for `bibupload` exist in `invenio-demosite`, but the demosite has never been tested in `.travis.yml` from what its git log reveals.

#### Solution 1
We can make the `demosite` part of the `invenio`'s travis test run. To do this cleanly, we would have to run the tests as they do currently, and __then__ test again with the demosite. After all, we should be able to, at a minimum, run the demosite record creation.

#### Solution 2
If including the `demosite` in the travis of `invenio` is deemed too much, we can add a couple of [simple black-box integration tests](https://github.com/dset0x/invenio/commit/5cb7ac6930672887ab0c1a4fcd7137df574f9ec9), so that we will at least not have developers who want to add some sample records in their database for testing purposes spend hours trying to figure out what's broken.

cc. @ioannistsanaktsidis

**Comment by tiborsimko** [comment]
Yes, it is annoying that after regression/functional tests have been split away into `invenio-demosite`, they are not being run as part of the main PR...  We've had a few similar issues of this kind already for other functionality. 

The solution we've been thinking about was to extend our [nightly Jenkins builds](http://jenkins.invenio-software.org/) to cover not only Invenio demo site v1.x legacy branches, but also v2.x demo site ones, the testing running via Docker.  CC-ing @lovasko @kaplun

**Comment by kaplun** [comment]
Note: the new dockerized Jenkins instance prototiped by @lovasko is available here: http://inv-bld-tst.cern.ch:8080/ (accessible only within CERN intranet)

**Comment by tiborsimko** [comment]
@lovasko @kaplun We need more though.  Should-have features: (1) run the tests and produce test report; (2) add `invenio-demosite` nightly job; (3) add `*-maint-x.y` jobs for each interesting branch.  Nice-to-have features that can come later: (4) produce code coverage report; (5) produce code vulnerability/kwalitee report.

**Comment by kaplun** [comment]
:+1:

**Comment by jirikuncar** [comment]
BibUpload has been removed from Invenio 3. If you have any tests for maint-1.x branches feel free to submit PRs.

**Comment by tiborsimko** [comment]
@jirikuncar BibUpload is very well tested in all the 1.x branches :smile: This issue was about 2.x only.

**Comment by jirikuncar** [comment]
Fixed typo 😉
