### ISSUE TITLE
Supporting local output formats

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#333]
Originally on 2010-11-04

When an updated version of Invenio is reinstalled over an already existing installation, any customization made to invenio-local.conf, any webstyle, any new websubmit function, any new bibformat element, any new format template are preserved. 

Output formats, however, have their names hardcoded into Invenio codebase, and the administrator will usually customize them in place, instead of creating new files. Hence, when make install is performed, any customization is lost.

To support -local suffix ala invenio(-local).conf might be a nice feature to have, so that administrators can simply customize a default output format (say HD.bfo can be customized by the admin by creating a file called HD-local.bfo which would not be overwritten by make install)

**Comment by jirikuncar** [comment]
Not applicable to 2.x branch. Re-open if needed for 1.x.
