### ISSUE TITLE
Overwriting/overloading of JSONalchemy fields not possible

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/invenio#3334]
For JSONalchemy fields added through modules such as the `_collections` field (https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/collections/recordext/fields/collections.cfg), it's impossible to alter it without receiving an error complaining about duplicate fields. In this specific instance, the problem is that the `_collections` field needs a @depends_on decorator based on which fields used in the collection dbqueries.

**Comment by egabancho** [comment]
@blixhavn could you add the error trace please?

**Comment by PXke** [comment]
It seems we can close this one, as we will be using 2.0.x for a while and the way JSONalchemy works will change.

**Comment by tiborsimko** [comment]
Closing, thanks.

**Comment by PXke** [comment]
:smile:
