### ISSUE TITLE
search: elasticsearch schema fields wrongly mapped to numeric

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio#3339]
The elasticsearch mapping for Record contains `numeric_detection": True`. This  enables the numeric fields autodetection.
With this option enabled, if a field which is not explicitly defined in the schema is present in a document and if it looks like a number, then it will mapped as a number. If next documents don't contain an integer for this field, the error `MapperParsingException` will be returned.

*Scenario:*
```
# create demo records
$ inveniomanage records create -t marcxml < invenio/testsuite/data/demo_record_marc_data.xml
# index the data
$ inveniomanage shell
  $ from invenio_records.models import Record
  $ from invenio.ext.es import index_record
  $ [index_record(r.id) for r in Record.query.all()]
...
RequestError: TransportError(400, u'MapperParsingException[failed to parse [universal_decimal_classification_number.universal_decimal_classification_number]]; nested: NumberFormatException[multiple points]; ')
```

**Comment by jalavik** [comment]
While on the topic of `SEARCH_RECORD_MAPPING` in the `es` extension, I guess the idea is to make it part of the general config object so that it is also easily customisable on the instance overlay. I guess it lives where it lives right now due to it being the first iteration of the extension.

**Comment by jmartinm** [comment]
:+1: @nharraud we have seen the same problem with our INSPIRE demo records.

And as @jalavik mentions, I guess this will soon be configurable per installation.

**Comment by nharraud** [comment]
@jalavik Yes, it will be configurable in the end. This is only temporary hard coded for easiness of development.
@jmartinm If you have similar dynamic schema issues you might want to also use `date_detection: false` which will prevent elasticsearch from trying to detect automatically dates.
