### ISSUE TITLE
BibCirculation: improve email notifications

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#335]
Originally on 2010-11-05

1. Email notifications sent to users (eg. overdue items) are currently stored in CFG_BIBCIRCULATION_TEMPLATES, in bibcirculation_config.py. This is not convenient for customizing the letters. Moving them to bibcirculation_templates.py would let admins overrides the messages more easily (eg. with bibcirculation_templates_ithaca.py)

2. It is not possible to change the subject of the email notifications. For eg. 
```
"LOAN RECALL: " + title
``` 
   is hardcoded in bibcirculation_daemon.py

3. Email notifications are not translated to user's preferred language.

4. Cosmetic improvements:
   - wrap messages at 80 chars (or so)
   - shorten URL /yourloans/display to /yourloans)

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-circulation #16](https://github.com/inveniosoftware/invenio-circulation/issues/16) via [**ZenHub**](https://www.zenhub.com/)
