### ISSUE TITLE
search: /export problems

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3351]
I can currently see 2 different places where the `/export` functionality is implemented:

1) [Invenio-records](https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/views.py#L133)

2) [Invenio ](https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/search/views/search.py#L333)

In 1) there is a problem as recids are passed ([see here](https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/views.py#L150)) but the `formatter` expects to have a record object [here](https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/formatter/engine.py#L184) so a page like `export/xm` crashes.

In 2) the same functionality seems to be implemented but this time correctly as record objects are passed.

Shall we remove 1) and leave only 2) ? In 2) we could add the route `@blueprint.route('/<int:recid>/export/<of>', methods=['GET', 'POST'])`

Any future plans for `/export` ?

**Comment by jirikuncar** [comment]
There are two different use cases that can co-exists until new REST API for search is in place.

**Comment by jmartinm** [comment]
Does it make sense to move this as a comment for https://github.com/inveniosoftware/invenio/issues/2478 ?

**Comment by jmartinm** [comment]
So I guess in the interim we can fix the view in 1) so that record objects are passed instead of recids.
