### ISSUE TITLE
encoder: process_batch_job gives wrong arguments to compose_file

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/invenio#3354]
In `process_batch_job`, `compose file` is called with directory, docname and extension as unnamed arguments [1], while the definition [2] takes only `dirname` and `extension` as unnamed arguments. This leads to `compose_file` returning `<directory>/<docname>.<docname>;<extension>` as path, instead of `<directory>/<docname>.<extension>`

[1] https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/encoder/batch_engine.py#L542
[2] https://github.com/inveniosoftware/invenio/blob/master/invenio/legacy/bibdocfile/api.py#L520

**Comment by blixhavn** [comment]
Before I start working on this: what is the preferred filename? `<docname>.<extension>;<extension>` or `<docname>.<extension>`?

**Comment by tiborsimko** [comment]
CC @ludmilamarian @drjova WRT video encoder

**Comment by ludmilamarian** [comment]
@blixhavn apparently ffmpeg  does not support ';foo' so going for `< docname>.<ext>` is better. So I think the commit is good to go. Anyway this renaming is just for processing, the full name with subformat and extension that will be stored in bobdoc is computed correctly afterwards.
