### ISSUE TITLE
search: query parser does not parse all possible combinations of NOT operator correctly

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio#3366]
The `NOT` operator is not parsed as NotOp.

OR NOT
-----------
`NOT` is parsed as a `Value`.

**Example:**
`test AND (author:"Alexander, S" OR NOT author:"Costa, M S")`

gives

`AndOp(ValueQuery(Value('test')), AndOp(OrOp(KeywordOp(Keyword('author'), DoubleQuotedValue('Alexander, S')), ValueQuery(Value('NOT'))), KeywordOp(Keyword('author'), DoubleQuotedValue('Costa, M S'))))`

AND (NOT ...
-----------------
`NOT` is parsed as a `Value`.

**Example:**
`test AND (NOT author:"Alexander, S")`

gives

`AndOp(ValueQuery(Value('test')), AndOp(ValueQuery(Value('NOT')), KeywordOp(Keyword('author'), DoubleQuotedValue('Alexander, S'))))`

Only AND NOT works
-----------------------------
NOT is then properly parsed as NotOp

**Example:**

`test AND (author:"Alexander, S" AND NOT author:"Costa, M S")`

gives

`AndOp(ValueQuery(Value('test')), AndOp(KeywordOp(Keyword('author'), DoubleQuotedValue('Alexander, S')), NotOp(KeywordOp(Keyword('author'), DoubleQuotedValue('Costa, M S')))))`

If some operations are not supported like `OR NOT`, then server should return an error. It should not parse it sometime as a `Value` and sometime as `NotOp`.

**Comment by jirikuncar** [comment]
@nharraud please move it to `invenio-query-parser`
