### ISSUE TITLE
RFC webaccessadmin replacement

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3381]
I'm working on access module refactoring (see #3328) and I want to port the `webaccessadmin` script in a `inveniomanage access` interface.
Can I remove the `demosite` [specific part](https://github.com/inveniosoftware/invenio/blob/b26a239abfb78a2613f2c6c94dbbd8abec35f642/invenio/modules/access/scripts/webaccessadmin.py#L62-L64) and use another approach to load actions/roles/useraccroles/authorizations/arguments?

**Comment by kaplun** [comment]
Ideally would be nice to be able to dump and load roles/actions/authorization/arguments. (actually actions are special in that they need to be rather collected via a registry)

**Comment by kaplun** [comment]
In this sense demosite specific roles and authorization would be simply some configuration/fixture that could be loaded from an overlay.

**Comment by hachreak** [comment]
@kaplun you talking about this [registry](https://github.com/inveniosoftware/invenio/blob/b26a239abfb78a2613f2c6c94dbbd8abec35f642/invenio/ext/principal/wrappers.py) for actions?
It loads all actions defined in `acl.py` (e.g. for [workflows](https://github.com/inveniosoftware/invenio/blob/b26a239abfb78a2613f2c6c94dbbd8abec35f642/invenio/modules/workflows/acl.py) ).
But, can you create a new actions in demosite with this method?
I tried to create `invenio_demosite/modules/access/acl.py` but it's not automatically loaded.

**Comment by jirikuncar** [comment]
@hachreak the `acl`s are loaded if imported in `views` or `__init__`.

**Comment by hachreak** [comment]
What can we create as fixtures and where?

**Comment by kaplun** [comment]
To whom are you asking this? Anyway, as far as I can think about it, anything (but actions)  in: https://github.com/inveniosoftware/invenio/blob/legacy/modules/webaccess/lib/access_control_config.py#L472-L647 is eligible to be transformed into fixtures (which should typically go into the demosite, they are specific to a given installation). 
Actions are already well implemented as a registry, thanks for the pointer.

**Comment by hachreak** [comment]
So, if we put all in fixtures, my next question is: do we still need `webaccessadmin` tool? :)

**Comment by jirikuncar** [comment]
> do we still need `webaccessadmin` tool?

We should have `manage` command to modify roles and rights.

**Comment by kaplun** [comment]
:+1:  Fixture are good just to initialize out of the box an instance with sensible defaults. Then inveniomanage (and possibly a web interface) would allow to fine tune authorizations.

**Comment by jirikuncar** [comment]
Check CLI implemented in Invenio-Access.
