### ISSUE TITLE
urlutils.py v.1.1

### ISSUE THREAD

**Issue by rthieledesy** [inveniosoftware/invenio#3382]
Hallo,

I have installed the Invenio 1.1.6 on Scientific Linux 6.5. We will starting to test the upgrading process on Invenio 1.2.
But in the moment, we get the following warning:
/usr/lib64/python2.6/site-packages/invenio/urlutils.py:40: DeprecationWarning: the md5 module is deprecated; use hashlib instead

I have seen, that for Invenio 1.2 the urutils.py is using haslib instead of md5.
Is it possible, that the urlutils.py v.1.1 is getting the md5 import from v.1.2? It would be helpful for avoiding the deprecation warnings.

Robert Thiele
DESY

**Comment by tiborsimko** [comment]
OK, nobody took this issue during Hacktoberfest, so I'm going to take it myself...

**Comment by tiborsimko** [comment]
Closed by #3718.
