### ISSUE TITLE
access: CFG_SUPERADMINROLE_ID is not accurate in the demosite.

### ISSUE THREAD

**Issue by jmacmahon** [inveniosoftware/invenio#3390]
The access module uses the `CFG_SUPERADMINROLE_ID` config variable to determine what role ID to add to authorisation requests: https://github.com/inveniosoftware/invenio/blob/maint-2.1/invenio/modules/access/control.py#L1474, but in the standard Invenio demosite installation, the `superadmin` role ID is 11.  This causes unexpected behaviour when authorizing users belonging to whichever role has ID 1.

## Environment
* Invenio `maint-2.1`
* Python `2.7.6`
* System: Ubuntu Trusty (`ubuntu/trusty64` Vagrant image)

## Steps to reproduce
With a standard Invenio demosite installation:
```
mysql> select id, name, description from accROLE where name = 'superadmin';
+----+------------+---------------------------+
| id | name       | description               |
+----+------------+---------------------------+
| 11 | superadmin | superuser with all rights |
+----+------------+---------------------------+
```
```
$ inveniomanage shell
>>> from invenio.modules.access.control import acc_find_possible_roles
>>> acc_find_possible_roles('viewstatistics', always_add_superadmin=True) # Should include superadmin role with ID 11
intbitset([1, 22])
```

### Expected behaviour
Returned `intbitset` object includes 11 (role id of `superadmin`).

### Actual behaviour
Returned `intbitset` object does not include 11, and includes 1 instead.

## Consequent bugs
Users belonging to the actual role with ID 1, in this case `thesescurator`, may perform any action.  An example user is `romeo`, with ID 5:
```
$ inveniomanage shell
>>> from invenio.modules.access.engine import acc_authorize_action
>>> acc_authorize_action(5, 'usedeposit')
(0, 'Authorization granted')
>>> acc_authorize_action(5, 'moderatecomments')
(0, 'Authorization granted')
>>> acc_authorize_action(5, 'non_existant_action')
(0, 'Authorization granted')
```

## Suggestion
Replace with a call to `acc_get_role_id(SUPERADMINROLE)`.  Was there a reason this approach was not taken in the first place?

**Comment by jalavik** [comment]
+1 on the suggestion. Not sure why this was done this way originally. It was recently moved it from a hardcoded value to this config, but I agree that this check is flawed in general. Replacing with `name= SUPERADMINROLE` at least does not rely on ordering of `INSERT` into the role table.

**Comment by kaplun** [comment]
> Was there a reason this approach was not taken in the first place?

I fear micro-optimization (because the superadmin role is checked continuously).

**Comment by jmacmahon** [comment]
If it's an optimisation issue, perhaps we could check the superadmin role ID once at the top of the file (i.e. at load time) and use that value later?  Since it's highly unlikely the ID will change while Invenio is running.

**Comment by kaplun** [comment]
You can skip optimization anyway, as it was more due to the old Invenio and not nicely using memoization and caching everywhere. :smile:
