### ISSUE TITLE
global: invenio-records needs version update

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3393]
Running:

```bash
$ inveniomanage records create inspire/demosite/data/demo-records.xml -t marcxml
```

gives the error:

```
'invenio.modules.documents.recordext.functions.set_record_documents' not found.
```

Problem seems to be that [this function](https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/documents/recordext/functions/set_record_documents.py#L27) is not defined in [Invenio-records 0.1.0](https://github.com/inveniosoftware/invenio-records/tree/v0.1.0)

Time to release new version of `invenio-records` and update the version in `setup.py`?

**Comment by jirikuncar** [comment]
Closed via https://github.com/inveniosoftware/invenio-records/releases/tag/v0.2.0
