### ISSUE TITLE
session: 500 error on https failure check

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3394]
The following lines of code https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/session/interface.py#L197-L207

raise a `BadRequest` exception that gets propagated until the user sees an Internal Server Error.

Even though we have not seen it often there is some assumption on that code that is not holding true in all situations and the current fallback is not user friendly.

* Any idea on how can it be that we are entering the `raise BadRequest` code path?
* What could be a better fallback for this situation? Just return?

**Comment by jirikuncar** [comment]
@jmartinm can you provide a case when it fails? You can add `@app.errorhandler(BadRequest)` in your overlay as a hotfix.

**Comment by jmartinm** [comment]
So this is the traceback:

http://pastebin.com/ATJLAZmu

Not sure how to reproduce it. It is happening from one machine for the user account of Annette (she logs in via ORCID and her account has superadmin rights)

If I remember correctly, this same error was happening at the beginning frequently until we added this configuration https://github.com/inspirehep/inspire-next/blob/master/inspire/config.py#L270 so maybe in that computer she has some outdated `remember_me` cookie without `secure=True` and the request is done via HTTP.

Note that at the moment we have 3 cookies for the session:

1) `remember_me` from Flask-Login
2) `session` from Invenio
3) `sessionstub` from Invenio

I am actually not sure what 3) is used for.

**Comment by jirikuncar** [comment]
@jmartinm it looks like she is accessing the site via HTTP when she is logged in (http://labs.inspirehep.net/admin/holdingpen/details/45141 instead of https://labs.inspirehep.net/admin/holdingpen/details/45141).

**Comment by jmartinm** [comment]
That is the weird thing. For me, if I am logged in and access the page 
http://labs.inspirehep.net/admin/holdingpen/details/45141 I get redirected to 
https://labs.inspirehep.net/admin/holdingpen/details/45141 without any error. Not sure at what level this redirection happens and why would it not work for her.

**Comment by jmartinm** [comment]
Just got this locally too.

I think this happens when `session` and `sessionstub` expire and the only cookie left is `remember_me` (from Flask-Login):

![screen shot 2015-07-29 at 9 20 16 am](https://cloud.githubusercontent.com/assets/580727/8951973/3b38e6ce-35d3-11e5-8252-1d91b7b4e59d.png)

As that cookie by default [is not marked as secure](https://github.com/maxcountryman/flask-login/blob/master/flask_login.py#L55) the request is sent via http.

On our overlay we have not seen this error any more from new users since we set [REMEMBER_COOKIE_SECURE = True](https://github.com/inspirehep/inspire-next/blob/master/inspire/config.py#L270)

Shall we set [for Invenio](https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/login/__init__.py#L106) also this variable with default value `True` ?

**Comment by jmartinm** [comment]
Removing the cookie and refreshing the page makes the 500 error go away.
