### ISSUE TITLE
install: remove --process-dependency-links reference

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3401]
In INSTALL.rst there is:

```bash
(invenio)$ pip install --process-dependency-links -e .[development]
```

Since it seems we are not using any more dependency links like we used to when this INSTALL file was created (https://github.com/inveniosoftware/invenio/blob/8e856b6edab2390e42c96db622c8ffa57907b547/setup.py#L55-L59) we can remove it from the installation instructions to not confuse the developers.

It is not recommended to use dependency links anyhow https://github.com/pypa/pip/issues/2023

**Comment by jmartinm** [comment]
Let me know if it makes sense and I will create PR.

**Comment by jmartinm** [comment]
For reference, I tried installing Invenio + INSPIRE without `--process-dependency-links` with no problem.

**Comment by jirikuncar** [comment]
:+1: we can remove it
