### ISSUE TITLE
demosite: load of demo records error

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3407]
How to reproduce
==============

```
$ inveniomanage database init --user=root --yes-i-know
```
```
$ inveniomanage database create
```
```
$ inveniomanage records create invenio/testsuite/data/demo_record_marc_data.xml -t marcxml
```

And get the following `sqlalchemy.exc.IntegrityError`:

http://pastebin.com/238DZJyH

**Comment by jirikuncar** [comment]
I can not reproduce it with latest Invenio and Invenio-Demosite master.

**Comment by jmartinm** [comment]
What database are you using?

I have:

```
mysql  Ver 14.14 Distrib 5.6.24, for osx10.10 (x86_64) using  EditLine wrapper
```
and can see the error.

**Comment by jirikuncar** [comment]
```
mysql  Ver 14.14 Distrib 5.6.25, for osx10.10 (x86_64) using  EditLine wrapper
```

**Comment by jmartinm** [comment]
OK. Upgrading mysql did not help.

`pip install invenio-records --upgrade`

did.

**Comment by jacquerie** [comment]
FWIW, I'm having the same issue, and upgrading `invenio-records` didn't solve it. This appears to happen on records that have a `controlfield` tag in them, since removing it makes `inveniomanage records create` work again.

**Comment by jirikuncar** [comment]
@jacquerie can you please provide more details and traceback? Maybe we need to submit an issue to DoJSON. Please make sure you are running latest version of all packages. Thanks

**Comment by tiborsimko** [comment]
@jmartinm @jacquerie In case of problems of this kind, you can easily use Docker to confirm/infirm whether latest `invenio-demosite` and friends behave OK or not:

``` 
$ cd ~/private/src/invenio
$ git fetch upstream
$ git checkout master
$ git merge --ff-only upstream/master
$ docker build -t invenio:latest .
$ cd ~/private/src/invenio-demosite
$ git fetch upstream
$ git checkout master
$ git merge --ff-only upstream/master
$ docker-compose -f docker-compose-dev.yml build
$ docker-compose -f docker-compose-dev.yml up
$ # now wait until all daemons are fully up and running
$ docker exec -i -t -u invenio inveniodemosite_web_1 \
          inveniomanage demosite populate \
          --packages=invenio_demosite.base --yes-i-know
$ w3m http://127.0.0.1:28080/search
```

see e.g. https://github.com/inveniosoftware/invenio-demosite/commit/c13311fe33ea48d2d1ae8f5bdbe2d112d3738bcd
