### ISSUE TITLE
RFC Problems during module separation

### ISSUE THREAD

**Issue by crepererum** [inveniosoftware/invenio#3413]
We started to rip out certain modules from Invenio core to improve maintainability and to speed up development. This issue contains some of the problems, that I faced during that process:

## Autodiscovery
**Problem:** Right now, modules have to be specified using the `PACKAGES` config variable. That makes creating overlays more difficult and error-prone, because devs need to specify the desired set twice (once in `setup.py`, a second time in `config.py`).

**Solution:** Implement entry points.

**Status:** Planned. 

## Test Overlays
**Problem:** To test a certain module, other modules that use that functionality are needed. This is especially true for visual test and automated browser tests, but also holds for presenting a good demo use case for a module.

**Solution:** Add a fake package to the modules to build a demo overlay.

**Status:** Implemented in https://github.com/inveniosoftware/invenio-jsonschemas/pull/1 and https://github.com/inveniosoftware/invenio/pull/3380.

##  "Module" vs "Package"
**Problem:** We somehow mix up the terms `module` and `package`. Our [cookiecutter template](https://github.com/inveniosoftware/cookiecutter-invenio-module) clearly calls the ripped out *things* modules and the Python parts packages. The dynamic loading system in `config.py` calls the single parts packages. In theory, a module can implement multiple packages, but I've never seen this in the wild and I think we do not really encourage people to do so.

**Solution:** Write some docs to clarify the module system, including the installation and loading as well as the relations `overlay->modules->packages`.

**Status:** TODO.

## require.js
**Problem:** Require.js uses [`settings.js`](https://github.com/inveniosoftware/invenio/blob/master/invenio/base/static/js/settings.js) and [`build.js`](https://github.com/inveniosoftware/invenio/blob/master/invenio/base/static/js/build.js) for getting the relations between the our JS files and vendors files correct. We've already seen that this [is not working well for overlays](https://github.com/zenodo/zenodo/blob/master/zenodo/base/static/js/settings.js#L164).

**Solution:** Replace the static version of the mentioned files with a dynamic version and some kind of registry.

**Status:** TODO.

## Upgrade Recipes
**Problem:** Right now, upgrades have to mention dependencies explicitly. Now imagine the scenario that we've faced during the [InnoDB upgrade](https://github.com/inveniosoftware/invenio/pull/3355). There we needed to fix module bugs before doing another global upgrade. Stating the fact that the core should not know about available modules, this upgrade would never be possible and [already let to some issues](https://github.com/inveniosoftware/invenio/issues/3406).

**Solution:** Implement the ability to specify a `before` relation of upgrades as well (in addition to the `after` relation).

**Status:** TODO.

## Load Order
**Problem:** Module devs currently have no way to control the load order of there module and having [cyclic dependencies](https://github.com/inveniosoftware/invenio/issues/3120#issuecomment-103816619) does not make this easier.

**Solution:** Using *Lazy{String,Dict,...}` and hope that it works? Leaving it to the overlay/site admin (i.e. `config.py`)?

**Status:** TODO.

----------------------------

**to be continued**

**Comment by jirikuncar** [comment]
> ### "Module" vs "Package"

Maybe we should use term "Distribution" or "Distribution Package" (https://packaging.python.org/en/latest/distributing.html#upload-your-distributions).

**Comment by jirikuncar** [comment]
> ### Upgrade Recipes

One *MUST* only depend of upgrades from its own module or dependencies.

**Comment by crepererum** [comment]
> One MUST only depend of upgrades from its own module or dependencies.
Yeah, in theory. As shown in the example, that is not really true.

**Comment by tiborsimko** [comment]
WRT upgrade recipes and package dependencies, I guess the practice will become closer to theory once we separate away all the modules into their own standalone packages with well defined dependencies between them.

**Comment by lnielsen** [comment]
> Autodiscovery with entry points

Don't you just end up in the same situation having to specify it twice - i.e. you have to specify dependencies twice in the setup.py (in ``requires`` and in ``entry_points``)? 

> "Module" vs "Package"

Agree that this is confusing, and inconsistent with Python's nomenclature. A package consists of modules (single python files). Another possibility is calling it "application", but that probably conflicts with Flask's nomenclature.

Partial documentation is available now in http://flask-appfactory.readthedocs.org/en/latest/ (but nomenclature should still be clarified).

> Load Order

Not sure what you mean here? Extensions and packages are loaded in order as they appear in their respective config variable. Lots of packages have bad imports due to legacy history, but I think that's being fixed as part of moving the modules out into separate repositories and making it more clear what is a dependency.

**Comment by tiborsimko** [comment]
I guess it is rather clear and self-understood that "Invenio module" != "Python module"?  

We are using "module" in a general sense of the word:

```
  module
  
     1. <programming> An independent piece of {software} which
     forms part of one or more larger {programs}.
```

or from another dictionary:

```
module
      4: a self-contained component (unit or item) that is used in
         combination with other components

```

We could perhaps use the term "component", although "module" is what we've been using historically.  (Hence speaking of a record editor module, a record formatter module, etc, where each component happens to be released as a Python package.)

**Comment by jirikuncar** [comment]
Invenio has been splitted info many independent packages https://github.com/inveniosoftware/?utf8=%E2%9C%93&query=invenio- (and more hosted by other institutes and organizations).
