### ISSUE TITLE
RFC search: facet filtering design

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio#3415]
Introduction
----------------
This issue defines the default facet filtering/faceting behavior, what parts are customizable and what other behavior it should be able to achieve with minimal customizations.
It should mainly contain high level specifications.
It will also list all related issues.

Default behavior
----------------------
**Definitions**
- Perform a search: the user clicks on the `search` button or reloads the page.
- Change facet filtering: the user changes included facets.
- User query: search query which can be edited by the user. It is in the search input box.

**Facets Menu**:
- There is one panel for each facet.
- Each panel list values most frequent to the user query only. Selected facet filters are not changing this list.
- There is a number of occurence count for each value. Selected facet filters are not changing these counters.
- Listed values and their counters are NOT updated when a value is added to query filters.
- The facet menu contains values 

**Query FIlters Widget**
- A widget displays the currently enabled facet filters in the form of a query.
- The widget is hidden if no facet filter is enabled.
- There is an edit button near the query. When it is clicked, the widget disappears, facet filters are cleared and their previous value is added to the user query in the form of additional query terms.

**Browser History**
- All facet filter changes are creating a new state in the browser history.
- Each time the user sends a new user query (by editing it and clicking "search" or pressing enter) a new state is pushed in the browser history.
- Going forward or backward in this history reselect the corresponding faceting.
- Going forward or backward in this history reload the corresponding search results.
- Going forward or backward in this history reload the corresponding user query.

**Search Results**
- The search results list and the counter of number of matching documents are updated each time facet filters or the user query change.

Other possible behaviors
---------------------------------

**Dynamic facet menu**
- The facet menu shows only the facet values frequent in documents matching BOTH user query and facet filters. Each time one of them change the list and the counters update. Asked by @jmartinm

*How*
TODO

**New search forgetting the previous facet filtering**
- When the user changes the user query and clicks on "search" or press enter in the search box, facet filtering is reset. Only the new user query remains. Asked by @jmartinm

*How*
TODO

**Boxed design of facet filtering**
- Have an alternative design for the Query Filters Widget which displays each facet value filter as a box which can be deleted. The resulting widget displays these boxes as an horizontal list. Asked by @lnielsen 

*How*
By overriding the jinja block `search_query_filters`, creating a new FlightJS component and overriding the main jinja block `javascript` where the FlightJS component will be attached to the new html element.

**Facet Menu with exclusion**
- Another design where facet values can be either included or excluded, not just included.

*How*
TODO: we need a design for this.

Related Issues
--------------------

**Comment by aw-bib** [comment]
Cc: @join2/librarians

**Comment by jirikuncar** [comment]
Follow Invenio-Search-JS for latest development.
