### ISSUE TITLE
WebSearch: accelerate nearest terms display for not-found phrases

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#3424]
Observed with @Kennethhole on some @TIND sites.

Searching for a Boolean query that does not find anything (say `first meeting at foo and bar`) is usually fast. (~0.1 seconds)

Searching for phrase query (`"first meeting at foo and bar"`) can be however very slow, e.g. ~0.1 seconds in collection index, ~5 seconds in title index, ~15 in global index.  (depending on the number of terms each given index has)

There is a solution: the admin can switch off the display of nearest terms altogether by setting `CFG_WEBSEARCH_DISPLAY_NEAREST_TERMS` to 0.

However, if the site needs to display nearest terms for the end users, then this facility must be speeded up:

- profiling (`search?p=...&verbose=9&profile=t`) shows that the bottleneck is `get_nearest_terms_in_idxphrase()`
- a possible solution is to dispatch user to `get_nearest_terms_in_bibwords()` if the index length is greater than ~50,000 terms  
  - the sweet spot should be find and made configurable via a new CFG variable  
  - the `get_nearest_terms_in_idxphrase()` query could first check the number of rows of e.g. `idxPHRASE08F` table and if the rows are less than ~50,000 then go for it, otherwise dispatch to `get_nearest_terms_in_bibwords()`.

@audub Can you please take care of this?

**Comment by audub** [comment]
Yes, we will look at it. Not sure that browsing words is much help for the user when searching for phrases though? I will discuss a bit more with @Kennethhole what we think is the best solution.

**Comment by audub** [comment]
I never followed up on this, but to inform others we ended up disabling the feature in config for the specific instance. It is how it is on cds afaik.

**Comment by tiborsimko** [comment]
OK, I'll close this issue then.
