### ISSUE TITLE
es: wildcard support

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3435]
Currently, our typeahead fields use [the wildcard notation](https://github.com/inspirehep/inspire-next/blob/master/inspire/modules/deposit/static/js/deposit/affiliations_typeahead.js#L33) in order to find a substring match in a given field.

While trying to replicate the behaviour with ES I have come to the same problem as http://stackoverflow.com/questions/23243867/elasticsearch-find-substring-match which can be solved by using [wildcard queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html).

The current query parser, with a query like `*SLAC*` will send the following to ES:

```
u'query': {'bool': 
  {'must': [{'multi_match': {'query': u'*SLAC*', 'fields': ['experimentautocomplete']}},
  {'term': {u'_collections': u'Experiments'}}]}}
```

I don't think the query parser is able at the moment to recognize wildcards? This should be added to https://github.com/inveniosoftware/invenio-query-parser/ and to Invenio's ES walker.

**Comment by jmartinm** [comment]
Actually the same can be achieved by using `regexp` - https://www.elastic.co/guide/en/elasticsearch/guide/current/_wildcard_and_regexp_queries.html

So for my use case I see that doing a query like ``/.*SLAC.*/`` will generate:

```
u'query': {'bool':
  {'must': [{'regexp': {'experiment_name': u'.*BNL-E.*'}},
  {'term': {u'_collections': u'Experiments'}}]}}
```

which is doing the right thing :)

If we want to simplify and not add another type of query (wildcard) I will close this issue

**Comment by jirikuncar** [comment]
Please fix the Elastic search visitor - https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/search/walkers/elasticsearch.py#L135-L147

--
cc @nharraud

**Comment by jirikuncar** [comment]
Fixed in Invenio-Query-Parser https://github.com/inveniosoftware/invenio-query-parser/blob/master/invenio_query_parser/contrib/elasticsearch/walkers/dsl.py#L106-L115.
