### ISSUE TITLE
Pages: Multi-language support

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/invenio#3446]
We need the pages module to be multi-language, where one URL shows content based on selected language, or redirects to the corresponding URL (i.e. [en] https://demo.tind.io/terms -> [de] https://demo.tind.io/bedingungen)

Is there any work being done on this, or have you discussed it?

**Comment by lnielsen** [comment]
Can you open this issue on inveniosoftware/invenio-pages instead.

**Comment by blixhavn** [comment]
Ah of course
