### ISSUE TITLE
es: ElasticSearch integration improvements

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3448]
In the current ElasticSearch integration we have 1 index called `records` and inside a document type called `record`. In order to be production ready, these are some changes that can be introduced:

* [ ] Allow separating document types in different indexes. This will make our integration [ES 2.0 ready and avoid conflicts in mappings](https://www.elastic.co/blog/great-mapping-refactoring) between different document types.

* [ ] Use aliases on top of indexes for zero downtime (https://www.elastic.co/guide/en/elasticsearch/guide/current/index-aliases.html).

* [ ] Allow each overlay to have its own mappings. Currently, the mapping is [hardcoded is `es.py`](https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/es.py)
    * We can have a registry of mappings as JSON files and map (based on name?) index -> mapping

**Comment by jirikuncar** [comment]
> Allow each overlay to have its own mappings.

We can start simply with a path to a `json` file or you can create a registry (what about merging/conflicts in mappings?).

**Comment by tiborsimko** [comment]
Note that @nharraud and @Letreguilly were looking exactly at the configuration of Elasticsearch mappings, using among other things the field aliases and extensible Jinja templates to allow each overlay to customise the mappings easily.  @Letreguilly has an example code already.

**Comment by jmartinm** [comment]
> Note that @nharraud and @Letreguilly were looking exactly at the configuration of Elasticsearch mappings, using among other things the field aliases and extensible Jinja templates to allow each overlay to customise the mappings easily. @Letreguilly has an example code already.

I did not see anything on Github. Can you create a WIP PR so that we can synchronize? I have a working branch and will create a PR now in order to use different ES indices. We can continue the discussion here.

**Comment by jmartinm** [comment]
The PR https://github.com/inveniosoftware/invenio/pull/3450 addresses using different indexes for different collections.

That would allow us, for example, to have the following configuration on INSPIRE https://github.com/inspirehep/inspire-next/pull/305

Please, review and comment on those PRs

**Comment by lnielsen** [comment]
Invenio-Search is now implementing all of above.
