### ISSUE TITLE
indexer: create manage hooks

### ISSUE THREAD

**Issue by eamonnmag** [inveniosoftware/invenio#3453]
So that we can say for example:

```
inveniomanage createindex create
inveniomanage reindex recreate
```

After speaking with @jmartinm, it would also be useful to recreate only specific indexes (as in collections), so 

```
inveniomanage index createindex publications
inveniomanage index reindex publications
```

Django haystack has a nice set of commands, using this as a template would be nice - http://django-haystack.readthedocs.org/en/latest/management_commands.html

**Comment by jirikuncar** [comment]
@eamonnmag @jmartinm shall it be part of `invenio-search`?

```
$ inveniomanage search index create <name>
$ inveniomanage search index recreate <name>
```

Is there any existing elasticsearch command-line tool?

**Comment by eamonnmag** [comment]
I think that makes sense to put it there, at least for me.
