### ISSUE TITLE
accounts: create manage hooks

### ISSUE THREAD

**Issue by eamonnmag** [inveniosoftware/invenio#3454]
So that we can create users for example for inveniomanage, e.g.

```
inveniomanage user createsuperuser --u eamonn --p mypassword --e eamonn@helloworld.com
inveniomanage user createuser --u eamonn --p mypassword --e eamonn@helloworld.com
```

**Comment by jirikuncar** [comment]
@eamonnmag yes. please re-open using https://github.com/inveniosoftware/invenio-accounts/issues/new

**Comment by eamonnmag** [comment]
Ah ok, sorry @jirikuncar, didn't see that!
