### ISSUE TITLE
RFC plotextractor utilities

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3482]
The module `invenio-oaiharvester` is the only one that use `invenio.utils.plotextractor`.
In the [roadmap](https://github.com/inveniosoftware/invenio/issues/3233) for legacy removal  these utilities are in the list.
What's the plan?
 1) Do we move the utilities inside `invenio-oaiharvester`?
 2) Do we remove from the #3233 list and leave inside invenio?
 3) Do we move into a separete package?
 4) .....

**Comment by jalavik** [comment]
Thanks for bringing this up @hachreak.

In it's present form the outer layers are quite specific to arXiv.org, however, probably the core pieces could be made generic (e.g. the idea of matching image references (with captions etc.) from TeX with local image files from an archive).

From that we could imagine an external package (after some modifications). The less preferred alternative would be to leave it as is in a submodule inside the INSPIRE overlay. I do not think it belongs inside `invenio-oaiharvester` and frankly I was leaning towards removing the `tasks/arxiv.py` file from `invenio-oaiharvester` as we migrate them to our INSPIRE overlay. 

In any case, the INSPIRE team can take care of this as we are the only clients and maintainers AFAIK.

**Comment by hachreak** [comment]
Currently:
- the `plotextractor` is broken because it use the legacy `search_engine`.
- but, the `search_engine` is broken because load [invenio_search.searchext.engines](https://github.com/inveniosoftware/invenio-search/tree/master/invenio_search/searchext/engines).native that actually doesn't exists. 

Can we easily create fix the problems in some way? Any idea?
Because most of the test errors on master is correlated with these [search_engine code](https://github.com/inveniosoftware/invenio/blob/master/invenio/legacy/search_engine/__init__.py#L80) lines.

@jirikuncar @jalavik

**Comment by jalavik** [comment]
@hachreak I guess we are going to anyway remove plotextractor from Invenio? But if you want to keep it here then take a look at our fix on INSPIRE labs-rc branch: https://github.com/inspirehep/invenio/commit/7e85701269ab41f353dfa7d24c4525377ef87a83

**Comment by kaplun** [comment]
@inspirehep/INSPIRE-DEV

**Comment by jalavik** [comment]
So I'll try to take the core out of plotextractor to https://github.com/inspirehep/plotextractor which just gets an input (path to tarball), and returns a JSON-like (list of dicts) of extracted captions and path to files. E.g. option (3). 

If that is okay we can close this RFC. @jirikuncar @hachreak 

PS: Feel free to remove the module from Invenio as `invenio-oaiharvester` no longer depends on it.
