### ISSUE TITLE
Improve 404 propagation to Sentry

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#3498]
Currently any 404 raised by at least the `legacy` extension, are propagated to Sentry (when enabled). This is suboptimal, as any wrong URL typed by any user or bot is causing an exception to be recorded.

It would be beneficial to just store those 404 caused by a request having a referer from the current site. At least this would be useful to spot broken links and in which pages they are contained.

**Comment by tiborsimko** [comment]
Live discussion: happens with `master` on INSPIRE LABS.

**Comment by kaplun** [comment]
Closing since legacy handler no longer exists on master
