### ISSUE TITLE
BibEdit: import data with crossref

### ISSUE THREAD

**Issue by chokribr** [inveniosoftware/invenio#3503]
I try to import data from crossref  but always i've got  this error "This is not a correct DOI, please correct it "

Note : by entring this URL in the Browser http://www.crossref.org/openurl/?pid=USERNAME&noredirect=tru&id=doi:10.1021/acsnano.5b02466 
i've got an XML record
i'm using Invenio v1.2.1

**Comment by kaplun** [comment]
Dear @chokribr what exactly are you typing as string in BibEdit? Note that the field accept only a plain doi such as: "10.1021/acsnano.5b02466", without further prefix. If e.g. I type "doi:10.1021/acsnano.5b02466" then I obtain exactly your same error.

**Comment by chokribr** [comment]
@kaplun @ludmilamarian
 ![doi](https://cloud.githubusercontent.com/assets/2951014/9872405/7e6a08ba-5b99-11e5-9c87-fd8c796a7b0f.png)

**Comment by chokribr** [comment]
@kaplun @ludmilamarian @jirikuncar i Think that the problem with password i'm using crossref openurl without password by testing the existance ":" + CFG_CROSSREF_PASSWORD variable and adding ":"  i've got the record https://github.com/inveniosoftware/invenio/blob/legacy/modules/miscutil/lib/crossrefutils.py#L69
![acs](https://cloud.githubusercontent.com/assets/2951014/9960945/090db0a8-5e1e-11e5-9d19-e28be18754c7.png)

**Comment by kaplun** [comment]
@chokribr you mean without password it works? Could then be a problem of encoding the URL of the request BibEdit does to crossref...

**Comment by kaplun** [comment]
@chokribr can you check if the patch in #3516 solves your issue?

**Comment by chokribr** [comment]
@kaplun the problem is with ":" 
#3516 http://www.doi.org/factsheets/DOIProxy.html

**Comment by kaplun** [comment]
Good point

**Comment by chokribr** [comment]
@kaplun i try this https://github.com/chokribr/invenio/commit/45f78bb6de207712a2ecdaae0f0505bddfa69145 
and it work

**Comment by kaplun** [comment]
@chokribr I think we should merge our two solutions, because both proper encoding of the request and support for accounts without password are both needed.

**Comment by chokribr** [comment]
many thanks sam @kaplun congrat  it's a pleasure to find solution with you
