### ISSUE TITLE
WIP: OAI-PMH server

### ISSUE THREAD

**Issue by Dziolas** [inveniosoftware/invenio#3534]
I'm working on OAI-PMH module for new Invenio. Currently I have implemented most of the protocol (v.2.0) and I will soon start connecting it to Invneio - I made it stand-alone for simplicity. 

After speaking with @lnielsen I know that the key elements from his point of view are:
- smart way of creating OAI sets
- OAuth autentication and sets restriction

I will implement new user interfaces for creating sets and managing access by OAuth. 
Currently in SCOAP3 we are using authentication were keys are generated by Invenio, I will try to make OAuth authentication backward compatible so my users can still use the same keys.

Do you have any other needs or recommendations?

**Comment by aw-bib** [comment]
There is a requirement for OA repos (DINI) to expose a large number of sets based on ddc classification of the content. Currently, this will result in a large number of set definitions and probably record updates. Probably, on could tackle this in a better way. @skaplun had some idea when he recently checked out BASE / Bielefekd repos.

**Comment by kaplun** [comment]
Yes, in Base they have implemented this dynamic set functionality which is basically making OAI-PMH super useful:
http://oai.base-search.net/index.html#dynamic-sets

That would cause sets to be created on the fly for the time of the request.

In fact we consider sets as simple queries over the set of records. We can think of pre-creating them but this could simply becoming nothing more than adding an alias and a description to a search query and exposing through `?verb=ListSets`.

The only tricky thing is what to do with records that are deleted, or that are moving in and out of a defined query.

But maybe, too bad for that functionality of OAI-PMH. One can always re-harvest a given set to have exactly the list of corresponding current records.

**Comment by Dziolas** [comment]
We can support both types of sets. Some can be classic OAI sets following standard and we can add the ad hoc setts as an extension.

**Comment by lnielsen** [comment]
Agreed - Dynamic sets looks like a very nice way to support very large number of sets (and allows anyone to harvest exactly what they like).

**Comment by aw-bib** [comment]
> One can always re-harvest a given set to have exactly the list of corresponding current records.

Be careful with that as a general solution. As a repo I have no way to drop a note to OpenAIRE or BASE that they should reharvest `foo` and `bar` but not `X` and `Y`.

So I think @Dziolas point of having both should be there to keep those services happy. (Thinking of sets like `open_access`, `ec_funded_ressources` etc. from DINI/DRIVER/OpenAIRE and whatnot guidelines.)

OTOH a dynamic set would be superuseful for this IMHO strange requirement from DINI to offer some 100 sets based on DDC for whatever use case this has.

**Comment by kaplun** [comment]
Yes yes, dynamic set were not meant as the only available sets. But even with static sets the question remains: in order to properly expose the fact that a record now entered a set (e.g. because the set definition has been amended) or it leaves it, we have to either:
* don't care about it
* keep track of all the timestamps of all the `N` records `x` `M` sets defined.

In Invenio legacy this was done by directly store the set information in the metadata, but we might want to:
* no longer do it
* move it to a dedicated Model that would implement such matrix and that a new daemon would keep up-to-date.

**Comment by aw-bib** [comment]
> In Invenio legacy this was done by directly store the set information in the metadata

Is this per see such a bad idea for the non-dynamic sets? For something more static, this ID e.g. can come in quite handy for dupe detection. (I think there was even an issue related.)

**Comment by kaplun** [comment]
I was referring not about the ID but the set information (what was going into $p - current sets,  and $q - previous sets).

**Comment by tiborsimko** [comment]
CC-ing @jirikuncar as per recent [Sprint-OAIServer](https://github.com/issues?q=user:inveniosoftware+milestone:Sprint-OAIServer)

**Comment by jirikuncar** [comment]
Dynamic sets are not part of OAI-PMH 2.0 standard hence we haven't implemented. If some is interested in having `listRecords` like output he can use the serializer and plug it as new output format to Invenio-Records-REST with full OAuth2 support.
