### ISSUE TITLE
Detailed record does not show report numbers

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#355]
Originally by *hoc* on 2010-11-16

As an example:
http://inspirebeta.net/record/873011?ln=en

here is the SPIRES record:

Accelerator and Target Technology for Accelerator Driven Transmutation and Energy Production.
By H. Aït Abderrahim (SCK-CEN, Mol), et al. 
FERMILAB-FN-0907-DI, LA-UR-10-06754,
Sep 17, 2010. 23pp.

**Comment by jirikuncar** [comment]
@kaplun It looks like INSPIRE related. Please close it if nothing has to be done on Invenio site.
