### ISSUE TITLE
inveniogc: missing recurse parameter for dir deletions

### ISSUE THREAD

**Issue by aw-bib** [inveniosoftware/invenio#3556]
The following rules in `inveniogc.py` miss out the fact that they actually find a directory and not a file. Thus they have to use `-rf` for deletion and not only `-f`:
- websubmit_icon_creator_*
- websubmit_file_stamper_*

This should affect `maint-1.1` and `maint-1.2` and can amount to quite some space used depending on the input files.

**Comment by tiborsimko** [comment]
Closed by #3716.
