### ISSUE TITLE
installation: add marc21 package

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#3596]
When `invenio-marc21` package is ready, add it to the demo site.

- [x] JSON schema for MARC21 bibliographic
- [x] JSON schema for MARC21 authority
- [x] Elasticsearch mapping for MARC21 bibliographic
- [x] Elasticsearch mapping for MARC21 authority
- [x] Nice record templates for MARC21 bibliographic
- [ ] Nice record templates for MARC21 authority

See also  https://github.com/inveniosoftware/dojson/issues/80#issuecomment-186213628

**Comment by switowski** [comment]
JSON schema for MARC21 bibliographic requires: https://github.com/inveniosoftware/dojson/issues/84
Elasticsearch mapping for MARC21 authority: we should be able to generate them now (to be checked/tested)
Nice record templates for MARC21 bibliographic - already created by @hachreak in https://github.com/inveniosoftware/invenio-marc21/pull/8

**Comment by tiborsimko** [comment]
The package was added by 561cc903, the templates will be prettified via https://github.com/issues?q=user%3Ainveniosoftware+milestone%3AI3B-Search.
