### ISSUE TITLE
installation: add indexing and searching

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#3597]
Now that [search sprint basics](https://github.com/issues?q=user:inveniosoftware+milestone:Sprint-Search-Basics) is over, add `invenio-indexer`, `invenio-search`, `invenio-search-ui` to the demo site.

**Comment by switowski** [comment]
Related with #3598

**Comment by hachreak** [comment]
@tiborsimko #3606 is merged, I think we can close this issue.

**Comment by jirikuncar** [comment]
Closed via #3606
