### ISSUE TITLE
installation: add demo front page

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#3598]
When a demo site is created, there is no front page, which is ugly. Within the "nice defaults" sprint philosophy, when we create an instance, we should generate *some* front page:

- e.g. similar to Google home page style, as we do in https://analysis-preservation.cern.ch/

- e.g. list past public records, as we do for Zenodo

and each instance can customise it if they want. 

See also https://github.com/inveniosoftware/invenio-base/issues/37 

Pre-requisites: https://github.com/inveniosoftware/invenio/issues/3597

**Comment by switowski** [comment]
This is something that @hachreak is currently working on.
We were thinking about a very simple page with search bar (as in the analysis-preservation) and when you click `search`, you get the list of records in `brief` format.
We wanted to make it a part of marc21 package (otherwise, as you said, marc21 won't have a front page).

**Comment by hachreak** [comment]
I was working to create an example search page with angularjs as mentioned by @tiborsimko (like google).
Maybe we can use it in demo site and leave only a more basic example of search on `invenio-marc21`.
WDYT @switowski

**Comment by switowski** [comment]
:+1: I agree, invenio might be a better place to tie various modules together (records and search interface) than marc21.

**Comment by tiborsimko** [comment]
> otherwise, as you said, marc21 won't have a front page

`invenio-marc21` does not have to have a front page, only to provide MARC21 related things (schemas, mappings, brief templates, detailed templates). 

We may have different packages for other "master formats" soon; imagine `invenio-ead`, `invenio-tei`, etc.  The people will then be able to do things like:

```
$ pip install invenio[marc21,ead,ils,multimedia]
```

to get a site that is ready to host MARC21 records, EAD records, and has support for Integrated Library System features (e.g. holdings) and for Multimedia features (e.g. IIIF).

The integration is indeed done on the `invenio` repository level, see musings in #3597 and https://github.com/inveniosoftware/dojson/issues/80#issuecomment-186213628

**Comment by hachreak** [comment]
1. should we remove the `/` page from invenio-marc21 views? (see https://github.com/inveniosoftware/invenio-marc21/blob/master/invenio_marc21/views.py#L43 )
2. where should be implemented the "default" homepage? here in `invenio` module?

**Comment by jirikuncar** [comment]
> 1. should we remove the / page from invenio-marc21 views?

Definitely YES.

> 2. where should be implemented the "default" homepage? here in invenio module?

Invenio-Base should have a question for default `/` endpoint during `instance create` process.

**Comment by jirikuncar** [comment]
Closed via inveniosoftware/invenio-base#58
