### ISSUE TITLE
Number of results show in XML-ish formats

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#363]
Originally on 2010-11-24

Many users need to create CVs and export their publication lists to bibliographic management software like EndNote or BibTeX.

These users are usually downloading far more than 25 records, so the limit should be increased dramatically for these sorts of downloads.  

At the very least some sort of notice should be given (rather than the comment at the top of EndNote which implies that the full result set is given:
http://inspirebeta.net/search?ln=en&p=dorfan%2C+j&f=&action_search=Search&sf=&so=d&rm=&rg=25&sc=0&of=xe

Which is above a file of 25 records...

**Comment by kaplun** [comment]
No energy left to bring this work back to legacy.
