### ISSUE TITLE
invenio_connector: fix broken upload_marcxml()

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#364]
Originally on 2010-11-25

`invenio_connector.py` permits to call batch uploader robot interface, but the functionality is apparently broken.  Should be investigated, fixed, and enriched with a test case.

**Comment by jirikuncar** [comment]
Functionality has been moved to [Invenio-Client](https://github.com/inveniosoftware/invenio-client/blob/master/invenio_client/connector.py) package. Please re-open the issue there.

**Comment by tiborsimko** [comment]
(No need to reopen there, this was tackled otherwise in the meantime.)
