### ISSUE TITLE
RFC Python 2.7 and 3.5 only?

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#3647]
For Invenio 3, we are supporting and testing four Python versions:

- 2.7
- 3.3
- 3.4
- 3.5

Proposal: what about retaining only two:

- 2.7
- 3.5

This will speed up our Travis CI builds and simplifies our life regarding Python dependencies that may not be 3.3 compliant anymore.   Moreover, the major operating systems have nowadays Python 3.5 packages already available, so there should be no need to support older ones...   

WDYT?

CC @inveniosoftware/triagers  

(stemmed from https://github.com/inveniosoftware/invenio-files-rest/pull/74#issuecomment-229317431)

**Comment by lnielsen** [comment]
Is this for RFC for what we test or what we support? (not sure if it makes sense to separate them)

I'm happy to cut out 3.3 + 3.4 from the tests, but I would say that for Python support we should likely support latest 2.7 + 3.x + 3.(x-1) - i.e. 2.7, 3.4, 3.5 and when 3.6 is released we support 2.7, 3.5, 3.6/

E.g. CC7 currently only have Python 3.4. Python 3.4 was released March 2014 which means we'll only be supporting releases which are up to roughly 2 years old.

On the other site, we might want to actively go towards dropping Python 2.7 support - it will make unicode-life a lot easier :-) Right now I think it's primarily xrootd python bindings which are blocking us.

**Comment by kaplun** [comment]
Please do not hurry up in dropping 2.7 :-) It's battle-tested. In INSPIRE we have `beard` that currently depends on Python 2.7 libraries for which there is not yet a 3.x counterpart (at the moment though beard is wrapped into a separate micro-service, so we don't depend on it, but just in case).

**Comment by tiborsimko** [comment]
> Is this for RFC for what we test or what we support? 

"supporting and testing" -- I was indeed looking at removing 3.3 and 3.4 also from Trove classifiers.  If we claim to support some Python version, then we'd better also be testing it.

> E.g. CC7 currently only have Python 3.4. 

... but its default Python version is 2.7.  Hence I thought that my proposal of supporting 2.7 and 3.5 may be enough.

- E.g. Ubuntu 14.04 LTS is Python 2.7 and 3.4. (Supported until mid 2019.)

- E.g. latest Ubuntu 16.04 LTS is Python 2.7 and 3.5.  

Covering 2.7 and 3.5 would seem the safest, provided that e.g. services on Ubuntu14 or CentOS7 stick to their Python 2 defaults.  If they would like to move to Python 3, then it would be nice to have Python 3.4 supported for some years to come indeed...but a reply "please stick to default 2.7 or else use Docker" would seem acceptable to me from the Invenio project point of view.   

> dropping Python 2.7 support [...] Right now I think it's primarily xrootd python bindings which are blocking us.

Indeed, dropping 2.7 and retaining 3.4 would be another interesting alternative...I'm afraid it may be perhaps a bit premature though. Any "guesstimate" about xrootd and Python 3?

P.S. We could also retain supporting 2.7, 3.4, 3.5, going for the less radical cut.  Although if we do keep supporting 2.7 for some years to come, then supporting 3.4 seems somewhat unnecessary to me...

**Comment by tiborsimko** [comment]
> In INSPIRE we have beard that currently depends on Python 2.7 libraries for which there is not yet a 3.x counterpart

The same question here: Do you have any "guesstimate" about when these libraries might start working on Python 3?

**Comment by lnielsen** [comment]
> Covering 2.7 and 3.5 would seem the safest, provided that e.g. services on Ubuntu14 or CentOS7 stick to their Python 2 defaults. If they would like to move to Python 3, then it would be nice to have Python 3.4 supported for some years to come indeed...but a reply "please stick to default 2.7 or else use Docker" would seem acceptable to me from the Invenio project point of view.

👍 Let's go for Python 2.7 and 3.5 for now then. However I would strongly advocate that in the same breath we also take a decision to work towards dropping Python 2.7 support all together. This doesn't mean drop it immediately - just that we know it is coming, and that we actively work towards making it happening - e.g. for me it would mean working with the EOS guys to help them migrate the xrootd bindings to python 3.

**Comment by kaplun** [comment]
Actually I just checked and the above library looks abandoned. However I just discovered ES has native support for phonetics algorithms, so we no longer have an issue here. :dancer:

**Comment by switowski** [comment]
CDS is also using `beard`. I don't care that much for 2.7 support (as long as we have some dependencies working only in Python 2.7 I guess it's easier to keep them for now), but I agree that keeping too many Python 3.x is unnecessary. If CC7 has Python 3.4, maybe it's easier to stick to this version for now (unless someone is really multiplying those matrices in his Invenio installation :wink: ).
Updating from 3.4 shouldn't be that much of a hassle.
What about we keep version 3.4 (or 3.5) in travis build (as the Python version that is recommended by Invenio) + the latest Python 3.x version to see if everything still works (Python 3.5 for now and 3.6 when it's released) ?

**Comment by tiborsimko** [comment]
@switowski Yes, that would be going for that less radical solution I mentioned above. ("We could also retain supporting 2.7, 3.4, 3.5, going for the less radical cut.")

**Comment by tiborsimko** [comment]
OK, let's go for 2.7 and 3.5 for the time being, and depending on the longevity of 2.7 support, we can recheck the question later.
