### ISSUE TITLE
RFC Flask 0.11 only?

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#3649]
After several Flask 0.11 Flask-CLI 0.4 related updates in our various core packages, it seems like an advantageous time to increase the minimal Flask version requirement to 0.11 and stop supporting 0.10.  This could attacked as part of the Invenio 3 Beta API cleaning sprint.

Does anyone need Flask 0.10 on running services?

CC @inveniosoftware/triagers

**Comment by jmartinm** [comment]
👍  Not us, so sounds good.

**Comment by jirikuncar** [comment]
We seem to agree about:

- [ ] firing batch update for all our repositories
- [ ] removing Flask-CLI
- [ ] Flask>=0.11

**Comment by nharraud** [comment]
@jirikuncar what do you mean by batch update?

**Comment by tiborsimko** [comment]
@nharraud It means that this will come as part of another multi-repository multi-PR campaign batch, similar to the past ones, e.g. this one was updating `inveniosoftware.org` canonical address everywhere:

- https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Atiborsimko+is%3Aclosed+global+inveniosoftware.org

For more, see this discussion thread:

- https://github.com/inveniosoftware/invenio-files-rest/pull/74#issuecomment-229197821

that gave birth to this RFC and the others #3647 #3650.

(Basically, Invenio 3 beta release oriented cleanup under way)
