### ISSUE TITLE
RFC Support for PyPy on Invenio 3

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio#3663]
**Proposal:**
Add PyPy to matrix on Travis.

**Question:**
Do we require tests to pass always or shall we allow fails with PyPy?

```
matrix:
  allow_failures:
    - python: pypy
```

**Examples:**
- https://github.com/inveniosoftware/invenio-config/pull/12

--
- cc @inveniosoftware/triagers 
- see also previous discussion on testing Python 3.3 and 3.4 in #3647

**Comment by switowski** [comment]
What is the benefit of supporting the PyPy and how difficult it is to achieve that ?
Even though I like the idea to add it to the test matrix (it would be cool to show that Invenio 3 supports PyPy) and see if it will work out of the box, if there is little benefit (if no one wants to actually use Invenio 3 with PyPy), maybe we shouldn't do this, as our tests will run slower ?

**Comment by nharraud** [comment]
For sure it would be great to support it. But as said @switowski, who will use it?
We already have problems releasing (especially on Friday evenings) when Travis takes hours to schedule tests. If no one asks for it now, maybe we could add this support later, like after the Invenio 3 release?

**Comment by jirikuncar** [comment]
It is nice to discover problems in your code just running it on different platforms. It might have some benefits for CPU/memory bounded applications. It looks like it is not such a pain like in the past. `lxml` and other big libraries already support PyPy and even if there is no immediate benefit it looks good for long term.

Are we sure that no one wants to use Invenio 3 with PyPy? What about our small packages like DoJSON, or Flask extensions?

**Comment by egabancho** [comment]
> Are we sure that no one wants to use Invenio 3 with PyPy? What about our small packages like DoJSON, or Flask extensions?

Does it make sense to decide depending on the package? 
I could imagine there might be someone interested on the "general purpose" package as @jirikuncar mentioned, but for the "true" Invenio ones I tend to think that I will add to much overhead to the test runs

**Comment by tiborsimko** [comment]
As long as we treat it with 'allow_failures`, then it would to be a good forward-looking idea.  We could start with a few typical "standalone" packages, and in the meantime check whether our core dependencies are PyPy-ready... and if not, they may be after Invenio 3.0.0b1 is out.

**Comment by lnielsen** [comment]
+1 for testing PyPy support for general purpose packages - and for Invenio-... packages with ``allow_failures`` on.

Also +1 for scheduling this after ``3.0.0b1`` - i.e. it's a nice-to-have, not a must-have.

**Comment by tiborsimko** [comment]
We seem to have general agreement, so I'm closing this RFC. 

One additional comment from my side would be to add the advertising PyPy  classifier to `setup.py` only when the CI tests for PyPy are passing. (At least for *some* class of use cases, e.g. when SQLlite backend is OK, while PostgreSQL backend is still not fully working.)
