### ISSUE TITLE
docs: link to LICENSE is broken

### ISSUE THREAD

**Issue by RaoOfPhysics** [inveniosoftware/invenio#3682]
It looks like the LICENSE file got deleted at some point and the link from the README is broken (https://github.com/inveniosoftware/invenio/blob/master/LICENSE).

**Comment by lnielsen** [comment]
Where do you find the link?

The license is in COPYING file: https://github.com/inveniosoftware/invenio/blob/master/COPYING

**Comment by jirikuncar** [comment]
The license badge in `README.rst` is should point to https://github.com/inveniosoftware/invenio/blob/master/COPYING.

**Comment by RaoOfPhysics** [comment]
Can take care of this. Any reason it links to COPYING rather than LICENSE? I think GitHub indexes projects and their licences based on the presence of the latter file: https://help.github.com/articles/open-source-licensing/ But I might be wrong…

Let me know whether I should change the README to point to COPYING or if I should rename the file.

Thanks.

**Comment by jirikuncar** [comment]
@RaoOfPhysics let's just change the link in the README so we have the license at the same place for all Invenio versions.

**Comment by lnielsen** [comment]
> Any reason it links to COPYING rather than LICENSE?

History - it's always been there, since the [guidlines on how to use GPL](https://www.gnu.org/licenses/gpl-howto.en.html) says "You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs the license is usually in a file called COPYING."

I think github should be able to detect the license correctly when it is in copying.

**Comment by lnielsen** [comment]
Just checked - github nicely detects the license file:

https://api.github.com/repos/inveniosoftware/invenio/license

**Comment by RaoOfPhysics** [comment]
On it.

**Comment by jirikuncar** [comment]
@RaoOfPhysics you can assign it to yourself and change status to "in work".

**Comment by RaoOfPhysics** [comment]
@jirikuncar: I'm not part of the organisation.

**Comment by jirikuncar** [comment]
@RaoOfPhysics hups. I'll do :)

**Comment by RaoOfPhysics** [comment]
Can be moved to `In Review` now, I guess. Also, Waffle doesn't seem to have updated the issue to the correct column: I still see it under `Ready`.

**Comment by jirikuncar** [comment]
@RaoOfPhysics Waffle moves it automatically only if you push branch to upstream with name e.g. `3682-license`.
