### ISSUE TITLE
Changing format takes you back to the beginning

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#369]
Originally on 2010-12-02

When navigating a longer search result, changing format takes you back to the beginning. In other words:

user does search -> gets 100 results -> uses next or jump to to get to record 91-100  -> changes format in format selector to, say, MARCXML -> gets record 1-10 

This makes it _very_ difficult to assemble a large search result output in a non-html format.   Especially since one can't see that these are records 1-10.   

I think the most intuitive thing would be for the format selector to redisplay exactly those records that are shown in the current view, not start over from the beginning.   

Note that this is tied to #363 about showing more information in XML-ish formats

**Comment by jirikuncar** [comment]
This has been fixed in `2.0.0`.
