### ISSUE TITLE
Typo in .gitignore file

### ISSUE THREAD

**Issue by PaulinaLach** [inveniosoftware/invenio#3747]
I found an small typo in `.gitignore`, which seems to be propagated across a lot of invenio modules: [typo](https://github.com/inveniosoftware/invenio/blob/master/.gitignore#L44)

**Comment by lnielsen** [comment]
Actually it's not a typo - see explanation https://github.com/github/gitignore/commit/ba6f0a94abe2c802caba33b42da1e6a36e40f526
