### ISSUE TITLE
Clean-css installation problem

### ISSUE THREAD

**Issue by tobiasfrust** [inveniosoftware/invenio#3748]
Hello,

I was trying to install Invenio3 using the Docker-method. I encountered the following problem. During `docker-compose build` an error occured with clean-css. The same applies when entering the homepage after a fresh install, you only get an internal server error.

The problem is caused by a major upgrade of clean-css to version 4 with major changes. It can be solved by editing line 139 in provision_web.sh:
`$sudo su -c "npm install -g node-sass@3.8.0 clean-css@3.4.24 requirejs uglify-js"`

I just wanted to let you know my investigations.

Best regards,

Tobias

**Comment by suso2** [comment]
Thank you very much!!!!
Now it works like a charm.
Only one question, what modules do you suggest for doing Invenio 3 similar to invenio 1.x?

Thanks again

**Comment by jirikuncar** [comment]
We should probably install `clean-css-cli` - see https://www.npmjs.com/package/clean-css#important-40-breaking-changes

**Comment by hachreak** [comment]
@jirikuncar I tried [6 days ago](https://github.com/CERNDocumentServer/cds/issues/390) and I had some problems with `webassets`.

**Comment by jirikuncar** [comment]
We should solve it in `webassets` (just created https://github.com/miracle2k/webassets/issues/485)

**Comment by lnielsen** [comment]
Invenio-Assets 1.0.0b5 should solve the problem by supporting both v3 and v4.

**Comment by tiborsimko** [comment]
In order not to wait for upstream `webassets` release, we went for `clean-css` pinning.

All the installation issues have been fixed yesterday for all of Docker, Ubuntu14, CentOS7 supported platforms. Please just use the latest master branch:

```console
$ git clone https://github.com/inveniosoftware/invenio
$ cd invenio/
$ docker-compose build
$ docker-compose up
$ docker-compose run --rm web ./scripts/populate-instance.sh
$ firefox http://127.0.0.1/records/1
```
