### ISSUE TITLE
./scripts/populate-instance.sh error messages

### ISSUE THREAD

**Issue by Quantentunnel** [inveniosoftware/invenio#3760]
Hi all!

Today it is the first time I try to install invenio by this installation guide: http://invenio.readthedocs.io/en/latest/installation/installation-detailed.html

I installed Centos 7 for this. For an automated unattended way i used the scripts. 

When I tried to execute this script ./scripts/populate-instance.sh , I got this error messages:

> ./scripts/populate-instance.sh: line 94: : No such file or directory
>./scripts/populate-instance.sh: line 97: workon: command not found
> ./scripts/populate-instance.sh: line 104: ip-xx-xx-xx-xx: command not found

However, I went on without fixing this issues because I did not know how. I tried to create a new instance (see chapter 2.2.9.1.) but for me it was not clear why this error message appers: 

> bash: mkvirtualenv: command not found

Do I have to open a phyton command line or something else? I have no experience in phyton. I think the installation instructions should be clearer and also understandable for newbies like me. And maybe it is possible to create a master script for single maschine installations which executes the other scripts in one go.

Thanks a lot and have a nice day!

**Comment by david-caro** [comment]
It looks to me that you are missing virtualenv and virtualenvwrapper, the first time you install virtualenvwrapper you might need to create a new bash session and/or reload the ~/.bashrc file, from the guide (http://invenio.readthedocs.io/en/latest/installation/installation-detailed.html#web):

```shell
    $ sudo pip install -U virtualenvwrapper setuptools pip
    if ! grep -q virtualenvwrapper ~/.bashrc; then
        mkdir -p "$HOME/.virtualenvs"
        echo "export WORKON_HOME=$HOME/.virtualenvs" >> "$HOME/.bashrc"
        echo "source $(which virtualenvwrapper.sh)" >> "$HOME/.bashrc"
    fi
    export WORKON_HOME=$HOME/.virtualenvs
    source "$(which virtualenvwrapper.sh)"
```

**Comment by Quantentunnel** [comment]
Thank you very, very much!

Because I used the scripts I didn´t had a closer look on what they did (or tried to do). Also the docu said: "Let’s see in detail what the web provisioning script does." For me it sounds that I don´t have do the following steps because the script does. 
However, after reading your post I had a closer on that steps and I found out that beside virtualenv and virtualenvwrapper also the Nginx web server were not installed. 
After all there are two error message left.

Error message 1 after running the populate-instance.sh-Script:
>  ./scripts/populate-instance.sh:  line 104: ip-xx-xx-xx-xx: command not found

Error message 2 in the ./scripts/create-instance.sh-Script:
>  #include <openssl/opensslv.h>
>                                 ^
>   compilation terminated.
>   error: command 'gcc' failed with exit status 1
> 
>   ----------------------------------------
>   Failed building wheel for cryptography
>   Running setup.py clean for cryptography
> Failed to build cryptography

> [...]                           
>     compilation terminated.
>     error: command 'gcc' failed with exit status 1
> 
>     ----------------------------------------
> Command "/root/.virtualenvs/localhost/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_JBa4N/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-X5KgHo-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/localhost/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-_JBa4N/cryptography/

GCC and openssl are installed.
Now I will try to install the system without using the scripts. Maybe they are not up to date and work not well with the current version of centOS. I don´t know, maybe thats the problem.

However, thank you very much again. My issue is not complety fixed but should we close this thread or might it be helpful if we keep it as an open issue?

**Comment by david-caro** [comment]
Glad to hear I could help, even if it was just a bit.
About the remainding errors, for the first one, it looks like an environment variable is wrong, empty or there's some 'template examples' not replaced somewhere. You can try running the script with 'bash -x /path/to/script' to get a more verbose output.

About the second, it seems like you are missing some headers for openssl, make sure that you have openssl-devel (and similar) packages installed, if that is the issue, it should be added to the docs imo.

About the docs themselves, there's an ongoing sprint on creating how-tos and docs for invenio right now. I'm not really involved, maybe one of the @inveniosoftware/admins want to comment on it.

**Comment by lnielsen** [comment]
Yep, we're writing up a complete set of tutorials for the upcoming [Invenio User Group Workshop](https://indico.cern.ch/event/557956/) (March 21-24). Also, we're trying to polish the initial experience with Invenio so that it becomes as easy as possible and you won't hit errors like the one above. We hope the tutorials hit the documentation in March/April. Stay tuned.

**Comment by Quantentunnel** [comment]
@david-caro Thanks! openssl-devel was also missing.

To sum up these packages were missing after using only the scripts (under CentOS 7.3):

- openssl-devel
- openssl
- gcc
- virtualenv (see post of @david-caro )
- virtualenvwrapper (see post of @david-caro )
- Nginx web server

I guess because of my tries / tests with the scripts I get this error message now when I try to execute the ./scripts/create-instance.sh-Script:

> cookiecutter.exceptions.OutputDirExistsException: Error: "ip-xx-xx-xx-xx" directory already exists.

Probably I should start with a fresh new install. However thank you very much for your help. Looking to the new documentation in March/April 2017. Hopefully the scripts are updated then, too. 
Last but not least: Thanks again!

**Comment by tiborsimko** [comment]
@Quantentunnel Some of the dependencies like `gcc` or `nginx` should have been installed for you by the provisioning scripts at the time...was there any error? Other dependencies like `openssl-devel` were indeed missing. Anyway we have fixed all the CentOS7 installation issues yesterday, so everything should be  working out of the box again.  Please just use the latest `master` branch:

```console
$ git clone https://github.com/inveniosoftware/invenio
$ cd invenio/
$ sed -i 's,ubuntu/trusty64,centos/7,g' Vagrantfile
$ vagrant up
$ vagrant ssh web -c 'source .inveniorc && /vagrant/scripts/create-instance.sh'
$ vagrant ssh web -c 'source .inveniorc && /vagrant/scripts/populate-instance.sh'
$ vagrant ssh web -c 'source .inveniorc && nohup /vagrant/scripts/start-instance.sh'
$ firefox http://192.168.50.10/records/1
```
