### ISSUE TITLE
empty database after install

### ISSUE THREAD

**Issue by heidricha** [inveniosoftware/invenio#3772]
The database looks like empty, Is there anywhere a create script I have to run by hand?

root@ef8eef3:/# psql -U invenio3 invenio3
psql (9.6.2)
Type "help" for help.

invenio3=# \dt
No relations found.

**Comment by lnielsen** [comment]
Did you run ``invenio db create``?

Note that for troubleshooting it might be faster to jump on our Gitter channel:
http://gitter.im/inveniosoftware/invenio

**Comment by heidricha** [comment]
Thanks!

I didn't.

'invenio3 db create'

makes login possible. I have found a few other lines about installation and support forums. (I'd expect to have a few hints about these in top level README though)

going on looking for a working server!

Thanks again!
