### ISSUE TITLE
Add a docker config for developpers

### ISSUE THREAD

**Issue by remileduc** [inveniosoftware/invenio#3802]
What?
------

In order to ease the integration of newcomers, we should have a fully working docker ready to develop.

The idea is to copy what have been done in https://github.com/cernopendata/opendata.cern.ch/blob/master/docker-compose-dev.yml with a specific docker-compose for developpers, with the necessary documentation.

This docker should:
- [x] run a demo site very easily (so it will be very close to the current `docker-compose.yml`
- [x] run invenio in debug mode (auto refresh...)
- [x] mount a dev folder so we can `pip install -e` any modules we want inside the containers, and thus work on a given module
- [ ] integrate a celery worker
- [x] install the debug toolbar
- [ ] add files for records
    - [ ] integrate invenio-records-files
    - [ ] add some example files to the demo records

Any other suggestions?
see https://github.com/inveniosoftware/invenio/pull/3803

How?
-----

The idea is to have the following development folder structure:

```yml
- dev
    - invenio (a clone of this repo)
    - modules (folder mounted into the containers)
        - invenio-records
        - invenio-i-like-you
        - ...
    - zenodo
    - ...
```

We have a `dev` folder containing a clone of `invenio`, `zenodo`, or all invenio instances you are working on...

It also contains a specific `modules` folder (you will be able to change the name in the `docker-compose-dev.yml`) that will be mounted in the containers. Thus, you can put here whatever you want to be accessible inside the containers.

Generally, you will have the clones of the modules you are working on here (or symlinks to them, or git-new-workdir, or whatever you want)

Then, you can `pip install -Ue` inside your docker to work on the modules you want.

**Comment by remileduc** [comment]
added the `add files for records` section

**Comment by lnielsen** [comment]
Now integrated with the cookiecutter templates
