### ISSUE TITLE
Docker demo installation outlined in the "getting started" does not work due to https problems

### ISSUE THREAD

**Issue by azazel75** [inveniosoftware/invenio#3811]
Hi all, 

as i've written in the title, trying out current recipe with docker outlined in the getting started  does not work. The build stage of the images completes without issues and the system  starts without any problem, but at the time of accessing it on "http://localhost", it redirects the communication to "https://localhost" which isn't mapped by docker so the load fails.

Looking into it, i've updated the nginx conf to proxy https connections and I've added a self-signed certificate to the image. Now  it correctly proxies https connections, but the invenio web instance keeps redirecting with a 302 Response...I'm stuck

Here is the updated nginx configuration:

```
server {

    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    
    server_name localhost;
    charset utf-8;

    location /static {
        root /home/invenio/.virtualenvs/invenio/var/instance;
    }

    location / {
        proxy_pass http://web:5000;
        proxy_set_header Host localhost:443;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}
```

Any idea of any INVENIO_ configuration that may help here or generally how to make it work?

**Comment by hachreak** [comment]
Have you tried to rebuild the docker image?
If you run `docker-compose build`, I think docker [is copying](https://github.com/inveniosoftware/invenio/blob/master/nginx/Dockerfile#L27) the nginx configuration inside the image built.
So, when you run docker with `docker-compose up`, docker will use that configuration (the copied version), also if you change the original version.

**Comment by azazel75** [comment]
hi @hachreak,

i did rebuild the image as i had to COPY in the self-signed ssl certificate and private key referred by the config file. To do that I've added  A COPY command to the nginx's Dockerfile.

As I have said, nginx works as expected, It's the invenio instance that keeps responding with redirects... are you  suggesting that I should re-build the instance image also?

**Comment by hachreak** [comment]
Ok, if you modified the nginx Dockerfile, then the image probably has been rebuilt.

The `5000` port is open? If yes, could you try to open `http://server:5000/`? It still redirect you to `https://server:5000/`? :smile:

**Comment by azazel75** [comment]
Yes, it does that, what follows is the log of connecting to https://localhost:5000
```
web_1            | 172.17.0.1 - - [26/Jun/2017 15:28:35] code 400, message Bad request syntax ('\x16\x03\x01\x00\xa3\x01\x00\x00\x9f\x03\x03\xaf\xd4\xbc}\xd6\xe5\xa3\x
c5S%\x85\xa4\xf8\x8e')
web_1            | 172.17.0.1 - - [26/Jun/2017 15:28:35] "���Լ}���S%����" 400 -
web_1            | 172.17.0.1 - - [26/Jun/2017 15:28:38] code 400, message Bad request syntax ('\x16\x03\x01\x00\xa3\x01\x00\x00\x9f\x03\x03\x8bQG\x9a\x85sC\xd2\x00\x1
5\xc7F\xe7\xf5\xb2yt\x1duF\xd8L\x9e\xb5\xbd{\xbb\xb6\xb4\xee\xc5\x14\x00\x00\x1e\xc0+\xc0/\xcc\xa9\xcc\xa8\xc0,\xc00\xc0')
web_1            | 172.17.0.1 - - [26/Jun/2017 15:28:38] "���QG��sC��F���ytuF�L���{������+�/̨̩�,�0�" 400 -
```

I presume that it expects to talk http and that the real http to https conversion should be a matter for the frontend http(s) server (nginx). As I said before, connecting instead to https://localhost now the invenio instance keeps responding with redirects, that the browser follows for some time and then gives up. Here is the log for that:

```
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:07] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:07 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:07] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:07 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:07] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:07 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:07] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:07 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:07] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:07 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:07] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:07 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:07] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:07 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:07] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:07 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:07] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:07 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:07] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:07 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:08] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:08 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:08] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:08 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:08] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:08 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:08] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:08 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:08] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:08 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
web_1            | 172.17.0.8 - - [26/Jun/2017 15:29:08] "GET / HTTP/1.0" 302 -
nginx_1          | 172.17.0.1 - - [26/Jun/2017:15:29:08 +0000] "GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54
.0" "-"
```

It would be interesting to know where to find the code that responds with that 302, to understand which environment variables may influence it. Unfortunately I was unable to find any hints and the configuration managed with the package entrypoints, while effective, makes "following the breadcrumbs" much more difficoult, with so many packages involved.

**Comment by hachreak** [comment]
Could you try also http://localhost:5000/ (without https)?

**Comment by azazel75** [comment]
as expected...

```
web_1            | 172.17.0.1 - - [26/Jun/2017 16:59:40] "GET / HTTP/1.1" 302 -
web_1            | 172.17.0.1 - - [26/Jun/2017 16:59:40] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xd8Se?y?\x10k\xf1\xcb\x11\x14\x7fK1\x81\x0e>\x1d\xb8Q#\xad@\x04\xca>\xae\x01')
web_1            | 172.17.0.1 - - [26/Jun/2017 16:59:40] "��Se?y?k��K1�>�Q#�@�>� U�+�/̨̩�,�0��/5" 400 -
```

now, after all these checks, are you finally sure of what's going on? You could have verified all this just by following your instructions here http://invenio-software.org/gettingstarted and by connecting to port 5000. I haven't changed anything of the configuration of the "web" image so that's the behavior you have programmed, but where?

**Comment by hachreak** [comment]
I found the problem!
Recently we introduced this [security configuration](https://github.com/inveniosoftware/invenio-app/blob/1c3c87c416f0416b7dd98ddf08e8b05db0a8385c/invenio_app/config.py#L61) for invenio.
Is using [flask-talisman](https://github.com/GoogleCloudPlatform/flask-talisman) plugin for flask to force to https.
You can try setting `APP_ENABLE_SECURE_HEADERS = False` inside your `invenio.cfg` configuration.

I will create a PR to fix the issue.
Thanks for reporting! :smile:

**Comment by azazel75** [comment]
@hachreak yeah, you got it, thanks! By the way, I'm now able to login with the default user but I don't see any content add/edit/delete interface... am I missing something?

**Comment by hachreak** [comment]
It has only `invenio-records` module that is used to show records.
There is no interface installed to edit/create.
