### ISSUE TITLE
installation: hanging "populate" demo site instance

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#3827]
Invenio demo site instance is hanging on:

```console
$ invenio index queue init
```

which makes `scripts/populate-instance.sh` to not return the prompt back and the demo site not properly populated.

Should be checked and fixed.

CC @dfdan

**Comment by hbayindir** [comment]
I have the same problem for some time. It looks like it started to happen after some Debian updates.

**Comment by diegodelemos** [comment]
The problem can be solved following this [patch](https://github.com/cernopendata/opendata.cern.ch/pull/1355/files), setting the `INVENIO_CELERY_BROKER_URL` env variable to the correct value. 

**Why?**
Essentially what was going wrong was that `CELERY_BROKER_URL`, which is the config variable for the broker url in Celery 4, was not being set and `invenio-celery` was [overwriting it with a default value](https://github.com/inveniosoftware/invenio-celery/blob/master/invenio_celery/config.py#L33) causing the Celery worker to try to connect to localhost.

@dfdan I would recommend you to follow the [Invenio-app-ils documentation](http://invenio-app-ils.readthedocs.io/en/latest/) which is up to date and it is the reference Invenio example (we will update the [config docs](http://invenio-app-ils.readthedocs.io/en/latest/installation.html#message-broker) to highlight this difference between Celery 3 and 4).

**Comment by tiborsimko** [comment]
@diegodelemos Regarding documentation, I recall discussing with @lnielsen in the past that we may perhaps move away from using the central `invenio` repository offering the installation of various flavours (`pip install invenio[ils,multimedia]`) into exposing separate flavour repositories directly (like `invenio-app-ils`) for the benefit of easing the dependency game...  However the current example installation is still listed in many places, including the Invenio home page and various documentations, so thanks for the fix 😄
