### ISSUE TITLE
RFC importing unicode_literals in each module that formats literal strings

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio#3830]
Relevant Zenodo Issue: https://github.com/zenodo/zenodo/issues/1305

Should we establish a practice that all ``from __future__`` imports also import ``unicode_literals``?
On Zenodo we are having some of those production errors, and to fully solve this problem it requires uniform handling of string literals formatting in all of invenio.

This would require a rather straightforward grep+replace script and PR campaign across inveniosoftware, as well as changes to cookiecutter and maybe ``./run-tests.sh`` to run this flake8 module: https://github.com/cogniteev/flake8-unicode-string-literal (although if we enforce it everywhere, it should not raise any warnings).

**Comment by lnielsen** [comment]
We previously went away from using ``from __future__ import unicode_literals``. I'll have to dig up the relevant issue why we didn't add it, but I think it had to deal with not being very reliable.

Ping @inveniosoftware/architects

**Comment by nharraud** [comment]
We run B2SHARE using python 3 so this change should have no effect.

**Comment by jirikuncar** [comment]
`unicode_literals` do not play nice with `click` (CLI).

**Comment by krzysztof** [comment]
@jirikuncar as per @egabancho suggestion - would it work if we added the import everywhere except ``cli.py`` ?

**Comment by jirikuncar** [comment]
The problem is when you make an import from cli that triggers import of a package with `unicode_literals`.

**Comment by jacquerie** [comment]
> `unicode_literals` do not play nice with `click` (CLI).

For reference: http://click.pocoo.org/5/python3/#unicode-literals
