### ISSUE TITLE
Add doc about `Modelling data`

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio#3831]
Add documentation about modelling data:
* JSONSchema
* JSONResolver
* linking between records

**Comment by valleyofblackpanther** [comment]
@ntarocco can I get any additional information on this issue to work on it? I mean it's straightforward but still need some help to get started.

**Comment by ntarocco** [comment]
Thank you! For your information, we have moved the development efforts to https://inveniordm.docs.cern.ch/, so any documentation should go there.
I think we can close this, the README of this repository will be updated soon.
