### ISSUE TITLE
Cloud storage

### ISSUE THREAD

**Issue by jim-bo** [inveniosoftware/invenio#3836]
Hello, I am considering using Invenio for a FAIR compliant research data storage system. I was wondering what support Invenio had for Google Cloud Storage Objects (equivalent of Amazon S3) buckets for document storage?

I saw some placeholder documentation for V2, but can't find any documentation in V3.

**Comment by lnielsen** [comment]
Invenio v3 Framework is not released yet so documentation is not yet in a usable state. We do support custom storage backends. Essentially you need either a plugin for PyFilesystem that supports Google Cloud Storage or Amazon S3, or alternatively you need to implement a [storage class](https://github.com/inveniosoftware/invenio-files-rest/blob/master/invenio_files_rest/storage/base.py#L72) in Invenio that supports it (you'll need to implement open, delete, save and send_file methods).

Here's an example of the default [PyFilesystem storage class](https://github.com/inveniosoftware/invenio-files-rest/blob/master/invenio_files_rest/storage/pyfs.py), so you can see how much is involved in implementing it.

Here's an example of a [PyFilesystem plugin](https://github.com/inveniosoftware/xrootdpyfs/) for a protocol called XRootD.

Most likely the easiest is to just implement a storage class for Invenio.
