### ISSUE TITLE
db create doesn't work

### ISSUE THREAD

**Issue by Atisom** [inveniosoftware/invenio#3844]
When I ran populate-instance.sh, I got this errors: [invenio_error.txt](https://github.com/inveniosoftware/invenio/files/1524163/invenio_error.txt)
How can I fix this?

It's a fresh install, Ubuntu 14.04 LTS
I followed these instructions: http://invenio.readthedocs.io/en/latest/deploymentguide/installation-detailed.html

Thanks,
Attila

**Comment by jacquerie** [comment]
Can you check which version you are running with
```shell
$ psql --version
```
since the JSONB type was introduced in PostgreSQL 9.4?

**Comment by Atisom** [comment]
```
$ psql --version
psql (PostgreSQL) 9.3.20
```

I upgraded my PostgreSQL then it works perfectly.

at now:
```
$ psql --version
psql (PostgreSQL) 9.4.15
```

Thank you!
