### ISSUE TITLE
ERROR in app: Failed to initialize entry point: invenio_oauthclient = invenio_oauthclient:InvenioOAuthClient

### ISSUE THREAD

**Issue by wtonribeiro** [inveniosoftware/invenio#3849]
from sqlalchemy_utils.types.encrypted import EncryptedType
ImportError: cannot import name EncryptedType

I am trying to install INVENIO 3. 
Afterward installing all the dependencies, I am running the script scripts/create-instance.sh and getting the following error:

ERROR in app: Failed to initialize entry point: invenio_oauthclient = invenio_oauthclient:InvenioOAuthClient
.
.
.
from sqlalchemy_utils.types.encrypted import EncryptedType
ImportError: cannot import name EncryptedType

Anyone could help me?

Best wishes
Washington

**Comment by lnielsen** [comment]
There are fixes on the way out now. In the meantime fix by manually installing SQLAlchemy-Utils v0.32

See:
- https://github.com/inveniosoftware/invenio-oauthclient/pull/159
- https://github.com/inveniosoftware/invenio-oauth2server/issues/170
