### ISSUE TITLE
global: package release script

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#3852]
- [ ] Determine package release workflow (what actually has to happen).

v1.0.0 releases:
- Update ``AUTHORS.rst`` (assuming an existing clean author list).
- Update ``setup.py``:
   - Classfiers: Change Development Status to Prod, Remove PyPy.
   - Requirements: No dev, alpha and beta packages.
- Remove ``MAINTAINERS``, ``RELEASE-NOTES.rst`` and ``.lgtm``.
- Bump ``version.py`` to ``1.0.0``

Other stuff:
- Change .travis.yml to ``inveniosoftware`` user for PyPI. (needs hashes from @lnielsen)

- ``MANIFEST.in`` includes ``.lgtm``

**Comment by krzysztof** [comment]
Which packages should be upgraded from alpha, beta, dev? All Invenio packages, or just the ones we will release right now?

**Comment by krzysztof** [comment]
- [ ] Manually upgrade dcxml to 1.0.0 here:
  - https://github.com/inveniosoftware/invenio-records-rest/blob/97c320c79e7c609b333a2a73fdfec3a26834dff3/setup.py
- [ ] Manually upgrade citeproc-py-styles to 1.0.0 here:
  - https://github.com/inveniosoftware/invenio-records-rest/blob/97c320c79e7c609b333a2a73fdfec3a26834dff3/setup.py
  - https://github.com/inveniosoftware/invenio-csl-rest/blob/0fdc1a2382fd2ddfd9e67bdc04ce78810cce1d6e/setup.py
