### ISSUE TITLE
docs: new section "Handling files" stub

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#3882]
~~Purpose of the section is to provide a temporary section, so that people looking for information on how Invenio handles files knows that the bundle is not yet released, but that the modules are already there today and used in production.~~

~~Bundle not yet finished (point to roadmap)~~
- Point to Files-REST, Records-Files, Previewer and IIIF.

*read before you start* https://www.divio.com/blog/documentation/

Ideas:

 Overview and principles

		- Integrating files into your application
		- Configuring your storage backend (and multiple backends) 
		- Serving files (to take from the module docs and rework)

		- Previewing files
		- IIIF image previewer 

		- Configuring integrity checks
			- setting up your low priority celery queue
		- Configuring nginx to allow for large file uploads

                To discuss:
		- Security considerations
		- Advanced topics:
			- Security
			- Storage backends (how to create new storage)

**Comment by Glignos** [comment]
We prepared with @diegodelemos  an initial skeleton for the documentation:
```
Managing Files
=========================

Overview and principles

- Integrating files into your application
- Managing files
    - Endpoints
        - Serving files (Records Files)(Provide detailed examples using Records-Files endpoints, as well as point to files rest for more detailed cases)
        - Uploading files(``)
        - Deleting files(``)
    - Permissions (??)
    - Security (Mentioned in Files-Rest)
- Storage
    - Configuring integrity checks (Files Rest)
    - Configuring your storage backend (and multiple backends) (Files Rest?)
- Previewing files?
    - IIIF image previewer (Invenio-IIIF give an example of how to use previewer and introduce a IIIF url(how to generate and what gets returned))
    - InvenioPreviewer (Preview any type of file, e.g. .zip, .pdf etc)
- Advanced topics:
    - Security considerations(??)
    - Storage backends(Remote? S3?)
- Deployment
    - Configuring nginx to allow for large file uploads( Mentioned in Files Rest)
    - Setting up your low priority celery queue(??)
```
