### ISSUE TITLE
Trouble bootstrapping at "Obtaining file" when following Quickstart docs

### ISSUE THREAD

**Issue by axfelix** [inveniosoftware/invenio#3887]
Hi,

I was trying to follow the Quickstart docs at https://invenio.readthedocs.io/en/latest/quickstart.html to run a test instance of Invenio, and I hit this error when running `./scripts/bootstrap`:

    (invenio-test) garnett@lib-garnett:~/invenio-test$ ./scripts/bootstrap 
    Obtaining file:///home/garnett/invenio-test
        Complete output from command python setup.py egg_info:
        error in invenio-test setup command: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'invenio-sfu = invenio-sfu.views:blueprint')

Was I supposed to be pointing to real, existing repositories when I filled out my config in the prior step?

Thanks!

**Comment by fenekku** [comment]
What did you fill out when you ran `cookiecutter gh:inveniosoftware/cookiecutter-invenio-datamodel --checkout v3.0` ? There is no need to point to an existing repository apriori. You probably also noticed that `'invenio-sfu = invenio-sfu.views:blueprint'` has spaces where the required formatting seems to not want spaces.

**Comment by axfelix** [comment]
I provided a bunch of dummy values that seemed to conform to the parameters -- e.g. a unique name for a transfix project, a repository name with a directory prefix -- but nothing that actually exists yet beyond this test install. Which config file should I be looking at to potentially solve whitespace problems? That's just terminal output I shared, I haven't gone poking in there yet because I was trying not to deviate from the docs.

**Comment by lnielsen** [comment]
In the parameter ``package_name`` did you change the default suggested one? 

@fenekku is right that ``invenio-sfu = invenio-sfu.views:blueprint`` ought to have been ``invenio_sfu = invenio_sfu.views:blueprint`` valid python variable name, but the cookiecutter template doesn't check for this.
