### ISSUE TITLE
Can't find documentation for MongoDB integration

### ISSUE THREAD

**Issue by ghltshubh** [inveniosoftware/invenio#3897]
In the [user docs](https://invenio.readthedocs.io/en/v2.0.1/getting-started/introduction.html) it is mentioned that invenio can be integrated with mongodb: but I can't find any documentation to do that.

**Comment by slint** [comment]
This seems to be much older Invenio v2 documentation. Keep in mind that [v2 is not suitable for production systems](https://invenio.readthedocs.io/en/latest/releases/v2.html) and isn't actively developed. If you are building something new you should start with the latest documentation on v3.

Invenio v3 does not officially support MongoDB, though this doesn't prevent anyone from using MongoDB to develop features or other Invenio modules.
