### ISSUE TITLE
[QA] Launch an Invenio instance on window 10

### ISSUE THREAD

**Issue by kickbotowski** [inveniosoftware/invenio#3920]
Hi Sir,

I just approached Invenio I have 2 questions please help me .
1. Is possible to Launch an Invenio instance on window 10?
2. I have do steps follow https://inveniosoftware.org/#getstarted. But on step 3, I cannot do it. If can , Please help me a doc to try deploy on win 10?

Br,
Kick

**Comment by mb-wali** [comment]
Hello sir,
i have tried to run it on windows 10 pro.
i had proplems running the linux scripts such as ./scripts/setup and so on.
i have used the git bash to run these scripts which works fine but there was some proplems with the packages and so on.
i would recommend to try in linux , you can use virtual box to install the linux of in getting started there is a link to download the OVA file to install it on virtual box.
