### ISSUE TITLE
invenio-admin version constraint

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio#3921]
invenio package force `invenio-admin<=1.1.0` but versions smaller than 1.1.1 has security issue.

**Comment by slint** [comment]
I think the security Flask-Admin version bump has been applied to the [`maint-1.0` branch](https://github.com/inveniosoftware/invenio-admin/commits/maint-1.0) and is part of the `1.0.1` release. Unless there's another issue currently.

**Comment by lnielsen** [comment]
Correct, Invenio 1.0.1 was released together with 1.1.1 and includes the security fixes. Invenio v3.0.x does not work with Invenio-Admin v1.1.x hence the requirement.
