### ISSUE TITLE
warnings: list of warning that should be ignored

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio#3936]
When Invenio is running, there are some common warning that we could "safely" (to be checked in details) ignore or at least somehow configure:
* `InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.` Normally we know for which servers we are adding `verify_certs=False` and why.

**Comment by lnielsen** [comment]
@ntarocco Hey, we've tried to find this warning, but we're not getting it. Do you remember where it was issued from?

**Comment by lnielsen** [comment]
Minimal example to reproduce warning:

```
from elasticsearch import Elasticsearch
from elasticsearch.connection import RequestsHttpConnection

es = Elasticsearch(
    hosts=[
        dict(
            host='...', port=443,
            http_auth=('...', '...'),
            use_ssl=True,
            verify_certs=False,
        ),
    ],
    connection_class=RequestsHttpConnection,
)
es.search(index="records", body={"query": {"match_all": {}}})
```

Also, you need a cluster with a self-signed certificate.

**Comment by lnielsen** [comment]
So after investigating a bit, I'm tempted to say that we should not fix this warning. It's a real warning that you are doing insecure stuff. I'd rather document how you can fix it in the case you are using self-signed certificates.

**Comment by lnielsen** [comment]
In 7.x+ version of the client library, you can get rid of the ``UserWarning`` by use of the [``ssl_show_warn``](https://elasticsearch-py.readthedocs.io/en/master/transports.html#requestshttpconnection) parameter

```python
use_ssl=True,
verify_certs=False,
ssl_show_warn=False,
```

You can disable the urllib3 warning like this:

```python
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```
