### ISSUE TITLE
setup database and indexes step : problem with elasticsearch

### ISSUE THREAD

**Issue by ayssi** [inveniosoftware/invenio#3938]
dear All,
during the installation of invenio 3.1 and at the database installation stage (./scripts/setup), the mysql tables are created but elasticsearch displays the following errors:
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))) caused by: ConnectionError(('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
Please note that all the container are up : 
*****-site_cache_1   docker-entrypoint.sh redis ...   Up      0.0.0.0:6379->6379/tcp
*****-site_db_1      docker-entrypoint.sh mysqld      Up      0.0.0.0:3306->3306/tcp, 33060/tcp
*****-site_es_1      /usr/local/bin/docker-entr ...   Up      0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp
******-site_mq_1      docker-entrypoint.sh rabbi ...   Up      15671/tcp, 0.0.0.0:15672->15672/tcp, 25672/tcp, 4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp
Thanks

**Comment by lnielsen** [comment]
Can you check if you have access to Elasticsearch on http://localhost:9200?

**Comment by ayssi** [comment]
with this test : curl http://localhost:9200
The response is : docker elasticsearch Failed to connect to ::1: Cannot assign requested address

**Comment by ayssi** [comment]
Question :  in order to solve the problem, can I simply install elasticsearch on the host machine without using Docker ?

**Comment by ayssi** [comment]
Th issue is solved. The solution found by reinstalling the entire system.
