### ISSUE TITLE
docs: review existing documentation for changes needed for the files bundle

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#3941]
Make sure that everything already written is still valid after addition of Files bundle.

**Comment by topless** [comment]
- [ ] [Invenio-Records-Files](https://github.com/inveniosoftware/invenio-records-files)
- [ ] [Invenio-Files-REST](https://github.com/inveniosoftware/invenio-files-rest)
- [ ] [Invenio-Previewer](https://github.com/inveniosoftware/invenio-previewer)
- [ ] [Invenio-IIIF](https://github.com/inveniosoftware/invenio-iiif)
