### ISSUE TITLE
Access through public ip

### ISSUE THREAD

**Issue by alifazeli** [inveniosoftware/invenio#3943]
Hi
I installed invenio 3 by docker in now it runs on https://127.0.0.1:5000
How can i access to it through public ip? forwarding port 5000 to local ip not works.
Any idea?

**Comment by lnielsen** [comment]
- General overview of the infrastructure: https://invenio.readthedocs.io/en/latest/architecture/infrastructure.html
- Tour of the infrastructure behind Invenio: https://github.com/inveniosoftware/training/tree/master/03-infrastructure-tour

In the generated skeleton you should have an overview of how to setup a production environment. See bottom of INSTALL.rst, and ``docker/nginx/``, ``docker/haproxy/`` and ``docker/uwsgi/``.
