### ISSUE TITLE
Host is not trusted

### ISSUE THREAD

**Issue by alifazeli** [inveniosoftware/invenio#3944]
Hi

When i try to create a record i get certificate error 

`curl -k --header "Content-Type: application/json" --request POST --data '{"title":"Some title", "contributors": [{"name": "Doe, John"}]}' https://127.0.0.1:5000/api/records/?prettyprint=1`

`"message": "Host \"127.0.0.1:5000\" is not trusted",
  "status": 400`
  
tnx for support

**Comment by lnielsen** [comment]
That's related to the [APP_ALLOWED_HOSTS](https://invenio-app.readthedocs.io/en/latest/configuration.html#invenio_app.config.APP_ALLOWED_HOSTS) configuration. Normally in the Cookiecutter-Invenio-Instance, this is set for you to localhost and 127.0.0.1 (see [here](https://github.com/inveniosoftware/cookiecutter-invenio-instance/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/config.py#L139))

If you are just testing, you can set it to None or empty list. Just don't deploy in production without it set correctly.

See also https://invenio.readthedocs.io/en/latest/deployment/securing-your-instance.html#allowed-hosts
