### ISSUE TITLE
invenio-deposit on invenio 3.1

### ISSUE THREAD

**Issue by ayssi** [inveniosoftware/invenio#3945]
I've just installed the **invenio-deposit** module and I need Help on how to use it.
**Question**: Can I have a use case for this module ? 
Many thanks for your cooperation.

**Comment by lnielsen** [comment]
The module is not yet released and support. On top, it is somewhat difficult to start with on your own, so I don't recommend starting out with it. We're planning refactoring of it during autumn/spring for the InvenioRDM project.
