### ISSUE TITLE
deposit module

### ISSUE THREAD

**Issue by ayssi** [inveniosoftware/invenio#3963]
any news about deposit module ? We want to lunch an Invenio repository but we have some difficulties to install and use deposit module on inevnio 3.1.
Thanks.

**Comment by lnielsen** [comment]
The deposit module is not likely to be out in final release until Summer 2020 as part of the InvenioRDM project. It's also likely to be refactored quite a lot between now and final release. There will be a lot of work on the module during Feb-May 2020.
