### ISSUE TITLE
global: battle test marshmallow v3 support

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#3967]
Test POST/PUT requests with Marshmallow 2/3 and ensure that the data sent is correctly stored in the record in the DB. **In particular, pay attention to the pid field.**

- [x] Test with Marshmallow 2 (normally installed when having a Python 2 virtual env)
- [x] Test with Marshmallow 3 (normally installed when having a Python 3 virtual env)
- [x] Test strict schemas definition

**Comment by topless** [comment]
# Marshmallow 2.20.5 & 3.2.2

> All the testing were done with `Python 3`

| module               | Marshmallow 2            | Marshmallow 3            |
| :------------------- | :----------------------: | :----------------------: |
| cookie-v3.1          | :heavy_check_mark:       | :heavy_multiplication_x: |
| cookie-v3.2          | :heavy_check_mark:       | :heavy_check_mark:       |
| invenio-rest         | :heavy_check_mark:       | :heavy_check_mark:       |
| invenio-records-rest | :heavy_check_mark:       | :heavy_check_mark:       |
| invenio-files-rest   | :heavy_check_mark:       | :heavy_check_mark:       |
| invenio-oaiserver    | :heavy_minus_sign:       | :heavy_minus_sign:       |

## Process

[Requests](https://gist.github.com/topless/635bf854516afb185d35fedca51f8d85) used for testing.

- Data created and edited with each version.
- Data created with v2 and edited with v3.
- DB monitoring for PID inconsistencies.
