### ISSUE TITLE
prepare release candidate for 3.2

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/invenio#3971]
check if modules released:
invenio-access
invenio-oaiserver
invenio-app
invenio-records-files
invenio-records-rest
invenio-files-rest
invenio-app
invenio-rest
and versions bumped in invenio

**Comment by topless** [comment]
|Repository                 |Last Commit|
|---------------------------|-----------------|
|invenio                    |release: 3.2.0a7|
|flask-iiif                 |release: v0.5.3|
|inveniosoftware.org        |rdm: update HZDR logo|
|invenio-accounts           |setup: add Flask-Admin as an extra  * Closes #268  Signed-off-by: Harris Tzovanakis <me@drjova.com>|
|invenio-pidstore           |travis: fix release|
|invenio-previewer          |preview: fix inline style for content security policy|
|invenio-oaiserver          |release: v1.1.2|
|invenio-search             |docs: fix references to older versions of ES|
|invenio-access             |release: v1.3.0|
|invenio-celery             |release: v1.1.1|
|invenio-db                 |setup: bumps SQLAlchemy version|
|invenio-admin              |release: v1.1.2|
|invenio-records-rest       |release: v1.6.3|
|invenio-files-rest         |release: v1.0.5|
|invenio-records-files      |release: v1.2.1|
|opensource                 |developers: change herrner to Herrner|
|invenio-app                |release: 1.2.4|
|training                   |tutorial 04: add warning not to use the sqlite with docker|
|pytest-invenio             |docs: document new location and bucket fixtures|
|invenio-app-ils            |ui: split stats and circulation stats api|
|invenio-s3                 |ext: fix typo on cached property|
|invenio-rdm-records        |cli: mint record ids with base32 provider|
|invenio-records-permissions|generators: implement Disable,SuperUser,defaults|
|invenio-cli                |setup: fix indentation|
|rfcs                       |Rename filename of RFC #8|
|base32-lib                 |release: v1.0.1|
|flask-kvsession            |tests: fix issues with pytest compatibility  Signed-off-by: Harris Tzovanakis <me@drjova.com>|
