### ISSUE TITLE
global: make invenio v3.3.0a1 release

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio#4002]
The modules that are needed to be updated along with the latest releases including the fixes are:

### `install_requires`

invenio-app>=1.2.3,<1.3.0
invenio-cache>=1.1.0,<1.2.0
invenio-celery>=1.2.0,<1.3.0
invenio-config>=1.0.2,<1.1.0
invenio-i18n>=1.2.0,<1.3.0

### `base`

invenio-admin>=1.2.0,<1.3.0
invenio-assets>=1.1.3,<1.2.0
invenio-formatter>=1.0.2,<1.1.0
invenio-logging>=1.3.0,<1.4.0
invenio-rest>=1.2.0,<1.3.0

### `auth`

invenio-access>=1.4.0,<1.5.0
invenio-accounts>=1.2.0,<1.3.0
invenio-oauth2server>=1.1.0,<1.2.0
invenio-oauthclient>=1.2.0,<1.3.0
invenio-userprofiles>=1.1.0,<1.2.0

### `metadata`

invenio-indexer>=1.1.1,<1.2.0
invenio-jsonschemas>=1.1.0,<1.2.0
invenio-oaiserver>=1.2.0,<1.3.0
invenio-pidstore>=1.2.0,<1.3.0
invenio-records-rest>=1.7.0,<1.8.0
invenio-records-ui>=1.1.0,<1.2.0
invenio-records>=1.3.0,<1.4.0
invenio-search-ui>=1.2.0,<1.3.0

### `files`

invenio-iiif>=1.1.0,<1.2.0
invenio-previewer>=1.2.0,<1.3.0

### `DB, ES`

invenio-search>=1.3.0,<1.4.0

### Pending release

- [ ] invenio-files-rest
- [x] invenio-records-files>=1.2.1,<1.3.0
- [ ] invenio-db
- [ ] invenio-mail>=1.0.2,<1.1.0
- [ ] invenio-theme>=1.1.4,<1.2.0

**Comment by ppanero** [comment]
Closed in favour of https://github.com/inveniosoftware/invenio/pull/4013
