### ISSUE TITLE
global: make a v3.2.2 release

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#4006]
After having fixed issues during the upcoming sprint, make a new v3.2.2 release of Invenio v3.2 that bumps the min versions of maintained modules.

- Work has to be done on maint-3.2 branch
- Release notes
- Cookiecutter should bump to v3.2.2

**Comment by ppanero** [comment]
- [ ] Work has to be done on maint-3.2 branch
- [ ] Release notes
- [ ] Cookiecutter should bump to v3.2.2

**Comment by ppanero** [comment]
Closed by #4015
