### ISSUE TITLE
ci: move release process to GitHub actions

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/invenio#4036]
Releasing through Travis is one of the main blocking factors when running Invenio sprints, all developers are submitting pull requests and our quota gets consumed, queuing release builds for long times (and consequently delaying other builds/releases which depend on it). If we move the releases to GitHub actions we would benefit from:
- Faster releases, as the release builds will be in a different system (GitHub actions) than the one to run pull requests tests (Travis)
- Gain experience and have an indicator regarding whether moving completely from Travis to GitHub actions would scale

**Comment by ppanero** [comment]
Some times we require releases by hand... having a script to release would be acceptable too? (maybe just for extreme situations?)

**Comment by diegodelemos** [comment]
This manual action would be just (correct me if I am wrong):
- Juggling with Git: Merging to the correct branch (the PR, if there is any, should already point to the correct branch), tagging etc...
- [Using twine for the release](https://twine.readthedocs.io/en/latest/#using-twine): whose documentation is clear and concise.

In my opinion, this should be rather a documentation snippet than a script since it is just 2~3 commands long, plus, these commands can change (merging and tagging), since the nature of this is "extreme situations"/unusual cases.

**Comment by ppanero** [comment]
Agree on that :)

**Comment by diegodelemos** [comment]
### Current stats

min/month: ~13,000 mins
average queue time: 4.38 mins
active repos: 59
builds/month: 746

Infor extracted from [Inveniosoftware's Travis insights](https://travis-ci.org/github/inveniosoftware?tab=insights).

### Comparison

**Note**: All data corresponds to the free/open source software plan for each system. Links to the sources are linked below.

| System | min/month| concurrent jobs | self-hosted runners | can scale beyond releases? |
|-|-|-|-|-|
| GitHub actions | unlimited  | 20 | yes | yes |
| Gitlab CI | 2.000 | _Not found_ | yes | yes |
| Gitlab CI (CERN) | - | - | - | yes* |
| Circle CI | ~2.500 | 1 | no | no |
| Travis CI | unlimited | 1 | no | no | 

(*) _Not sure_ since it would depend on requesting more resources internally at CERN if the limits are met.

Info sources:
- GH actions [pricing](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions)
- GitLab CICD [pricing](https://about.gitlab.com/pricing/), [📄 docs on how to do it](https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html), [🎥 short video tutorial](https://www.youtube.com/watch?v=qgl3F2j-1cI)
- Circle CI [pricing](https://circleci.com/pricing/)
- Travis CI [pricing](https://travis-ci.com/plans)


#### Considerations

If the system allows self-hosted runners we will always be able to scale even in the worst-case scenario, but if the chosen system can by default absorb the load:
- It will be simpler, it will work out of the box
- We will remove almost completely any doubts regarding [security concerns](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories) since we would activate only the self-hosted runners when there is a usage peak.

CC @inveniosoftware/architects

**Comment by ntarocco** [comment]
Thank you for this investigation! 🚀 
It looks like, from this table, that `GitHub actions` is a clear winner for our needs, with Travis just behind. Randomly checking some our builds in a few Invenio modules, each job takes from 10 to 20 minutes.

For CircleCI, this means:
`2500 / 15 min = 166 builds`
Excluding Invenio sprints, if between ILS and RDM we create a couple of PRs per project per day day, and we run it a couple of times, it means:
` 2 projs x 2 PRs x 2 runs = 8 builds per day` (IMHO, it is much higher in reality... but we can exclude weekends!)

We can basically run builds for `166 / 8 = 20 days`...
