### ISSUE TITLE
installation: start testing pip 2020

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/invenio#4038]
Taking into account the [changes in pip resolver](https://pip.pypa.io/en/stable/user_guide/#resolver-changes-2020), we should run `pip install --use-feature 2020-resolver` for all Invenio modules and find out what are the big showstoppers we will find when the new resolver makes it to production (the testing could be done by means of a small script). Errors like the following will show up:
```console
Running setup.py develop for invenio-oauthclient
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

invenio-db 1.0.5 requires SQLAlchemy-Utils<0.36,>=0.33.1, but you'll have sqlalchemy-utils 0.36.8 which is incompatible.
```

If problems are found, try to fix them if they are addressable on the spot, otherwise, add a comment in https://github.com/inveniosoftware/rfcs/issues/29 documenting the findings as much as possible so the next person taking it will have an easier job.

**Comment by frankois** [comment]
Outcome reported here: https://github.com/inveniosoftware/rfcs/issues/29#issuecomment-677676683
