### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/invenio#4050]
At the end of the sprint, create a release on [inveniosoftware/invenio](https://github.com/inveniosoftware/invenio) to update the documentation page to "latest".

**Comment by ntarocco** [comment]
It will happen [here](https://github.com/inveniosoftware/invenio/pull/4051)

**Comment by FlorianCassayre** [comment]
Reopening as the documentation is still not up to date. I'm not exactly sure how the [versioning on readthedocs](https://readthedocs.org/projects/invenio/versions/) works but I think it requires manual intervention.

**Comment by ntarocco** [comment]
It looks like that `latest` in readthedocs.io is pointing to `maint-3.3`, see it [here](https://readthedocs.org/projects/invenio/builds/11127123/), while `master` is showing correctly the changes.

**Comment by ntarocco** [comment]
It was a decision to have the `latest` pointing to the latest released stable version, so Invenio 3.3 and not master.
The changes will appear when Invenio 3.4 will be released. We can keep it like this for the time being...
