### ISSUE TITLE
GitHub Actions Sprint (Dec 2020)

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#4066]
### Goal

The goal of the sprint is to migrate repositories under https://github.com/inveniosoftware/ from TravisCI to GitHub Actions. 

### Background

- [List of repositories](https://github.com/inveniosoftware/opensource/blob/master/repositories.yml)
- [RFC on PyPI Publish via GitHub Actions](https://github.com/inveniosoftware/rfcs/blob/master/rfcs/framework-0038-pypi-release-with-gh-actions.md)
- [RFC on Reproducible tests](https://github.com/inveniosoftware/rfcs/blob/master/rfcs/framework-0039-reproducible-ci.md)

### Plan

- **Track 1:** Enable GitHub Actions on Invenio v3.4 repositories ([base, auth, metadata, files and utilities bundles](https://invenio.readthedocs.io/en/master/documentation/bundles/index.html))
  - Add [``.github/workflows/tests.yml``](https://github.com/inveniosoftware/.github/blob/master/workflow-templates/tests.yml)
  - Add [``.github/workflows/pypi-publish.yml``](https://github.com/inveniosoftware/.github/blob/master/workflow-templates/pypi-publish.yml)
  - Disable TravisCI tests
  - Change GitHub branch protection to not require TravisCI to pass (see [repositories.yml](https://github.com/inveniosoftware/opensource/blob/master/repositories.yml#L284-L286))
  - Pay attention to PyPI publish commands (``compile_catalog``).

- **Track 2:** Update cookiecutter-invenio-module to latest standards.

- **Track 3:** Green tests and reproducible tests
  - Match test matrix (with some degree of freedom) with Travis matrix. 
  - Align with cookiecutter-invenio-module 
    - Reproducible tests with docker-services-cli
    - pytest-invenio v1.4.0
    - Some further changes from cookiecutter-invenio-module. 
  - Remove ``.travis.yml`` when green.

**Comment by mvidalgarcia** [comment]
## Critical Repositories

| Repo | GA status |
|----- |---------- |
| invenio-formatter | [![](https://github.com/inveniosoftware/invenio-formatter/workflows/CI/badge.svg)](https://github.com/inveniosoftware/invenio-formatter/actions) |
| invenio-theme | [![](https://github.com/inveniosoftware/invenio-theme/workflows/CI/badge.svg)](https://github.com/inveniosoftware/invenio-theme/actions) |
| invenio-accounts | [![](https://github.com/inveniosoftware/invenio-accounts/workflows/CI/badge.svg)](https://github.com/inveniosoftware/invenio-accounts/actions) |
| invenio-oauth2server | [![](https://github.com/inveniosoftware/invenio-oauth2server/workflows/CI/badge.svg)](https://github.com/inveniosoftware/invenio-oauth2server/actions) |
| invenio-oauthclient | [![](https://github.com/inveniosoftware/invenio-oauthclient/workflows/CI/badge.svg)](https://github.com/inveniosoftware/invenio-oauthclient/actions) |
| invenio-userprofiles | [![](https://github.com/inveniosoftware/invenio-userprofiles/workflows/CI/badge.svg)](https://github.com/inveniosoftware/invenio-userprofiles/actions) |
| invenio-records-ui | [![](https://github.com/inveniosoftware/invenio-records-ui/workflows/CI/badge.svg)](https://github.com/inveniosoftware/invenio-records-ui/actions) |
| invenio-records | [![](https://github.com/inveniosoftware/invenio-records/workflows/CI/badge.svg)](https://github.com/inveniosoftware/invenio-records/actions) |
| invenio-search-ui | [![](https://github.com/inveniosoftware/invenio-search-ui/workflows/CI/badge.svg)](https://github.com/inveniosoftware/invenio-search-ui/actions) |
| invenio-previewer | [![](https://github.com/inveniosoftware/invenio-previewer/workflows/CI/badge.svg)](https://github.com/inveniosoftware/invenio-previewer/actions) |
| cookiecutter-invenio-instance | [![](https://github.com/inveniosoftware/cookiecutter-invenio-instance/workflows/CI/badge.svg)](https://github.com/inveniosoftware/cookiecutter-invenio-instance/actions) |
