### ISSUE TITLE
Set up instances for WHO, CDS and ILS

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio#4094]
Request all the services needed for setting up the new sites: 
- CDS
- WHO
- ILS
- OAIS-Registry

Things to do:

- [x] Create Openshif project
  - [x] Project category: `Official` 
  - [x]  Project name (IMPORTANT - not easy to change): 
    - [x] CDS: `cds-rdm-sandbox`
    - [x] ILS: `invenioils-prod`
    - [x] WHO: `who-rdm-prod`
    - [x] OAIS-Registry
    - [x] ~Should we have a Sandbox instance for all the projects.~
- [x] Request DBOD 
  - [x] Category: `Test` if Sandbox `PROD` if Prod
  - [x] Type: `PostgreSQL`
  - [x] Admin group:
    - [x] CDS: `cds-operators`
    - [x] ILS: `invenio-admins`
    - [x] WHO: `who-rdm-operators`
    - [x] When creating e-groups also add the e-group admin, `dr-opetators`?
- [x] Secrets, check how we manage them.
  - [x] CDS use tbag.  
  - [x] ILS uses tbag.
  - [x] OAIS-Registry
  - [x] WHO only keep them in OKD4 (it's a prototype)
- [X] Check how to deploy docker images
    - Images are build and uploaded when pushing to each repository.
- [x] Setup routes, no custom routes needed
- [x] OpenSearch use existing cluster? https://es-rdmqa.cern.ch/ Follow Pablo P. guide in internal-docs

**Comment by avivace** [comment]
Digital Memory / OAIS details were added. Our values.yaml is committed in a private repository
