### ISSUE TITLE
WebSearch: Incorrect parsing of user input

### ISSUE THREAD

**Issue by ppiotr** [inveniosoftware/invenio#418]
Originally on 2010-12-03

following lines in search_engine.py look more than suspicious.

   elif p.startswith("cocitedwith:"):  #WAS EXPERIMENTAL
      (...)
      recID = p[12:]

For example in the case of having some logical operator after this, Invenio crashes.

example:

http://inspirebeta.net/search?ln=en&p=cocitedwith%3A561945+and+doesnotwork&f=&action_search=Search&sf=&so=d&rm=&rg=25&sc=0&of=hb

RT 106598

**Comment by jirikuncar** [comment]
FIxed with new search unit (see https://github.com/inveniosoftware/invenio/commit/4b95199889cbf814a2ef134cb149946f44a58d1e#diff-be41293cb5b20239b11f6b00a3405eec).
