### ISSUE TITLE
search: citesummary quirks

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#420]
Originally on 2010-12-03

There are 3 quirks/improvements to be done with citesummary format:

1) The links on the numbers in the citesummary tables now function correctly if the users uses advanced search, as per #340.  However, the links are generated by taking the users search and appending one or two terms in invenio syntax  (i.e. user searches 

```
Author:brooks 
```
and citesummary generates  
```
author:brooks and Collection:citeable and cited:50->100
```

This is fine.   But Invnenio syntax mixed with SPIRES syntax can be odd, and many (most?) people will be doing:

```
find a brooks, t
```
so the resulting links are
```
find a brooks, t and collection:citeable and cited:50->100
```

I have not seen any evidence of this failing, but mixing the syntaxes can lead to odd results, especially with authors.   This should be confirmed to work correctly and/or fixed to ensure it works.

2) We should add a link to "remove Review of Particle Properties from analysis" (we might check if one is in the results first)  We usually do this by ```
-title:rpp
```
since anything with title:rpp is assumed to be an RPP and thus off the carts as far as citation analysis goes.   People like to be able to remove these easily and redo the analysis.   We might check the result for possible RPPs and then display "This set includes at least one Review of Particle Properties, which is usually very highly cited, click here to remove from analysis"


3) When one follows the links off of the numbers, the results are sorted in "times cited order"   I think this is incorrect, and confusing to the user - particularly if one then wants to do another search using the regular search box.    It is too hard to see that the search order has been changed, and the new search is in a confusing order.    It is arguable whether the search from the citesummary link should be in times-cited order.   However, the fact that the users then needs to change the rank order (which is hard to find...) back to "or rank by" (which is not intuitive...) to get the standard search behavior is a bad problem, especially for the following use case:

Search a set of papers (say by a particular person)
Look at the top to see what they've done recently
Select citesummary to see their overall picture
Look at the few highly cited ones to see what they've done that was big (here sort barely matters)

Now, you have a good picture of the person, so you move to the next (reviewer/candidate/author/friend/whatever):

Search the set of papers
Look at the top to see what they have done recently....

oops, the top is now the highly cited papers by this person, how did that happen...

So I suggest that the links off the numbers should report in default sort order - by the principle of least surprise.  possibly one could solve this by  other means as well.     



see also #326 #134 for other changes to this popular format.

**Comment by jirikuncar** [comment]
@kaplun is it still relevant? If yes can we test mixing of Invenio and INSPIRE syntax using `invenio-query-parser`?

**Comment by kaplun** [comment]
I am not sure. There is quite some work from Joe and Valkyrie that simply got abandoned (before I moved to INSPIRE) and is now in a dusty state (too old to be applied cleanely). I am not sure all these functionalities are really worth anymore.

Related to the SPIRES syntax being mixed up with Invenio one, I personally don't see the benefit. Additionally if the aim is to append some Invenio specific token to an initial SPIRES query, we could use the `invenio-query-parser` to first translate the SPIRES query to Invenio and then append the additional Invenio part.
