### ISSUE TITLE
Date ranges can't cross year boundaries

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#422]
Originally

Example:
```
year:2008-02->2008-06
```
works ok.

However
```
year:2008-02->2009-02
```
yields the same results as
```
year:2008-02->2009
```

For the moment I suggest working around by splitting your date search in twain (range to end of year, range from beginning of next).  But this should be repaired.

**Comment by jirikuncar** [comment]
Should be handled correctly in Invenio 3 by Elasticsearch when a field is mapped as date.
