### ISSUE TITLE
Remove diacritics using Unicode normalization

### ISSUE THREAD

**Issue by fjorba** [inveniosoftware/invenio#425]
Originally on 2010-12-10

Some time ago I found this recipe for removing diacritics that I've been using in my local utilities.  It may provide a better solution than the strip_accents() funcion in search_engine.py, and it could boost indexing performance quite a bit.

http://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-in-a-python-unicode-string

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 6 years. A quick fix would be [`unidecode('Jiří Kunčar'.decode('utf-8')) == 'Jiri Kuncar'`](https://twitter.com/jirikuncar/status/744889514376716288) if needed.

--
cc @inveniosoftware/triagers

**Comment by kaplun** [comment]
Additionally ES supports the icu plugin: https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-normalization-charfilter.html
