### ISSUE TITLE
bibsched should be part of init script

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#435]
Originally on 2010-12-18

bibsched daemon should be part of the init script like other server application. In this way it could be started automatically upon reboot of a machine and it could halt in a clean way all the running tasks in case of a shutdown.

This would be very useful in case e.g. of unforeseen powercuts.

**Comment by PXke** [comment]
Any progress on it since last message ?

**Comment by PXke** [comment]
@kaplun @lnielsen because notifications are cool :sunglasses:

**Comment by kaplun** [comment]
@jalavik are we doing anything of the sort for production or Labs on INSPIRE?

**Comment by jalavik** [comment]
@kaplun I don't think so. I guess Carmens branch could be taken and adopted if necessary for RHEL.

**Comment by PXke** [comment]
@jalavik  Does it mean, this is already existing but it is in an old branch ?

**Comment by jalavik** [comment]
@PXke Yeah, see comment above here: https://github.com/inveniosoftware/invenio/issues/435#issuecomment-41834420

**Comment by PXke** [comment]
@jalavik Amazing. I though it was a link to old ticket ! 
@lnielsen  @kaplun  : Do you know if we have a variant for redhat distributions ?

**Comment by lnielsen** [comment]
@PXke This has lost priority for me, so not planning to work on this. Feel free to grab it :-)

**Comment by tiborsimko** [comment]
I'm closing this ticket.  BibSched is deprecated and nobody seemed to have picked up the task.  If someone does, please reopen.
