### ISSUE TITLE
WebSubmit: Function Allocate_ALEPH_SYS.py to not allocate SYSNO if already done

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#439]
Originally on 2011-01-11

Function Allocate_ALEPH_SYS.py does allocate an "Aleph" system number even if one has already been allocated for the current submission. It can happen that the function is run twice in some particular scenarios.

Similarly to Create_Recid.py, the function could check that a system number has not already been allocated in file "SNa500".

**Comment by ludmilamarian** [comment]
We are not using aleph anymore, so I think we can close this one.
