### ISSUE TITLE
WebSubmit: enhance Send_Approval_Request function

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#440]
Originally on 2011-01-12

Send_Approval_Request.py function is used to send a notification email to referees. The sent email could be enriched with additional information regarding the document to approve.

A parameter could be added to the function to refer to a list of filenames (comma-separated list) in the submission directory that would be added to the email.

**Comment by jirikuncar** [comment]
@switowski @egabancho is it still needed?

**Comment by switowski** [comment]
@jirikuncar it seems like this function is no longer used anywhere on CDS (@egabancho can you confirm), so we can close this issue and possibly remove the function if no one else is using it.

**Comment by egabancho** [comment]
I think this function is not used on CDS (at least in the past few years), we use custom functions for all the approval workflows.

Probably this was Invenio oriented rather than CDS centric.

**Comment by jirikuncar** [comment]
We can close it as nobody needs it in 1.x.
