### ISSUE TITLE
Logging external URL download

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#449]
Originally on 2011-01-18

Records might reference not only BibDocFile owned URLs but also external (to Invenio) URLs. It would be nice though to still be able to log when users actually clicks and download such URLs through the record.

This is possible by actually providing the user not the real URL but an intermediate Invenio URL that will then take care of logging the click and redirecting to the real external URL.

**Comment by ludmilamarian** [comment]
@kaplun do you think this is still an issue to address for legacy, or we can leave it for master? Currently, we do record statistics for external URLs via custom events - but one needs to define such custom events for the files that they want to monitor.

**Comment by kaplun** [comment]
Ah nope :-) It was needed for OpenAIRE(!).
