### ISSUE TITLE
RFC 'Restrict further searches to this collection' checkbox

### ISSUE THREAD

**Issue by fjorba** [inveniosoftware/invenio#450]
Originally on 2011-01-19

(Quoted verbatim from a mail I wrote to the -users list 9 jan 2009)

Hi all,

I have been thinking on a search option, easy to implement, that could benefit a lot current Invenio sites.

As you know, you can start searching an Invenio site at any collection, and the first search is effectively restricted to this collection.  But as soon as you start clicking hyperlinks, the searches are no longer restricted to this original collection.  The current software allows, of course, to restrict afterwards those searches to any collection via the pulldown menu of the list of all collections, but in many installations this list is quite long, and not practical to do more than once or twice.  Adding a '&c=mycollection' to the url is sometimes faster, but we cannot expect to do that to everybody.  And indeed, there are cases that creating such an isolated view of the site is useful and desirable.

The solution I've come up with is to add a checkbox next to the search field with the text *Restrict further searches to this collection* or similar.  If checked the collection name would be 'sticky' until unchecked again.

I think that it would be relatively easy to implement.  Unfortunately, I cannot do much of it now, except of asking your opinion about it.

What do you think?

Thanks,

Ferran

**Comment by jirikuncar** [comment]
- `p=of&c=mycollection` will be translated to `p=of collection:"mycollection"` in *2.1*

**Comment by jirikuncar** [comment]
Collection facets with checkboxes has been added to master (2.2+).
