### ISSUE TITLE
search misses accented chars

### ISSUE THREAD

**Issue by romanchyla** [inveniosoftware/invenio#455]
Originally on 2011-01-24

In CDS, searching for:

physik fuer ingenieure
physik fur ingenieure
Physik für Ingenieure

works not, what works is this:

physik f\"ur ingenieure

which is very wierd.

**Comment by jirikuncar** [comment]
@kaplun has there been any progress with custom tokenizers for `bibindex` supporting mentioned characters?

**Comment by tiborsimko** [comment]
I'm not sure whether multiple alternative transliterations for a term are possible with recent INSPIRE improvements...  "für -> fur, fuer" is the main issue at hand here.  In theory, people could write their own tokenisers to achieve this.  In practice, we can muse whether Invenio should do this by default...

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
