### ISSUE TITLE
full-text snippets: `Show more' snippets and `Find inside' facility

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#46]
Originally on 2010-05-11

By default, in the HTML brief format on the search results pages, we
are showing only a limited number of snippets, governed by the
CFG_WEBSEARCH_FULLTEXT_SNIPPETS configuration variable.

The snippet box on the search results page should offer a link in the
bottom-right entitled e.g. `Show more` that the user could click upon
to see more snippets.  This link would lead the user to the Fulltext
tab on the detailed record page for the given record.  This page would
offer on the rhs a box entitled `Find inside` that would provide
snippet grepping facility with more snippets to show.  It would be
kind of similar to `Search in this book' of Google Books.

Here is an ASCII art mock-up of the detailed record page tab:

```

Information | References (34) | Citations (124) | Fulltext (3)


 Main file(s):                              Find inside:

 thesis                                     [neutralino_______] [FIND]
 version 1
  thesis.pdf [247.7 KB] 04 May 2010         1. ... supersymmetric neutralino ...
                                            2. ... 238 GeV neutralinos ...
                                           20. ... neutralino dark matter ...

                                            [view next 20 snippets]
```

**Comment by kaplun** [comment]
:+1:
