### ISSUE TITLE
automated file converter daemon

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#47]
Originally on 2010-05-16

It would be great to have a deamon (BibTask) to perform conversions. We might have a new table (e.g. conversion) with:

```
id_bibdoc
format
status
id_users
comment
```

where id_bibdoc is the document involved in the conversion, format is the desired format, status is either 'waiting', 'running', 'done', 'error', id_users is a intbitset of all the uid of users that should be alerted about the outcome of a given conversion (e.g. a user that have asked for a conversion or a submitter).
In case of error, comment would contain the error message.

**Comment by tiborsimko** [comment]
This will be taken care of via OAIS like format migrations in another repository.
