### ISSUE TITLE
WebJournal: fix bfe_webjournal_widget_whatsNew.py ordering and language

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#479]
Originally on 2011-02-08

When several new articles are at the same position (773__c) or if the position is missing, the widget fails at correctly displaying all articles.

Also the widget does not seem to fall back on an alternative language when the user-chosen language is missing from the MARC.

The aboves are correctly handled in bfe_webjournal_sub_navigation.py, which does very similar things.

**Comment by jirikuncar** [comment]
@kasioumis @egabancho @switowski is it still valid?
