### ISSUE TITLE
BibClassify should check remotely new version of the ontology also in the standalone mode

### ISSUE THREAD

**Issue by romanchyla** [inveniosoftware/invenio#482]
Originally on 2011-02-09

BibClassify checks the remote ontology if ran inside invenio (because it has the url), but we should be able to tell BibClassify to check the url also on the command line (and for the lazy of us, also to know the url of the ontology)

Which is for HEPont:  http://www-library.desy.de/HEPont.rdf

This should probably happen at bibclassify_cli.main() because deeper bibclassify operates with the taxonomy name and passing the url would mean changing too many things (but on the other hand, if the remote url it will be checked re-checked again when run inside invenio - but ok, should not be that bad)

**Comment by jirikuncar** [comment]
Check https://github.com/inspirehep/magpie
