### ISSUE TITLE
bibupload and large files

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#490]
Originally on 2011-02-14

Uploading large files to bibupload presents a couple of problems which would be nice to fix:

1) bibupload large_file.xml

where large file is ~10^5 recs can kill the server by eating swap space.  bibupload could look at the xml file and chunk it before processing to prevent this type of occurrence.

2) bibupload small_file_??.xml

(i.e. breaking the large_file into several small ones and sending them in) will fail because bibupload will only take the first file (failing silently, I believe!)

bibupload should take all files given to it, and loop over them at a high level - i.e. running sequentially, not stitching it together as one file which would break the swapspace.

**Comment by jirikuncar** [comment]
Superseded by `deposit` module and *PLUpload* supporting file chunks.

**Comment by jalavik** [comment]
I guess this use case was meant for the back end when uploading  huge MARCXML file. On the other hand the user could simply chunk this himself or that we in the new `uploader` stream the input into workflows.

**Comment by lnielsen** [comment]
@jalavik Yep, agree. User can chunk it themselves, and actually ``invenio.legacy.bibupload.utils:bibupload_record()`` will do the chunking for you.
