### ISSUE TITLE
BibEdit: Use bibupload quarantine status for document locking

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#492]
Originally on 2011-02-15

If it makes sense, use bibupload quarantine status for internal document locking.  If it doesn't make sense, then at least respect when documents are marked as quarantined and give the user a helpful error message (using #491) to tell them that the document is in an unsteady state because of another bibupload job (which could be someone else editing with bibedit, but could also be a long-running load).

**Comment by kaplun** [comment]
:+1:
