### ISSUE TITLE
WebSearch: improve/fix "NOT" operator

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#495]
Originally on 2011-02-16

When a query includes a "NOT" expression for which there is no result, the search engine returns no result, whatever the rest of the query matches. For example the following query does not return any result on the Atlantis Demo Site:

`muon -foo`

though "muon" matches some documents (and "foo" does not). 
One could expect to still get the documents matching "muon".

**Comment by jirikuncar** [comment]
Works on `master` (2.1.dev). @tiborsimko can you confirm that it has been fixed for 1.x?

**Comment by tiborsimko** [comment]
Yes, the original problem had been fixed in Invenio 1.2 already.
