### ISSUE TITLE
RFC uploader: sendforaudit REST hook

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#496]
Originally on 2011-02-17

Mike showed me a workflow he had for generating web forms completely independent of the spires web site, which interact with spires.  He suggested we have something similar for INSPIRE.  This is that ticket.

The idea is to have a REST hook similar to robotupload, but with the following changes:
* Everything is sent into the holding pen
* Email is generated to an address specified in CFG_SENDFORAUDIT_EMAIL with a forged, user-supplied From

With these two changes we can permit posting to sendforaudit from random members of the general public.  Users can make their own forms, or we can make forms for them without having to fit them into the Invenio universe.

Future enhancements might include an authorization system based on magic strings (rather than the IP-based system that robotupload uses)

**Comment by kaplun** [comment]
I am keeping this issue open as it might be interesting to take into account when implementing REST API for posting records to Invenio 2. Indeed an interface that allows to simply check the given input without actually performing a change would be cool.

What web API shall we design? @lnielsen @jirikuncar ?

**Comment by jirikuncar** [comment]
It looks like custom deposit type with REST API hooks, that can be implemented in overlay.

**Comment by kaplun** [comment]
Nope that is not for Deposit but to wrap low-level `uploader`. Don't we foresee an simpler web API for that? (as we today have in the form of batchuploader). That is going to be useful to upload *n* records.

**Comment by jirikuncar** [comment]
You can have very simple deposit workflow that creates only SIPs and runs uploader. Uploader itself doesn't have access right checks. For deposit module access rights see #2906.

**Comment by kaplun** [comment]
I will try reformulating: today catalogers have batchupload: from a given set of records in MARCXML (e.g. obtain from a search query) they download the XML, save it into a file, edit the file with emacs, and reupload the file via batchupload (that could amount to thousands of records modified in one go).

Batchuploader is a simple web layer on top of bibupload with additional authorization rights.

Today we have the uploader workflow (which is simply a client to deposit). Shall we standardize on a simple web layer on top of the uploader workflow too? (I don't think we need to bring the whole deposit stack into this).

E.g. I don't see with deposit REST API how can one build an upload simulator, an uploader for multiple records, a way to replace a record. etc. These are all lower-level operations around uploader.

**Comment by lnielsen** [comment]
@kaplun The use case you describe is something along the lines of "non-trivial batch editing of a set of large set of records by a cataloguer". I think it's definitely a use case we must support, but I'm not to sure how to best support it. E.g. I think it could be valuable to download a set of records, run it through OpenRefine to clean the metadata and re-upload it.

Now, is a records REST API with POST/PUT support the right thing for that? Not sure. Perhaps if you build an import/export layer on top of it, that cataloguers can interact with. What about validation, conflicts, etc.? How are they resolved in a manner that makes it easy for the cataloguer to do their job.

**Comment by tiborsimko** [comment]
Export-edit-import is definitely an interesting workflow to support, e.g. TIND builds a standalone MARC editor to answer similar need (CC @Kennethhole). In view of Invenio 3 and its REST API, I propose to close this issue here and eventually re-raise the need elsewhere.
