### ISSUE TITLE
BibUpload: large record history table

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#498]
Originally on 2011-02-17

INSPIRE Prod has a ~5Gb record history table, and thus bibupload runs very slowly.  Tibor and I discussed a bit IRL, and there might be a nice solution to have a facility to move this table to an "old" section periodically to clear space on high-volume sites.  I understand something similar is done on bibsched tasks.

**Comment by tiborsimko** [comment]
Closing the issue as it can be worked around via DB partitioning.
