### ISSUE TITLE
bibdesk integration

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#501]
Originally by *annetteh* on 2011-02-19

bibdesk is a bibtex bibliography manager for Mac.
http://bibdesk.sourceforge.net/
"BibDesk currently has support for Google Scholar, HCite, CiteULike, ACMDL, Hubmed, and Spires"
It looks like one needs to contact them to support Inspire.
A user mentioned the missing bibdesk integration as a major obstacle to switching to Inspire.

Annette

**Comment by jirikuncar** [comment]
I'm closing this issue as it's service/overlay specific.
