### ISSUE TITLE
Advanced search hangs with SPIRES syntax

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#502]
Originally on 2011-02-20

http://inspirebeta.net/search?ln=en&as=1&so=a&m1=a&p1=find+a+ji%2C+c-r&op1=a&m2=a&p2=&f2=&op2=a&m3=a&p3=&f3=&action_search=Search

versus:

http://inspirebeta.net/search?ln=en&as=1&so=a&p1=find+a+ji%2C+c-r&op1=a&m2=a&p2=&f2=&op2=a&m3=a&p3=&f3=&action_search=Search

(I.e. removing the m1=a flag does the trick)

Again this is a reason to hide and/or redesign the "advanced search page" as we've discussed.

**Comment by jalavik** [comment]
Search is being deprecated in favour of Elasticsearch. Closing this issue now.
