### ISSUE TITLE
WebSearch: fix search field drop-down behaviour

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#503]
Originally on 2011-02-21

If people search for P1 P2 P3 in F, this query is always interpreted
as sending P1 P2 P3 to F, regardless of what is inside Pi.  The theory
was that if people selected F from the drop-down menu, the typed
search terms should be dispatched there.  However, if there is some Pi
of the form Fi:Xi, it would be much better to dispatch this search
unit to Fi instead.

This will fix queries like `ellis title:muon` in the `author`
drop-down menu, because it would effectively query for `ellis` in the
`author` index (as asked for by the drop-down) AND for `muon` in the
`title` index (as asked for by the colon syntax).

Note that this dispatching is what Invenio already does when
F=anyfield; basically we just need to do it for any F.  This should be
done by modifying `create_basic_search_units()`.

**Comment by jirikuncar** [comment]
`p[1-3]`, `f[1-3]` arguments are being deprecated in 2.x.
