### ISSUE TITLE
Forgiving Journal Searching

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#509]
Originally on 2011-02-24

depends on #505

Once #505 is complete, the journals.kb should be used to provide journal searching that can accept journals in CODEN form, std. abbrev form, or other common abbreviations.

We might also allow for indexing the full reference, but also the journal, volume and page independently, so that:

journal:56

would find everything on page 56 or volume 56

**Comment by kaplun** [comment]
This should be better address with the consistent invenio-search-syntax
