### ISSUE TITLE
Portalboxes to be displayed in search results

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#515]
Originally on 2011-02-24

Currently portalboxes are only displayed in collection splash pages generated by webcoll.

However they are perfectly usable in search results too.

As search results might display several collections at once, portalboxes of the collection specified by the "cc" can be used.

(this was initially requested by EuCARD)

**Comment by jirikuncar** [comment]
Do we need the feature by default or we let overlays to implement it in case they need it?

**Comment by kaplun** [comment]
Are there still portalboxes in Invenio 2? Wasn't this delegated to some template per collection?

**Comment by jirikuncar** [comment]
The portalboxes are still there for "user"/"admin" defined content. One can create custom collection template that will render their content also on search results page.

**Comment by lnielsen** [comment]
This is now much easier by use of Jinja2 templating which can load portal boxes as they like.
