### ISSUE TITLE
Country searching in HEP

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#520]
Originally by *hoc* on 2011-02-24

e.g.
fin cc australia
Now this is a bit of a cheat, because it relies on the INST database being available as a lookup to go from the ICN to the COUNTRY but it's something we'll need to make sure works when we have INST ported over.

**Comment by kaplun** [comment]
We now have country search in INSPIRE, basically. In 2.x this has to be implemented properly in INSPIRE overlay
