### ISSUE TITLE
collections: simple search for collection

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#522]
Originally by *annetteh* on 2011-02-25

Collections should be included in the search index to enable a simple search
"Rappold thesis"
instead of 
"Rappold collection:thesis"
or
"fin a rappold and tc thesis"

**Comment by jirikuncar** [comment]
It should be possible with RFC #2638 and implementation in #2587.

**Comment by jirikuncar** [comment]
I can confirm that collection index now contains *all* system collections not only values from `980` (see 0d45658).
