### ISSUE TITLE
WebSubmit: clean and commit Force_{Index|Format|Webcoll}_Record functions

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#524]
Originally on 2011-02-25

These functions exist at CERN to force quick indexing/formatting/webcolling of submitted/modified records in some specific workflows.

They could be cleaned and integrated into core Invenio.

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
