### ISSUE TITLE
Generic LibX toolbar

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#536]
Originally on 2011-03-03

Today a LibX toolbar is available for CDS users:

http://libx.org/editions/download.php?edition=4F46CD81

LibX toolbar need to be customized for a particular repository. It would be nice to provide a default Invenio based LibX toolbar that can be quickly cloned and customized by simply providing the URL of the installation of Invenio.

This would require enriching the INSTALL guide of Invenio to advertize the URL of such Invenio LibX toolbar and to commit the 
```
invenio_search_implementation.js
```
file into Invenio GIT.

**Comment by jirikuncar** [comment]
This is CDS specific and probably it should go to the overlay.

--
cc @egabancho @kasioumis

**Comment by kaplun** [comment]
Nope. The issue was precisely not to make it CDS specific, rather Invenio specific. The thing is that LibX toolbars can be cloned, so, by providing an Invenio basic one, an admin can easily clone it and customized it for its specific installation.

**Comment by kaplun** [comment]
The `invenio_search_implementation.js` is rather `invenio-query-parser` specific so it could be committed there.

**Comment by tiborsimko** [comment]
@kaplun If this is labelled as "someday", then please keep the issue closed.  We know that we have several dormant tasks in the "someday" pool that can be reopened later when resources permit.  So there is no need to keep the issue open, unless someone actively works on it.
