### ISSUE TITLE
More granular re-indexing tuning

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#537]
Originally on 2011-03-03

With the new release, new table have been introduced, namely idxPAIR and  idxPHRASE. It should be possible to ask bibindex to --reindex only those (this is especially needed in case of upgrade of an existing system).

Moreover, on the fly creation of these tables might be put in place, so that the first time bibindex is run on an index that don't have such tables, these are automatically created (this is especially needed in case of upgrade of an existing system that had more indexes than the default 16 that are coming with a default Invenio installation).

**Comment by jirikuncar** [comment]
Invenio 3 is using Elasticsearch which takes care about index creation. Advanced (re)indexing support has been moved to Invenio-Indexer package.
