### ISSUE TITLE
Full-stop at end causes search to fail

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#538]
Originally by *hoc* on 2011-03-04

find t Gamma Rays From The Galactic Center and the WMAP Haze.
fails

find t Gamma Rays From The Galactic Center and the WMAP Haze
is fine

This seems a little too restrictive.

Heath

**Comment by jirikuncar** [comment]
@tiborsimko is the "black magic" [1] with stripping '.' characters desirable? If yes shall we port it to new search engine?

--
[1] http://invenio-software.org/repo/personal/invenio-valkyrie/commit/?h=538-full_stop_at_end_of_search_causes_failure&id=d947a55e1fd193b58cd78df8e281a08db996abb6

**Comment by jirikuncar** [comment]
Can be achieved by custom search unit or query enhancer that can do special term value manipulation (available in `2.1`).
