### ISSUE TITLE
WebJournal: invalidate cache upon metadata update

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#555]
Originally on 2011-03-15

Implement cache invalidation upon article update. This can be done with a BibTasklet, or the --post-process argument of BibTasks, or a regular BibTask. It needs in any case to run after the corresponding BibUpload

See also https://savannah.cern.ch/task/index.php?6294

**Comment by ludmilamarian** [comment]
I don't remember having this issue recently, so I think it can be closed.
