### ISSUE TITLE
bibtask signal handling should be improved

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#558]
Originally on 2011-03-17

When bibtasks are put to sleep or stopped or killed, the corresponding signal should automatically be sent to any process that was indirectly launched by the task.

This is in particular is needed if the task don't specify a callback function for the stop signal.

An equivalent callback function should be allowed to be specified for the sleep signal.

**Comment by jalavik** [comment]
BibSched is being deprecated in favor of Celery.
