### ISSUE TITLE
WebSearch: improve similar records search

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio#566]
Originally on 2011-03-24

Currently, while looking for 'Similar records' there is no way of restricting the query output, by adding more specific search terms.
p='recid:123 foo' when rm='wrd' will return 0 results, even if the intersection of p='recid:123';rm='wrd' and p='foo';rm='wrd' is not empty.

**Comment by jirikuncar** [comment]
`similarto:123 foo` shoud work. It needs to be verified on "real" world example.

**Comment by jirikuncar** [comment]
Implemented in https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/search/searchext/units/similarto.py#L43, however it doesn't work with demosite at it defines only `demo_jif` and not `jif` as required. It probably needs quite extensive refactoring of *bibrank*.
