### ISSUE TITLE
inveniocfg should have a --quiet option

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#577]
Originally on 2011-04-01

Actually I believe it should be silent by default and give me output when I ask for it with -v, and more output when I ask for -v -v.  

But since that will probably make people who have gotten used to its current un-unixy behavior nervous, I want an option like --quiet so that it only gives me output when something unexpected happens.  I suppose its chattiness could also be controlled via a CFG variable.

**Comment by jirikuncar** [comment]
Invenio 1.x is in feature freeze state. Invenio 3 comes with reworked CLI that is less chatty by default.
