### ISSUE TITLE
dbdump: check disk space before processing

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#578]
Originally on 2011-04-01

Currently dbdump can rotate its dump files via the N argument.  The
rotation happens after a new dump was taken, so actually the required
temporary disk space is N+1 times the size of the dump file.

It will be good to check available disk space before processing.  So,
look for latest dump file and estimate whether it is safe to make a
new dump.  If OK, continue.  If not OK, alert the admin (by
registering an exception) but do not stop the queue with an error,
because the Invenio site can still operate normally.  (So this is a
continuable error situation.)

Note that on some sites, the DB dump space lives on an AFS folder, so
the disk free space estimation should use either (i) `fs listq`
command, or if it is a regular Unix filesystem, (ii) `df -k` command.

**Comment by tiborsimko** [comment]
@kaplun Have you addressed this in the INSPIRE OPS repository?

**Comment by kaplun** [comment]
Nope. And everything related `dbdump` from INSPIRE is nowadays in `legacy` too.
