### ISSUE TITLE
Keep a lastrun field for each remote oaiset, not for the whole repository

### ISSUE THREAD

**Issue by fjorba** [inveniosoftware/invenio#587]
Originally on 2011-04-04

Now there is a single lastrun field for each repository, even if this repository has multiple oaisets to be harvested.  Thus, if the procedure fails before the whole site is completed, the lastrun time is not updated and we end up with duplicate records.

A solution would be to have a more granular table for remote oaisets.  The admin UI is fine, it is ok to have a single entry for a a single remote site, but table with the lastrun value should be set to the oaiset value, in a more relational fashion, so to say.

This way, we have an additional benefit: if we add a new oaiset to be harvested today, even if this oaiset has existed for some time, we have the guarantee that all those records are going to be harvested.  Now it is not the case.

And, as errors happen, if something goes wrong, it would be easier to cherry-pick the missing oaisets to harvest them manually.

**Comment by lnielsen** [comment]
Should be done as part of the rewrite of oairepository - related to #2464

**Comment by jirikuncar** [comment]
Shall be done when we rewrite OAIHarvester using https://pypi.python.org/pypi/pyoai.

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-oaiharvester #30](https://github.com/inveniosoftware/invenio-oaiharvester/issues/30) via [**ZenHub**](https://www.zenhub.com/)
