### ISSUE TITLE
bibclassify: text needs preprocessing

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#589]
Originally by _jpcorral_ on 2011-04-05

When the text is extracted from a PDF using pdftotext can appear some ligatures like this: [...]role of medium eﬀects was emphasized.[...]
After the solution is applied: [...]role of medium effects was emphasized.[...]

The text can be normalize in the function normalize_fulltext of bibclassify_text_normalizer.py

Reference: this ticket #317 show the problem bibdocfile module with ligatures

**Comment by kaplun** [comment]
Not really solved into magpie, but indeed no more useful. The general idea remains that both bibclassify and magpie needs text cleanup before hand (something that is done by http://gituhub.com/inspirehep/refextractutils)
