### ISSUE TITLE
Warning messages for changed/null result searches should be more visible

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#595]
Originally on 2011-04-08

This is predominantly a CSS change, but may need some template changes.   The principle should be that warning messages need to be very very visible if the results shown are likely not what the user was expecting to see.   

Note that this is somewhat different from Google, which inlines the warning messages about auto-correcting typos in searches.   We would like to fail in a noisier manner than google, because while in google returning nothing or a small result is almost always a failure, that is not the case for us.   0 results are often a very informative and correct result, so if we have modified a search to give some results rather than show 0 results, we need to make sure the user realizes we have done that...

Possibly .js hiding of results under a message like:

"Your search returned no results click here to repeat search with xxx"

would be appropriate, but at the very least we should have a very visible box that displaces the standard search results downwards visibly, and the std search results might be offset or styled differently.

**Comment by jirikuncar** [comment]
Error messages in Invenio 2+ are rendered as standard Bootstrap alerts.
