### ISSUE TITLE
make full-text URL tag more MARC indicator friendly

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#61]
Originally on 2010-05-25

Reported by Vesa, concerns BibIndex indexing of external files, and
may also concern other modules:

The full text is hard coded in many places to 8564_u. However we and
probably other libraries too are actually using the second
indicator. Normally for us it is 85641u, but can be also 0 or 2.

**Comment by kaplun** [comment]
8564_u is hardcoded in toooo many places to make it a quick fix. Given the current `legacy` code base freeze and shifting master format from `MARCXML` to `JSON` I am closing this issue.
