### ISSUE TITLE
WebDAV support for fulltext files

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#610]
Originally on 2011-04-18

It would be great if Invenio supported the [WebDAV protocol](http://www.webdav.org/)

For example one would be able to mount a given record as a remote filesystem, and directly copy/move files (even creazier idea: one should be able to mount any collection or search query... of course only final files could be then modified and only for authorized records).

One way to achieve this is by extending the webinterface_handler to delegate WebDAV operations (PROPFIND, LOCK, PUT etc.) to a WebDAV handler that should be fully intefrated with Invenio (for instance it should understand the bibdocfile structure).

A couple of Python WebDAV server side implementation do exist:
* [PyWebDAV](http://code.google.com/p/pywebdav/)
* [WsgiDAV](http://code.google.com/p/wsgidav/)

The latter seems more easily integrable with Invenio which is already based on WSGI.

**Comment by tiborsimko** [comment]
FWIW `pyfilesystem` supports WebDav...

**Comment by kaplun** [comment]
Here, the other way round was proposed, i.e. to have Invenio acting as a webdav server, so that one could mount an Invenio record or collection on query :-)

**Comment by tiborsimko** [comment]
Oh, indeed.  For some very, very, very later someday, perhaps...

**Comment by kaplun** [comment]
Maybe...
