### ISSUE TITLE
bug in bibformat session management

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#611]
Originally on 2011-04-18

Today I was watching someone use the format editor in the bibformat admin interface and they would make changes and make changes and nothing was actually changing when you reloaded the pages.

Their session was old.  once they logged back in to the site, everything worked properly.  They commented that this has happened to them several other times, when they left work in the middle of editing a format and came in the next day (or a few days later) and found it strangely not working.

So there are two problems:
1. your session expires and you don't get told.  this is pretty bad.
2. if you have an expired session, the format editor won't save anything (as indeed it shouldn't), but it doesn't tell you that it's failing.  this one is really bad.

**Comment by jirikuncar** [comment]
In Invenio 2.x it's not anymore possible to edit output formats via admin interface, because we are using Jinja2.
