### ISSUE TITLE
bibupload hook for checking affiliations and emailing RT

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#620]
Originally on 2011-04-26

I'd like to be able to send a record or fragment to bibupload, and have bibupload check the data in some arbitrary way, like for instance having it see if all of the affiliations in the record fragment are for institutions which exist in the database.  When the filter fails, I'd like to have it take arbitrary action, like for instance emailing an address (I'd set it to be RT) with a formatted message, either on a per-failure basis or for the whole fragment.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 5 years. Follow https://github.com/inveniosoftware/invenio-checker for updates. cc @inveniosoftware/triagers
