### ISSUE TITLE
WebSearch: improve browsing in tiny collections

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#625]
Originally

When browsing in a tiny collection, say one that contains only 1,000
records while the site as a whole contains 1,000,000 records, the
browse results pages usually do not return any values back and do not
even print some user-related hint as to what is happening.

We should do two things: (i) minimally, an indication to the user
should be printed saying that no values were found yet and offering
a link to continue browsing depending on the temporary term where the
previous browse attempt stopped; (ii) ideally, for tiny collections,
the collection-specific browsing should not be done_a posteriori_
by post-filtering of the any-collection values, but_a priori_ so
that if a collection contains only few thousands records (up to some
`CFG_WEBSEARCH_BROWSE_COLLECTION_POSTFILTERING_LIMIT` we shall
introduce), the browse engine could dynamically fetch all the values
for all the records in the given collection and browse inside this
list rather than using post-filtering of any-collection values.

**Comment by kaplun** [comment]
Given `legacy` freeze I am closing this.
