### ISSUE TITLE
Number of citations displayed in format does not match number in link

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#628]
Originally by _hoc_ on 2011-05-09

Hi,

Here's an example with two papers:

find bull astro-ph/0207347 or t Cosmological Consequences of a Rolling Homogeneous Scalar Field
http://tinyurl.com/4xlshf5

You'll see that on this page it says these two papers have 1693 and 1998 citations respectively. But when you click on the citation links it finds 1692 and 1997 papers - the numbers are off by 1.

This does not happen for these papers in SPIRES.

Heath.

**Comment by kaplun** [comment]
This is going to be solved within INSPIRE by several techniques (including proper cache invalidation, and simply rounding out citation numbers).
