### ISSUE TITLE
Reinstate references to citation_conference for Google format

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#639]
Originally by *[valkyrie (@valkyriesavage)](https://github.com/valkyriesavage)* on 2011-05-17

The 773 tag in MARC currently holds "Presented at", etc., instead of the name of the conference an item was presented at.

Once this is corrected, we should add a reference to it in the Google Scholar meta format for maximum information passing.

**Comment by jirikuncar** [comment]
@kaplun @kasioumis is there something what needs to be done in Invenio itself to solve this issue?

**Comment by tiborsimko** [comment]
Export for Google has been reworked since, so this is most probably not applicable anymore, and can be closed.
