### ISSUE TITLE
BibRank: enrich status reporting

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#648]
Originally on 2011-05-23

When BibRank word similarity method runs and finishes table flush, the bibsched monitor status stays at `rnkWORD01F flush ended` and one does not get to see the further progress status of the re-balancing phase e.g. `Phase 1: ......processed 10000/21664 terms` and the like.  This is hidden from the bibsched monitor creating false illusion about task progress.  Therefore we should put more task status update hooks into bibrank internals.

**Comment by jirikuncar** [comment]
Is it still needed?

**Comment by tiborsimko** [comment]
It's not really needed anymore.  The fix is simple, if one needs it, then just add `task_update_progress()` calls around given lines, for example:

```python
write_message('......processed %d/%d words' % (nb_words_done, nb_words_total))
task_update_progress("%s flushed %d/%d words" % (self.tablename, nb_words_done, nb_words_total))
```
