### ISSUE TITLE
BibCirculation: clean `invenio-ie7.css`

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#650]
Originally on 2011-05-25

Clean `webstyle/css/invenio-ie7.css` that came to_next_ during recent BibCirculation update and that seems to be unreferenced.  (E.g. plug it or remove it.)

**Comment by jirikuncar** [comment]
It's referenced in `modules/webstyle/lib/webstyle_templates.py:378:    <link rel="stylesheet" type="text/css" href="%(cssurl)s/img/invenio%(cssskin)s-ie7.css" />`
