### ISSUE TITLE
BibDocFile-level restriction

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#655]
Originally on 2011-05-27

It would be nice to be able to restrict a specific format of a `BibDocFile`. 

Take e.g. the use case of multimedia handling, where a master video is uploaded and slaves are created. Now both master and slaves are related to the same content, and therefore, because of the `bibdocfile` philosophy they should belong to the same `BibDoc`. However, a common policy might impose that the master should be restricted, while the slaves should be public.

Currently this is only possible by either assigning the master to a different `BibDoc` (hence with a different `docname`) or by setting the `HIDDEN` flag to the master format. The latter solution is not ideal, because the master would not be streamable anymore.

An even more granular solution is therefore envisaged. 

The near-future `BibDocMoreInfo` refactoring by Piotr (where this class will become a generic container of properties, either at the `BibDoc` level or at the `BibDocFile` level) will possibly handle it as yet a new `BibDocFile` property.

**Comment by jirikuncar** [comment]
Invenio 1.x is in feature freeze state. Check https://github.com/inveniosoftware/invenio-files-rest if you are using Invenio 3.x.
