### ISSUE TITLE
BibExport: add option to select all fields

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#658]
Originally on 2011-05-31

When defining queries for a Job you can specify which fields to output, but there is no easy way of getting all the fields, i.e. the whole record. Now you have to specify any field you want. Adding a wildcard-option would make life easier when you want to grab the entire set of fields from a record.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 5 years. Please note that Invenio 1.x is in feature freeze state, hence closing. cc @inveniosoftware/triagers
