### ISSUE TITLE
Migrating away from epydoc to...

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#663]
Originally on 2011-06-06

Hi,

the epydoc tool we were using (and according to which syntax we were creating docstring), seems to be unmaintained since 2008, and no longer work on Python 2.7(!)

<http://wiki.python.org/moin/DocumentationTools>

Apparently the successor of epydoc is [pydoctor](http://codespeak.net/~mwh/pydoctor/), but what about switching to [Sphinx](http://sphinx.pocoo.org/), the tool used to generate the official Python documentation?

**Comment by jirikuncar** [comment]
Sphinx and `rst` has been chosen.

See auto-generated docs here: http://invenio.readthedocs.org
