### ISSUE TITLE
Startup of MontySolr

### ISSUE THREAD

**Issue by romanchyla** [inveniosoftware/invenio#672]
Originally on 2011-06-14

Currenty, montysolr must be started via JettyRunnerPythonVM, but this class contains too much code - what is needed is a simple wrapper around the start.jar which is distributed with Solr (if we use Jetty; if we don't use Jetty, then simple wrapper around the Tomcat startup script).

The wrapper must:
1. load jcc
2. start MontySolr

(optionally, start some diagnostic test)

**Comment by jalavik** [comment]
Unrelated to Invenio today.
