### ISSUE TITLE
MontySolr - Improve the handler/dispatcher mechanism

### ISSUE THREAD

**Issue by romanchyla** [inveniosoftware/invenio#675]
Originally on 2011-06-14

MontySolr has configuration that tells it where to search/find handlers that will respond to messages coming from Java. However, one needs to edit the config file by hand - so more flexible solution is needed.

Also the handler should support registration of message handlers with wildcards.

**Comment by jirikuncar** [comment]
Invenio 3 is using Elasticsearch instead.
