### ISSUE TITLE
MontySolr - frontend dispatching module

### ISSUE THREAD

**Issue by romanchyla** [inveniosoftware/invenio#676]
Originally on 2011-06-14

When Invenio asks for the search results the remove service (MontySolr) it passes the query and all the parameters, it receives back:

1. search results (IDs)
2. OR citation summaries (in certain cases)

What needs to be done:
 
 - paging
 - display of results inside collections (now the results are one-dimensional)
 - display of error messages

**Comment by jirikuncar** [comment]
Invenio 3 is using Elasticsearch instead.
