### ISSUE TITLE
harvest DOIs from arxiv

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#678]
Originally by *annetteh* on 2011-06-15

DOIs should be harvested from arxiv which has a dedicated doi field.
example:
http://inspirebeta.net/record/913556
http://arxiv.org/abs/arXiv:1106.2519
Journal reference: 	Nuclear Physics B (Proc. Suppl.) 214 (2011) 137--142
DOI: 	10.1016/j.nuclphysbps.2011.03.073

**Comment by jalavik** [comment]
Already addressed.
