### ISSUE TITLE
verbose should be sticky on invenio

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#679]
Originally by *[valkyrie (@valkyriesavage)](https://github.com/valkyriesavage)* on 2011-06-15

When I am testing on my invenio site, I want to test multiple queries through the web interface and receive the verbose output for each without having to type &verbose=9 into the bar after each search.

I suppose this should be possible to put into the request object, but I am not sure how to do it.  Sam, I don't know if you know how to do this either, but I think you probably know who does know.  If you could pass this off to whomever you think appropriate, that would be great.

**Comment by jirikuncar** [comment]
Flask-DebugToolbar can be enabled on Invenio 2+ instances. It provides nice support for profiling requests.
