### ISSUE TITLE
generalization of second-order operators in SEQP

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#688]
Originally by *[valkyrie (@valkyriesavage)](https://github.com/valkyriesavage)* on 2011-06-17

currently, refersto and citedby are hard-coded in several places, but in order to facilitate inter-collection searches (for #420) we will need to generalize it to look in a configuration file.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 5 years, hence closing. cc @inveniosoftware/triagers
