### ISSUE TITLE
fin dk a: b: c does not work properly in INSPIRE

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#699]
Originally by *[valkyrie (@valkyriesavage)](https://github.com/valkyriesavage)* on 2011-06-22

as far as I can tell, the two sub-tasks here are

0) ensuring that the STISC is correctly emitting the terms searched for 
and
1) ensuring that INSPIRE's install is correctly indexing the keywords

**Comment by jirikuncar** [comment]
@kaplun it looks like specific BibIndex problem. Has it been fixed in 1.x?

**Comment by kaplun** [comment]
I assume nope.

**Comment by kaplun** [comment]
It's sad to see so much work that has never be integrated. I guess it's too much of a pain as of today to integrate this. I will have a look.

**Comment by kaplun** [comment]
I guess it's pointless today to try to integrate the work. However the branch comes with nice unit/regression tests. Maybe these could be ported to invenio_query_parser...

**Comment by kaplun** [comment]
See: https://github.com/kaplun/invenio/tree/702-desy_keywords_particles

**Comment by kaplun** [comment]
@Panos512 is investigating it with `invenio-query-parser`.

**Comment by kaplun** [comment]
Moved to inveniosoftware/invenio-query-parser#38
