### ISSUE TITLE
paren parser garbles "or"

### ISSUE THREAD

**Issue by traviscb** [inveniosoftware/invenio#700]
Originally on 2011-06-22

User reports...TCB verified:

If I type

  find (title top or t or top-quark or top-antitop) and (a abachi or abbott or abazov) and cn d0

it returns 71 papers (I am hoping to get all 80) so this is close.

If I type

  find (title top or t or top-quark or top-antitop or t-tbar) and (a abachi or abbott or abazov) and cn d0

just adding t-tbar trying to find the missing 9 papers, then I get only 6 records returned, 

Problem is clear from here:

http://inspirebeta.net/search?ln=en&ln=en&verbose=9&p=find+%28title+top+or+t+or+top-quark+or+top-antitop+or+t-bar%29+and+%28a+abachi+or+abbott+or+abazov%29+and+cn+d0&action_search=Search&sf=&so=d&rm=&rg=25&sc=0&of=hb

Where s_p_p completely mangles the ands and ors.   I'm guessing this is because the user used "t" as a search term (top quark) and this is confusing things...

**Comment by jalavik** [comment]
If needed, should be reopened on `invenio-query-parser`.
