### ISSUE TITLE
DESY keywords should be split into particles at index time

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#702]
Originally by *[valkyrie (@valkyriesavage)](https://github.com/valkyriesavage)* on 2011-06-22

695__a:(pi+ pi-) should become

pi+
pi-
(pi+ pi-)

in the index.  Solving this ticket depends upon getting a list of particles in something called HEPont.rdf

**Comment by jirikuncar** [comment]
A custom tokenizer can be introduced in overlay.
