### ISSUE TITLE
Portable installation

### ISSUE THREAD

**Issue by romanchyla** [inveniosoftware/invenio#704]
Originally on 2011-06-24

People usually tend to set up link pointing to the /opt/invenio/lib/python/

But this is not working for multiple installations. The following change makes invenio portable; it just adds python lib to the apache wsgi config so every installation can have different setup

https://github.com/romanchyla/invenio/tree/portable-installation

**Comment by jirikuncar** [comment]
Invenio 2.0+ can be installed in separate virtual environments.

--
There is also a trick for 1.x versions if you need it.

**Comment by tiborsimko** [comment]
For the record, Invenio 1.x also runs well in separate virtual environments.  One can use [invenio-initialise-virtualenv](https://github.com/tiborsimko/invenio-devscripts/blob/master/invenio-initialise-virtualenv) helper script to kick start things:

```
$ mkvirtualenv invenio-maint-1.0
$ invenio-initialise-virtualenv --yes-i-know
$ deactivate && workon invenio-maint-1.0
$ invenio-recreate-demo-site --yes-i-know
```
