### ISSUE TITLE
Enhance identifier based duplicate detection

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#710]
Originally by *arwagner* on 2011-06-27

Besides checking the field 035 for duplicate entries it would make sense to add other fields to this simplistic check.

024 7_ $2doi $0 10.1016/123.456.789

comes to mind immediately. Given the semantics of (http://www.loc.gov/marc/bibliographic/bd024.html) 024 the whole family qualifies for dupe checking. However, for 7_ the identifier to compare would be the combination (concatenation) of $2 and $a while for other indicators (1_, 2_, 3_) the content of field $a would suffice.

Usecases: e.g. external document delivery from publishers, avoiding to list every identifier twice to keep to the MARC standard.

Sample of a collection of identfiers (unique IDs for Physical Review / D):

	024 7_ $2ERA $a ERA:1078
	024 7_ $2EZBID $a EZBID:52540
	024 7_ $2ISI $a ISI:PHYSICAL REVIEW D
	024 7_ $2JCR $a JCR:PHYS REV D
	024 7_ $2Medline $a medline:0242621
	024 7_ $2OCLC $a OCLC:645318259
	024 7_ $2SCOPUS $a SCOPUS:110157
	024 7_ $2SCOPUS $a SCOPUS:29459
	024 7_ $2ZDBID $a ZDBID:1461167-3
	024 7_ $2ZDBPPN $a ZDPPN:019545339

**Comment by jirikuncar** [comment]
One can use PID fetchers to extract identifiers and compare them with already registered ones in Invenio 3.
