### ISSUE TITLE
Include data from authority records while indexing

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#727]
Originally by *cdickins* on 2011-07-06

* when indexing fields that are under authority control, get the relevant data from referenced authority records and include it in the word, pair and phrase index tables

- if an authority record is added or modified, make sure the dependent fields (and ONLY the dependent fields) of other (typically bibliographic) records are reindexed upon request, even though their 'modification_date' timestamp may not have changed. E.g.: re-indexing all recently modified records for field '100!__a' should not only re-index field '100!__a' for recently modified authority records, but should also re-index field '100!__a' of bibliographic records that have NOT been recently updated, but that are under authority control and in field '100!__0' refer to a recently updated authority record and hence need to be reindexed, including the data e.g. of the '100!__a', '400!__a' and '500!__a' fields of the recently updated authority record.

**Comment by jirikuncar** [comment]
It can be configured by `INDEXER_REPLACE_REFS` in Invenio-Indexer.
