### ISSUE TITLE
search_unit functions should be smarter, moved

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#728]
Originally by *[valkyrie (@valkyriesavage)](https://github.com/valkyriesavage)* on 2011-07-07

Smarts for, e.g., expanding out author names and parsing dates like "today" and "yesterday - 2" and "this month" should be moved from the SPIRES parser into the search_unit functions.

Also, the search_unit functions should be refactored out of search_engine.py into a more accessible and less frightening place.

**Comment by jirikuncar** [comment]
> the search_unit functions should be refactored out of search_engine.py into a more accessible and less frightening place.

This has been already done in `2.1`.

**Comment by jirikuncar** [comment]
> parsing dates like "today" and "yesterday - 2" and "this month"

@jalavik @kaplun how is it suppose to work?

**Comment by jirikuncar** [comment]
> parsing dates like "today" and "yesterday - 2" and "this month"

It can be implemented by custom search unit functions.
