### ISSUE TITLE
More tags need to be added to some fields

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#738]
Originally by *[valkyrie (@valkyriesavage)](https://github.com/valkyriesavage)* on 2011-07-11

Based on the bibstat output Tibor sent in February I'd like to suggest the following extensions to the logical fields:

anyfield: + 020__a 0247_a 035__a 100__i  110__a 242__b 245__b 260__a 260__b 260__c  502__b 502__c 502__d  505__r 505__t  693__a 700__i 701__a 701__q 701__i 701_j 701__u

author: + 100__i 700__i 505__r

doi: + 0247_a

reference: + 999C5m 999C5h 999C5a 999C5u

title: + 242__b 245__b

year: + 260__c 502__c

and some additions to the PHYSICAL TAG DEFINITIONS

020__a ... ISBN
0247_a ... standard identifier
242__b ... translated subtitle
245__b ... subtitle
260__a ... place of publication
260__b ... publisher
260__c ... year of publication
502__b ... thesis degree
502__c ...  institution granting degree
502__d ... year of degree
505__t ... chapter title
505__r ... author of book chapter
540__a ... terms governing use and reproduction
540__u ... license url
542__f ... copyright statement
542__u ... copyright url
693__a ... accelerator
701__a ... thesis supervisor
701__q ... supervisor alternate name
701__u ... supervisor affiliation
701__i ... supervisor Inspire id
701__j ... supervisor other id
999C5m ... unidentified part of reference
999C5o ... reference number
999C5h ... author of reference
999C5u ... url in reference

...copied from mailing list

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-marc21 #39](https://github.com/inveniosoftware/invenio-marc21/issues/39) via [**ZenHub**](https://www.zenhub.com/)
