### ISSUE TITLE
Inspire: dot in searches

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#739]
Originally by *annetteh* on 2011-07-11

A search for "J.J. Coll. Engin. Tech." in inst stumbles over the dots:

No exact match found for j.j., using j j instead...

No exact match found for coll., using coll instead...

No exact match found for engin., using engin instead...

No exact match found for tech., using tech instead...

http://inspirebeta.net/search?ln=de&cc=Institutions&ln=de&cc=Institutions&p=j.j.+coll.+engin.+tech.&action_search=Suchen&sf=&so=d&rm=&rg=25&sc=0&of=hb

**Comment by jirikuncar** [comment]
Current state:
```python
In [1]: from invenio.modules.search.api import SearchEngine

In [2]: s = SearchEngine('J.J. Coll. Engin. Tech.')

In [3]: s.query
Out[3]: AndOp(AndOp(AndOp(ValueQuery(Value('J.J.')), ValueQuery(Value('Coll.'))), ValueQuery(Value('Engin.'))), ValueQuery(Value('Tech.')))

In [4]: s = SearchEngine('"J.J. Coll. Engin. Tech."')

In [5]: s.query
Out[5]: ValueQuery(DoubleQuotedValue('J.J. Coll. Engin. Tech.'))

In [6]: s = SearchEngine("'J.J. Coll. Engin. Tech.'")

In [7]: s.query
Out[7]: ValueQuery(SingleQuotedValue('J.J. Coll. Engin. Tech.'))
```

**Comment by jalavik** [comment]
Current state looks good. Search is going to change drastically soon, so will close this for now.
