### ISSUE TITLE
Indexing: take (ed) and add to $100__e

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#750]
Originally on 2011-07-20

Cf. thread starting at http://www.slac.stanford.edu/cgi-bin/lwgate/INSPIRE-DEV/archives/inspire-dev.201107/date/article-149.html

Right now BibIndexFuzzyNameTokenizer is dropping (ed) etc. but it would be nice if we actually started putting this material into 100e so it could be searched.  This has three parts:

- BibIndexFuzzyNameTokenizer sends (ed) et al to whatever puts things in the actual indexes
* We need an actual index for 100e and a way for BIFNT to put things into it (Tibor?)
* We need keywords for the various syntaxes to allow searching within 100e; this requires deciding on syntax.

**Comment by jirikuncar** [comment]
INSPIRE specific issue.
