### ISSUE TITLE
BibCirculation: display link to add copy when all items are missing

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#757]
Originally on 2011-07-22

When viewing the "Holdings" tab of a record for which "[all copies are missing](http://invenio-software.org/repo/invenio/tree/modules/bibcirculation/lib/bibcirculation_templates.py?h=next#n287)", the display misses an admin link to "add a copy", as it is done when there are simply [no copies](http://invenio-software.org/repo/invenio/tree/modules/bibcirculation/lib/bibcirculation_templates.py?h=next#n278).

(Requested by Jens in [RQF0020333](https://cern.service-now.com/nav_to.do?uri=u_request_fulfillment.do?sys_id=bd00c28df50c98009878e86b196c5cb5))

Note that it is still possible to add new copies from the BibCirculation admin interface in this case.

**Comment by tiborsimko** [comment]
@egabancho @kasioumis @ludmilamarian Is this still the case in CDS formats?
