### ISSUE TITLE
Verify that bibsched is not running in automatic mode before running regression tests

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#763]
Originally by *cdickins* on 2011-07-29

Certain regression tests require bibsched not to be running in automatic mode (e.g. bibupload_regression_tests.py). Before running, INVENIO's regression test suite should check for this and warn the user if necessary.

**Comment by tiborsimko** [comment]
The regression tests are destructive, the user is supposed to add the "yes I know" argument, it does not seem necessary to add another restriction layer.
