### ISSUE TITLE
BibRank number crunching parts should be cython-ized

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#765]
Originally on 2011-08-03

BibRank speed can be improved 100 times, by simply moving the number crunching parts (e.g. loops) into [cython](http://cython.org) code. This would automatically translate the Python into C while at the same time allowing for static declaration of variable types.

**Comment by jirikuncar** [comment]
BibRank is no longer needed since we are migrating to Elasticsearch.
