### ISSUE TITLE
Multiple RSA server certificates not allowed

### ISSUE THREAD

**Issue by romanchyla** [inveniosoftware/invenio#766]
Originally on 2011-08-03

Invenio creates apache conf that will not work if there are existing virtual hosts because only one ssl certificate is allowed per IP.

The solution is to move the ssl directive *inside* the <VirtualHost>, eg.

<VirtualHost *:9443>
        SSLCertificateFile /etc/apache2/ssl/server.crt
        SSLCertificateKeyFile /etc/apache2/ssl/server.key
        ....
</VirtualHost>

**Comment by jirikuncar** [comment]
@dset0x can you have a look if the ssl directive is in correct place in new Apache config created in #2645?

**Comment by dset0x** [comment]
https://wiki.apache.org/httpd/NameBasedSSLVHosts

In short, and I paraphrase:

> What Apache does in case there are multiple virtualhosts under the same IP, it only consults the first SSL certificate uses it for all of them.

This is fine for some cases, but left to the administrator to ensure that it is correct.

> If one serves multiple sub-domains of a domain and owns a wildcard certificate (`*.mydomain.org`) then it's fine to use the same cert in all blocks.

I believe that if we were to default to moving the SSL directives outside of the vhost, we would create more confusion. What we *can* do is allow the user to create certificate-less SSL blocks and warn them about it while it is being created. Thoughts?

**Comment by lnielsen** [comment]
Let's close the issues, since each instance can overwrite the Apache templates as they see fit.

**Comment by dset0x** [comment]
@lnielsen While that is true, we are trying to cover these few somewhat common cases.

**Comment by tiborsimko** [comment]
> https://wiki.apache.org/httpd/NameBasedSSLVHosts

I guess the original issue may have been meant for boxes having more than one IP address?  Otherwise with name-based vhost technique there are indeed problems with multiple certiicates, unless people switch away from `mod_ssl`...

**Comment by dset0x** [comment]
Ah, looks like we were placing the certificates outside the block at the time

> The solution is to move the ssl directive inside the , eg.

> inside the ,

![back-to-the-future](https://cloud.githubusercontent.com/assets/8993055/6843154/51d2898e-d3a0-11e4-91f1-e9c4a0f7a981.jpg)

$ git log
$ /Apr.*2011 \+
$ git checkout 8950f030cb6406f973858fcdd0aa649913ae233a
$ vim $(ack -l SSLCertificateFile)

**Comment by kaplun** [comment]
Shouldn't we simply assume nowadays Apache support SNI?
https://wiki.apache.org/httpd/NameBasedSSLVHostsWithSNI

E.g. check https://www.ssllabs.com/ssltest/analyze.html?d=labs.inspirehep.net

which is based on Apache from SLC6.

**Comment by dset0x** [comment]
> Shouldn't we simply assume nowadays Apache support SNI?
 https://wiki.apache.org/httpd/NameBasedSSLVHostsWithSNI

> > Prerequisites to use SNI
    Use OpenSSL 0.9.8f or later 
[...]

We already require OpenSSL 1.0.1e with #2645 so we should be covered indeed.

BTW, SNI is up to each respective sysadmin to decide whether they want to disable or not and we should probably not touch directives related to it.

Let's close this issue.
