### ISSUE TITLE
Enhance the documentation of WebColl for CFG_WEBSEARCH_I18N_LATEST_ADDITIONS

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#770]
Originally by *calvarez* on 2011-08-05

This request comes from ticket #767.
It is not clear in WebColl that if you don't set CFG_WEBSEARCH_I18N_LATEST_ADDITIONS to 1 (default is 0), the pregenerated pages of the collections will not be in English. It would be good if it is specified in the WebColl documentation and not only in the variable docstring

**Comment by jirikuncar** [comment]
The issue has been stalled for 5 years.
