### ISSUE TITLE
find j phys.rev. and whitespace

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#774]
Originally by *hoc* on 2011-08-09

find j Phys.Rev.,D41,2330 [works]
http://inspirebeta.net/search?ln=en&ln=en&p=find+j+Phys.Rev.%2CD41%2C2330 

find j Phys.Rev., D41,2330 [does not work]
http://inspirebeta.net/search?ln=en&ln=en&p=find+j+Phys.Rev.%2C+D41%2C2330

This whitespace rule is far too strict. Whitespace following punctuation should be ignored
([\,\.\:])\s+ -> $1

**Comment by jalavik** [comment]
Reopened on `invenio-query-parser`: https://github.com/inveniosoftware/invenio-query-parser/issues/21
