### ISSUE TITLE
Admin activities translation

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#776]
Originally by *Maddog* on 2011-08-11

In invenio.access_control_config.CFG_ACC_ACTIVITIES_URLS the names of the activities there shouldn't be translated (e.g. _("Run Record Editor") should be just "Run Record Editor"). When your default language of the repository is not english and you have the translation for the activities, the activities names are forced in default language (in the drop down menu on homepage) all the time. I just pulled them out from the gettext function and it works just fine.

**Comment by jirikuncar** [comment]
Deprecated in `2.x` and replaced by *Flask-Admin* with full i18n support.
