### ISSUE TITLE
Advanced record conversion

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#777]
Originally by *Maddog* on 2011-08-11

I must say, I've been running CDS Invenio for about a year now a i find converting record (mainly harvested) only by XSLT or CGF insufficient. I suggest you to enable the option of converting record with Python itself (in case of messy repositories it's necessary). I've attached my own implementation of this feature (modified bin/bibconvert and invenio.bibconvert_python_engine), which works fine for me so far. In attached bibconvert_python_engine.py there are also some classes that create an object model of MARC. I am using them to make nice clean XMLs and sometimes to work with MARC records (there might be some mess in the code, I've been too lazy to clean it up)

**Comment by jirikuncar** [comment]
Custom (Python) serializers can be provided in Invenio 3.
