### ISSUE TITLE
Batch uploader: record number and day time sanity limits

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#78]
Originally on 2010-05-28

Put some sanity limits in place and make them configurable.  Example:
up to 5,000 records, accept job anytime.  Above 5,000 records, force
people to use the time scheduling option, selecting 'night' hours.

**Comment by lnielsen** [comment]
Closing as this one doesn't seem relevant for Invenio 3 and v1/v2 is in feature freeze.
