### ISSUE TITLE
WebStyle: gap between header menu and search box

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#784]
Originally by *jpcorral* on 2011-08-19

This problem appears in INSPIRE (not CDS). Using a very long query the page loads with enough space to show the query but due to the `visibility: hidden;` CSS property in the following classes it is not displayed to the user: `navtrailbox, navtrailboxbody, navtrail`

This creates a gap between the header menu and the search box. `display: none;` would be a better property to use as it would not reserve the space on the page and the query will not be shown.

An alternative suggestion is; If the HTML code for the query is not needed then do not send it to client. This could be done by removing the table with the class `navtrailbox`.

For example: http://tinyurl.com/longqueryinspire

**Comment by jirikuncar** [comment]
Problem solved in overlays. Invenio 3 comes with clean Bootstrap templates.
