### ISSUE TITLE
Mobile browser file download broken

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#787]
Originally by *arwagner* on 2011-08-24

It seems that there is a problem with full text files and mobile browsers.

I tried to fetch the PDF from http://cdsweb.cern.ch/record/1376677 by just clicking on the PDF link on the page using Android (2.2 Frojo) with the build in version of Chrome. Clicked on the PDF link: nothing happens. (It should start a download in the background, local PDF apps then show the file).

I tried the same with the usual desktop version of Chrome and it works fine.

**Comment by jirikuncar** [comment]
Invenio-Files-REST should provide better user experience.
