### ISSUE TITLE
Submitters can't edit their own records

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#788]
Originally by *Maddog* on 2011-08-24

If I am not mistaken, in version 0.99.1 a submitter could edit his own record (if value in 8560_f == logged users's e-mail). In version 1.0 It's no longer possilbe. I don't know if this feature is globally useful, but for us it definitely is.

**Comment by jirikuncar** [comment]
Similar feature is possible new `deposit` module. See example workflow in `zenodo` overlay.

--
PS: @jmartinm is there any progress in `BibEdit` with this issue?

**Comment by jmartinm** [comment]
I actually never saw this issue before and not sure it was ever possible to access BibEdit without the proper ``runbibedit`` authorization for the user. Do you know if it ever worked and was used, for example, in CDS where there is a lot of websubmit? @egabancho @switowski

**Comment by jmartinm** [comment]
maybe it is wrongly labeled and this was possible in websubmit? (and not in BibEdit)

**Comment by egabancho** [comment]
If we are talking about WebSubmit, for sure the owner of a record can modify it if there is a modification interface.
I agree with @jmartinm that the only way to edit a record via BibEdit it to be listed inside `runbibedit` and I think it should remain like this.
