### ISSUE TITLE
searching for author:"Abbott, R B"

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#789]
Originally by *cdickins* on 2011-08-24

**Current behavior**
 Requesting /search?p=author:"Abbott, R B" returns:
 ----------------------
 Boolean query returned no hits. Please combine your search terms differently.
 85	 	and
 1	 	Abbott, R B
 ----------------------
 Requesting /search?p=author:"Abbott, R* B" returns 1 hit (recID 16).

-*Expected behavior**
 Requesting /search?p=author:"Abbott, R B" returns 1 hit (recID 16).

Presumably this is due to "r" (i.e. the "R" in "Abbott, R B") being a key in _SPIRES_TO_INVENIO_KEYWORDS_MATCHINGS (search_engine_query_parser.py).

**Comment by jirikuncar** [comment]
Fixed in 2.1 since dc74feff.
