### ISSUE TITLE
spires parser should special-case journals

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#797]
Originally on 2011-08-30

journal shouldn't display the behavior that most other things do, where they say that:
find t foo bar baz
means:
title:foo and title:bar and title:baz

it's not obvious, because of search_unit parsing of comma splits and so forth, but I think what we want is more like:
find j nucl phys b
becomes:
journal:"nucl phys b"

**Comment by jirikuncar** [comment]
Please re-open in *Invenio Query Parser* if it is still relevant.
