### ISSUE TITLE
search: default search fields

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#800]
Originally by _Maddog_ on 2011-08-30

So far if I want to specify common search fields for all collections (different than default) I'd have to change the search fields at all collections separately, because default set of searchfields is hard-coded (invenio.websearch_webcoll.create_searchwithin_selection_box). It would be great if the default set of search fields would be either parameterized(e.g. in invenio(-local).conf) or inherited from parent collection.
The same thing applies to sort options and search options (although I still didn't find what the search options are for).

**Comment by jirikuncar** [comment]
> inherited from parent collection

Inheritance can we very tricky if we allow multiple parents (see also https://github.com/inveniosoftware/invenio/issues/1241#issuecomment-72015260).

**Comment by tiborsimko** [comment]
BTW for some of @Kennethhole's use case needed something similar: if a collection C8 does not have any search fields defined, and if some ancestor C3 has, then it should use its settings instead of template default ones.

**Comment by tiborsimko** [comment]
@Kennethhole @PXke Would you need this for legacy v1.x code base?

**Comment by PXke** [comment]
@tiborsimko I will let @Kennethhole  answer.

**Comment by Kennethhole** [comment]
Hi sorry for a late answer. 
Yes it is quite time consuming to manage every single collection. Also, if you would like to add one additional field, the default list is wiped out, and you have to set up the list from scratch for every single collection. 

If inheritance is a time consuming, I think having it in the local config file is sufficient. We haven`t had a case where we want to differentiate between the different collections, it is just about adding some few more fields (such as subject).

**Comment by tiborsimko** [comment]
@Kennethhole OK, thanks.  One can consider this to be more of a bug than a feature, so I'm putting this for v1.2.x already.
