### ISSUE TITLE
WebComment: introduce separate Comments (N1) and Reviews (N2) tabs

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#802]
Originally on 2011-08-31

Invenio offers optional commenting and reviewing facilities that every
installation can separately enable or disable.  (This is governed by
`CFG_WEBCOMMENT_ALLOW_COMMENTS` and `CFG_WEBCOMMENT_ALLOW_REVIEWS`.)

However, on the HTML detailed format on the Detailed record pages,
there is only one common tab called "Discussion (3)" where comments
and reviews are presented as sub-tabs, so to speak.  This does not
work coherently with the HTML brief format where we display comment
and review information apart:

```
1. Development of photon beam diagnostics for VUV radiation from a
   SASE FEL / Treusch, R ; Lokajczyk, T ; Xu, W ; Jastrow, U ; et al
   [TESLA-FEL-99-07]

   Detailed record - Similar records - 2 comments - 1 review
```

The goal of this ticket is to introduce two separate "Comments (2)"
and "Reviews (1)" tabs on the detailed record pages, which will both
harmonise the situation and make the UI clearer should a site enable
one or both of these facilities.

**Comment by jirikuncar** [comment]
Solved in a9dd2a8a for Invenio 2.x.
