### ISSUE TITLE
BibCirculation: display status of ILL and purchases

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#807]
Originally on 2011-09-07

Tullio Basaglia wrote:
  In BibCirculation, a user, when checking his/her loans and requests, should be able to check the status also of the ILLs/puchases. This is not the case today. If I log in and select "your loans" I see only the loans and the requests.

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-circulation #18](https://github.com/inveniosoftware/invenio-circulation/issues/18) via [**ZenHub**](https://www.zenhub.com/)
