### ISSUE TITLE
Remove BibTex output item count limits

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#811]
Originally on 2011-09-08

From hoc:
  It would probably be better for this to work like the LaTeX CV format, which 
  can display over 1,000 records at a time.  Certainly, a limit of 1,000 would be 
  more suitable than the 100 limit as the point of the bibtex format is not to 
  read the result but cut-and-paste to a file.

The limit is inside search_engine.py, but the effect is seen in the output format.  There is machinery in search_engine meant to raise (remove?) this limit for xml output formats; perhaps that is helpful here.

**Comment by lnielsen** [comment]
Fixed in Invenio 3 using Records-REST serialisers and Elasticsearch max search result limit.
