### ISSUE TITLE
INSPIRE: check jquery-min version, update formats

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#812]
Originally on 2011-09-08

There's a new (as of a week ago) jquery-min.js inclusion in the default page headers of inspire master.  Go through the formats (like referenceinp) that do something unconventional (like loading jquery from Google) and confirm whether they work with this version.  If they do, then remove their separate downlading of jquery in preference to the local one.

**Comment by kaplun** [comment]
No longer an issue in master
