### ISSUE TITLE
INSPIRE: Fix abbreviation mappings for type code

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#813]
Originally on 2011-09-08

e.g., 
  Indeed it works. Only problem is that 980 has not all conf tags.
  
```
  fin tc c*165,340*
  980:conference*165,340*
  690c:"conference paper"**247,933*
```
 
 This is no consistent behavior. For others - like review or book - it's the 
 other way around.

So some of this is probably in the data, e.g., we need to be consistent in the contents of 980 tags.  And that may be enough.  But we may also want to address whether for example c maps to conference or conference paper or whether one maps to the other, in the type code kbr.

**Comment by kaplun** [comment]
Moved into INSPIRE internals
