### ISSUE TITLE
INSPIRE: Move blog link, news box?

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#818]
Originally on 2011-09-13

Probably we should have a link in the orange box under INSPIRE, above
symmetry breaking.  And probably we should include links to blog posts in the
NEWS box along with the tweets.  We could accomplish this by either tweeting
when we have a blog post (which I think is a bit lame) or by modifying the script
that scrapes the twitter RSS to also scrape the blog RSS, and include blog post
titles as a clickable link in the stream.  The News box should probably be allowed
to be longer in that case though.

**Comment by jalavik** [comment]
Unrelated and outdated.
