### ISSUE TITLE
WebComment: use CKEditor native support for inline comments in replies

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#819]
Originally on 2011-09-14

CKEditor 3.6.2 introduced the possibility to exit from blockquotes by using the Enter key on empty paragraphs, behaving more like in mail client where users expect to be able to insert inline replies. See http://dev.ckeditor.com/ticket/7354

A workaround to mimic that behaviour had been introduced with commit 4e5bb5f9f6e7526ee678e57c13df5abd0e3bed55 (+ later fixes):
  When displaying the editor to submit a reply, use a markup that will let users insert inline comments in the quoted replies. This is done by using a block for each line instead of a single <div> for the complete quotation.

This workaround introduced overheads in the processing/cleaning and displaying of comments (to circumvent various behaviours in various browsers), which could be avoided by using the newly introduced feature.

Unfortunately it is currently not fully possible to make use of this feature as it does only apply to CKEditor area configured with enterMode=P, while WebComment area use enterMode=BR (closer to the behaviour of a plain textarea). See
http://dev.ckeditor.com/ticket/8304

So either wait for the above ticket to be closed, or update WebComment to use enterMode=BR.

**Comment by lnielsen** [comment]
Invenio v1/2 is in feature freeze so closing ticket.
