### ISSUE TITLE
WebSearch: fix SPIRES search mode when terms contain quoted colons

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#824]
Originally on 2011-09-28

The SPIRES search syntax mode does not work well for keyword searches
containing terms including colons.  The SQPP/SPIRES syntax parser is 
probably confused by the presence of colon, even though (i) the
colon is quoted and (i) the term before the colon is not valid logical field.  
The Invenio search syntax mode works well here.  Compare:

```
  keyword:"coupling: Yukawa"      ... good, 4117 records found
  find keyword "coupling: Yukawa" ... bad, 3 records found
  find keyword coupling: Yukawa   ... bad, 0 records found
```

**Comment by jirikuncar** [comment]
Issue moved to [inveniosoftware/invenio-query-parser #57](https://github.com/inveniosoftware/invenio-query-parser/issues/57) via [**ZenHub**](https://www.zenhub.com/)
