### ISSUE TITLE
Creation of basket when setting up an alert

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#826]
Originally on 2011-09-29

When setting a new alert, if the result has to be stored in a basket, it
is possible only to choose among existing baskets.
It would be nice to be able to create a new basket to store the result
of the alert.

**Comment by jirikuncar** [comment]
No milestone, no assignee, no update for 5 years. No fix?

**Comment by kaplun** [comment]
Not my fault :dancer: I don't work for CDS since before we migrated to Github (INSPIRE does not use baskets nor alerts)
