### ISSUE TITLE
Error when PyStemmer is not installed and stemming is still enabled

### ISSUE THREAD

**Issue by romanchyla** [inveniosoftware/invenio#827]
Originally on 2011-09-30

I don't know (yet) the cause, but when the global index (in the demo site) has stemming enabled AND if PyStemmer is not enabled, the index will contain only stemmed values, but not original tokens.

To reproduce:
1. load demo records
2. search for ellis [0 hits]
3. search for elli [11 hits]

Or:
1. load demo records
2. change configuration of global index (deactivate stemming)
3. search for ellis [11 hits]

The issue is solved by installing PyStemmer, but PyStemmer is only recommended. 

I have to find out what is doing the stemming instead and why it is not indexing also the original words.

**Comment by kaplun** [comment]
PyStemmer is nowadays set as dependency in `requirements.txt`. So no longer need to handle its absence.
