### ISSUE TITLE
Batch uploader: possibility to add link labels and other tags

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#83]
Originally on 2010-05-28

When attaching full-text documents, it would be good to have a
possibility to specify link labels ($y) and other additional metadata
like restrictions ($r).  People should be able to specify most of the
reasonable FFT subfields, see BibUpload Admin Guide.

**Comment by lnielsen** [comment]
Superseded by Invenio-Files-REST in Invenio 3.
