### ISSUE TITLE
Improved wash_urlargd()

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#831]
Originally by *[pglauner](https://github.com/pglauner)* on 2011-10-11

Idea: There is an argument xyz:
```
argd = wash_urlargd(form, {'xyz': (int, DEFAULT)})
```
Suggest that xyz must be >= 0. Negative values might be caught by
```
if argd['xyz'] < 0:
   do something
```
or are not caught at all, which might result in an exception or even worse.

wash_urlargd() should be extended to handle this.

Alternatively, a complete new function could be created to handle a lot of other cool things like accepting a list of permitted values &c.

**Comment by lnielsen** [comment]
``wash_urlard`` is not used on Invenio 3 anymore.
