### ISSUE TITLE
WebSearch: configurable latest additions list generator

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#833]
Originally on 2011-10-19

1) Currently Invenio installation can enable or disable latest addition lists on collection splash pages
by tweaking `CFG_WEBSEARCH_INSTANT_BROWSE` in `invenio-local.conf`.  However this does not permit collection-dependent behaviour.

2) For some collections it does not make sense to provide latest additions first, or latest additions should be listed differently.  We currently treat this problem by hard-coding decisions in `websearch_webcoll.py` in `create_latest_additions_info()` via tweaks like:

```
                # sort some CERN collections specially:
                if self.name in ['Videos',
                                 'Video Clips',
                                 'Video Movies',
                                 'Video News',
                                 'Video Rushes',
                                 'Webcast',
                                 'ATLAS Videos', 
                                 'Restricted Video Movies',
                                 'Restricted Video Rushes',
                                 'LHC First Beam Videos',
                                 'CERN openlab Videos']:
                    recIDs = sort_records(None, recIDs, '269__c')
```

and the like.

3) The goal of this ticket is to take above-mentioned CERN hacks outside of the source code and create general infrastructure where latest addition lists can be made easily customisable by Invenio administators.  For example, we can have various latest addition listing algorithm living as small Python files in a plugin directory and a new DB table `collection_latestadditions` will permit admins to decide which lister plugin will be used for which collection.  WebSearch Admin UI should be enhanced to allow such configuration.  The feature was called historically "instant browse" so the naming could go something like "instant browse list generator" or somesuch.

**Comment by jirikuncar** [comment]
Invenio 3 provides nice support via templates by using Invenio-Search-JS and Invenio-Records-REST integration.
