### ISSUE TITLE
XML CiteSummary Silently Fails

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#838]
Originally on 2011-11-01

XML citesummary silently fails in INSPIRE.

http://inspirehepdev.cern.ch/search?ln=en&ln=en&p=find+a+r+m+barnett+and+t+rpp&action_search=Search&sf=&so=d&rm=&rg=25&sc=0&of=xcs&verbose=9

gives a service failure message without logging any warnings or errors, and 

http://inspirehep.net/search?ln=en&ln=en&p=find+a+r+m+barnett+and+t+rpp&action_search=Search&sf=&so=d&rm=&rg=25&sc=0&of=xcs

gives output which appears to be valid, but vacuous.

It's not obvious to me what this is even for, and I question the value of having code that we don't need.  Are other Invenio instances successfully using this?  I assert that since we don't know how long its been broken, and users aren't complaining about it, we must not need it.  

Tibor, please reply and let me know who is using this (it appears to have been added by Marko?) and advise as to whether it should be retained (in which case this ticket stands for fixing this feature in INSPIRE so it works correctly, and adding unit and regression tests so that it doesn't break in the future) or discarded (in which case this ticket stands for the easier job of removing the xcs output format from search_engine_summarizer and friends.)  Once we know where to go, I guess it can be reassigned.  Probably to me?

**Comment by lnielsen** [comment]
@kaplun For INSPIRE, closing for Invenio.
