### ISSUE TITLE
Batch uploader: enable sending "index files"

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#84]
Originally on 2010-05-28

When uploading full-text files, enable a mode for uploading an "index
file" looking like like

```
 1 foo.pdf $y Published version $r Springer
23 bar.pdf $y Fulltext
```

That is, first column is the record ID, second column the file name
(either location absolute, or to be looked from the given folder), and
what follows is the other metadata for FFT.

**Comment by lnielsen** [comment]
Superseded by Invenio-Records-REST and Invenio-Files-REST in Invenio 3.
