### ISSUE TITLE
INSPIRE: Outstanding issues with latex formats

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#847]
Originally on 2011-11-20

I fixed a lot of things in #841 (including #829) but not everything.  The history there is becoming too intricate to follow and it has drifted from its original purpose.  So I want to push that branch into production, mark that ticket as fixed, and then fix these remaining outstanding issues:

# Records can get confused about %%CITATION, e.g.
```
%\cite{hep-th/9312104}
\bibitem{hep-th/9312104}
  E.~Witten,
  %``The Verlinde algebra and the cohomology of the Grassmannian,''
  In *Cambridge 1993, Geometry, topology, and physics* 357-422
  [hep-th/9312104].
  %%CITATION = .....,,;%%
}}
Even though there's an eprint number, the system does not give a %%CITATION.  Its not clear what those dots are about.

# While most things have %%CITATION, not everything does, e.g.:
{{{
%\cite{arXiv:1004.0616}
\bibitem{arXiv:1004.0616}
  R.~Longo and E.~Witten,
  %``An Algebraic Construction of Boundary Quantum Field Theory,''
  Commun.\  Math.\  Phys.\ \ {\bf 303} (2011) 213
  [arXiv:1004.0616 [math-ph]].
```
This appears to be happening (on DEV) only for things which have both a pubnote and an arxiv number, but for which the coden lookup fails.  More investigation is needed.

**Comment by jalavik** [comment]
BibTex output have recently been redone. Moved this issue to be checked if OK under INSPIRE channels.
