### ISSUE TITLE
allow for dynamic document generation

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#851]
Originally by *[hoangelos](https://github.com/hoangelos)* on 2011-11-22

In Invenio, all documents must be on disk to be served.  To allow for arXiv's dynamic document generation, Invenio needs to have some concept of which source document should be dynamically generated.  It also need to keep track of what's considered a source document.

**Comment by jirikuncar** [comment]
Concept similar to thumbnails generation using Flask-IIIF can be used also for serving documents. One can implement custom view implementation for serving files via Invenio-Records-REST (see `view_imp='invenio_files_rest.views.file_download_ui'`).
