### ISSUE TITLE
WebSearch: fix search using parentheses inside regular expressions

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio#861]
Originally on 2011-12-02

`search_pattern_parenthesised()` is breaking the regex search when the search pattern contains parentheses.

Example (taken from the Invenio Search Guide - find all titles containing words dense and matter that are separated by at most one word that doesn't contain the letter l)
Searching for `title:/dense ([^ l]* )?matter/`
produces the following output:
```
Search stage 1: search_pattern_parenthesised() searched 'title:/dense ([^ l]* )?matter/'.
Search stage 1: search_pattern_parenthesised() returned ['+', 'title:/dense', '+', '[^ + l]*', '+', '?matter/'].
Search stage 1: basic search units are: [['+', '/dense', 'title', 'w']]
[...]
```

`search_pattern_parenthesised()` should not trigger the use of the parenthesis parser but forward the search query as it is to the `search_pattern()` function, like in the following example:

Searching for `title:/dense ([^l]* )?matter/` - note the missing space between `^` and `l` inside the parentheses which will not trigger the use of parenthesis parser - general case of `(foo)` vs `(foo bar)`, produces the following output:
```
Search stage 1: basic search units are: [['+', 'dense ([^l]* )?matter', 'title', 'r']]
[..]
```

**Comment by jirikuncar** [comment]
It works with `invenio_query_parser`:
```python
>>> from invenio.modules.search import api
>>> s = api.SearchEngine('title:/dense ([^ l]* )?matter/')
>>> s.query
KeywordOp(Keyword('title'), RegexValue('dense ([^ l]* )?matter'))
```
even with parenthesis:
```
>>> s = api.SearchEngine('(title:/dense ([^ l]* )?matter/ AND author:ellis) OR year:2000')
>>> s.query
OrOp(AndOp(KeywordOp(Keyword('title'), RegexValue('dense ([^ l]* )?matter')), KeywordOp(Keyword('author'), Value('ellis'))), KeywordOp(Keyword('year'), Value('2000')))
```

**Comment by jirikuncar** [comment]
Please re-open if needed in `invenio_query_parser` package.
