### ISSUE TITLE
Inspire: bug in searching for several eprints

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#863]
Originally by *annetteh* on 2011-12-20

	find eprint hep-ph/0504227
gives correctly 1 result, as does
	find eprint astro-ph/0603660

But
	find eprint astro-ph/0603660 or hep-ph/0504227
gives an error message:
	Search term reportnumber:hep-ph/0504227 inside index Reportnummer did not match any record
Same negative result for
	find eprint astro-ph/0603660 or eprint hep-ph/0504227

https://inspirert.cern.ch/Ticket/Display.html?id=157717

**Comment by jalavik** [comment]
Closing as duplicate of #858
