### ISSUE TITLE
WebSearch: syntax independent date math

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#865]
Originally on 2012-01-05

As mentioned in #263#comment:13 merge notes, the date math should be stripped away from the SPIRES syntax parser, so that queries like `today - 7` work independently either in Invenio or in SPIRES search syntax mode.  IOW, `today -7` does not need to be parsed, it can be passed as such by the parser, and it will get properly expanded by `search_unit_in_bibrec()` and friends, similarly to how span queries work.

Submitting this as a standalone ticket so that the merge comment is more visible.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 4 years. If you need this feature, please re-open it in Invenio-Query-Parser repository. cc @inveniosoftware/triagers
