### ISSUE TITLE
Invenio whitepaper

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#875]
Originally on 2012-01-27

It would be nice to write a sort of white paper documenting the whole Invenio at least in a bird view. Such a paper that can then be put e.g. on CDS, would then be possibly cited in other papers building around Invenio technology.

**Comment by jirikuncar** [comment]
What about getting DOIs from @zenodo?

**Comment by lnielsen** [comment]
I would close this issue as it is kind of a metaissue like "improve documentation"? If someone has the time and wants to write the paper they can reopen the ticket or create a new one.

**Comment by tiborsimko** [comment]
Yes, this is a meta issue that we don't need to have open in the issue tracker.
