### ISSUE TITLE
WebSearch: introduce `whois` operator

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#877]
Originally on 2012-01-30

In SPIRES query mode, a search for `whois ellis` should expand into `find name ellis` in HEPNames collection. This is easy to do, since `whois` operator cannot be apparently combined in Boolean queries and whatnot, so a simple query replacement will do.  The only complication not to forget is to alter the searched collection to HEPNames regardless of the starting collection the user originated his/her query from.

**Comment by jirikuncar** [comment]
It should probably go to `invenio-query-parser` package.

**Comment by lnielsen** [comment]
is it really needed? Isn't it something that can be customised by an overlay if they so desire?

**Comment by jirikuncar** [comment]
Yes, it will go to invenio_query_parse.contrib.sprires. It's here until @jalavik moves it to new package.

**Comment by tiborsimko** [comment]
This was needed for the INSPIRE service, so that original SPIRES query syntax would be fully respected.  It's possible that the priority has decreased with time.  CC @kaplun.   And :+1:  for closing it here and moving the task, if needed, to `invenio-query-parser` project.

**Comment by jalavik** [comment]
Closing and added to query parser.
