### ISSUE TITLE
Introduce 'whereis' query

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#888]
Originally by *hoc* on 2012-01-30

In SPIRES query mode, a search for whereis harvard should expand into a "harvard" search in the INST collection. This is easy to do, since whereis operator cannot be apparently combined in Boolean queries and whatnot, so a simple query replacement will do. The only complication not to forget is to alter the searched collection to INST regardless of the starting collection the user originated his/her query from.

**Comment by jalavik** [comment]
Closed and added to query parser.
