### ISSUE TITLE
Investigate development of personalized homepage

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#891]
Originally on 2012-02-01

The main goal of this task is to investigate how to ease access to preferred/personal/relevant user content. A proposal is sketched under the form of a personalized homepage with direct links to such content.  Note that this ticket can be seen as a high-level, stub ticket, as it proposes several independent paths to explore, possibly triggering discussion and the creation of subtickets/tasks that can be achieved progressively.

Contents of interest to the users of Invenio can potentially fall into the following (non-exhaustive) categories: 
 - records marked as favorites by the user (currently handled with personal baskets)
 - records marked as interesting by colleagues (shared baskets, tags)
 - record matching some user-defined criteria (based on metadata: search, alerts) and pre-defined criteria (collections) 
(we reduce the notion of *content* to *records*, leaving aside other type of contents such as comments, which remain attached to a record). 

Handling such personal content is already well covered by Invenio, but simply not made easily accessible or convenient enough for a daily use. Some trivial improvements can be done, but also more radical changes involving renaming of concepts or replacement of current features can be considered. Some of these are described below.

One of they key aspects of this proposal is to bring content of interest to the front: many user-workflows involve accessing content in leaf collections, buried in the collection tree. A basic improvement would be to bring these collections to the main page, more or less as if they were attached as virtual subcollections to the root collection tree, possibly in their own area/box (one could see them as *bookmarks* to collections). Users would be able to add or remove collections to this area as wanted.

This "personalized" homepage could be extended at a later stage to support direct access to other types of views:
 - personal baskets
 - shared baskets
 - searches
 - tags (if implemented and sensibly different from saved searches)

A basic implementation would simply link these *bookmarks* to the already existing tools (eg. link to WebBasket, link to collection page, etc.). A more ambitious scenario would consider a new unified interface to deal with this content: a basket would look like any other collection, in which you can search, set an RSS feed, etc. Some differences would still exist as you can for example reorder or annotate records in a basket, but not in standard collection. The same would apply to the creation process that would be slightly different for each case: creating a basket only require a name, while a saved search requires to set a query. Still, giving the feeling that the same knowledge can be used to deal with these different tools (and ensuring that it is mostly true) by using similar layout/look/controls/patterns would help user adoption. See some early mockups attached to this ticket, *2007_YourCollections.jpg* and *2007_YourCollectionsHomagePage.jpg* (Disclaimer: these mockups no longer fully reflect the description made here, but can at least help visualize the idea behind).

It should ideally be possible to switch on/off the personalized homepage globally, as well as per user choice. 

It should be decided if linked collection can be renamed or must retain the original name of the collection.

The personalized box could appear with entire content on the main page, or just as a summary linking to a more complete separate interface.

Bringing awareness of the latest changes in a set of records would help making the tool even more useful. For example with a label indicating the number of new records added to a collection/basket/search since last time it was viewed by the user (or simpler: added in the last 24h or week): Books ^(12,263) **+20**^

A good default set of collections to add to the personal homepage for new users could be the restricted collections to which the user has access. 
An automatic addition of most visited leaf collections by the user could be considered.
A configuration file or plug-in based infrastructure could be implemented to add specific collections to the personal homepage (for new or already existing users) based for eg. on group membership such that 1) new users immediately have access to relevant collections and 2) existing users are made aware of new important collections. The user should ideally be offered the option to add or remove any default collections, and be given the assurance that they will not come back.

Alternatives (possibly incompatible with the above) and misc comments:
 - Support for nested personal collections
 - Fully customizable collection tree
 - Submission workflows could also be part of the personal homepage, though it might be confusing and not necessary (the submissions having already gone under a refresh to display only relevant workflows to the user)

(Note: the mockups originally lived at https://twiki.cern.ch/twiki/bin/view/CDS/InvenioUsabilityYourCDS)

**Comment by jirikuncar** [comment]
Invenio 3 allows overlay developers to create and register own endpoint as homepage. cc @inveniosoftware/triagers
