### ISSUE TITLE
More visible alert subscription box

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#893]
Originally on 2012-02-01

The WebAlert module (along with RSS subscription) is one of those useful features that users are not always aware of. It would be good to make it more visible, for eg. by advertising the subscription box at the top of search results pages. See attached mockups using a tooltip next to search box. 

Given that subscribing to alerts is not a frequent task, this contextual help should only be displayed to a given user for a limited time only (displayed X times, or only for 48 hours, or until the user "closed" the help), just enough to make the user aware of the feature, and provided that he is instructed on how to use the feature after the tooltip has disappeared.

Ideally this kind of contextual help would be generalized to other cases where we want to make users aware of some feature on a given page ("Did you know...?"). If centrally managed (WebHelp module?), such a system would help to launch advertisement/training campaigns of existing/new features, and ensure that such hints would remain unobtrusive (eg. just one tooltip displayed per day/week/month).

If such a framework is implemented, it would also be useful to offer the possibility to insert tooltips that are opened at user request, when clicking on a help anchor (eg `[?]`).

**Comment by jirikuncar** [comment]
Invenio 1.x is currently in feature freeze state. New alerting package should be developed for Invenio 3.
