### ISSUE TITLE
Real OpenURL link resolver

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#903]
Originally on 2012-02-09

In Invenio, a rudimentary OpenURL link resolver is available that resolves OpenURL to content directly hosted in the corresponding Invenio repository.

However this could be extended to fully support insitutional electronic journal subscription.

Suppose (See #902), that a collection in Invenio is configured to contain records following a certain MARC convention that would each represent an institutional electronic journal subscription.

E.g. see: http://cdsweb.cern.ch/record/229770

This is indeed implemented, ad hoc, at CERN, in the form of the [Periodicals collection](http://cdsweb.cern.ch/collection/Periodicals).

By carefully using information contained in each of these records, thanks to an ad hoc algorithm, a generic form is provided that translate a "journal title" + "year" + "volume" + "initial page" into an URL pointing to the desired article. 

Every electronic journal has its own rules to build such URLs (given the above parameters), but these can be enumerated.

If this is factored out in a *plugin infrastructure*, where each URL-building algorithm is mapped into a plugin, then these plugin would allow to build a generic **OpenURL handler** that would resolve request into real papers for which the given institution has access to.

Such algorithm might be checked regularly via some dedicated tasklets to check that they are still valid, or if they require update.

**Comment by jirikuncar** [comment]
No milestone, no assignee, no update for 4 years. No fix?
