### ISSUE TITLE
xmlmarclint does not like empty tags

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#907]
Originally on 2012-02-19

When incoming file `foo.xml` contains empty tags such as:

```
  <datafield tag="506" ind1="0" ind2=" ">
  </datafield>
```

then `xmlmarclint` reports troubles:

```
$ sudo -u www-data  /opt/invenio/bin/xmlmarclint -v9
[...]
(8, '(field number: 1)'
```

We may want to ignore them.

(See also `CFG_BIBRECORD_KEEP_SINGLETONS` in `bibrecord.py`.)

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 4 years. Invenio 3 is using DoJSON package that accepts empty tags. cc @inveniosoftware/triagers
