### ISSUE TITLE
WebSearch: wider wild card search when no direct hit was found

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#916]
Originally on 2012-02-27

In demo site, when looking for "theo", there is no direct hit.  In this case, the user is offered a list of nearest terms.  Instead of offering the list of nearest terms, it may be interesting to silently enrich the query term by a trailing wild card, i.e. to search for "theo*", and show these results.  This behaviour could be triggered by a new configuration variable say CFG_WEBSEARCH_SILENT_TRAILING_WILDCARD, or we could rely on "ap" (=alternative patterns) for that.  The functionality could be put into search_unit_in_bibwords() or higher up into its caller.

**Comment by jirikuncar** [comment]
Can it be solved via https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html ?

--
cc @inveniosoftware/triagers
