### ISSUE TITLE
Documents loaded from cmsdoc should show URL

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#922]
Originally by *fcosta* on 2012-03-01

Documents loaded from cmsdoc have an URL showing where the fulltext was taken from.
For historical reasons, the URL is hidden (hack).
It should be displayed, according to requests by users.

Example: see URL http://cmsdoc.cern.ch/ftp/TDR/HCAL/hcal.html (in the MARC) of record 
https://cdsweb.cern.ch/record/357153?ln=en

This request is/may be linked to request of detecting URLs (and e-mails) in the Note field.

**Comment by egabancho** [comment]
See https://github.com/inveniosoftware/invenio/issues/922#issuecomment-56158537
