### ISSUE TITLE
Disk space checker

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#926]
Originally on 2012-03-01

Currently Invenio lacks an integrated tool to check if is it running out disk space.

This could be implemented as an bibtasklet that could check a configurable list of partitions. Special care must be given to AFS paths (used e.g. at CERN on CDS and INSPIRE), where a different check based on quota must be peformed.

**Comment by jirikuncar** [comment]
I'm not sure if this is really an Invenio job. I will focus on separating storage backends.

**Comment by lnielsen** [comment]
@jirikuncar Agree.
