### ISSUE TITLE
HTTPS and input and textarea

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#930]
Originally on 2012-03-02

Currently, any HTTP link contained in an HTTPS response is rewritten to start with HTTPS. This should however exclude HTTP link that are not going to be rendered as HTML, such as when they are contained in HTML-escaped text inside texarea or input tags.

**Comment by jirikuncar** [comment]
In 2.x we are using urls without `CFG_SITE(_SECURE)_URL` generated by `flask.url_for`. Rewriting whole response data can be very costly and should be avoided.

**Comment by lnielsen** [comment]
-1 from me. The links should be correct from the beginning, and not automatically fixed up. Also, let's go for HTTPS only (re. #931 )

**Comment by jirikuncar** [comment]
Shall we use everywhere 'url_for(..., _external=True)'?

**Comment by tiborsimko** [comment]
Closing as superseeded by RFC #931.
