### ISSUE TITLE
Using HTTPS only

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#931]
Originally on 2012-03-02

Currently, when an authenticated Invenio user makes an HTTP request, he will be redirected to an HTTPS request.

The viceversa should happen as well: i.e. when a guest user perform an HTTPS request, for speed reason he should be redirected to HTTP.

**Comment by jirikuncar** [comment]
> guest user perform an HTTPS request, for speed reason he should be redirected to HTTP

IMHO nowadays HTTPS speed is not an issue. Moreover, I would be in favor of serving HTTPS **only**.

**Comment by jalavik** [comment]
+1 on HTTPS only

**Comment by lnielsen** [comment]
+1 for HTTPS only. It would honestly make life easier.

**Comment by tiborsimko** [comment]
Seems timely to switch to serving HTTPS only, though we should beware of possible API use cases in various installations.  Changed topic to RFC that we can advertise more widely in our user community (e.g. mailing list).

**Comment by tiborsimko** [comment]
Conclusion from Invenio Developer Forum 2015-03-30: let us use only one "CFG_SITE_URL" and installations can decide to use HTTPS only (the default) or HTTP only (e.g. open data), not mixing the two.

**Comment by jirikuncar** [comment]
Then we could remove following hack: https://github.com/inveniosoftware/invenio/blob/master/invenio/base/wrappers.py#L73-L96

**Comment by lnielsen** [comment]
I'm still +1 on this.

**Comment by jirikuncar** [comment]
### Solution

- remove custom configuration options: `CFG_SITE_URL`, `CFG_SITE_SECURE_URL`
- remove SSLify extension as it won't be not needed
- use `SERVER_NAME` (standard Flask config) if you need to change your routing behind proxy

**Comment by tiborsimko** [comment]
Triage discussion: the issue is low priority now since admins can use HTTPS only in their current CFG_SITE_*URL variables and do the HTTP/HTTPS redirection in front of the Invenio application e.g. in Apache.

**Comment by tiborsimko** [comment]
The implementation started in #3637.
