### ISSUE TITLE
WebComment: add comments RSS feed

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#935]
Originally on 2012-03-07

It is wanted to add a way to subscribe to the RSS feed of comments of a given record, in a addition to the email notifications. The comment feed of each record could for eg. be made available at URL:
```
http://localhost/record/97/comments/rss
```

The creation of the RSS would be made very simple due to the already existing APIs to retrieve comments, and the storage of these comments in MySQL tables in a consistent way. It might be needed though to remove all existing HTML markup of the comments using the already existing washing facilities.

It should be possible to cache the RSS output for each record somewhere in `/opt/invenio/var/cache`

== Comment feeds of restricted records

Access to comment feed of restricted record could be made available thanks to #806 Authenticated Invenio API. See also how Indico does export iCal feeds of protected events http://indico-software.org/img/ical.png

== Comment feed of a collection

It might be useful to offer a feed aggregating all the comments of a given collection. This would be heavier to compute, though perfectly possible if cached (one feed per collection).

Further developments might also consider a collection feed aggregating both records and comments, for an easier tracking of the changes in a collection.

One could furthermore consider adding comment (+record) feeds for custom search queries. In this case computation of the feed would be even heavier, and less easily "cacheable".

== Comment feeds in baskets

The very same export should be added to comments (*notes*) submitted on baskets. It would however seem more useful to offer comment feeds not on a single record of the basket, but on the whole basket (as it could be done for the feeds of a collection).

Access to restricted baskets could also be handled by #806 Authenticated Invenio API.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 4 years. Simple example if needed in overlay using Flask http://flask.pocoo.org/snippets/10/ . cc @inveniosoftware/triagers
