### ISSUE TITLE
BibIndex: create special category index for Indico search

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#937]
Originally on 2012-03-08

In order to speed up Indico Search, a special category index is to be created with special tokenising rules that are very similar to DESY keyword tokenising rules.  (That is, split phrase by colon, see also #699.)

Example of the input:

```
  <datafield tag="650" ind1=" " ind2="7">
    <subfield code="a">0:1l28:1l8:662</subfield>
  </datafield>
```

We want to tokenise this into four index terms:

```
 0:1l28:1l8:662
 0:1l28:1l8
 0:1l28
 0
```

**Comment by jirikuncar** [comment]
@ludmilamarian @egabancho @switowski is it still relevant?

**Comment by egabancho** [comment]
cc @kasioumis

**Comment by kaplun** [comment]
Indico search is no longer based on Invenio.
