### ISSUE TITLE
WebSearch: XML output and split-by-collection

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#938]
Originally on 2012-03-08

Indico Search calls Invenio instance and gets results in MARCXML.  The search is being called twice, once for collection Foo and once for collection Bar.  In order to speed up the queries, it would be good to enrich XML output with comments specifying results split by collection.  This will necessitate only one search call from Indico.

Using Invenio demo site as an exapmle, for a query like `http://invenio-demo.cern.ch/search?p=nuclear&of=xm&sc=1`, the system can reply in enriched markup e.g. using XML comments like:

```
[...]
<!-- Search-Engine-Total-Number-Of-Results: 7 -->
<!-- Search-Engine-Collection: Articles and Preprints -->
<!-- Search-Engine-Collection-Number-Of-Results: 6 -->
<record>
  <controlfield tag="001">65</controlfield>
  [...]
</record>
[...]
<!-- Search-Engine-Collection: Books and Reports -->
<!-- Search-Engine-Collection-Number-Of-Results: 1 -->
<record>
  <controlfield tag="001">32</controlfield>
</record>
```

See also #363.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 4 years. It was either fixed in overlay or it is not needed anymore. cc @egabancho @ludmilamarian
