### ISSUE TITLE
WebSearch: HTTP APIs to query available search fields/indexes, rankings, etc.

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#940]
Originally on 2012-03-09

Along with the (soon-to-be) added HTTP APIs to retrieve the available collections of an Invenio-based repo, we could also add support for querying some additional information to launch a query via the search APIs. For eg, it should be possible to query about:

 - available fields/indexes (*author*, *title*, *language*, etc)
 - available ranking methods (*citation*, *wrd*, etc.)
 - available output formats (*xm*, *hb*, *hx*, etc.)
 - available languages (*en*, *it*, *de*, etc.)
 - etc. (?)

The returned structured (json?) should possibly contain a description for each value.

The above values could also be returned as part of the information sent along with the available collection list, as these values might also vary based on the collection. Alternatively, we could offer the possibility to filter the retrieved values per collection. For eg. the Invenio connector (client) could be augmented with the following functions:

```
def get_fields(c=None, ln=None):
   """
   Returns list of available search index, and their mapping to MARC fields:
   {'title': ['titolo', ['245__a', '246__b', '111__a']],
    'abstract': ['riassunto', ['520__%', '590__%']],
    ...
   }
   @param c: list of fields specifically relevant for given collection
   @param ln: language for the description. If not specified, default language 
              of the repository
   """
   [...]


def get_ranking_methods(c=None, ln=None):
   """
   Returns list of available ranking methods:
   {'wrd': 'word similarity',
    'citation': ''times cited',
    ...
   }
   @param c: list of rankings specifically relevant for given collection
   @param ln: language for the description. If not specified, default language 
              of the repository
   """
   [...]

def get_output_formats(c=None, ln=None):
   """
   Returns list of available output formats:
   {'hb': 'HTML brief',
    'hx': ''BibTeX',
    ...
   }
   @param c: list of output formats specifically relevant for given collection
   @param ln: language for the description. If not specified, default language 
              of the repository
   """
   [...]

def get_languages():
   """
   Returns list of available output languages
   {'en': 'English',
    'de': 'Deutsch',
    'it': 'Italiano',
    ...
   }
   """
   [...]
```

In the above examples one could imagine removing the *ln* parameter and returning all variants in the same call, to minimize number of requests.

It could also be made mandatory to authenticate to use these API, in order to invite developers to use these APIs with care (eg. with client-side caching).

**Comment by jirikuncar** [comment]
superseded by #2478

**Comment by tiborsimko** [comment]
> superseded by #2478

Well this is not about Record API or Search API, but about "meta API" for discovery, to enable anyone to easily see "what we've got".  Kind of API-for-API that would generate "processable docs" from API docstrings, say.  We mused about it [at the wiki](http://invenio-software.org/wiki/Talk/WebAPIs#a3.4API-for-APIs) but not turned that to a ticket yet.

**Comment by jirikuncar** [comment]
> - available fields/indexes (author, title, language, etc)

should go to `indexer`

> - available ranking methods (citation, wrd, etc.)

probably `indexer/sorter`

> - available output formats (xm, hb, hx, etc.)

should go to `formatter`

> - available languages (en, it, de, etc.)

is it record related?

**Comment by tiborsimko** [comment]
> is it record related?

I guess the UI languages were meant; kind of providing generic meta information about the installation.
(One could also show Invenio version, number of records, etc.)

On the same track, one may want to expose in a processable way which collections the site has, expose their descriptions as a means of documenting them, etc.  This is good for posterity.  Hence this ticket is kind of wider.  

I think we can keep it closed here, especially if we start musing about making an API-for-API framework, as it were, in another ticket.  (I think Kostas did not get there yet, so we did not started.)
