### ISSUE TITLE
xvol needed in INSPIRE

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#942]
Originally by *hoc* on 2012-03-12

SPIRES had an index, xvol, which takes the volume element from the standard, journal-volume-page triplet. So in a publication note such as 
Phys.Rev. D85 (2012) 045032
the xvol is "D85"

This is especially needed for the easy search where it is currently expected (though incorrectly coded as jvol):
http://inspirehep.net/help/easy-search

**Comment by jalavik** [comment]
Non Invenio related. Moved to appropriate INSPIRE channels.
