### ISSUE TITLE
WebSearch: find eprint astro-ph/0101431 or nucl-th/0204034

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#947]
Originally on 2012-03-14

The precedence rules for regexp queries vs Boolean queries are currently such as user searches for:

```
find eprint astro-ph/0101431 or nucl-th/0204034
```

on the demo site breaks.  

This is because slashes look like regexp queries, while most users would expect `OR` to take precedence here.

However, see also queries like:

```
title:/foo or bar/
```

when defining what a good default behaviour should look like.

In order to quick fix this situation, we may want to rely on the fact than arXiv numbers have alphanumeric characters just before and just after slash, while in the other cases
there is a white space character to either side of the slash.

P.S. As usual, a test case for the above query (that matches Atlantis demo site records) should be written as part of this ticket.

**Comment by jalavik** [comment]
Moved to appropriate INSPIRe channels.
