### ISSUE TITLE
BibCirculation: improve holding request list

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#949]
Originally on 2012-03-16

When viewing a specific item, you can see the current hold request for this item. When you click on the button to view these requests, you are presented with a list of the request. However, the only option here is to cancel it. To fulfill the loan, one has to note down the requestor and perform a normal load procedure (name then barcode).

To improve the workflow, there should be an option to fulfill the request, i.e. taking out a loan on this user, where you only need to specify the barcode of the holding that is being taken out.

**Comment by jirikuncar** [comment]
The issue seems to be stalled for 4 years. Check a progress on new circulation package: https://github.com/inveniosoftware/invenio-circulation 

--
cc @inveniosoftware/triagers
