### ISSUE TITLE
BibdocFile --set-doctype not working

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#980]
Originally by _[adeiana (@Osso)](https://github.com/Osso)_ on 2012-03-30

When I try to set the doctype via --set-doctype
e.g.  bibdocfile --recid 1 --set-doctype INSPIRE-PUBLIC
The doctype is still "main".

I am not sure how it should be handled:
- creating a new bibdoc revision ?
- just changing the doctype ?

I tracked down where the handling was done.
line 1528 and above in bibupload.py 
We check that if filename is not changed, we do not create a revision.
So we can either still and a new condition for creating a new revision
OR
Above line 1528, we make it so the doctype is updated for the current revision

**Comment by aw-bib** [comment]
In invenio 1.1.6 this prolblem still seems to persist. As far as I can see, the relevant table does not get updated by the backend at all. Probably, the fix from @ludmilamarian could make it to maint-1.1?
