### ISSUE TITLE
OAI-ORE support

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#999]
Originally on 2012-04-10

[Open Archives Initiative Object Reuse and Exchange](http://www.openarchives.org/ore/) defines standards for the description and exchange of aggregations of Web resources [...]

In Invenio aggregation might come from different sources:
* the DB:
  - *collections* aggregate *records*
  - *records* links to *documents*
  - *documents* links to *revisions* of documents
  - *revisions* of document link to *formats* of documents
* [MARC 76x-78x fields](http://www.loc.gov/marc/bibliographic/bd76x78x.html) (at CERN e.g. these are used to link a record to the official publication, or a conference with its talks, a talk with the contribution and the proceeding, etc. or can be used to link a photo to a photoshoot). (in OpenAIREplus datasets will be linked to publications).

Implementation details will be added as comments to this ticket.

**Comment by lnielsen** [comment]
This is an idea, and as far as I'm aware no one are planning to work on this so I'll close it as an idea for some day.
